'use strict';
/** EchoLens prebuilt tracks - Bootcamps (2 weeks, 4 sessions -> 4 levels).
 * Every problem carries: real-world context, a course-link note showing exactly
 * which session/point it maps to, reference links for the student, and a
 * solution guideline visible ONLY to teachers and admins. */

module.exports = [
{
  key: 'bc01-automation', course_code: 'BC-01', title: 'AI Automation with n8n & Make.com',
  description: '2-week quest: from your first workflow to a working AI-powered business automation.',
  pass_mark: 60, titleNames: ['Flow Rookie', 'Node Wrangler', 'Automation Architect', 'Workflow Wizard'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'First Automation', topic: 'Automation thinking, triggers, and actions',
      problems: [
        { title: 'Map a Manual Process', points: 50, difficulty: 'Basic',
          description: 'Pick a real repetitive task from your life or a family business (e.g. copying order messages from WhatsApp into a register). Document it as a flowchart: trigger, steps, decision points, output. Identify which steps a machine could do. Submit as PDF.\nCourse link: Session 1 - "What is automation: triggers, actions, and workflows."',
          criteria: ['Clear single trigger identified', 'At least 4 concrete process steps documented', 'Human vs machine steps honestly labelled'],
          hint: 'Focus on naming the exact data that moves between each step - that\'s usually where the "could a machine do this" answer becomes obvious.',
          refs: [['n8n: workflow concepts', 'https://docs.n8n.io/workflows/'], ['Make: scenarios basics', 'https://www.make.com/en/help/scenarios']],
          solution: 'Look for a clear trigger, 4+ concrete steps, and honest human-vs-machine labelling. Strong answers name the data moving between steps. Common miss: no decision points.' },
        { title: 'Hello, Workflow', points: 70, difficulty: 'Core',
          description: 'Build your first live workflow in n8n or Make: when a form is submitted (Google Forms/Typeform), send yourself an email or Telegram message with the answers. Submit screenshots of the workflow and the received message in a Word/PDF report.\nCourse link: Session 1 - building trigger-to-action flows hands-on.',
          criteria: ['Workflow triggers on a real form submission', 'Message includes mapped fields, not hardcoded text', 'Screenshots show both the workflow and received message'],
          hint: 'Submit a real test entry through the actual form rather than the builder\'s test button, so you can see the genuine field names available to map.',
          refs: [['n8n quickstart', 'https://docs.n8n.io/try-it-out/'], ['Make: get started', 'https://www.make.com/en/help/get-started']],
          solution: 'Check the trigger fires on real form data and the message includes mapped fields (not hardcoded text). Field mapping is the concept being tested.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Data in Motion', topic: 'Connecting apps, mapping fields, filters',
      problems: [
        { title: 'Sheet Sync', points: 70, difficulty: 'Core',
          description: 'Automate: every new Google Form response lands as a clean row in Google Sheets, with a timestamp and a computed field (e.g. order total = qty x price). Add a filter so only responses above a threshold trigger a notification. Report with screenshots + a paragraph on what broke and how you fixed it.\nCourse link: Session 2 - field mapping, filters, and conditional paths.',
          criteria: ['Row includes a timestamp and a correctly computed field', 'Filter only notifies above the chosen threshold', 'Report explains a real bug and its fix'],
          hint: 'Build and test the computed field on its own first, then add the filter - and try a response sitting exactly at the threshold to see which side it lands on.',
          refs: [['n8n: IF node', 'https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.if/'], ['Make: filters', 'https://www.make.com/en/help/scenarios/filtering']],
          solution: 'The computed field and working filter are the pass criteria. Watch for students hardcoding values instead of referencing incoming fields.' },
        { title: 'The Router', points: 90, difficulty: 'Boss',
          description: 'Real scenario: a small academy receives inquiries for different courses. Build a workflow that routes each inquiry to a different channel (email A for AI courses, email B for design) based on a dropdown answer, and logs everything to one sheet. Explain your routing logic in the report.\nCourse link: Session 2 - branching workflows with routers/switch nodes.',
          criteria: ['Each dropdown answer routes to the correct channel', 'A fallback branch handles unexpected answers', 'Every inquiry is logged to one shared sheet'],
          hint: 'Wire up the default/fallback branch on the switch node first, then add the specific routes - it\'s easy to forget the "none of the above" case until it breaks in testing.',
          refs: [['n8n: Switch node', 'https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.switch/'], ['Make: routers', 'https://www.make.com/en/help/scenarios/router']],
          solution: 'Expect a switch/router with 2+ branches plus a shared logging step. Good answers handle the "none of the above" fallback branch.' },
      ] },
    { no: 3, week: 2, session: 3, title: 'AI Joins the Flow', topic: 'Adding LLM steps to workflows',
      problems: [
        { title: 'Auto-Summarizer', points: 90, difficulty: 'Core',
          description: 'Extend a workflow with an AI step: long customer messages get summarized to 2 lines and classified (complaint / question / order) before being logged. Use any LLM node (OpenAI/Gemini). Include 3 real test messages and the AI outputs in your report.\nCourse link: Session 3 - LLM nodes, prompts inside workflows.',
          criteria: ['Summary reliably compressed to 2 lines', 'Classification uses a fixed label set (complaint/question/order)', '3 real test messages with AI outputs included'],
          hint: 'Tell the AI node exactly what shape the output should take (e.g. two labelled fields) so the rest of the workflow can parse it instead of dealing with loose free text.',
          refs: [['n8n: OpenAI node', 'https://docs.n8n.io/integrations/builtin/app-nodes/n8n-nodes-base.openai/'], ['Prompting guide', 'https://platform.openai.com/docs/guides/prompt-engineering']],
          solution: 'Grade the prompt quality: does it constrain output format? Classification should use a fixed label set. Deduct if outputs are unparsed free text.' },
        { title: 'Reply Draft Machine', points: 110, difficulty: 'Boss',
          description: 'Build the classic business win: incoming inquiry -> AI drafts a polite reply in the business tone -> draft is sent to the owner for approval (email/Telegram), never directly to the customer. Explain why the human-approval step matters. This mirrors how real companies deploy AI safely.\nCourse link: Session 3 - human-in-the-loop AI automation.',
          criteria: ['Draft is never sent straight to the customer', 'Owner approval step is required before send', 'Explanation covers why the approval gate matters'],
          hint: 'Picture what happens the day the AI drafts something off-tone or wrong - the approval gate exists precisely to catch that before a customer ever sees it.',
          refs: [['n8n: wait/approval patterns', 'https://docs.n8n.io/integrations/builtin/core-nodes/n8n-nodes-base.wait/']],
          solution: 'The approval gate is the core concept - auto-sending fails the exercise. Strong answers include tone instructions and a fallback for AI errors.' },
      ] },
    { no: 4, week: 2, session: 4, title: 'Capstone: Ship an Automation', topic: 'End-to-end business automation',
      problems: [
        { title: 'The Business Pipeline', points: 150, difficulty: 'Boss',
          description: 'Design and build a complete automation for a real Pakistani small business scenario (order intake, student registration, invoice reminders - your pick): trigger -> processing -> AI step -> storage -> notification, with at least one branch and one error path. Deliver a PDF: problem, flow diagram, screenshots, cost estimate on free tiers, and a 5-line pitch you could send the business owner.\nCourse link: Sessions 1-4 combined - this is your portfolio piece.',
          criteria: ['Full trigger-to-notification pipeline works end-to-end', 'At least one branch and one error path included', 'PDF includes flow diagram, cost estimate, and owner pitch'],
          hint: 'Build and test each stage on its own (trigger, then AI step, then storage) before wiring the full chain together - it\'s far easier to debug one broken link at a time.',
          refs: [['n8n error handling', 'https://docs.n8n.io/flow-logic/error-handling/'], ['Make: error handlers', 'https://www.make.com/en/help/errors/error-handlers']],
          solution: 'Rubric: working end-to-end (40%), branch + error path (20%), AI step adds real value (20%), clarity of report and pitch (20%).' },
      ] },
  ],
},
{
  key: 'bc02-prompting', course_code: 'BC-02', title: 'Prompt Engineering & ChatGPT/Claude Mastery',
  description: '2-week quest: from casual chatting to engineered, reusable prompt systems.',
  pass_mark: 60, titleNames: ['Prompt Rookie', 'Context Crafter', 'Instruction Designer', 'Prompt Engineer'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Anatomy of a Prompt', topic: 'Role, task, context, format',
      problems: [
        { title: 'Before and After', points: 50, difficulty: 'Basic',
          description: 'Take 3 vague prompts you would naturally type (e.g. "write a CV") and re-engineer each using the Role-Task-Context-Format pattern. Show both outputs side by side and annotate what changed and why. Submit as PDF.\nCourse link: Session 1 - the four building blocks of a prompt.',
          criteria: ['All 3 prompts rewritten with Role-Task-Context-Format', 'Before and after outputs shown side by side', 'Annotations name which block drove the improvement'],
          hint: 'Add one block at a time to your rewrite so you can actually see which piece - role, task, context, or format - is doing the heavy lifting.',
          refs: [['Anthropic prompting guide', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview'], ['OpenAI prompting', 'https://platform.openai.com/docs/guides/prompt-engineering']],
          solution: 'Look for all four blocks present and a genuine quality jump in outputs. Annotations should name the block responsible for each improvement.' },
        { title: 'The Format Contract', points: 70, difficulty: 'Core',
          description: 'Real use: a shop owner wants product descriptions in a strict format (name, 2 benefits, price line, hashtags). Write ONE prompt that reliably produces this format for any product, test it on 4 products, and show all outputs. Explain how you enforced structure.\nCourse link: Session 1 - output formatting and constraints.',
          criteria: ['One reusable prompt tested across all 4 products', 'Output format stays consistent every time', 'Explanation of how structure was enforced'],
          hint: 'Give the model an explicit template or tags to fill in rather than just describing the format in words - it holds up far better across different products.',
          refs: [['Claude: use XML tags', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/use-xml-tags']],
          solution: 'Consistency across all 4 outputs is the pass bar. Good answers use explicit templates or tags; weak ones just hope.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Few-Shot Power', topic: 'Examples, tone control, iteration',
      problems: [
        { title: 'Teach by Example', points: 70, difficulty: 'Core',
          description: 'Build a few-shot prompt that converts formal English announcements into friendly Roman-Urdu WhatsApp messages, using 3 examples you write yourself. Test on 3 new announcements. Compare against a zero-shot attempt.\nCourse link: Session 2 - few-shot prompting and why examples beat instructions.',
          criteria: ['3 self-written examples used in the few-shot prompt', 'Zero-shot and few-shot outputs compared on 3 new announcements', 'Explanation of why the few-shot version performed better'],
          hint: 'Keep your three examples consistent in tone and structure - inconsistent examples confuse the model more than having no examples at all.',
          refs: [['Few-shot prompting', 'https://www.promptingguide.ai/techniques/fewshot']],
          solution: 'Examples should be consistent in style; the few-shot version should clearly outperform zero-shot on tone. Check the student explains WHY it works.' },
        { title: 'The Style Cloner', points: 90, difficulty: 'Boss',
          description: 'Pick a writing style you admire (a columnist, a brand). Extract its rules by asking the model to analyze 2 samples, then build a prompt that writes NEW content in that style. Include an honest failure analysis: where does the clone break?\nCourse link: Session 2 - iterative prompt refinement.',
          criteria: ['Style rules extracted from 2 real samples first', 'New content generated actually matches that style', 'Honest failure analysis names where the clone breaks'],
          hint: 'Ask the model to describe the style in concrete terms - sentence length, tone, recurring quirks - before asking it to generate anything new in that style.',
          refs: [['Prompting techniques guide', 'https://www.promptingguide.ai/']],
          solution: 'The two-step method (analyze then generate) is the concept. Reward honest failure analysis over inflated claims.' },
      ] },
    { no: 3, week: 2, session: 3, title: 'Reasoning and Guardrails', topic: 'Chain-of-thought, verification, safety',
      problems: [
        { title: 'Show Your Working', points: 90, difficulty: 'Core',
          description: 'Take 3 multi-step problems (a zakat calculation, a discount stacking question, a scheduling conflict). Compare direct answers vs "think step by step" prompting. Document accuracy differences and explain when reasoning prompts matter.\nCourse link: Session 3 - chain-of-thought prompting.',
          criteria: ['All 3 problems tested with direct vs step-by-step prompting', 'Accuracy differences documented per problem', 'Answers verified by hand, not assumed correct'],
          hint: 'Pick problems where a shortcut mistake is easy to make - that\'s where "think step by step" usually shows its biggest advantage over a direct answer.',
          refs: [['CoT prompting', 'https://www.promptingguide.ai/techniques/cot']],
          solution: 'At least one problem should show a real accuracy difference. Check calculations were actually verified by hand, not assumed.' },
        { title: 'The Verifier Pattern', points: 110, difficulty: 'Boss',
          description: 'Real risk: AI confidently gets facts wrong. Build a two-prompt system: prompt A answers a question, prompt B critiques A\'s answer for errors and unsupported claims. Test it on 3 questions where you know the truth (one should trip the model). Report what the verifier caught and missed.\nCourse link: Session 3 - self-critique and hallucination handling.',
          criteria: ['Two-prompt system with a distinct critique step', 'At least one genuine error actually caught', 'Report also covers what the verifier missed'],
          hint: 'Give the critique prompt the original answer text to work from, and pick a question you already suspect the model gets wrong so the verifier has something real to catch.',
          refs: [['Reducing hallucinations', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/reduce-hallucinations']],
          solution: 'Pass requires one genuine caught error. Discuss verifier limits - it can rubber-stamp. Strong answers ground the verifier with source text.' },
      ] },
    { no: 4, week: 2, session: 4, title: 'Capstone: Prompt System', topic: 'Reusable prompt libraries for real work',
      problems: [
        { title: 'Your Prompt Toolkit', points: 150, difficulty: 'Boss',
          description: 'Build a documented 5-prompt toolkit for one real role (teacher, freelancer, shop owner, student). Each prompt: purpose, full text, one worked example, known limitations. Package as a professional PDF someone could actually use tomorrow.\nCourse link: Sessions 1-4 combined - your portfolio deliverable.',
          criteria: ['5 prompts documented for one real role', 'Each prompt has purpose, full text, and a worked example', 'Known limitations honestly listed per prompt'],
          hint: 'Actually run each prompt on a real task from that role before writing it up - limitations you discover by using the prompt are far more convincing than guessed ones.',
          refs: [['Anthropic prompt library', 'https://docs.anthropic.com/en/resources/prompt-library/library']],
          solution: 'Rubric: prompts use course techniques (40%), realistic worked examples (30%), honest limitations (15%), presentation (15%).' },
      ] },
  ],
},
{
  key: 'bc03-everyday-ai', course_code: 'BC-03', free: true, title: 'Everyday AI: Smarter Study, Work & Content',
  description: '2-week quest: make AI a daily advantage in study, work, and content creation.',
  pass_mark: 60, titleNames: ['AI Curious', 'Daily Driver', 'Productivity Pro', 'AI Power User'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Study Smarter', topic: 'AI for learning and exam prep',
      problems: [
        { title: 'The Personal Tutor', points: 50, difficulty: 'Basic',
          description: 'Take one topic you find hard. Use AI three ways: explain like I\'m 12, generate a 10-question self-quiz, and create a 1-page revision sheet. Include everything plus a reflection: which method taught you most and why?\nCourse link: Session 1 - AI as a study partner, not an answer machine.',
          criteria: ['All three AI methods used on the same topic', 'Quiz answers verified against a textbook', 'Reflection explains which method taught most and why'],
          hint: 'Test yourself again a day later without looking at the material - the method that actually stuck is the real answer to "which taught you most."',
          refs: [['Learning with AI (Google)', 'https://grow.google/ai/']],
          solution: 'Grade the reflection hardest - the point is metacognition. Quiz answers should be verified against a textbook, and say so.' },
        { title: 'Source-Checked Notes', points: 70, difficulty: 'Core',
          description: 'AI sometimes invents facts. Ask AI to summarize a topic from your syllabus, then fact-check every claim against your textbook or an official source, marking each TRUE / FALSE / UNVERIFIABLE. Report the error rate and what you learned about trusting AI.\nCourse link: Session 1 - verification habits and hallucinations.',
          criteria: ['Every claim in the summary individually fact-checked', 'Each claim marked TRUE / FALSE / UNVERIFIABLE with a cited source', 'Error rate reported with a genuine reflection on trusting AI'],
          hint: 'Check the smallest, most specific claims first - dates, numbers, names - that\'s where AI summaries most often quietly drift from the source.',
          refs: [['On AI hallucinations', 'https://www.ibm.com/topics/ai-hallucinations']],
          solution: 'Pass = every claim actually checked with a cited source. The lesson lands when they find at least one wrong or unverifiable claim.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Work Accelerator', topic: 'Email, documents, spreadsheets with AI',
      problems: [
        { title: 'The Inbox Assistant', points: 70, difficulty: 'Core',
          description: 'Draft 4 real-world messages with AI: a job application email, a polite fee-negotiation, a complaint escalation, and a professional excuse/delay message. For each: your prompt, the draft, and YOUR edits with reasons. Unedited AI text fails.\nCourse link: Session 2 - AI-assisted (not AI-replaced) professional writing.',
          criteria: ['All 4 message types drafted with a shown prompt', 'Every draft carries your own edits with reasons', 'Edits show real tone or cultural-fit corrections'],
          hint: 'Read each AI draft out loud before editing it - awkward phrasing and generic filler are much easier to catch that way than by silently scanning the text.',
          refs: [['Effective business emails', 'https://www.grammarly.com/blog/professional-email/']],
          solution: 'The edits are the assignment. Look for tone corrections, cultural fit, and removal of AI filler. No edits = automatic resubmit.' },
        { title: 'Spreadsheet Sidekick', points: 90, difficulty: 'Boss',
          description: 'Take a messy real dataset (your expenses, a shop register - 30+ rows). Use AI to: suggest a cleaning plan, write the Excel/Sheets formulas you need, and draft insights. Verify each formula works and each insight is true. Submit before/after sheets and the verification log.\nCourse link: Session 2 - AI for data work with verification.',
          criteria: ['Dataset of 30+ rows cleaned per an AI-suggested plan', 'Every formula pasted in and confirmed working', 'Insights backed by an actual number from the data'],
          hint: 'Paste each formula into the sheet and check its result before moving to the next one - AI-suggested formulas sometimes reference the wrong column or range.',
          refs: [['Google Sheets formulas', 'https://support.google.com/docs/table/25273']],
          solution: 'Formulas must be pasted AND confirmed working. Insights need a number behind them. Watch for invented column references.' },
      ] },
    { no: 3, week: 2, session: 3, title: 'Content Engine', topic: 'Social posts, visuals, video scripts',
      problems: [
        { title: 'The 7-Day Content Kit', points: 90, difficulty: 'Core',
          description: 'For a real or imagined small brand, produce a 7-day content calendar with AI: post copy per day, image ideas/AI-image prompts, hashtags, and posting times with reasoning. Present as a client-ready PDF.\nCourse link: Session 3 - AI content workflows.',
          criteria: ['Full 7-day calendar with copy, image ideas, and hashtags', 'Posting times each include a stated reason', 'Brand voice stays consistent across all 7 days'],
          hint: 'Write a one-line brand voice description first and check each day\'s post against it - that\'s what keeps the whole week feeling like one brand.',
          refs: [['Content calendar basics', 'https://blog.hootsuite.com/how-to-create-a-social-media-content-calendar/']],
          solution: 'Consistency of brand voice across 7 days is the differentiator. Deduct for generic copy that could belong to any brand.' },
        { title: 'One Idea, Five Formats', points: 110, difficulty: 'Boss',
          description: 'Real content teams repurpose. Take one idea and use AI to turn it into: a LinkedIn post, a Twitter/X thread, a 60-second video script, an infographic outline, and an email newsletter blurb - each genuinely adapted to its platform, not copy-pasted. Annotate the adaptations.\nCourse link: Session 3 - platform-aware content repurposing.',
          criteria: ['All 5 formats genuinely adapted, not copy-pasted', 'Format-native features present (thread numbering, script timing, subject line)', 'Adaptations annotated and explained'],
          hint: 'Start from each platform\'s constraints - character limits, timing, visual layout - rather than the original text, so every format ends up shaped for where it lives.',
          refs: [['Repurposing content guide', 'https://buffer.com/library/repurposing-content/']],
          solution: 'Check format-native features: thread numbering, script timing cues, subject line. Same text in 5 wrappers fails.' },
      ] },
    { no: 4, week: 2, session: 4, title: 'Capstone: Your AI Stack', topic: 'Personal AI operating system',
      problems: [
        { title: 'The Personal AI Playbook', points: 150, difficulty: 'Boss',
          description: 'Document your personal AI stack: 5 recurring tasks in your life, the exact AI workflow you now use for each (tool, prompt, verification step), time saved per week (measured, not guessed), and one task you decided NOT to use AI for, with reasoning. This is the habit the whole bootcamp was building.\nCourse link: Sessions 1-4 combined.',
          criteria: ['5 recurring tasks documented with tool, prompt, and verification step', 'Time saved per week measured, not guessed', 'One honest not-AI task included with reasoning'],
          hint: 'Actually time yourself doing a task with and without AI over a few days before writing down a number - guessed estimates are usually way off in one direction or the other.',
          refs: [],
          solution: 'Rubric: real measured tasks (40%), verification steps present (25%), honest not-AI case (20%), clarity (15%). Guessed numbers get challenged.' },
      ] },
  ],
},
];
