'use strict';
/** EchoLens prebuilt tracks - Bootcamps (2 weeks; paid = 8 one-hour classes -> 8
 * levels, free funnel bootcamps = 4 two-hour classes -> 4 levels of 5 quests).
 * August 2026 refresh: every class is one level with a one-line topic (the
 * public outline), five hands-on quests, and each course closes with a real
 * production end project. `submission` picks the workspace the portal shows:
 *   doc      -> Word/PDF report upload only
 *   prompt   -> AI Prompt Lab workbook (write + run prompts, submit directly)
 *   code-ai  -> built-in compiler with the AI copilot beside it
 *   excel-ai -> workbook upload + AI copilot linked to the sheet
 *   multi    -> multiple PDF/image files per submission
 */

module.exports = [
{
  key: 'bc01-automation', course_code: 'BC-01', title: 'AI Automation with n8n & Make.com',
  description: 'Week 1 builds the workflow muscle. Week 2 adds the AI layer clients actually pay for in 2026 - ending with a sellable, client-ready automation.',
  outcome: 'Leave able to build and sell a client-ready AI automation - the exact skill that reaches billable freelance level at $30-70/hour within a couple of months.',
  submission: 'doc',
  key_concepts: [
    'Triggers, actions, and the workflow model', 'Data mapping, JSON, filters, formatters',
    'Connecting Sheets, Gmail, Slack, Calendar, any API', 'Routing, conditions, error handling, dedupe',
    'Adding Claude, GPT, or Gemini steps in a flow', 'AI pipelines: summarise, classify, translate, repurpose',
    'The AI Agent node: brain, memory, tools', 'Packaging, documenting, and pricing a client automation',
  ],
  end_project: {
    title: 'AI Lead and Support Autopilot',
    tagline: 'A deployed automation a real business could run from day one.',
    description: 'A complete, live workflow that takes a business from raw inbound leads and messages to organised, AI-enriched, routed and responded-to records, with a daily digest in the owner\'s inbox - documented and packaged as a service you can actually sell.',
    includes: [
      'Intake from two sources at once (web form or webhook + an email inbox) into one clean records sheet',
      'AI enrichment that classifies every lead or message by intent and gives it a score',
      'Deduplication on a unique key with append-or-update, so nothing is logged twice',
      'Routing: hot leads to Slack with an AI-drafted reply, support messages to the right place, cold leads to nurture',
      'An AI agent wired to a webhook that answers FAQs from a knowledge sheet like a chatbot',
      'Error handling that alerts the moment a step fails',
      'A scheduled daily AI digest email summarising every new lead',
      'A one-page runbook plus a one-paragraph pitch a client could buy from',
    ],
    shipped_when: 'It runs end to end on live test accounts, handles a batch of ten sample leads correctly, and exports as a workflow file a client could import and deploy.',
  },
  pass_mark: 60, titleNames: ['Flow Rookie', 'Node Wrangler', 'Automation Architect', 'Workflow Wizard'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Your first working automation', topic: 'What a workflow really is: the trigger-then-action shape, nodes, testing, and when to pick n8n vs Make',
      problems: [
        { title: 'Lead Capture Classic', points: 40, difficulty: 'Basic',
          description: 'Build a scenario that fires on a new Google Form response and adds a clean row to a Google Sheet. Submit screenshots + a short note as PDF/Word.',
          criteria: ['Trigger fires on a real form response', 'Row lands clean in the sheet with mapped fields', 'Screenshots show the workflow and the result'],
          hint: 'Send a real test entry through the form so the trigger exposes the genuine field names to map.',
          solution: 'Pass = real trigger + mapped (not hardcoded) fields in the sheet row.' },
        { title: 'Nine O\'Clock Digest', points: 50, difficulty: 'Core',
          description: 'Build a workflow on a schedule trigger that sends you a Slack or email summary every morning at nine.',
          criteria: ['Schedule trigger set to 9:00 daily', 'Message actually arrives in Slack or email', 'Summary content is assembled in the workflow, not typed by hand'],
          hint: 'Test with a one-minute schedule first, then switch the cron to 9 a.m. once it works.',
          solution: 'Check the schedule expression and that the message body is built from workflow data.' },
        { title: 'Drive Watchdog', points: 50, difficulty: 'Core',
          description: 'Build an automation that notifies you the moment a file lands in a specific Drive folder.',
          criteria: ['Watches one specific folder, not all of Drive', 'Notification includes the file name', 'Fires on a fresh upload during testing'],
          hint: 'Point the trigger at the folder ID, then drop a test file in and watch the execution log.',
          solution: 'Folder-scoped trigger + file name mapped into the notification.' },
        { title: 'Webhook Logger', points: 60, difficulty: 'Core',
          description: 'Build a webhook-triggered workflow that logs whatever data hits it into a sheet.',
          criteria: ['Webhook URL receives a test payload', 'Incoming fields are written to sheet columns', 'Works for a second, differently-shaped test payload'],
          hint: 'Fire a test request at the webhook (curl, Postman, or a form) and inspect the captured body before mapping.',
          solution: 'Look for a real webhook execution in the log and generic field handling.' },
        { title: 'Fix the Broken Flow', points: 80, difficulty: 'Boss',
          description: 'Take a broken two-node workflow and fix the trigger-to-action wiring so it runs end to end. Explain what was wrong.',
          criteria: ['The original fault is named correctly', 'Workflow now runs end to end', 'Explanation covers how you diagnosed it'],
          hint: 'Run the trigger alone first and read its output - broken wiring is almost always a field that no longer exists downstream.',
          solution: 'Grade the diagnosis, not just the fix - they must state the actual fault.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Working with data', topic: 'Reading JSON, mapping fields node to node, filters, and formatting text, numbers and dates',
      problems: [
        { title: 'Tidy Slack Message', points: 40, difficulty: 'Basic',
          description: 'Map the name, email, and phone from a form into one tidy, formatted Slack message.',
          criteria: ['All three fields mapped from the form', 'Message is formatted for a human reader', 'No hardcoded sample values'],
          hint: 'Build the message text around the mapped variables, then send a test entry to see it rendered.',
          solution: 'Mapped fields inside a readable template = pass.' },
        { title: 'Name Splitter', points: 50, difficulty: 'Core',
          description: 'Build a step that splits a full name into first name and last name.',
          criteria: ['First and last name come out as separate fields', 'Works on a two-word and a three-word name', 'Split logic shown in the workflow, not done by hand'],
          hint: 'Split on the first space only - everything after it belongs to the last name.',
          solution: 'Check the three-word-name case (e.g. Muhammad Ali Khan).' },
        { title: 'City Filter', points: 50, difficulty: 'Core',
          description: 'Filter incoming leads so only ones from a chosen city continue down the workflow.',
          criteria: ['Filter condition matches the city field', 'A lead from another city is stopped', 'A matching lead passes through'],
          hint: 'Test both sides of the filter - one lead that should pass and one that should be dropped.',
          solution: 'Both test cases (pass + drop) evidenced in screenshots.' },
        { title: 'Human-Readable Dates', points: 60, difficulty: 'Core',
          description: 'Turn a raw timestamp into a human-readable date inside a notification.',
          criteria: ['Raw timestamp converted with a formatter step', 'Output reads naturally (e.g. 16 Jul 2026, 9:00 am)', 'Timezone is handled deliberately'],
          hint: 'Use the date/time formatter node rather than string surgery - and set the timezone explicitly.',
          solution: 'Formatter node used; timezone stated.' },
        { title: 'Lead Summary Line', points: 80, difficulty: 'Boss',
          description: 'Combine two fields into a single lead summary line and write it to a sheet.',
          criteria: ['Two fields merged into one clean line', 'Summary written to a new sheet column', 'Format stays consistent across multiple test leads'],
          hint: 'Decide the exact sentence shape first ("Ayesha from Lahore - budget 50k"), then map fields into it.',
          solution: 'Consistency across 2+ test rows is the bar.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Connecting the apps clients live in', topic: 'Sheets, Gmail, Slack and Calendar connections, safe authentication, and the HTTP node for any API',
      problems: [
        { title: 'Welcome Mailer', points: 40, difficulty: 'Basic',
          description: 'Build a workflow that emails a personalised welcome to every new row added to a sheet.',
          criteria: ['Triggers on a new sheet row', 'Email greets the person by their mapped name', 'A test email actually arrives'],
          hint: 'Personalisation means mapped fields in the subject or body - test with your own address.',
          solution: 'Mapped name in the received email = pass.' },
        { title: 'RSS to Slack', points: 50, difficulty: 'Core',
          description: 'Auto-post new items from an RSS or blog feed into a Slack channel.',
          criteria: ['Feed is polled for new items only', 'Post includes title and link', 'Duplicates are not re-posted'],
          hint: 'Most RSS triggers de-duplicate by item ID for you - confirm it by running twice.',
          solution: 'Run twice; second run must not repost old items.' },
        { title: 'Row to Calendar', points: 50, difficulty: 'Core',
          description: 'When a new row is added to a sheet, create a matching Google Calendar event.',
          criteria: ['Event created from row data', 'Date/time fields map correctly', 'Event title is meaningful, not raw data'],
          hint: 'Get the date column into ISO format before it reaches the Calendar node.',
          solution: 'Check date mapping - the classic failure is a text date the Calendar node rejects.' },
        { title: 'Contact Form Pipeline', points: 60, difficulty: 'Core',
          description: 'Build a contact-form-to-records flow: form, then sheet, then a confirmation email back to the sender.',
          criteria: ['Form entry lands in the sheet', 'Sender receives a confirmation email', 'All three stages run from one submission'],
          hint: 'Chain it stage by stage - confirm the sheet write before wiring the email.',
          solution: 'One test submission should evidence all three stages.' },
        { title: 'Any API, No Connector', points: 80, difficulty: 'Boss',
          description: 'Call an external API with the HTTP node (e.g. a live currency rate) and write the result to a sheet.',
          criteria: ['HTTP node calls a real public API', 'Needed value is parsed from the JSON response', 'Result lands in the sheet'],
          hint: 'Run the HTTP node alone first and read the response shape before you try to map from it.',
          solution: 'Any free API is fine; parsing the nested JSON value is the concept.' },
      ] },
    { no: 4, week: 1, session: 4, title: 'Logic, routing, and not breaking', topic: 'Routers and switches, conditions, error alerts, and the append-or-update dedupe trick',
      problems: [
        { title: 'Hot or Cold', points: 40, difficulty: 'Basic',
          description: 'Route incoming leads: send hot ones to Slack and drop cold ones into a nurture sheet.',
          criteria: ['Router splits on a lead field', 'Hot path posts to Slack', 'Cold path writes to the nurture sheet'],
          hint: 'Define "hot" as a concrete condition (budget, keyword, dropdown answer) before wiring branches.',
          solution: 'Both branches tested with one lead each.' },
        { title: 'Approval Gate', points: 50, difficulty: 'Core',
          description: 'Build an approval path where an order above a set value goes for manual review and the rest auto-confirm.',
          criteria: ['Threshold condition works at the boundary', 'High orders go to review, not auto-confirm', 'Normal orders confirm automatically'],
          hint: 'Test an order sitting exactly on the threshold to see which side your condition sends it.',
          solution: 'Boundary-value test is what separates strong answers.' },
        { title: 'Scream on Failure', points: 50, difficulty: 'Core',
          description: 'Add error handling that pings you on Slack the moment a step fails.',
          criteria: ['Error path or error workflow configured', 'A forced failure triggers the ping', 'Ping says which step failed'],
          hint: 'Force a failure on purpose (bad credential, wrong sheet ID) to prove the alert fires.',
          solution: 'Evidence of a deliberately-triggered failure alert.' },
        { title: 'Weekdays Only', points: 60, difficulty: 'Core',
          description: 'Make a workflow that only runs on weekdays using a day condition.',
          criteria: ['Day-of-week condition present', 'Weekend executions stop early', 'Weekday executions continue'],
          hint: 'Read the current day inside the flow and branch on it - simpler than fighting cron syntax.',
          solution: 'Either cron weekday spec or an IF on the day name is fine.' },
        { title: 'Never Log Twice', points: 80, difficulty: 'Boss',
          description: 'De-duplicate a lead feed by matching on the email with append-or-update, so one lead is never logged twice.',
          criteria: ['Email used as the unique matching key', 'Re-sending the same lead updates, not duplicates', 'A new lead still appends normally'],
          hint: 'Submit the same lead twice and check the sheet - one row, updated, is the win condition.',
          solution: 'The double-submit test with a single resulting row is the pass bar.' },
      ] },
    { no: 5, week: 2, session: 5, title: 'Adding AI to the workflow', topic: 'Dropping a Claude/GPT/Gemini step into a flow, prompts built from live data, and the HTTP + AI scraper pattern',
      problems: [
        { title: 'One-Line Email Summariser', points: 40, difficulty: 'Basic',
          description: 'Auto-summarise every incoming customer email into a single line written to a sheet - the highest-ROI automation of the year.',
          criteria: ['AI step receives the real email body', 'Summary is reliably one line', 'Summary lands in the sheet'],
          hint: 'Tell the model the exact output shape ("one line, max 20 words, no preamble") or it will ramble.',
          solution: 'Constrained prompt + sheet write on 2+ test emails.' },
        { title: 'Support Sorter', points: 50, difficulty: 'Core',
          description: 'Classify each new support message as billing, technical, or other with AI, then route it accordingly.',
          criteria: ['AI returns only one of the three fixed labels', 'Router branches on the label', 'One test message per category routed correctly'],
          hint: 'Force the label set in the prompt ("reply with exactly one word: billing, technical, or other").',
          solution: 'Fixed label set + working router = pass.' },
        { title: 'Reply Draft Machine', points: 50, difficulty: 'Core',
          description: 'Generate a personalised reply draft for every new lead using AI (draft only - a human sends it).',
          criteria: ['Draft uses the lead\'s actual details', 'Tone instruction present in the prompt', 'Draft goes to the owner, never straight to the lead'],
          hint: 'The human-approval habit is the professional part - the draft should land in your inbox or Slack.',
          solution: 'Auto-sending to the customer fails the exercise.' },
        { title: 'Universal Scraper', points: 60, difficulty: 'Core',
          description: 'Use the HTTP + AI scraper pattern: pull a web page and have the model extract the three facts you care about.',
          criteria: ['HTTP node fetches the raw page', 'AI extracts three named facts', 'Output is structured, not a paragraph'],
          hint: 'Hand the messy HTML straight to the model and ask for a fixed JSON of your three fields.',
          solution: 'Structured extraction from raw HTML is the concept.' },
        { title: 'Invoice Reader', points: 80, difficulty: 'Boss',
          description: 'Extract structured fields - total, date, and vendor - from a messy invoice or receipt into a sheet.',
          criteria: ['All three fields extracted correctly', 'Output format fixed so the sheet mapping never breaks', 'Tested on two different invoices'],
          hint: 'Demand JSON with exactly those three keys, then map the parsed values to columns.',
          solution: 'Two different invoices parsed correctly = pass.' },
      ] },
    { no: 6, week: 2, session: 6, title: 'AI content and data pipelines', topic: 'Chaining AI steps: content repurposing, sentiment, translation, and enforcing fixed output formats',
      problems: [
        { title: 'Topic to LinkedIn Post', points: 40, difficulty: 'Basic',
          description: 'Build a repurposing pipeline: one topic in a sheet becomes a drafted LinkedIn post - the single most in-demand content automation.',
          criteria: ['Topic read from the sheet', 'AI drafts a complete post', 'Draft written back or delivered for review'],
          hint: 'Give the model a post structure (hook, body, call to action) so drafts come out consistent.',
          solution: 'Structured prompt; draft stored for human review.' },
        { title: 'Blog to Captions', points: 50, difficulty: 'Core',
          description: 'Turn one blog post into a set of short social captions automatically.',
          criteria: ['Full post goes in, multiple captions come out', 'Caption count and length constrained', 'Captions are genuinely distinct, not repeats'],
          hint: 'Ask for a numbered list of exactly N captions under a character limit.',
          solution: 'Constrained, distinct captions = pass.' },
        { title: 'Review Sentiment Guard', points: 50, difficulty: 'Core',
          description: 'Run sentiment on new reviews and flag the negative ones straight to Slack.',
          criteria: ['Sentiment step labels each review', 'Only negatives reach Slack', 'Flag message includes the review text'],
          hint: 'Three fixed labels (positive/neutral/negative) filter far more reliably than a 1-10 score.',
          solution: 'Fixed labels + negative-only routing.' },
        { title: 'Auto Translator', points: 60, difficulty: 'Core',
          description: 'Auto-translate incoming messages into English and store both versions side by side.',
          criteria: ['Original and translation stored together', 'Non-English test message handled', 'Already-English input passes through sensibly'],
          hint: 'Tell the model to return the text unchanged when it is already English - and test that case.',
          solution: 'The already-English edge case separates strong answers.' },
        { title: 'SEO Batch Run', points: 80, difficulty: 'Boss',
          description: 'Generate SEO meta descriptions for a whole list of page titles in one run.',
          criteria: ['Loops over every row in the list', 'Each description respects a length limit', 'Results written back beside their titles'],
          hint: 'Iterate row by row rather than one giant prompt - per-row output stays parseable.',
          solution: 'Whole list processed, length-limited, mapped back.' },
      ] },
    { no: 7, week: 2, session: 7, title: 'AI agents and tool calling', topic: 'The AI Agent node\'s four parts - chat model, system prompt, memory, tools - and the jump from workflow to agent',
      problems: [
        { title: 'Sheet-Brained Agent', points: 40, difficulty: 'Basic',
          description: 'Build an AI agent that answers questions from a Google Sheet used as its knowledge base.',
          criteria: ['Agent has the sheet wired as a tool or context', 'Answers come from sheet data, not invention', 'One question answered correctly in testing'],
          hint: 'Ask something only your sheet knows - if the answer matches the sheet, the wiring works.',
          solution: 'Grounded answer traceable to the sheet.' },
        { title: 'Think, Then Act', points: 50, difficulty: 'Core',
          description: 'Build an agent that reads a request and decides on its own whether to look something up, calculate, or just reply.',
          criteria: ['Agent has at least two tools', 'Tool choice differs across test requests', 'Direct-reply case works with no tool call'],
          hint: 'Send three requests engineered for three different behaviours and screenshot the run logs.',
          solution: 'Run logs must show different tool choices.' },
        { title: 'Follow-Up Sender', points: 50, difficulty: 'Core',
          description: 'Give an agent a send-email tool and have it draft and send follow-ups.',
          criteria: ['Send-email wired as an agent tool', 'Draft is contextual to the lead', 'A safety rule limits who it can email'],
          hint: 'Constrain the tool (test addresses only) in the system prompt - agents with send powers need fences.',
          solution: 'Working tool call + a stated guardrail.' },
        { title: 'FAQ Chatbot', points: 60, difficulty: 'Core',
          description: 'Wire a customer FAQ agent to a webhook so it behaves like a chatbot.',
          criteria: ['Webhook in, agent answer out', 'Answers grounded in the FAQ content', 'Off-topic questions politely declined'],
          hint: 'Test with one FAQ question and one nonsense question - the second reveals your system prompt quality.',
          solution: 'Grounded answers + polite refusal on drift.' },
        { title: 'Agent With a Memory', points: 80, difficulty: 'Boss',
          description: 'Add simple memory so the agent remembers a name and the last few messages.',
          criteria: ['Memory component attached', 'Agent recalls the name given earlier in the chat', 'Recall shown across at least three turns'],
          hint: 'Tell it your name in turn one, ask "what is my name?" in turn three - screenshot both.',
          solution: 'The three-turn recall test is the pass bar.' },
      ] },
    { no: 8, week: 2, session: 8, title: 'Capstone: a client-ready automation', topic: 'Packaging, documenting and pricing your automation - plus the human check before anything auto-sends',
      problems: [
        { title: 'Build the Intake', points: 50, difficulty: 'Core',
          description: 'Build the capstone intake: a form or webhook that captures every lead detail into a sheet.',
          criteria: ['All lead fields captured', 'Sheet is clean and consistently formatted', 'Tested with multiple sample leads'],
          hint: 'This sheet is the backbone of the whole autopilot - name columns like a database, not a scratchpad.',
          solution: 'Clean schema + multiple test rows.' },
        { title: 'Enrich and Score', points: 60, difficulty: 'Core',
          description: 'Add AI enrichment that classifies each lead by intent and gives it a score.',
          criteria: ['Intent label from a fixed set', 'Numeric score with stated meaning', 'Both written back to the lead row'],
          hint: 'Define the score scale in the prompt (e.g. 1-10 with anchors) or scores will drift run to run.',
          solution: 'Fixed labels + anchored scoring.' },
        { title: 'Route Hot and Cold', points: 60, difficulty: 'Core',
          description: 'Add routing: hot leads go to Slack with an instant AI reply draft, the rest to nurture.',
          criteria: ['Routing keyed on the AI score/intent', 'Hot path includes the AI reply draft', 'Nurture path records cold leads'],
          hint: 'Reuse your Class 4 router and Class 5 draft machine - the capstone is assembly, not reinvention.',
          solution: 'Both paths tested with real sample leads.' },
        { title: 'The Daily Digest', points: 70, difficulty: 'Core',
          description: 'Add a daily AI digest email that summarises every new lead for the client.',
          criteria: ['Scheduled once daily', 'Digest covers all of that day\'s leads', 'Readable in under a minute'],
          hint: 'Aggregate the day\'s rows first, then send one summarisation call - not one per lead.',
          solution: 'One scheduled run, one aggregated summary.' },
        { title: 'Package and Pitch', points: 120, difficulty: 'Boss',
          description: 'Document the whole workflow as a one-page runbook and write a one-paragraph pitch you could post on Upwork to sell it. Submit runbook + pitch + workflow export as PDF/Word.',
          criteria: ['Runbook lets a stranger operate the automation', 'Pitch sells the outcome, not the node list', 'Workflow export included and importable'],
          hint: 'Write the pitch around what the owner stops doing manually - clients buy saved hours, not "n8n nodes".',
          solution: 'Rubric: working end-to-end 40%, runbook clarity 30%, pitch quality 30%.' },
      ] },
  ],
},
{
  key: 'bc02-prompting', course_code: 'BC-02', title: 'Prompt Engineering & ChatGPT/Claude Mastery',
  description: 'No theory to memorise - only prompts to write, run and sharpen in the built-in Prompt Lab. Week 1 builds control over a single prompt; Week 2 turns prompts into systems and sellable products.',
  outcome: 'Leave able to make a model do reliable, professional work on demand - and package that skill into a reusable prompt asset you can sell or use daily at work.',
  submission: 'prompt',
  key_concepts: [
    'The five-part prompt: role, task, context, format, constraints', 'Structured, reliable output and few-shot prompting',
    'The five work patterns: rewrite, extract, summarise, classify, generate', 'Reasoning, decomposition, and self-check prompts',
    'Prompt chaining into multi-step workflows', 'Custom GPTs and Claude Projects with guardrails',
    'Domain prompt packs that sell', 'Packaging prompts as a reusable product',
  ],
  end_project: {
    title: 'A Deployable Custom Assistant and Prompt Pack',
    tagline: 'A live, shareable assistant plus a pack someone could buy and use today.',
    description: 'One working custom assistant (a Custom GPT or Claude Project) built for a specific profession, backed by a documented prompt pack - packaged as a product: a link a buyer can open and a guide they can follow, proven consistent across real inputs.',
    includes: [
      'A defined niche and the exact problem the assistant solves',
      'A strong system prompt: persona, rules, output format, and clean refusals when asked to drift',
      'A small knowledge base or instruction set loaded into it',
      'At least one reliable prompt chain built into the usage guide',
      'A prompt pack of five or more reusable prompts with placeholders and fixed output formats',
      'Tested on three or more real inputs for consistent results',
      'A short usage guide and a one-line sales pitch',
    ],
    shipped_when: 'The assistant is live and shareable by link, behaves consistently across test inputs, stays on topic and refuses off-topic asks, and the pack is a clean document a buyer could use with no editing.',
  },
  pass_mark: 60, titleNames: ['Prompt Rookie', 'Context Crafter', 'Instruction Designer', 'Prompt Engineer'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'The anatomy of a strong prompt', topic: 'Role, task, context, format, constraints - the five parts that separate a vague ask from a reliable one',
      problems: [
        { title: 'Lazy Prompt Rebuild', points: 40, difficulty: 'Basic',
          description: 'Rewrite a lazy prompt ("write about marketing") into a full role + task + context + format prompt in the Prompt Lab, run both, and note the difference.',
          criteria: ['All five parts present in the rebuilt prompt', 'Both versions actually run in the workbook', 'One-line note names what improved and why'],
          hint: 'Add one part at a time and rerun - you will see exactly which block does the heavy lifting.',
          solution: 'Both runs in the workbook + a genuine quality jump.' },
        { title: 'Bullets to LinkedIn', points: 50, difficulty: 'Core',
          description: 'Write a prompt that turns rough bullet points into a polished LinkedIn post in a set tone.',
          criteria: ['Tone named explicitly in the prompt', 'Output is a complete post, not bullets restated', 'Works on a second set of bullets without editing the prompt'],
          hint: 'Describe the tone with an example phrase, not just an adjective - "confident but never salesy" beats "professional".',
          solution: 'Reusability across two inputs is the bar.' },
        { title: 'The Tough Interviewer', points: 50, difficulty: 'Core',
          description: 'Write a prompt that makes the model act as a tough interviewer for a job you actually want.',
          criteria: ['Role and job context set clearly', 'Questions are challenging and role-specific', 'Interviewer stays in character across turns'],
          hint: 'Give it rules of engagement: one question at a time, follow up on weak answers, never break character.',
          solution: 'In-character multi-turn behaviour in the workbook.' },
        { title: 'Explain It to a 12-Year-Old', points: 60, difficulty: 'Core',
          description: 'Write a prompt that explains a hard topic to a twelve-year-old inside a strict word limit.',
          criteria: ['Word limit stated and respected', 'Explanation genuinely simple, no jargon', 'Topic is actually hard, not trivial'],
          hint: 'Ask it to count the words at the end - models respect limits far better when made to check.',
          solution: 'Check the limit was honoured on the run.' },
        { title: 'Seven-Day Content Table', points: 80, difficulty: 'Boss',
          description: 'Write a prompt that returns a seven-day content plan for a niche as a fixed-format table.',
          criteria: ['Table columns named in the prompt', 'All seven days present in the output', 'Rerun keeps the identical format'],
          hint: 'Spell out the exact header row you want - the model will fill a template far more reliably than invent one.',
          solution: 'Two runs, same structure = pass.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Reliable, structured output', topic: 'Forcing clean tables, JSON and fixed sections every time, plus few-shot examples and filler-killing constraints',
      problems: [
        { title: 'Markdown Table Contract', points: 40, difficulty: 'Basic',
          description: 'Write a prompt that always returns a clean markdown table with the exact columns you named.',
          criteria: ['Columns specified in the prompt', 'Output is a valid markdown table', 'Holds on a rerun with different data'],
          hint: 'Add "output the table only - no text before or after" to kill the preamble.',
          solution: 'Format stability across two runs.' },
        { title: 'Messy Text to JSON', points: 50, difficulty: 'Core',
          description: 'Write a prompt that pulls contact details out of a messy paragraph into JSON.',
          criteria: ['JSON keys defined in the prompt', 'Output parses as valid JSON', 'Missing fields handled (null, not invented)'],
          hint: 'Show the exact JSON shape you want and say "use null for anything not present".',
          solution: 'Valid JSON + honest nulls.' },
        { title: 'House Style Few-Shot', points: 50, difficulty: 'Core',
          description: 'Use two example captions to lock a house style, then have the model generate five more that match.',
          criteria: ['Two examples embedded in the prompt', 'Five new captions generated', 'New captions genuinely match the example style'],
          hint: 'Keep the two examples consistent with each other - inconsistent examples confuse more than help.',
          solution: 'Style match is judged against the examples.' },
        { title: 'Exactly Three Options', points: 60, difficulty: 'Core',
          description: 'Write a prompt that returns exactly three options - no intro, no closing line, every single time.',
          criteria: ['Exactly three options in the output', 'Zero preamble or sign-off', 'Holds on a second run'],
          hint: 'Constraints work best as hard rules: "Output exactly 3 numbered options. Nothing else."',
          solution: 'Both runs clean = pass.' },
        { title: 'The Silent Classifier', points: 80, difficulty: 'Boss',
          description: 'Write a classifier prompt that sorts customer messages into fixed categories and outputs nothing else.',
          criteria: ['Category set is closed and named', 'Output is the label only', 'Five test messages classified correctly'],
          hint: 'Include one ambiguous test message - a good classifier prompt says how to break ties.',
          solution: 'Label-only output on all five tests.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'The five daily work patterns', topic: 'Rewrite, extract, summarise, classify, generate - the five moves that cover most real work',
      problems: [
        { title: 'Thread to Three Lines', points: 40, difficulty: 'Basic',
          description: 'Summarise a long email thread into a three-line action summary.',
          criteria: ['Exactly three lines', 'Actions and owners surface, not chit-chat', 'Nothing important from the thread is lost'],
          hint: 'Ask for "who must do what by when" - that framing filters the noise automatically.',
          solution: 'Compare against the thread for dropped actions.' },
        { title: 'Meeting Notes Miner', points: 50, difficulty: 'Core',
          description: 'Extract every task and its owner from meeting notes into a checklist.',
          criteria: ['All tasks captured', 'Each task paired with its owner', 'Checklist format, ready to paste'],
          hint: 'Tell it to mark unowned tasks as "UNASSIGNED" rather than guessing an owner.',
          solution: 'Completeness check against the source notes.' },
        { title: 'Blunt to Professional', points: 50, difficulty: 'Core',
          description: 'Rewrite a blunt message into a polite, professional one without losing the point.',
          criteria: ['Core message fully intact', 'Tone genuinely professional', 'No apologetic padding that weakens it'],
          hint: 'Add "keep it firm - polite does not mean soft" or the rewrite will over-cushion.',
          solution: 'Point preserved + tone fixed.' },
        { title: 'Ticket Triage', points: 60, difficulty: 'Core',
          description: 'Classify a list of ten support tickets by urgency.',
          criteria: ['Urgency levels defined in the prompt', 'All ten tickets labelled', 'Borderline cases labelled consistently'],
          hint: 'Define each urgency level with one example so the model has anchors, not vibes.',
          solution: 'Consistent anchored labels across the ten.' },
        { title: 'Five Cold Emails', points: 80, difficulty: 'Boss',
          description: 'Generate five genuinely different cold outreach emails for one service.',
          criteria: ['Five distinct angles, not five rewordings', 'Each has a clear hook and call to action', 'All stay truthful to the service'],
          hint: 'Name five different angles in the prompt (pain, proof, curiosity, offer, story) and demand one email per angle.',
          solution: 'Distinctness of angle is the grade.' },
      ] },
    { no: 4, week: 1, session: 4, title: 'Reasoning and reliability', topic: 'Step-by-step working, decomposing big tasks, self-check instructions, and making the model ask before guessing',
      problems: [
        { title: 'Show the Working', points: 40, difficulty: 'Basic',
          description: 'Prompt the model to solve a multi-step word problem showing each step, then verify the result yourself.',
          criteria: ['Steps shown, not just the answer', 'Final answer verified by hand', 'Verification noted in the workbook'],
          hint: 'Pick a problem where a shortcut mistake is easy - that is where step-by-step earns its keep.',
          solution: 'Hand verification stated = pass.' },
        { title: 'Launch Plan Decomposer', points: 50, difficulty: 'Core',
          description: 'Have a prompt break a big goal - plan a product launch - into a clean sequenced step list.',
          criteria: ['Steps in genuine dependency order', 'Each step concrete enough to act on', 'No vague filler steps'],
          hint: 'Ask it to mark which steps block which - that forces real sequencing.',
          solution: 'Sequence logic is what you grade.' },
        { title: 'Self-Check Draft', points: 50, difficulty: 'Core',
          description: 'Add a self-check instruction so the model reviews and corrects its own draft before finalising.',
          criteria: ['Prompt contains an explicit review step', 'The check catches or confirms something specific', 'Final output reflects the correction'],
          hint: 'Give the checker a checklist ("check numbers, names, tone") - "review your answer" alone is too weak.',
          solution: 'Visible check-then-fix in the run.' },
        { title: 'Ask Before Guessing', points: 60, difficulty: 'Core',
          description: 'Write a prompt that asks two clarifying questions before it attempts an ambiguous brief.',
          criteria: ['Model asks exactly two questions first', 'Questions target the real ambiguities', 'Only proceeds after answers'],
          hint: 'Feed it a genuinely vague brief - a specific brief gives the questions nothing to grab.',
          solution: 'Question quality over question count.' },
        { title: 'Direct vs Reasoned', points: 80, difficulty: 'Boss',
          description: 'Run a direct prompt and a reasoning prompt on the same tricky question and note where they differ.',
          criteria: ['Both runs in the workbook', 'Difference described concretely', 'Conclusion on when reasoning prompts matter'],
          hint: 'Trick questions with units, dates or percentages show the sharpest gaps.',
          solution: 'The comparison note is the deliverable.' },
      ] },
    { no: 5, week: 2, session: 5, title: 'Prompt chaining and workflows', topic: 'Multi-step prompting where each output feeds the next, and designing chains you can rerun forever',
      problems: [
        { title: 'Idea, Outline, Draft', points: 40, difficulty: 'Basic',
          description: 'Chain three prompts in the Prompt Lab: idea, then outline, then full draft.',
          criteria: ['Three distinct chained steps', 'Each step consumes the previous output', 'Final draft traceable back to the idea'],
          hint: 'Paste the previous output in explicitly - the chain is yours to operate, not the model\'s to remember.',
          solution: 'Three linked runs in the workbook.' },
        { title: 'Research to Report', points: 50, difficulty: 'Core',
          description: 'Chain raw research notes into key themes, then into a short report.',
          criteria: ['Themes step genuinely condenses the notes', 'Report built from the themes only', 'No invented facts along the way'],
          hint: 'Tell the report step "use only the themes above" to stop it re-imagining the research.',
          solution: 'Fact-fidelity across the chain.' },
        { title: 'Features to Ad Copy', points: 50, difficulty: 'Core',
          description: 'Chain product features into benefits, then into ad copy.',
          criteria: ['Every feature translated to a benefit', 'Copy leads with benefits, not features', 'Chain rerunnable on another product'],
          hint: 'The middle step is the skill - "what does the customer get?" per feature, one line each.',
          solution: 'Benefit translation quality.' },
        { title: 'Transcript Multiplier', points: 60, difficulty: 'Core',
          description: 'Chain a transcript into a summary, then social posts, then a newsletter.',
          criteria: ['All three outputs produced in order', 'Each output fits its format', 'Voice stays consistent throughout'],
          hint: 'Set the voice once at the top of the chain and repeat it in every step.',
          solution: 'Three format-correct outputs.' },
        { title: 'The Repurposing Machine', points: 80, difficulty: 'Boss',
          description: 'Build a reusable content repurposing chain and run it end to end on one source piece.',
          criteria: ['Chain documented step by step with placeholders', 'Full run on a real source shown', 'A stranger could rerun it from the doc'],
          hint: 'Write each step as PROMPT + WHERE ITS INPUT COMES FROM - that is what makes it reusable.',
          solution: 'Rerunnability by a stranger is the bar.' },
      ] },
    { no: 6, week: 2, session: 6, title: 'Custom assistants', topic: 'System prompts that hold, Custom GPTs / Claude Projects with knowledge, personas, firm rules and refusing drift',
      problems: [
        { title: 'Brand Voice Keeper', points: 40, difficulty: 'Basic',
          description: 'Write a system prompt for a brand voice assistant that always writes in one defined tone.',
          criteria: ['Tone defined with examples, not adjectives', 'Holds across three different requests', 'Never slips into generic AI voice'],
          hint: 'Include two sample sentences in the voice - examples anchor tone better than descriptions.',
          solution: 'Tone stability across three test asks.' },
        { title: 'Resume Builder Bot', points: 50, difficulty: 'Core',
          description: 'Build a custom assistant that helps write resumes and cover letters to a set structure.',
          criteria: ['Structure enforced in the system prompt', 'Asks for missing info instead of inventing it', 'Output ready to paste'],
          hint: 'List the exact sections and their order - and forbid invented achievements explicitly.',
          solution: 'Structure + no-invention rule both hold.' },
        { title: 'Study Buddy With Rules', points: 50, difficulty: 'Core',
          description: 'Create a study buddy assistant with fixed rules: it quizzes, it never just hands over the answer.',
          criteria: ['Quizzes rather than answers', 'Holds the rule when begged for the answer', 'Gives hints that teach'],
          hint: 'Test it by asking for the answer directly - the rule only counts if it survives pressure.',
          solution: 'The pressure test is the grade.' },
        { title: 'FAQ-Only Support Agent', points: 60, difficulty: 'Core',
          description: 'Build a support assistant given a small FAQ as its only knowledge.',
          criteria: ['Answers strictly from the FAQ', 'Says "I don\'t know" beyond it', 'Cites which FAQ entry it used'],
          hint: 'Ask one question the FAQ cannot answer - honest refusal there is the pass condition.',
          solution: 'Grounded answers + honest gaps.' },
        { title: 'The Drift Refuser', points: 80, difficulty: 'Boss',
          description: 'Write a system prompt that keeps an assistant strictly on one subject and politely refuses off-topic asks.',
          criteria: ['On-topic questions answered normally', 'Off-topic asks refused politely', 'Refusal redirects back to the subject'],
          hint: 'Script the refusal sentence in the system prompt so the model does not improvise a rude one.',
          solution: 'Test both sides: one on-topic, two off-topic.' },
      ] },
    { no: 7, week: 2, session: 7, title: 'Domain prompts that sell', topic: 'Where prompt skill turns into paid work - marketing, coding, data, business - and pricing by the outcome it saves',
      problems: [
        { title: 'Campaign Brief Generator', points: 40, difficulty: 'Basic',
          description: 'Marketing: a prompt that produces a full campaign brief from one product line.',
          criteria: ['Brief covers audience, message, channels, timeline', 'Works from a single product-line input', 'Output paste-ready for a marketer'],
          hint: 'Steal the section headings from a real campaign brief template and hard-code them.',
          solution: 'Completeness of the brief sections.' },
        { title: 'Code Review Prompt', points: 50, difficulty: 'Core',
          description: 'Coding: a prompt that reviews a code snippet and lists the bugs and their fixes.',
          criteria: ['Bugs listed with line references', 'Each bug paired with a concrete fix', 'No invented issues on clean code'],
          hint: 'Test it on clean code too - a reviewer that always finds "bugs" is worthless.',
          solution: 'The clean-code test separates real prompts.' },
        { title: 'Numbers to Insight', points: 50, difficulty: 'Core',
          description: 'Data: a prompt that reads pasted numbers and writes a short insight summary.',
          criteria: ['Insights reference actual figures', 'Top trend and top risk named', 'No claims the data cannot support'],
          hint: 'Demand "every claim must quote a number from the data" - it kills hallucinated insights.',
          solution: 'Claim-to-number traceability.' },
        { title: 'Idea to One-Pager', points: 60, difficulty: 'Core',
          description: 'Business: a prompt that turns a rough idea into a one-page plan.',
          criteria: ['Fixed one-page structure', 'Covers problem, solution, market, next steps', 'Fits one page - genuinely'],
          hint: 'Cap each section at 2-3 sentences in the prompt or it will sprawl past a page.',
          solution: 'Structure + length discipline.' },
        { title: 'Profession Pack of Five', points: 80, difficulty: 'Boss',
          description: 'Build a pack of five reusable prompts for one profession of your choice.',
          criteria: ['Five prompts, one coherent profession', 'Each has placeholders for the buyer\'s inputs', 'Each run at least once in the workbook'],
          hint: 'Pick the profession\'s five most repeated tasks - reusability comes from frequency.',
          solution: 'Runs shown for all five prompts.' },
      ] },
    { no: 8, week: 2, session: 8, title: 'Capstone: a reusable prompt product', topic: 'Packaging prompts as a sellable asset: placeholders, consistency testing, a usage guide and a one-line pitch',
      problems: [
        { title: 'Name the Problem', points: 50, difficulty: 'Core',
          description: 'Pick a niche and write down the exact problem your prompt product solves.',
          criteria: ['Niche specific enough to name a buyer', 'Problem stated in the buyer\'s words', 'One line on why AI + your prompt beats doing it manually'],
          hint: 'If you cannot picture one specific person paying for this, narrow the niche again.',
          solution: 'Specificity of niche and problem.' },
        { title: 'The Core Prompt', points: 60, difficulty: 'Core',
          description: 'Build the core reusable prompt with clear placeholders for the inputs.',
          criteria: ['Placeholders clearly marked', 'Instructions survive any reasonable input', 'Run once with placeholders filled'],
          hint: 'Use loud placeholders like [PASTE PRODUCT DETAILS HERE] - buyers skim.',
          solution: 'One filled run in the workbook.' },
        { title: 'Zero-Edit Output', points: 60, difficulty: 'Core',
          description: 'Add a structured output format the buyer can use with no editing.',
          criteria: ['Output format fixed and named', 'Result usable as-is by the buyer', 'No AI preamble or sign-off'],
          hint: 'Picture where the buyer pastes the output - format for that exact destination.',
          solution: 'Paste-ready output on the test run.' },
        { title: 'The Consistency Gauntlet', points: 70, difficulty: 'Core',
          description: 'Test the prompt on three different inputs and tighten it until the results stay consistent.',
          criteria: ['Three genuinely different inputs run', 'Inconsistencies found and fixed', 'Final version rerun clean'],
          hint: 'Make input three an awkward edge case - easy inputs hide weak prompts.',
          solution: 'Before/after tightening visible in the workbook.' },
        { title: 'Guide and Pitch', points: 120, difficulty: 'Boss',
          description: 'Write a short usage guide and a one-line sales pitch for your prompt product, and submit the complete workbook.',
          criteria: ['Guide covers setup, inputs and expected output', 'Pitch sells the outcome in one line', 'Complete product runs shown in the workbook'],
          hint: 'The pitch formula: who it is for + what they get + how fast.',
          solution: 'Rubric: product quality 40%, consistency evidence 30%, guide + pitch 30%.' },
      ] },
  ],
},
{
  key: 'bc03-everyday-ai', course_code: 'BC-03', free: true, title: 'Everyday AI: Smarter Study, Work & Content',
  description: 'Everyday AI is a free two-week bootcamp that teaches you to use ChatGPT, Claude, and Gemini to study smarter, work faster, and create better content. No coding, no jargon - just practical AI skills you will use the same day, from summarising a textbook chapter to writing emails and planning your week. Open to everyone in Pakistan who wants to stop watching AI from the sidelines and start actually using it.',
  outcome: 'Leave with three real weekly tasks automated with AI, a custom assistant built for your most frequent task, and proof - in saved minutes - that you now study, work and create faster than you did two weeks ago.',
  submission: 'prompt',
  instructor: 'Associate Instructor: 1+ year of practical AI use, a strong communicator with a content or education background.',
  keywords: ['free AI course', 'learn ChatGPT free', 'AI course Pakistan', 'AI for students', 'free AI bootcamp', 'ChatGPT for studying', 'AI tools for work', 'artificial intelligence for beginners', 'everyday AI course'],
  key_concepts: [
    'Talking to AI so it understands you', 'The five parts of a prompt that works',
    'AI for studying and revision', 'AI for everyday work tasks',
    'AI for content and social media', 'Checking AI output and spotting mistakes',
    'Building your own AI helper', 'Using AI honestly and safely',
  ],
  end_project: {
    title: 'Your Personal AI Workflow',
    tagline: 'Three real tasks from your own week, automated with AI and proven to save you time.',
    description: 'Pick three things you genuinely do every week - studying, working, or creating - and build a reliable AI workflow for each one. This is not a hypothetical exercise: by the end you should be finishing real tasks faster than you were two weeks ago.',
    includes: [
      'Three real recurring tasks from your own study, work, or content life',
      'A tested, reusable prompt saved for each one',
      'One custom AI assistant built for your most frequent task',
      'A before and after time comparison for at least one task',
      'A fact-check step written into any prompt that produces claims',
      'A short note on where you still do the work yourself, and why',
      'Everything saved in one document you can reuse next week',
    ],
    shipped_when: 'You run all three workflows on a real task in front of the class, the output is good enough to use as it is, and you can show the time you saved.',
  },
  pass_mark: 60, titleNames: ['AI Curious', 'Daily Driver', 'Productivity Pro', 'AI Power User'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Meeting AI properly', topic: 'What ChatGPT, Claude and Gemini actually do, choosing the right tool for the job, and the five parts of a strong prompt: role, task, context, format, limits',
      problems: [
        { title: 'Three Tools, One Question', points: 40, difficulty: 'Basic',
          description: 'Ask ChatGPT, Claude, and Gemini the same real question from your own life, paste all three answers into the workbook, and note which one you would actually use and why.',
          criteria: ['The same real question put to all three tools', 'All three answers captured in the workbook', 'A clear pick with a concrete reason, not just a vibe'],
          hint: 'Pick a question you genuinely need answered this week - real stakes make the differences between the tools obvious.',
          solution: 'Three real answers + a reasoned pick = pass.' },
        { title: 'Lazy Prompt Rescue', points: 50, difficulty: 'Core',
          description: 'Take a lazy prompt like "help me with my assignment" and rewrite it with role, task, context, and format. Run both versions and note the difference.',
          criteria: ['All four parts present in the rebuilt prompt', 'Both versions actually run in the workbook', 'One line naming what improved and why'],
          hint: 'Add the parts one at a time and rerun - you will see exactly which block does the heavy lifting.',
          solution: 'Both runs in the workbook + a genuine quality jump.' },
        { title: 'Three Levels Until It Clicks', points: 50, difficulty: 'Core',
          description: 'Ask AI to explain a topic you find hard at three different levels - like you are ten, like a fellow student, like an expert - until one finally clicks.',
          criteria: ['The topic is genuinely hard for you', 'Three distinct explanation levels run', 'A note on which level clicked and why'],
          hint: 'Name the audience in each prompt ("explain this to a ten-year-old") - the audience line is what changes the answer.',
          solution: 'Three runs + the "which clicked" reflection.' },
        { title: 'The Strict Limit', points: 60, difficulty: 'Core',
          description: 'Give AI a task with a hard constraint: exactly five bullet points, each under ten words. Rerun and tighten the prompt until it obeys every rule.',
          criteria: ['The constraint stated explicitly in the prompt', 'Output obeys both rules exactly', 'Constraint still holds on a rerun'],
          hint: 'Ask the model to count the words in each bullet at the end - models respect limits far better when made to check.',
          solution: 'Two clean constrained runs = pass.' },
        { title: 'Catch the Lie', points: 80, difficulty: 'Boss',
          description: 'Find one thing AI got wrong or made up during this class, and write down exactly how you caught it.',
          criteria: ['A real error or invention identified', 'The wrong claim quoted in the workbook', 'The catching method described so someone else could repeat it'],
          hint: 'Ask about something specific you know cold - your own city, course, or team - errors surface fastest where you are the expert.',
          solution: 'The method write-up is the deliverable, not the gotcha.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'AI for studying and everyday work', topic: 'Summarising notes and chapters, generating practice questions, emails that sound like you, cleaning messy notes, and planning a week with AI',
      problems: [
        { title: 'One-Page Revision Sheet', points: 40, difficulty: 'Basic',
          description: 'Paste a long chapter or article into the workbook and turn it into a one-page revision sheet you would actually revise from.',
          criteria: ['A real chapter or article used as input', 'The sheet fits one page and keeps the key points', 'Nothing important invented or dropped - spot-checked against the source'],
          hint: 'Tell it the format you revise from - headings, bullets, definitions boxed - or you will get a generic summary instead of a revision sheet.',
          solution: 'Spot-check the sheet against the source material.' },
        { title: 'The Ten-Question Quiz', points: 50, difficulty: 'Core',
          description: 'Have AI quiz you with ten questions on a topic, answer them yourself, then have it mark your answers.',
          criteria: ['Ten questions generated on your topic', 'You answered before seeing the answers', 'The marking verified against your textbook or notes'],
          hint: 'Ask for the questions first and the answers only after you reply - otherwise you will peek.',
          solution: 'Verified marking is the pass bar.' },
        { title: 'Messy Notes, Clean Notes', points: 50, difficulty: 'Core',
          description: 'Turn your rough class notes into clean, organised study notes with headings and structure.',
          criteria: ['Real rough notes used as input', 'Output organised with a clear structure', 'Facts preserved - anything unclear flagged, not filled in'],
          hint: 'Tell the model to mark anything it cannot read or understand with [CHECK] instead of guessing what you meant.',
          solution: 'Clean structure + honest gap-flags.' },
        { title: 'The Polite Ask', points: 60, difficulty: 'Core',
          description: 'Write a polite email asking a teacher or manager for an extension or a meeting - drafted with AI, edited by you until it sounds like you.',
          criteria: ['The ask is clear in the first two lines', 'Tone polite but not grovelling', 'Your own edits visible - raw AI text does not pass'],
          hint: 'Give the model one sentence of real context and your usual sign-off - that is what makes the draft sound like you.',
          solution: 'The edits are the assignment.' },
        { title: 'The Realistic Week', points: 80, difficulty: 'Boss',
          description: 'Give AI your week\'s real tasks and get back a realistic day-by-day plan you would actually follow.',
          criteria: ['Your genuine task list used as input', 'Work spread across days realistically, with slack', 'Fixed commitments respected, not overwritten'],
          hint: 'Tell it your immovables first - classes, work hours, family time - then let it fill the gaps around them.',
          solution: 'Realism beats prettiness: would they actually follow it?' },
      ] },
    { no: 3, week: 2, session: 3, title: 'AI for content that sounds human', topic: 'Captions, posts and scripts that hold attention, adapting one idea across platforms, finding and fixing the AI tells, and simple image generation',
      problems: [
        { title: 'One Idea, Three Platforms', points: 40, difficulty: 'Basic',
          description: 'Turn one idea into an Instagram caption, a LinkedIn post, and a WhatsApp message - each genuinely shaped for its platform.',
          criteria: ['One idea drives all three versions', 'Each version fits its platform\'s length, tone, and habits', 'Not the same text pasted three times'],
          hint: 'Name the platform and its culture in each prompt - length, formality, emoji habits - and the outputs will diverge on their own.',
          solution: 'Platform-native differences are the grade.' },
        { title: 'Five Hooks', points: 50, difficulty: 'Core',
          description: 'Write five hooks for a short video and pick the one you would actually post, with a reason.',
          criteria: ['Five genuinely different hook angles', 'Each hook short enough to say in a couple of seconds', 'A pick with a reason you believe'],
          hint: 'Ask for five different angles - question, bold claim, common mistake, number, story - not five rewordings of one line.',
          solution: 'Distinctness of angle is what you grade.' },
        { title: 'De-AI the Paragraph', points: 50, difficulty: 'Core',
          description: 'Take an obviously AI-written paragraph and rewrite it so it sounds like a real person, naming the AI tells you removed.',
          criteria: ['The original AI paragraph included', 'The rewrite removes the tells you found', 'The tells named explicitly in the workbook'],
          hint: 'Hunt the classics: "delve", "in today\'s fast-paced world", perfectly balanced triads, and a total absence of opinion.',
          solution: 'Named tells + a genuinely human rewrite.' },
        { title: 'Only You Could Write This', points: 60, difficulty: 'Core',
          description: 'Add one specific personal example to an AI draft that only you could have written, and show the before and after.',
          criteria: ['The AI draft shown before and after', 'The added example is specific and real', 'The example woven into the draft, not bolted on'],
          hint: 'Use a moment with a place, a person, or a number in it - specifics are the one thing AI cannot fake about your life.',
          solution: 'The example must be unfakeable.' },
        { title: 'The Image Refinery', points: 80, difficulty: 'Boss',
          description: 'Generate an image for a post and refine the prompt over several rounds until the image actually fits.',
          criteria: ['First and final prompts both in the workbook', 'At least three refinement rounds shown', 'The final image genuinely fits the post it is for'],
          hint: 'Change one thing per round - style, framing, lighting - so you learn which words move the image.',
          solution: 'The prompt evolution is the deliverable.' },
      ] },
    { no: 4, week: 2, session: 4, title: 'Checking AI and building your own helper', topic: 'Spotting hallucinations, verifying facts and sources, what you should never paste into an AI tool, honest use, and a custom assistant with your own instructions',
      problems: [
        { title: 'Five Facts, Five Checks', points: 40, difficulty: 'Basic',
          description: 'Ask AI for five facts with sources, then verify each one and record what was wrong.',
          criteria: ['Five factual claims with sources requested', 'Every claim checked against a real source', 'Each marked TRUE / FALSE / UNVERIFIABLE with notes'],
          hint: 'Check the sources themselves first - AI sometimes invents the reference, not just the fact.',
          solution: 'The lesson lands when at least one claim fails the check.' },
        { title: 'Find the Invention', points: 50, difficulty: 'Core',
          description: 'Take a confident-sounding AI answer and find the part it invented.',
          criteria: ['A confident, fluent answer captured in the workbook', 'The invented or unsupported part identified', 'Evidence given for why it is wrong'],
          hint: 'Confidence is not accuracy - the smoothest sentence in the answer is often the made-up one.',
          solution: 'Identified invention + the evidence against it.' },
        { title: 'The Never-Paste List', points: 50, difficulty: 'Core',
          description: 'List the personal or private information you will never paste into an AI tool, and why.',
          criteria: ['At least five concrete types of information listed', 'Each item has a because attached', 'Covers your own IDs and accounts and other people\'s data'],
          hint: 'Think about other people\'s information too - their messages, photos, and details are not yours to paste.',
          solution: 'Reasoning quality over list length.' },
        { title: 'Build Your Assistant', points: 60, difficulty: 'Core',
          description: 'Build a custom AI assistant with your own written rules for your most common task.',
          criteria: ['Instructions written for one specific recurring task', 'Rules cover tone, format, and what it must refuse', 'The assistant produces usable output on its first real run'],
          hint: 'Write the instructions like a job description: what it does, how it answers, and what it never does.',
          solution: 'Specificity of the instruction set is the grade.' },
        { title: 'The Consistency Gauntlet', points: 80, difficulty: 'Boss',
          description: 'Test your assistant three times on different inputs and tighten its instructions until it is consistent.',
          criteria: ['Three genuinely different real inputs tested', 'Inconsistencies found and the instructions tightened', 'The final version rerun clean'],
          hint: 'Make the third test an awkward edge case - easy inputs hide weak instructions.',
          solution: 'Before/after tightening visible in the workbook.' },
      ] },
  ],
},
];
