'use strict';
/** EchoLens prebuilt track - 3D Modeling, Rendering and Introductory Animation.
 * Same 12-class, 5-quest-per-class shape as the design specialist tracks
 * (see specialist.js ST-02/ST-03) - a real week 1..6 curriculum, not a
 * coarse milestone ladder. Teachers can edit any problem or add levels via
 * the editor. Solutions are teacher-only. */

module.exports = [
{
  key: '3d01-modeling', course_code: '3D-01', title: '3D Modeling, Rendering and Introductory Animation',
  free: false, submission: 'multi',
  description: '3D Modeling, Rendering and Introductory Animation teaches you to create professional 3D visuals in Blender, the free industry standard tool. Over six live weeks you will model, texture, light, render, and animate, building a portfolio ready 3D scene from scratch with no expensive software required. Perfect for aspiring 3D artists, product designers, and animators in Pakistan who want practical, in demand 3D skills and a reel piece that wins freelance work.',
  outcome: 'Leave with a portfolio-ready 3D scene: modelled, UV unwrapped, textured, lit, rendered and animated in Blender - the exact deliverable clients pay for.',
  instructor: '3+ years in 3D, with a Blender portfolio spanning modeling, texturing, lighting, and rendering.',
  keywords: ['3D modeling course', 'learn Blender online', 'Blender course Pakistan', '3D rendering course', '3D animation for beginners', 'product visualisation course', '3D design bootcamp', 'learn 3D modeling', 'Blender for beginners'],
  key_concepts: [
    'The 3D pipeline and the Blender interface', 'Primitives and transform tools',
    'Mesh editing: extrude, inset, bevel, loop cut',
    'Modifiers: Mirror, Subdivision, Solidify, Screw, Array, Boolean',
    'Organic modeling, curves, and Shrinkwrap', 'UV unwrapping',
    'PBR texturing and materials', 'Lighting: three point and HDRI',
    'Cameras, composition, and rendering with Eevee and Cycles',
    'Animation: keyframes and interpolation',
  ],
  end_project: {
    title: 'A Rendered 3D Product Scene with Animation',
    tagline: 'One polished, lit, textured 3D scene with a short animation, the reel piece that wins 3D freelance work.',
    description: 'Combine everything from the six weeks into one finished piece: a modelled object or small scene, properly UV unwrapped and textured with PBR materials, lit for mood, composed through a camera, and finished with a short animation and a final render. Most students build a product visualisation, the exact deliverable clients pay for.',
    includes: [
      'A model built with clean geometry using at least three modifiers from the course',
      'Correct UV unwrapping with no visible stretching',
      'PBR materials with at least one image texture and one normal map',
      'A deliberate lighting setup, three point or HDRI, that sets a mood',
      'A camera composed with the rule of thirds and depth of field',
      'A short animation, a turntable or object motion, with proper interpolation',
      'A final still render and a rendered animation exported in a shareable format',
      'Consistent quality that looks intentional, not accidental',
    ],
    shipped_when: 'The still render looks like a finished product shot, the animation plays smoothly, the textures sit right with no stretching, and the piece is good enough to post on a portfolio or a reel.',
  },
  clos: [
    'CLO1: Model clean, non-destructive 3D geometry in Blender using primitives, mesh editing, and modifiers.',
    'CLO2: UV unwrap and texture a model with PBR materials, then light and compose it for a professional render.',
    'CLO3: Animate an object with keyframes and interpolation, and export a finished, portfolio-ready render.',
  ],
  pass_mark: 60, titleNames: ['Mesh Rookie', 'Modifier Apprentice', 'Texture Artisan', 'Lighting Director', '3D Generalist'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Introduction to 3D and the interface', topic: 'The 3D pipeline, interface tour, viewport shading modes, navigation and scene setup',
      problems: [
        { title: 'Frame the Cube', points: 40, difficulty: 'Basic',
          description: 'Navigate the viewport: orbit, pan, and zoom to frame the default cube from three angles.',
          criteria: ['All three navigation actions demonstrated', 'Cube framed cleanly from three distinct angles', 'Screenshots or recording show each angle'],
          hint: 'Practice with the middle mouse button for orbit and shift+middle for pan until it feels automatic.',
          solution: 'Three distinct, cleanly framed angles using real orbit/pan/zoom.' },
        { title: 'Four Shading Modes', points: 50, difficulty: 'Core',
          description: 'Switch between all four shading modes and note what each one shows.',
          criteria: ['All four modes demonstrated on the same object', 'A clear note written for each mode', 'Notes correctly describe what each mode reveals'],
          hint: 'Add a coloured material before switching modes so the difference between solid and material preview is obvious.',
          solution: 'Four accurate notes matched to four correctly identified modes.' },
        { title: 'Scene Units Setup', points: 50, difficulty: 'Core',
          description: 'Set the scene units to metric and save the file with a clear name.',
          criteria: ['Units correctly set to metric in scene properties', 'File saved with a clear, descriptive name', 'Settings verified after saving'],
          hint: 'Check the properties panel\'s scene tab, not the preferences - unit settings are per-file.',
          solution: 'A metric-configured file saved with a descriptive name.' },
        { title: 'Customise and Reset Layout', points: 60, difficulty: 'Core',
          description: 'Customise the interface layout, then reset it to default.',
          criteria: ['Layout genuinely customised (panels moved or resized)', 'Successfully reset back to the default layout', 'Both states shown or described'],
          hint: 'Use the workspace menu\'s reset option rather than manually undoing every change one by one.',
          solution: 'Evidence of a real customisation followed by a clean reset.' },
        { title: 'Name Every Editor', points: 80, difficulty: 'Boss',
          description: 'Name each editor, the viewport, outliner, properties, and timeline, and its purpose in one line.',
          criteria: ['All four editors correctly named', 'Each purpose described accurately in one line', 'Descriptions are specific, not generic'],
          hint: 'Describe what you\'d actually use each editor FOR in a real project, not just what it displays.',
          solution: 'Four accurate, specific one-line purpose descriptions.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Basic objects and transform tools', topic: 'Adding primitives, the 3D cursor, move/rotate/scale, object origin and snapping',
      problems: [
        { title: 'Arrange the Primitives', points: 40, difficulty: 'Basic',
          description: 'Add a cube, sphere, cylinder, and cone, and arrange them in a neat row.',
          criteria: ['All four primitives added', 'Arranged in a genuinely neat, evenly spaced row', 'Objects are not overlapping or misaligned'],
          hint: 'Use numeric input for the spacing between objects rather than eyeballing the gaps.',
          solution: 'Four primitives evenly and neatly arranged.' },
        { title: 'Exact Numeric Placement', points: 50, difficulty: 'Core',
          description: 'Use G, R, and S with numeric input to place an object at an exact position.',
          criteria: ['All three transforms (G, R, S) used with typed numeric values', 'Final position is verifiably exact', 'Object ends at the intended location'],
          hint: 'Type the axis letter right after G or S (like Gx5) to constrain the move to one axis precisely.',
          solution: 'An object placed at an exact, numerically verified position.' },
        { title: 'Snap to Grid', points: 50, difficulty: 'Core',
          description: 'Snap objects to the grid and to one another.',
          criteria: ['Snapping enabled and demonstrated to the grid', 'Snapping demonstrated between two objects', 'Final positions are precisely snapped, not approximate'],
          hint: 'Turn on snapping with the magnet icon and try both "increment" and "vertex" snap modes to see the difference.',
          solution: 'Evidence of precise snapping to both grid and object.' },
        { title: 'Snowman from Primitives', points: 60, difficulty: 'Core',
          description: 'Build a simple snowman from primitives using transforms only.',
          criteria: ['Built entirely from primitive shapes', 'Only move/rotate/scale used, no mesh editing', 'Recognisable as a snowman'],
          hint: 'Stack three scaled spheres and use small cones or cylinders for the details, using only transforms.',
          solution: 'A recognisable snowman built purely from transformed primitives.' },
        { title: 'Reset Origin and Rotate', points: 80, difficulty: 'Boss',
          description: 'Reset an object\'s origin and use it as the pivot for a rotation.',
          criteria: ['Origin correctly reset to a meaningful point', 'Rotation genuinely pivots around the new origin', 'Result demonstrates the origin actually changed behaviour'],
          hint: 'Use "Set Origin to 3D Cursor" after positioning the cursor exactly where you want the pivot to be.',
          solution: 'A rotation that visibly pivots from the newly set origin.' },
      ] },
    { no: 3, week: 2, session: 3, title: 'Edit mode and mesh editing basics', topic: 'Vertices, edges and faces, extrude/inset/bevel/loop cut/subdivide/merge, normals and face orientation',
      problems: [
        { title: 'L-Shaped Sofa Base', points: 40, difficulty: 'Basic',
          description: 'Extrude a cube into a simple L shaped sofa base.',
          criteria: ['Extrude used to create the L shape', 'Proportions look like a plausible sofa base', 'Geometry stays clean, no stray vertices'],
          hint: 'Select the correct face before extruding - the wrong face selection is the most common first mistake.',
          solution: 'A clean L-shaped base built with extrude.' },
        { title: 'Loop Cut and Inset Detail', points: 50, difficulty: 'Core',
          description: 'Use loop cut and inset to add detail to a face.',
          criteria: ['Loop cut used correctly', 'Inset used correctly on a face', 'Added detail looks intentional, not accidental'],
          hint: 'Scroll the mouse wheel before clicking a loop cut to control how many cuts get added at once.',
          solution: 'Deliberate, clean detail added via loop cut and inset.' },
        { title: 'Bevel for Softness', points: 50, difficulty: 'Core',
          description: 'Bevel the edges of a cube for a softer look.',
          criteria: ['Bevel applied to appropriate edges', 'Result visibly softer than a sharp cube', 'Bevel amount looks intentional, not extreme or negligible'],
          hint: 'Increase the bevel segments for a rounder look instead of just increasing the bevel width.',
          solution: 'A visibly softened cube with a well-judged bevel amount.' },
        { title: 'Model a Mug', points: 60, difficulty: 'Core',
          description: 'Model a simple mug using extrude and inset.',
          criteria: ['Recognisable mug shape and handle', 'Built using extrude and inset as the core tools', 'Geometry is clean and manifold'],
          hint: 'Model the handle as a separate loop of extrusions bridged to the body, rather than trying to inset it directly.',
          solution: 'A recognisable, cleanly built mug.' },
        { title: 'Check Face Orientation', points: 80, difficulty: 'Boss',
          description: 'Check and fix the face orientation, the normals, on a model.',
          criteria: ['Face orientation overlay used to check the model', 'Any flipped normals correctly identified', 'All normals fixed and consistent'],
          hint: 'Turn on the face orientation overlay (blue = correct, red = flipped) before assuming everything is fine.',
          solution: 'A model with fully correct, verified face orientation.' },
      ] },
    { no: 4, week: 2, session: 4, title: 'Modifiers I: Mirror and Subdivision Surface', topic: 'Non-destructive modeling philosophy, the Mirror modifier, Subdivision Surface and edge creasing',
      problems: [
        { title: 'Mirror for Symmetry', points: 40, difficulty: 'Basic',
          description: 'Model half an object and mirror it for perfect symmetry.',
          criteria: ['Only half the object modelled directly', 'Mirror modifier produces perfect symmetry', 'Modifier kept live, not applied destructively'],
          hint: 'Make sure your object\'s origin sits exactly on the mirror axis or the symmetry will be offset.',
          solution: 'A perfectly symmetrical result from a non-destructive Mirror modifier.' },
        { title: 'Smooth with Subdivision', points: 50, difficulty: 'Core',
          description: 'Apply Subdivision Surface to smooth a blocky model.',
          criteria: ['Subdivision Surface modifier added', 'Blocky model becomes visibly smoother', 'Base mesh remains editable underneath'],
          hint: 'Keep the modifier live rather than applying it, so you can still adjust the base shape afterward.',
          solution: 'A visibly smoothed model with the modifier still live and editable.' },
        { title: 'Control with Edge Creasing', points: 50, difficulty: 'Core',
          description: 'Use edge creasing to control a subdivided shape.',
          criteria: ['Creasing applied to specific edges', 'Creased edges stay sharper than the rest', 'Overall shape remains intentional and controlled'],
          hint: 'Select the edges you want to stay sharp and increase their crease value rather than adding more geometry.',
          solution: 'A subdivided shape with deliberately controlled sharp edges.' },
        { title: 'Symmetrical Character Head', points: 60, difficulty: 'Core',
          description: 'Model a symmetrical character head half using Mirror.',
          criteria: ['Only half modelled, Mirror handles the rest', 'Recognisable as a head form', 'Symmetry is clean with no visible seam'],
          hint: 'Work with proportional editing turned on to keep the organic head shape smooth as you adjust it.',
          solution: 'A recognisable, seamlessly symmetrical head half.' },
        { title: 'Combine Mirror and Subdivision', points: 80, difficulty: 'Boss',
          description: 'Combine Mirror and Subdivision on one model, kept non destructive.',
          criteria: ['Both modifiers active on the same model', 'Modifier order produces a clean result', 'Nothing applied destructively, base mesh still editable'],
          hint: 'Put Mirror above Subdivision Surface in the modifier stack - the order changes the result significantly.',
          solution: 'A clean combined result with correct modifier order, fully non-destructive.' },
      ] },
    { no: 5, week: 3, session: 5, title: 'Modifiers II: Solidify and Screw', topic: 'Solidify for thickness, Screw for lathed geometry, where each modifier fits in a real model',
      problems: [
        { title: 'Bowl Wall with Solidify', points: 40, difficulty: 'Basic',
          description: 'Give a flat plane thickness with Solidify to make a bowl wall.',
          criteria: ['Solidify modifier correctly applied', 'Thickness looks proportional to a real bowl wall', 'Shape reads clearly as a bowl'],
          hint: 'Shape the base curve of the bowl first, then add Solidify last so the thickness follows the final form.',
          solution: 'A bowl wall with proportional, correctly applied thickness.' },
        { title: 'Wine Glass with Screw', points: 50, difficulty: 'Core',
          description: 'Model a wine glass profile and lathe it with Screw.',
          criteria: ['Profile curve is a plausible half wine-glass silhouette', 'Screw modifier correctly lathes it into a full glass', 'Result is smooth and symmetrical'],
          hint: 'Model the profile as a 2D curve or edge chain right on the rotation axis before adding Screw.',
          solution: 'A smooth, symmetrical wine glass built from a lathed profile.' },
        { title: 'Spiral Spring', points: 50, difficulty: 'Core',
          description: 'Create a spiral spring using the Screw modifier.',
          criteria: ['Screw modifier settings produce a genuine spiral, not a flat ring', 'Spring proportions look plausible', 'Coil spacing is even'],
          hint: 'Increase the Screw modifier\'s "Screw" offset value to pull the lathe into a rising spiral rather than a flat circle.',
          solution: 'A plausible, evenly coiled spiral spring.' },
        { title: 'Thickness on a Curved Surface', points: 60, difficulty: 'Core',
          description: 'Add thickness to a curved surface and check the result.',
          criteria: ['Solidify applied to a genuinely curved surface', 'No visible pinching or geometry errors', 'Result checked and confirmed clean'],
          hint: 'Watch for pinching at tight curves - you may need to adjust the offset or thickness value to fix it.',
          solution: 'A curved surface with clean, error-free added thickness.' },
        { title: 'Vase from Profile', points: 80, difficulty: 'Boss',
          description: 'Model a simple vase using a profile and Screw.',
          criteria: ['Profile curve shows a considered vase silhouette', 'Screw modifier produces a clean lathed vase', 'Final form looks intentional, not accidental'],
          hint: 'Add a few more control points to your profile curve where the vase silhouette changes direction sharply.',
          solution: 'An intentional, well-formed vase built from a lathed profile.' },
      ] },
    { no: 6, week: 3, session: 6, title: 'Modifiers III: Array and Boolean', topic: 'Array for repeating geometry, Boolean union/difference/intersect, cleanup after booleans',
      problems: [
        { title: 'Array a Fence or Columns', points: 40, difficulty: 'Basic',
          description: 'Use Array to build a row of columns or a fence.',
          criteria: ['Array modifier correctly repeats the base object', 'Spacing between repeats is even', 'Count and offset look intentional'],
          hint: 'Adjust the relative offset value rather than moving copies manually to keep the spacing perfectly even.',
          solution: 'An evenly spaced, intentional row built with Array.' },
        { title: 'Boolean Difference Hole', points: 50, difficulty: 'Core',
          description: 'Use Boolean difference to cut a clean hole through a cube.',
          criteria: ['Boolean difference correctly cuts through the cube', 'Hole edges are clean, not glitchy', 'Cutting object correctly positioned before applying'],
          hint: 'Make sure the cutting object fully passes through the target on both sides, or the hole won\'t cut cleanly through.',
          solution: 'A clean, fully-cut hole with no boolean glitches.' },
        { title: 'Boolean Union', points: 50, difficulty: 'Core',
          description: 'Combine two shapes with a Boolean union.',
          criteria: ['Union correctly merges the two shapes into one', 'Resulting mesh has no visible seams or errors', 'Shapes overlap enough for a clean merge'],
          hint: 'Overlap the two shapes generously before the union - boolean operations can fail or glitch on barely-touching geometry.',
          solution: 'A cleanly merged single shape with no visible seams.' },
        { title: 'Wheel Rim with Array', points: 60, difficulty: 'Core',
          description: 'Build a simple wheel rim using Array around a centre.',
          criteria: ['Spokes correctly arrayed around a central point', 'Rotation-based array setup used, not manual duplication', 'Result reads as a plausible wheel rim'],
          hint: 'Use an empty at the wheel\'s centre as the Array modifier\'s object offset to rotate the spokes around it.',
          solution: 'A plausible wheel rim built with rotational Array.' },
        { title: 'Clean Up a Boolean Result', points: 80, difficulty: 'Boss',
          description: 'Clean up a Boolean result: remove doubles and fix n gons.',
          criteria: ['Duplicate vertices merged/removed', 'N-gons identified and resolved', 'Final mesh is clean, manifold geometry'],
          hint: 'Use "Merge by Distance" first, then check the statistics overlay or select-by-trait tools to hunt down remaining n-gons.',
          solution: 'A fully cleaned, manifold mesh with no doubles or stray n-gons.' },
      ] },
    { no: 7, week: 4, session: 7, title: 'Organic modeling and curves', topic: 'Topology for organic surfaces, Shrinkwrap and proportional editing, Bezier curves and curve-to-mesh conversion',
      problems: [
        { title: 'Proportional Editing Sculpt', points: 40, difficulty: 'Basic',
          description: 'Use proportional editing to sculpt a soft, rounded form.',
          criteria: ['Proportional editing genuinely used, not direct vertex moves', 'Result is smooth and rounded, not blocky', 'Falloff radius looks intentional'],
          hint: 'Adjust the proportional editing radius with the scroll wheel while dragging to control how wide the influence spreads.',
          solution: 'A smooth, deliberately rounded form shaped with proportional editing.' },
        { title: 'Fit with Shrinkwrap', points: 50, difficulty: 'Core',
          description: 'Use Shrinkwrap to fit one surface onto another.',
          criteria: ['Shrinkwrap modifier correctly targets the base surface', 'Fitted surface follows the target\'s contours', 'No obvious gaps or clipping'],
          hint: 'Give the fitted surface enough subdivisions first, or Shrinkwrap won\'t have enough geometry to follow the contours closely.',
          solution: 'A surface that closely, cleanly follows its Shrinkwrap target.' },
        { title: 'Bezier Curve to Mesh', points: 50, difficulty: 'Core',
          description: 'Create a Bezier curve and convert it to a mesh.',
          criteria: ['Curve shape is deliberate, not just a default line', 'Conversion to mesh completes cleanly', 'Resulting mesh is usable, not degenerate'],
          hint: 'Adjust the curve\'s bevel depth before converting so the resulting mesh actually has visible thickness.',
          solution: 'A deliberately shaped curve cleanly converted to a usable mesh.' },
        { title: 'Rope or Cable from a Curve', points: 60, difficulty: 'Core',
          description: 'Model a simple rope or cable from a curve.',
          criteria: ['Path follows a plausible, non-straight route', 'Bevel gives it a rope or cable-like thickness', 'Result reads clearly as a rope or cable'],
          hint: 'Add a few bend points to the curve path - a perfectly straight cable rarely looks convincing.',
          solution: 'A convincing rope or cable following a natural curved path.' },
        { title: 'Retopologise to Quads', points: 80, difficulty: 'Boss',
          description: 'Retopologise a rounded shape toward clean quad topology.',
          criteria: ['New topology is predominantly quads', 'Edge flow follows the form\'s natural curves', 'Result is cleaner than the starting mesh'],
          hint: 'Follow the major curves of the form with your edge loops rather than laying a generic flat grid over it.',
          solution: 'Clean, form-following quad topology, visibly improved from the start.' },
      ] },
    { no: 8, week: 4, session: 8, title: 'UV unwrapping fundamentals', topic: 'Why UVs matter, placing seams, Smart UV Project / Unwrap / Follow Active Quads, checking results in the UV editor',
      problems: [
        { title: 'Unwrap a Cube', points: 40, difficulty: 'Basic',
          description: 'Place seams on a cube and unwrap it cleanly.',
          criteria: ['Seams placed at logical edges', 'Unwrap produces a clean, non-overlapping layout', 'Faces are not distorted'],
          hint: 'Mark seams along edges you\'d naturally cut if unfolding a cardboard box, not random edges.',
          solution: 'A clean, logically seamed, non-overlapping unwrap.' },
        { title: 'Smart UV Project', points: 50, difficulty: 'Core',
          description: 'Use Smart UV Project on a complex object and inspect the result.',
          criteria: ['Smart UV Project applied to a genuinely complex object', 'Resulting UV islands inspected in the UV editor', 'Obvious problems identified, if any'],
          hint: 'Check the island margin setting before running Smart UV Project - too small a margin causes texture bleeding later.',
          solution: 'A correctly generated and honestly inspected UV layout.' },
        { title: 'Unwrap a Cylinder', points: 50, difficulty: 'Core',
          description: 'Unwrap a cylinder cleanly, like a can label.',
          criteria: ['Seam placed sensibly along one vertical edge', 'Unwrapped result looks like a flattened label shape', 'Top and bottom caps handled separately and cleanly'],
          hint: 'Mark a seam down one side and around both caps separately, just like unrolling a real can label.',
          solution: 'A cylinder unwrapped cleanly into a label-like flat shape.' },
        { title: 'Fix Stretching with a Test Grid', points: 60, difficulty: 'Core',
          description: 'Apply a test grid texture and fix any stretching.',
          criteria: ['Test grid texture applied and visible in render/preview', 'Any stretching areas correctly identified', 'Stretching fixed by adjusting seams or unwrap'],
          hint: 'Look for grid squares that turn into stretched rectangles - that\'s exactly where the UVs need more seams or relaxing.',
          solution: 'An even grid pattern across the model with stretching fixed.' },
        { title: 'Efficient UV Layout', points: 80, difficulty: 'Boss',
          description: 'Lay out the UVs efficiently in the UV editor.',
          criteria: ['UV islands packed with minimal wasted space', 'Islands are not overlapping', 'Consistent texel density across islands'],
          hint: 'Use the UV editor\'s pack islands tool as a starting point, then manually nudge for even texel density.',
          solution: 'An efficiently packed layout with consistent texel density.' },
      ] },
    { no: 9, week: 5, session: 9, title: 'Texturing and PBR materials basics', topic: 'PBR base colour/roughness/metallic/normal/height, sourcing and applying image textures, preview vs rendered view',
      problems: [
        { title: 'Base Colour Material', points: 40, difficulty: 'Basic',
          description: 'Apply a base colour material to a model.',
          criteria: ['Material correctly created and assigned', 'Base colour is visible in material preview', 'Colour choice suits the object'],
          hint: 'Check the material preview shading mode to confirm the colour is actually applying, not just set.',
          solution: 'A correctly assigned, visibly applied base colour material.' },
        { title: 'Roughness and Metallic', points: 50, difficulty: 'Core',
          description: 'Set up a PBR material with roughness and metallic.',
          criteria: ['Roughness value affects the surface believably', 'Metallic value produces the intended look (metal or non-metal)', 'Combination reads as a coherent real-world material'],
          hint: 'Materials are usually either fully metallic or fully non-metallic - values in between rarely look physically correct.',
          solution: 'A coherent, believable metallic/roughness combination.' },
        { title: 'Apply an Image Texture', points: 50, difficulty: 'Core',
          description: 'Apply an image texture using the model\'s UVs.',
          criteria: ['Texture correctly follows the model\'s UV layout', 'No obvious stretching or misalignment', 'Texture is connected through the proper shader node'],
          hint: 'Confirm your UV unwrap from the previous class is clean first - a bad unwrap will make any texture look wrong.',
          solution: 'A correctly mapped, undistorted applied texture.' },
        { title: 'Add a Normal Map', points: 60, difficulty: 'Core',
          description: 'Add a normal map for surface detail.',
          criteria: ['Normal map correctly connected through a Normal Map node', 'Surface detail is visibly enhanced', 'Normal map colour space set correctly (non-colour)'],
          hint: 'Set the normal map\'s image colour space to Non-Color, not sRGB, or the detail will look wrong.',
          solution: 'A correctly connected normal map with visible added detail.' },
        { title: 'Preview vs Rendered', points: 80, difficulty: 'Boss',
          description: 'Compare material preview and rendered view on one object.',
          criteria: ['Both views shown side by side on the same object', 'Differences between the two are specifically noted', 'Notes correctly explain why the difference exists'],
          hint: 'Pay attention to how lighting and reflections differ between the two - material preview uses a fixed studio setup.',
          solution: 'A correct, specific explanation of the differences between the two views.' },
      ] },
    { no: 10, week: 5, session: 10, title: 'Lighting fundamentals', topic: 'Light types, three point lighting (key/fill/rim), environment and HDRI lighting, colour and mood',
      problems: [
        { title: 'Sun Light and Shadows', points: 40, difficulty: 'Basic',
          description: 'Set up a single sun light and observe the shadows.',
          criteria: ['Sun light correctly added to the scene', 'Shadow direction and softness observed and noted', 'Angle produces a clear, deliberate shadow'],
          hint: 'Rotate the sun light and watch the shadow angle change in real time to understand the relationship.',
          solution: 'A deliberately angled sun light with observed, noted shadow behaviour.' },
        { title: 'Three Point Lighting', points: 50, difficulty: 'Core',
          description: 'Build a three point lighting setup with key, fill, and rim.',
          criteria: ['All three lights present and correctly roled', 'Key light is clearly the dominant light source', 'Rim light separates the subject from the background'],
          hint: 'Set up the key light first and get it right before adding fill and rim - each light\'s job depends on the one before it.',
          solution: 'A correctly roled three point setup with a well-separated subject.' },
        { title: 'HDRI Environment', points: 50, difficulty: 'Core',
          description: 'Add an HDRI environment for realistic lighting.',
          criteria: ['HDRI correctly loaded and applied to the world', 'Lighting on the subject looks realistic', 'Rotation of the HDRI considered for best result'],
          hint: 'Rotate the HDRI environment texture until the reflections and light direction flatter your subject.',
          solution: 'Realistic HDRI lighting with a deliberately chosen rotation.' },
        { title: 'Warm vs Cool Mood', points: 60, difficulty: 'Core',
          description: 'Adjust colour and intensity to set a warm versus a cool mood.',
          criteria: ['Two clearly distinct mood renders produced', 'Colour temperature genuinely shifts the mood', 'Intensity adjusted appropriately for each mood'],
          hint: 'Change colour temperature significantly, not subtly - a believable mood shift needs a real colour difference.',
          solution: 'Two renders with a genuinely distinct, deliberate mood difference.' },
        { title: 'Light a Product', points: 80, difficulty: 'Boss',
          description: 'Light a single product so it looks professional.',
          criteria: ['Lighting setup is deliberate, not default', 'Product reads clearly with good form definition', 'Result looks comparable to a professional product shot'],
          hint: 'Study a real professional product photo\'s lighting before setting up your own - notice how many light sources it actually uses.',
          solution: 'A professional-quality lit product render.' },
      ] },
    { no: 11, week: 6, session: 11, title: 'Cameras, composition, and rendering', topic: 'Focal length and depth of field, composition (rule of thirds, leading lines), Eevee vs Cycles, render settings',
      problems: [
        { title: 'Rule of Thirds Framing', points: 40, difficulty: 'Basic',
          description: 'Add a camera and frame a scene using the rule of thirds.',
          criteria: ['Camera correctly added and aimed', 'Key subject positioned on a rule-of-thirds line or intersection', 'Composition feels intentional'],
          hint: 'Turn on the camera\'s composition guide overlay to see the rule-of-thirds grid while framing.',
          solution: 'A deliberately composed frame using the rule of thirds.' },
        { title: 'Depth of Field', points: 50, difficulty: 'Core',
          description: 'Set the focal length and add depth of field.',
          criteria: ['Focal length set to a deliberate value', 'Depth of field visibly blurs the background/foreground', 'Subject stays in sharp focus'],
          hint: 'Use the camera\'s focus distance eyedropper to click directly on your subject for accurate focus.',
          solution: 'A shot with correctly focused subject and visible depth of field blur.' },
        { title: 'Eevee vs Cycles', points: 50, difficulty: 'Core',
          description: 'Render one image in Eevee and one in Cycles, then compare.',
          criteria: ['Same scene rendered in both engines', 'Visual differences specifically noted', 'Comparison covers both quality and render time'],
          hint: 'Time both renders and note the difference - render engine choice is a real production tradeoff, not just visual.',
          solution: 'Two renders with a specific, informed engine comparison.' },
        { title: 'Clean Render Settings', points: 60, difficulty: 'Core',
          description: 'Set resolution, samples, and denoising for a clean render.',
          criteria: ['Resolution set appropriately for the output', 'Sample count high enough to avoid visible noise', 'Denoising used correctly, not masking a bad setup'],
          hint: 'Increase samples until the noise clears rather than relying entirely on denoising to hide a low sample count.',
          solution: 'A clean, noise-free render with sensible settings.' },
        { title: 'Final Product Shot', points: 80, difficulty: 'Boss',
          description: 'Render a final product shot and save the image.',
          criteria: ['Combines composition, focus, and lighting from this and prior classes', 'Final image is saved in an appropriate format', 'Result looks like a finished product shot'],
          hint: 'Review the shot against a real product photography reference before calling it final.',
          solution: 'A polished, saved, professional-looking final product shot.' },
      ] },
    { no: 12, week: 6, session: 12, title: 'Animation basics and final project', topic: 'The timeline and keyframes, animating location/rotation/scale, interpolation, parenting and exporting',
      problems: [
        { title: 'Keyframe A to B', points: 40, difficulty: 'Basic',
          description: 'Keyframe an object moving from point A to point B.',
          criteria: ['Start and end keyframes correctly set', 'Object moves smoothly between them on playback', 'Timing feels deliberate'],
          hint: 'Set the start keyframe first at frame 1, move the playhead forward, then set the end keyframe.',
          solution: 'A smooth, deliberately timed A-to-B animation.' },
        { title: 'Rotation and Scale Together', points: 50, difficulty: 'Core',
          description: 'Animate rotation and scale together.',
          criteria: ['Both rotation and scale keyframed', 'Both animate together believably', 'Motion looks intentional, not accidental'],
          hint: 'Keyframe both properties at the same frames initially, then offset slightly for a more natural feel.',
          solution: 'A believable combined rotation and scale animation.' },
        { title: 'Interpolation Comparison', points: 50, difficulty: 'Core',
          description: 'Change interpolation from linear to ease and compare the feel.',
          criteria: ['Both linear and ease versions produced', 'Difference in feel is correctly described', 'Ease version genuinely feels smoother'],
          hint: 'Open the graph editor to see the curve shape change between linear and ease - it explains the feel difference.',
          solution: 'Two versions with an accurate, felt description of the interpolation difference.' },
        { title: 'Parent and Animate', points: 60, difficulty: 'Core',
          description: 'Parent one object to another and animate the parent.',
          criteria: ['Parenting relationship correctly set up', 'Animating the parent correctly moves the child too', 'Relationship is intentional, not accidental'],
          hint: 'Confirm the child\'s origin is where you want it before parenting - parenting doesn\'t change the pivot point.',
          solution: 'A correct parent-child animation relationship.' },
        { title: 'Export a Rendered Animation', points: 80, difficulty: 'Boss',
          description: 'Export a short rendered animation in a shareable format.',
          criteria: ['Animation fully rendered, not just previewed', 'Exported in a genuinely shareable video format', 'Plays back correctly outside of Blender'],
          hint: 'Set the output format to a standard video codec (like FFmpeg H.264) rather than an image sequence, so it plays anywhere.',
          solution: 'A correctly exported, playable rendered animation file.' },
      ] },
  ],
},
];
