'use strict';
/** EchoLens tracks - Free Micro Courses (FC-01..FC-10).
 * Ten free computer-science basics, each finished in a single 60-90 minute
 * slot: one level, eight quests, no lectures. free: true -> every quest is
 * open to signed-in learners and completing all eight above the pass mark
 * issues the verified certificate automatically. None of these topics
 * overlap with a paid EchoLens course.
 * submission: 'file' marks the no-compiler courses (terminal/paper work is
 * submitted as text, PDF, or screenshots); the rest use the code workspace.
 */

module.exports = [

{
  key: 'fc01-c-basics', course_code: 'FC-01', free: true, friendly_grading: true, default_language: 'c',
  title: 'CS-101: Fundamentals of C',
  description: 'Procedural programming foundation covering low-level memory addressing, pointer arithmetic, and core execution mechanics. C is the language behind operating systems, databases, and almost every other language you will ever use, and it is on nearly every university syllabus in Pakistan - a first working C program removes a real fear for a lot of students. Ten topics, three tasks each, certificate at the end.',
  outcome: 'Understand the compilation flow, memory structure, and basic syntax of procedural C; implement decision-making logic, loops, and custom functions using value-passing conventions; manipulate arrays and perform raw memory addressing using pointers.',
  keywords: ['fundamentals of C', 'basics of C programming', 'free C course', 'learn C language online', 'C programming for beginners'],
  key_concepts: ['Compiling and running a C program', 'Variables and data types', 'Input/output with scanf and printf', 'Arithmetic and relational operators', 'Conditional statements', 'Loops', 'Functions', '1D arrays', 'Pointers', 'Strings'],
  pass_mark: 60, titleNames: ['C Starter', 'C Solver'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'Environment & Hello World', video_url: 'https://www.youtube.com/watch?v=b00HsZvg-V0', topic: 'C is a compiled language where code is converted into machine code before running. Execution starts at main().\n\n#include <stdio.h>\nint main() {\n    printf("Hello, Platform!\\n");\n    return 0;\n}',
      problems: [
        { title: 'Print Greeting', points: 30, difficulty: 'Basic',
          description: "Output 'Hello, Platform!' to stdout.",
          criteria: ['#include <stdio.h> is present', "Output is exactly: Hello, Platform!"],
          hint: 'Include <stdio.h> and use printf().',
          solution: 'A compiling main with one printf, exact spelling.' },
        { title: 'Line Breaks', points: 30, difficulty: 'Basic',
          description: 'Output two lines using a single printf.',
          criteria: ['Only one printf call is used', 'Two separate lines appear in the output'],
          hint: 'Insert the escape sequence \\n between the two lines.',
          solution: 'One printf with \\n splitting the two lines.' },
        { title: 'Return Codes', points: 40, difficulty: 'Core',
          description: 'Modify main to return 0 explicitly.',
          criteria: ['main has an explicit return statement', 'The value returned is 0'],
          hint: 'Write return 0; before the closing brace.',
          solution: 'main ends with return 0; instead of falling off the end.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Variables & Data Types', video_url: 'https://www.youtube.com/watch?v=QtTijZXFl5s', topic: 'Variables act as labeled containers. Primitive types store integers, decimals (float/double), or single characters (char).\n\n#include <stdio.h>\nint main() {\n    int age = 20;\n    float height = 5.9;\n    printf("Age: %d\\n", age);\n    return 0;\n}',
      problems: [
        { title: 'Declaring Integers', points: 30, difficulty: 'Basic',
          description: 'Create two int variables and print their sum.',
          criteria: ['Two int variables declared', 'The sum is printed using %d'],
          hint: 'Use the %d format specifier in printf.',
          solution: 'Two ints declared, summed, and printed with %d.' },
        { title: 'Floating Precision', points: 30, difficulty: 'Basic',
          description: 'Declare a double holding 3.14159 and print it.',
          criteria: ['A double variable holds 3.14159', 'Printed with the %lf specifier'],
          hint: 'Use %lf to print doubles.',
          solution: 'double declared and printed with %lf, decimal places visible.' },
        { title: 'ASCII Values', points: 40, difficulty: 'Core',
          description: "Assign the character 'A' to a char variable and print its integer (ASCII) value.",
          criteria: ["A char variable holds 'A'", 'Printed as an integer, not a character'],
          hint: 'Print a char variable using %d to see its ASCII value.',
          solution: 'char assigned, printed with %d, yields 65.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Basic Input/Output', video_url: 'https://www.youtube.com/watch?v=hSHFjPvqFjw', topic: 'Programs read user input using scanf() with memory addresses (&) and display text outputs using printf().\n\n#include <stdio.h>\nint main() {\n    int num;\n    scanf("%d", &num);\n    printf("Entered: %d\\n", num);\n    return 0;\n}',
      problems: [
        { title: 'User Age', points: 30, difficulty: 'Basic',
          description: "Read an integer age and print 'Age: X'.",
          criteria: ['age read with scanf("%d", &age);', "Output follows the exact 'Age: X' shape"],
          hint: 'Use scanf("%d", &age);.',
          solution: 'One scanf read, one printf in the required shape.' },
        { title: 'Multi-Input', points: 40, difficulty: 'Core',
          description: 'Read two floats and print their product.',
          criteria: ['Both floats read in one scanf call', 'The printed product is correct for any input'],
          hint: 'Use scanf("%f %f", &a, &b);.',
          solution: 'Two floats read together, multiplied, and printed.' },
        { title: 'Char Reader', points: 40, difficulty: 'Core',
          description: 'Read a single character and print it in quotes.',
          criteria: ['A single char is read correctly', "Output wraps the character in quotes, e.g. 'A'"],
          hint: 'Use a leading space before %c in scanf to skip stray whitespace.',
          solution: 'scanf(" %c", &c) then printed inside quote characters.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'Arithmetic & Relational Operators', video_url: 'https://www.youtube.com/watch?v=8N5_27GaBxA', topic: 'Arithmetic operators compute numbers (+, -, *, /, %) while relational operators compare values, returning 1 or 0.\n\n#include <stdio.h>\nint main() {\n    int rem = 10 % 3;\n    int check = (10 > 5);\n    printf("Rem: %d, Check: %d\\n", rem, check);\n    return 0;\n}',
      problems: [
        { title: 'Modulo Check', points: 30, difficulty: 'Basic',
          description: 'Calculate the remainder of 27 divided by 4.',
          criteria: ['The % operator is used', 'The printed remainder is correct (3)'],
          hint: 'Use the % operator.',
          solution: '27 % 4 printed, equals 3.' },
        { title: 'Comparison', points: 30, difficulty: 'Basic',
          description: 'Print the result of the expression (10 > 5) directly.',
          criteria: ['The comparison is printed as a number, not text', 'Output is 1'],
          hint: 'Output the expression using %d.',
          solution: 'printf("%d", (10 > 5)); prints 1.' },
        { title: 'Average Calculator', points: 40, difficulty: 'Core',
          description: 'Calculate the floating-point average of 3 integers.',
          criteria: ['Three ints are summed', 'The average keeps its decimal part (not integer division)'],
          hint: 'Cast the sum to float before dividing.',
          solution: '(float)sum / 3 - casting before the divide is the pass/fail line.' },
      ] },
    { no: 5, week: 2, session: 2, title: 'Conditional Statements', video_url: 'https://www.youtube.com/watch?v=SOnpOBvyhDM', topic: 'Conditional statements steer execution along different paths using if, else if, else, or switch conditions.\n\n#include <stdio.h>\nint main() {\n    int score = 85;\n    if (score >= 50) printf("Pass\\n");\n    else printf("Fail\\n");\n    return 0;\n}',
      problems: [
        { title: 'Even or Odd', points: 30, difficulty: 'Basic',
          description: "Read an int and print 'Even' or 'Odd'.",
          criteria: ['Uses n % 2 == 0 to decide', 'Correct for both an even and an odd input'],
          hint: 'Use n % 2 == 0.',
          solution: 'if (n % 2 == 0) Even, else Odd.' },
        { title: 'Grade Categorization', points: 30, difficulty: 'Basic',
          description: "Output 'P' for a score >= 50, else 'F'.",
          criteria: ['The threshold is exactly 50', "Prints exactly 'P' or 'F'"],
          hint: 'Use an if (score >= 50) check.',
          solution: 'Single if/else printing P or F.' },
        { title: 'Simple Calculator Switch', points: 40, difficulty: 'Core',
          description: 'Perform +, -, *, or / on two numbers using a switch statement on the operator character.',
          criteria: ['A switch statement selects the operation', 'All four operators produce the correct result'],
          hint: "Match case '+': and case '-': (and the rest) inside the switch.",
          solution: 'switch on the operator char, one case per operator, each returning the right result.' },
      ] },
    { no: 6, week: 2, session: 3, title: 'Loops (for, while)', video_url: 'https://www.youtube.com/watch?v=Rtww83GH0BU', topic: 'Loops repeat code blocks continuously until conditions change. Use for for fixed iterations and while for conditions.\n\n#include <stdio.h>\nint main() {\n    for (int i = 1; i <= 5; i++) {\n        printf("%d ", i);\n    }\n    return 0;\n}',
      problems: [
        { title: 'Count to N', points: 30, difficulty: 'Basic',
          description: 'Print the integers 1 through N.',
          criteria: ['A for loop produces the numbers, not hard-coded prints', 'N itself is included in the output'],
          hint: 'for(int i=1; i<=N; i++).',
          solution: 'Loop bound is <= N so the last number prints too.' },
        { title: 'Sum of Inputs', points: 40, difficulty: 'Core',
          description: 'Read numbers until a 0 is entered, then output the total sum.',
          criteria: ['A while loop reads until 0 is seen', '0 itself is not added to the total'],
          hint: 'Use while(num != 0).',
          solution: 'Loop reads and accumulates until the sentinel 0 stops it.' },
        { title: 'Factorial', points: 40, difficulty: 'Core',
          description: 'Calculate the factorial of N using a loop.',
          criteria: ['fact starts at 1, not 0', 'Correct result for at least one N > 1 (e.g. 5! = 120)'],
          hint: 'Initialize fact = 1 and multiply iteratively.',
          solution: 'fact = 1 then fact *= i across the loop.' },
      ] },
    { no: 7, week: 3, session: 1, title: 'Functions', video_url: 'https://www.youtube.com/watch?v=lv5IDF7dmBk', topic: 'Functions modularize code into reusable sub-routines accepting parameters and returning values.\n\n#include <stdio.h>\nint add(int a, int b) { return a + b; }\nint main() {\n    printf("Sum: %d\\n", add(5, 7));\n    return 0;\n}',
      problems: [
        { title: 'Square Function', points: 30, difficulty: 'Basic',
          description: 'Write int square(int x) returning x squared.',
          criteria: ['A separate function named square exists', 'Returns (not prints) the correct value'],
          hint: 'return x * x;',
          solution: 'square(x) returns x*x, called from main.' },
        { title: 'Max Value', points: 30, difficulty: 'Basic',
          description: 'Return the larger of two integers from a function.',
          criteria: ['The function returns, not prints, the result', 'Correct when the two numbers are equal too'],
          hint: 'Use a ternary: return (a > b) ? a : b;.',
          solution: 'Ternary or if/else returning the larger value.' },
        { title: 'Void Function', points: 40, difficulty: 'Core',
          description: 'Print a banner from a function that returns no value.',
          criteria: ['Function return type is void', 'main calls it and the banner appears'],
          hint: 'Set the function return type to void.',
          solution: 'void bannerFn() prints directly, called from main with no assignment.' },
      ] },
    { no: 8, week: 3, session: 2, title: '1D Arrays', video_url: 'https://www.youtube.com/watch?v=7F-Q2oVBYKk', topic: 'Arrays store indexed, sequential sequences of elements of identical data types in contiguous memory.\n\n#include <stdio.h>\nint main() {\n    int arr[3] = {10, 20, 30};\n    printf("%d\\n", arr[0]);\n    return 0;\n}',
      problems: [
        { title: 'Array Initialization', points: 30, difficulty: 'Basic',
          description: 'Declare an array of size 5 and print its 3rd element.',
          criteria: ['Array declared with 5 elements', 'The value printed is at index 2'],
          hint: 'The 3rd element is at index 2.',
          solution: 'arr[2] printed - the off-by-one is the whole lesson.' },
        { title: 'Array Sum', points: 40, difficulty: 'Core',
          description: 'Read 5 integers into an array and compute their sum.',
          criteria: ['All 5 values come from user input', 'A loop accumulates the sum, not manual addition'],
          hint: 'Loop index i from 0 to 4, accumulating sum.',
          solution: 'A read-loop filling the array, then a sum-loop (or combined).' },
        { title: 'Find Minimum', points: 40, difficulty: 'Core',
          description: 'Iterate through an array to find the minimum value.',
          criteria: ['min starts at arr[0], not a hard-coded guess', 'Correct minimum for any arrangement of values'],
          hint: 'Set min = arr[0] and update whenever arr[i] < min.',
          solution: 'Running-minimum pattern across the array.' },
      ] },
    { no: 9, week: 3, session: 3, title: 'Basic Pointers', video_url: 'https://www.youtube.com/watch?v=5BpYD7TxvKU', topic: 'Pointers hold raw memory addresses of target variables, permitting direct memory manipulation.\n\n#include <stdio.h>\nint main() {\n    int x = 42;\n    int *ptr = &x;\n    printf("Val: %d, Addr: %p\\n", *ptr, ptr);\n    return 0;\n}',
      problems: [
        { title: 'Address Printing', points: 30, difficulty: 'Basic',
          description: "Store a variable's address in a pointer and print the address.",
          criteria: ['A pointer holds &var', 'Printed with the %p specifier'],
          hint: 'Use the %p specifier and &var.',
          solution: 'int *ptr = &x; printed with %p.' },
        { title: 'Value Modification', points: 40, difficulty: 'Core',
          description: 'Change a variable\'s value to 100 through its pointer.',
          criteria: ['The change happens via dereference, not directly on the variable', 'The variable reads 100 afterward'],
          hint: 'Assign through the dereference: *ptr = 100;.',
          solution: '*ptr = 100; then the original variable prints 100.' },
        { title: 'Pointer Addition', points: 40, difficulty: 'Core',
          description: 'Write a function that puts the sum of two numbers into a pointer target.',
          criteria: ['Function takes a result pointer parameter', 'The sum is written through that pointer, not returned'],
          hint: 'Dereference the result parameter: *res = *a + *b;.',
          solution: 'void addInto(int *res, int a, int b) writing through *res.' },
      ] },
    { no: 10, week: 4, session: 1, title: 'Strings in C', video_url: 'https://www.youtube.com/watch?v=CJ_pzdZ39N4', topic: "Strings are character arrays ending with a null byte ('\\0'), processed using standard functions in <string.h>.\n\n#include <stdio.h>\n#include <string.h>\nint main() {\n    char s[] = \"Hello\";\n    printf(\"Len: %lu\\n\", strlen(s));\n    return 0;\n}",
      problems: [
        { title: 'Length Counter', points: 30, difficulty: 'Basic',
          description: "Print a string's character count, excluding the null terminator.",
          criteria: ['#include <string.h> is present', 'strlen is used, not a manual count'],
          hint: 'Use strlen(str) from <string.h>.',
          solution: 'strlen(str) printed directly.' },
        { title: 'String Concatenation', points: 40, difficulty: 'Core',
          description: "Join the two strings 'Hello ' and 'World'.",
          criteria: ['strcat is used to join them', 'The destination buffer is large enough for both'],
          hint: 'Use strcat(str1, str2).',
          solution: 'strcat into a buffer sized for both strings, then printed.' },
        { title: 'Custom String Reverser', points: 60, difficulty: 'Boss',
          description: 'Print a string in reverse order using a loop (not a library reverse function).',
          criteria: ['A loop walks the string backward', 'The reversed output matches the input exactly, reversed'],
          hint: 'Start the loop at strlen(str) - 1 and count down to 0.',
          solution: 'Backward loop from length-1 to 0, printing one character per step.' },
      ] },
  ],
},

{
  key: 'fc02-cpp-objects', course_code: 'FC-02', free: true, friendly_grading: true, default_language: 'cpp',
  title: 'CS-102: Fundamentals of C++',
  description: 'Object-oriented evolution of C featuring standard template libraries, input/output streams, references, and memory abstractions. C++ is the standard teaching language for data structures and competitive programming, and it is on nearly every university syllabus in Pakistan. Ten topics, three tasks each, certificate at the end.',
  outcome: 'Utilize modern standard library streams (cin, cout) and references for structured code; implement functional abstractions using function overloading, default parameters, and namespaces; apply C++ standard containers (std::vector, std::string) for dynamic data management.',
  keywords: ['fundamentals of C++', 'basics of C++', 'free C++ course', 'learn C++ online', 'C++ for beginners'],
  key_concepts: ['Streams: cin and cout', 'References vs pointers', 'Function overloading and default parameters', 'std::string', 'std::vector', 'Dynamic memory with new/delete', 'Range-based loops and auto', 'Structs vs classes', 'STL algorithms', 'File handling with fstream'],
  pass_mark: 60, titleNames: ['Object Rookie', 'Class Builder'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'From C to C++ (Streams)', video_url: 'https://www.youtube.com/watch?v=qWDZ4ZZGAmQ', topic: 'C++ introduces standard stream abstractions (cout, cin) inside the std namespace for modern input and output.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    cout << "Hello C++" << endl;\n    return 0;\n}',
      problems: [
        { title: 'Hello C++', points: 30, difficulty: 'Basic',
          description: "Print 'Hello C++' using cout and endl.",
          criteria: ['<iostream> is included', "Output is exactly: Hello C++"],
          hint: '<iostream> header required.',
          solution: 'One cout << "Hello C++" << endl; line.' },
        { title: 'Stream Reader', points: 30, difficulty: 'Basic',
          description: 'Read an int using cin and print its double.',
          criteria: ['cin reads the number', 'The value printed is exactly double the input'],
          hint: 'cin >> num;.',
          solution: 'cin into an int, then cout num * 2.' },
        { title: 'Namespace Access', points: 40, difficulty: 'Core',
          description: 'Print text without the std:: qualification.',
          criteria: ['using namespace std; appears at the top', 'cout is used unqualified'],
          hint: 'Use using namespace std; at the top of the file.',
          solution: 'The using-namespace line makes bare cout/endl work.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'References vs Pointers', video_url: 'https://www.youtube.com/watch?v=DvUYbUn9uQ4', topic: 'A reference acts as an alias for an existing variable, enabling direct access without pointer syntax.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    int val = 10;\n    int &ref = val;\n    ref = 50;\n    cout << val << endl; // Prints 50\n    return 0;\n}',
      problems: [
        { title: 'Reference Alias', points: 30, difficulty: 'Basic',
          description: 'Modify a variable through a reference alias.',
          criteria: ['A reference (&) is declared to the variable', 'Changing the reference changes the original variable'],
          hint: 'int &ref = val; ref = 50;.',
          solution: 'Reference declared and assigned; original variable reflects the change.' },
        { title: 'Swap via Reference', points: 40, difficulty: 'Core',
          description: 'Swap two integers using reference parameters.',
          criteria: ['Function parameters are references, not values', 'Both variables are actually swapped in main'],
          hint: 'Write void swap(int &a, int &b).',
          solution: 'swap(int&, int&) using a temp variable, called from main.' },
        { title: 'Const Reference', points: 40, difficulty: 'Core',
          description: 'Pass a string to a function via const reference.',
          criteria: ['Parameter is const std::string&', 'The function reads the string without copying or modifying it'],
          hint: 'Use a const std::string &s parameter.',
          solution: 'Function signature takes const string& and only reads it.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Overloading & Defaults', video_url: 'https://www.youtube.com/watch?v=GUZ6_Ur6ar8', topic: 'Functions can share names if parameters differ, or declare optional fallback parameter values.\n\n#include <iostream>\nusing namespace std;\nvoid greet(string name = "Guest") {\n    cout << "Hello " << name << endl;\n}\nint main() { greet(); return 0; }',
      problems: [
        { title: 'Overloaded Add', points: 30, difficulty: 'Basic',
          description: 'Write add() for two ints and a separate add() for two doubles.',
          criteria: ['Two functions share the name add', 'Each is called with its matching type and returns the correct sum'],
          hint: 'Same function name, different parameter types.',
          solution: 'add(int,int) and add(double,double) overloads, both called.' },
        { title: 'Default Greeting', points: 30, difficulty: 'Basic',
          description: 'Write a function with an optional fallback parameter.',
          criteria: ['A default value is assigned in the signature', 'Calling with no argument uses the default'],
          hint: 'Assign a default value in the function signature.',
          solution: 'greet(string name = "Guest") called both with and without an argument.' },
        { title: 'Overload Ambiguity', points: 40, difficulty: 'Core',
          description: 'Resolve a compilation error caused by an ambiguous overloaded call.',
          criteria: ['The ambiguous call is identified', 'An explicit cast resolves it to one specific overload'],
          hint: 'Explicitly cast the argument types on the call.',
          solution: 'A cast like (double)x picks the intended overload.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'std::string Class', video_url: 'https://www.youtube.com/watch?v=LuFRDp9kKZ4', topic: 'The std::string class manages text dynamically, supporting operations like concatenation and substring extraction.\n\n#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    string s = "Hello ";\n    s += "World";\n    cout << s << endl;\n    return 0;\n}',
      problems: [
        { title: 'String Append', points: 30, difficulty: 'Basic',
          description: 'Concatenate two strings using +.',
          criteria: ['The + operator joins two std::string values', 'The joined result is printed'],
          hint: 'string full = s1 + s2;.',
          solution: 'Two strings combined with + and printed.' },
        { title: 'Substring Extraction', points: 30, difficulty: 'Basic',
          description: 'Extract part of a string using .substr().',
          criteria: ['.substr() is used, not manual character copying', 'The extracted piece matches the requested range'],
          hint: 'Use str.substr(0, 3) for the first 3 characters.',
          solution: '.substr(start, length) called and its result printed.' },
        { title: 'Line Reader', points: 40, difficulty: 'Core',
          description: 'Read a full line of input, including spaces.',
          criteria: ['std::getline is used, not cin >>', 'Spaces in the input are preserved in the output'],
          hint: 'Use std::getline(std::cin, str).',
          solution: 'getline captures the whole line, spaces included.' },
      ] },
    { no: 5, week: 2, session: 2, title: 'Standard Vectors', video_url: 'https://www.youtube.com/watch?v=vSio4fvNgzg', topic: 'std::vector provides dynamic arrays that resize automatically as elements are added or deleted.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<int> v = {10, 20};\n    v.push_back(30);\n    cout << v.size() << endl;\n    return 0;\n}',
      problems: [
        { title: 'Pushing Data', points: 30, difficulty: 'Basic',
          description: 'Instantiate a vector and push values into it.',
          criteria: ['.push_back() is used to add elements', 'At least 3 elements end up in the vector'],
          hint: 'Use the .push_back() method.',
          solution: 'vector<int> built up with push_back calls.' },
        { title: 'Vector Size', points: 30, difficulty: 'Basic',
          description: 'Print the element count and the last item of a vector.',
          criteria: ['.size() prints the correct count', '.back() prints the correct last element'],
          hint: 'Use .size() and .back() methods.',
          solution: 'v.size() and v.back() both printed correctly.' },
        { title: 'Vector Traversal', points: 40, difficulty: 'Core',
          description: 'Loop through a vector using a range-based loop.',
          criteria: ['for(auto elem : vec) syntax is used, not an index loop', 'Every element is printed in order'],
          hint: 'for(auto elem : vec).',
          solution: 'Range-based for loop printing every element.' },
      ] },
    { no: 6, week: 2, session: 3, title: 'Dynamic Memory (new/delete)', video_url: 'https://www.youtube.com/watch?v=zQZMc8FXPYY', topic: 'Heap memory is allocated dynamically using the new operator and freed manually using delete.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    int *p = new int(42);\n    cout << *p << endl;\n    delete p;\n    return 0;\n}',
      problems: [
        { title: 'Heap Integer', points: 30, difficulty: 'Basic',
          description: 'Allocate an int on the heap, print it, then free the memory.',
          criteria: ['new int(value) allocates it', 'delete frees it before the program ends'],
          hint: 'int* ptr = new int(42); delete ptr;.',
          solution: 'Allocated with new, dereferenced and printed, then delete.' },
        { title: 'Dynamic Array', points: 40, difficulty: 'Core',
          description: 'Allocate a dynamic array of size N on the heap.',
          criteria: ['new int[n] allocates based on a runtime size', 'The array is usable (values can be set/read)'],
          hint: 'int* arr = new int[n];.',
          solution: 'new[] used with a variable size, not a fixed literal.' },
        { title: 'Freeing Arrays', points: 40, difficulty: 'Core',
          description: 'Release a dynamically allocated array safely.',
          criteria: ['delete[] is used, not plain delete', 'It matches the earlier new[] allocation'],
          hint: 'Use array syntax: delete[] arr;.',
          solution: 'delete[] arr; matching the new[] used to allocate it.' },
      ] },
    { no: 7, week: 3, session: 1, title: 'Range Loops & Auto', video_url: 'https://www.youtube.com/watch?v=wDj7Wx7mwa8', topic: 'The auto keyword infers variable types automatically while range-based loops simplify container traversal.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<int> nums = {1, 2, 3};\n    for (auto x : nums) cout << x << " ";\n    return 0;\n}',
      problems: [
        { title: 'Auto Types', points: 30, difficulty: 'Basic',
          description: 'Declare a variable using auto.',
          criteria: ['auto is used instead of an explicit type', 'The inferred type behaves correctly (e.g. arithmetic works)'],
          hint: 'auto x = 5;.',
          solution: 'auto-declared variable used correctly afterward.' },
        { title: 'Range Modify', points: 40, difficulty: 'Core',
          description: 'Modify items in a vector by capturing the loop variable by reference.',
          criteria: ['for(auto &x : vec) syntax is used', 'The original vector is actually changed after the loop'],
          hint: 'for(auto &x : vec).',
          solution: 'Reference capture in the range-for actually mutates the container.' },
        { title: 'Const Iteration', points: 30, difficulty: 'Basic',
          description: 'Print a vector safely without modifying it.',
          criteria: ['for(const auto &x : vec) syntax is used', 'The vector is unchanged after printing'],
          hint: 'Use for(const auto &x : vec).',
          solution: 'const-reference range-for used purely for reading.' },
      ] },
    { no: 8, week: 3, session: 2, title: 'Structs vs Classes', video_url: 'https://www.youtube.com/watch?v=FnwbsHtCJ1o', topic: 'Structs default to public member visibility, while classes enforce private access specifiers by default.\n\n#include <iostream>\nusing namespace std;\nclass Player {\n    string name;\npublic:\n    void setName(string n) { name = n; }\n};\nint main() { Player p; return 0; }',
      problems: [
        { title: 'Simple Struct', points: 30, difficulty: 'Basic',
          description: 'Create a Point struct with x and y members.',
          criteria: ['struct Point has x and y', 'Members are accessed via the dot operator'],
          hint: 'Access members via the dot operator.',
          solution: 'struct Point { int x, y; }; used with p.x / p.y.' },
        { title: 'Basic Class', points: 30, difficulty: 'Basic',
          description: 'Write a class with a private member name.',
          criteria: ['name is declared under a private: label', 'The class still compiles with a public interface to use it'],
          hint: 'Place the private: label before the member.',
          solution: 'private: name; with a public method to set/read it.' },
        { title: 'Member Access', points: 40, difficulty: 'Core',
          description: 'Access private data through a public getter method.',
          criteria: ['A public getter method exists', 'It returns the private member\'s exact value'],
          hint: 'Create a public getter method.',
          solution: 'getName() returns the private name field.' },
      ] },
    { no: 9, week: 3, session: 3, title: 'STL Algorithms', video_url: 'https://www.youtube.com/watch?v=QTjc0HYfjYg', topic: 'The <algorithm> header offers utility functions for sorting, searching, and reversing collections.\n\n#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n    vector<int> v = {3, 1, 2};\n    sort(v.begin(), v.end());\n    return 0;\n}',
      problems: [
        { title: 'Vector Sort', points: 30, difficulty: 'Basic',
          description: 'Sort an unsorted vector in ascending order.',
          criteria: ['<algorithm> is included', 'std::sort(v.begin(), v.end()); produces ascending order'],
          hint: 'std::sort(v.begin(), v.end());.',
          solution: 'sort() called with begin/end iterators, result printed ascending.' },
        { title: 'Vector Reverse', points: 30, difficulty: 'Basic',
          description: 'Reverse the elements of a vector in place.',
          criteria: ['std::reverse is used, not a manual loop', 'The vector is reversed after the call'],
          hint: 'std::reverse(v.begin(), v.end());.',
          solution: 'reverse() called with begin/end, result printed in reverse.' },
        { title: 'Search Element', points: 40, difficulty: 'Core',
          description: 'Find a value in a vector using std::find.',
          criteria: ['std::find is used', 'The returned iterator is compared against v.end() to detect "not found"'],
          hint: 'Compare the iterator against v.end().',
          solution: 'find() result compared to end(); reports found/not found correctly.' },
      ] },
    { no: 10, week: 4, session: 1, title: 'File Handling (fstream)', video_url: 'https://www.youtube.com/watch?v=rkJJzH-ymg8', topic: 'File stream objects (ifstream, ofstream) enable program interaction with persistent files on disk.\n\n#include <iostream>\n#include <fstream>\nusing namespace std;\nint main() {\n    ofstream out("test.txt");\n    out << "Hello File";\n    out.close();\n    return 0;\n}',
      problems: [
        { title: 'Write File', points: 30, difficulty: 'Basic',
          description: 'Open a file, write one line, and close the handle.',
          criteria: ['ofstream opens the file', 'The line is written and the file is closed'],
          hint: 'ofstream out("test.txt"); out << "data";.',
          solution: 'ofstream opened, written to, then .close()d.' },
        { title: 'Read File', points: 40, difficulty: 'Core',
          description: 'Read a string back from a file stream.',
          criteria: ['ifstream opens the same file', 'The read content matches what was written'],
          hint: 'ifstream in("test.txt"); in >> str;.',
          solution: 'ifstream reading back what an earlier ofstream wrote.' },
        { title: 'Check Open State', points: 60, difficulty: 'Boss',
          description: 'Verify a file stream is open before attempting to read from it.',
          criteria: ['.is_open() is checked before reading', 'A missing/unopenable file is handled without a crash'],
          hint: 'Use the .is_open() check on the file stream.',
          solution: 'if (in.is_open()) guards the read; the missing-file case is handled gracefully.' },
      ] },
  ],
},

{
  key: 'fc03-java-basics', course_code: 'FC-03', free: true,
  title: 'Basics of Java',
  description: 'Java still runs banking systems, enterprise software, and Android apps, and it is the language most computer science degrees are taught in. Getting one program running removes the setup barrier that stops most beginners. One 90-minute slot, eight quests, certificate at the end.',
  outcome: 'Run Java programs: printing, variables, Scanner input, conditions, loops, and a simple method.',
  keywords: ['basics of Java', 'free Java course', 'learn Java online', 'Java for beginners', 'Java programming basics'],
  key_concepts: ['The structure of a Java program', 'Printing output and declaring variables', 'Reading user input with Scanner', 'Conditions and loops', 'Writing a simple method'],
  pass_mark: 60, titleNames: ['Java Starter', 'Method Writer'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: Java running', topic: 'The language of enterprise and Android - structure, Scanner, conditions, loops, and a first method',
      problems: [
        { title: 'Hello World in Java', points: 30, difficulty: 'Basic',
          description: 'Print Hello World from a Java program.',
          criteria: ['A class with a main method', 'System.out.println prints Hello World'],
          hint: 'In the EchoLens compiler your class must be called Main: public class Main { public static void main(String[] args) { ... } }',
          solution: 'The full class + main ceremony, compiling and printing.' },
        { title: 'City and Age', points: 30, difficulty: 'Basic',
          description: 'Store your city and your age in variables and print both.',
          criteria: ['A String and an int variable', 'Both printed'],
          hint: 'Join text and variables with +: "I live in " + city',
          solution: 'Two typed variables printed together.' },
        { title: 'Echo a Number', points: 40, difficulty: 'Core',
          description: 'Use Scanner to ask for a number and print it back.',
          criteria: ['A Scanner reads the number', 'The same number is printed back'],
          hint: 'import java.util.Scanner; then new Scanner(System.in) and nextInt().',
          solution: 'Working Scanner round-trip.' },
        { title: 'Which is Bigger', points: 40, difficulty: 'Core',
          description: 'Ask for two numbers and print which is bigger.',
          criteria: ['Both numbers read with Scanner', 'if/else prints the right answer'],
          hint: 'Read both first, compare after - and decide what to print when they are equal.',
          solution: 'Two reads, one comparison, correct output.' },
        { title: 'First Ten Evens', points: 40, difficulty: 'Core',
          description: 'Print the first ten even numbers with a loop.',
          criteria: ['A loop produces the numbers', 'Output is 2 through 20'],
          hint: 'Either loop i from 1 to 10 and print 2*i, or step by 2 - both are correct.',
          solution: 'Ten even numbers from a loop, not typed out.' },
        { title: 'A Greeting Method', points: 40, difficulty: 'Core',
          description: 'Write a method that takes a name and prints a greeting.',
          criteria: ['A separate method with a String parameter', 'main calls it at least once'],
          hint: 'static void greet(String name) { ... } sits beside main inside the class.',
          solution: 'Real method with a parameter, invoked from main.' },
        { title: 'Marks to Grade', points: 40, difficulty: 'Core',
          description: 'Ask for a mark out of a hundred and print the grade letter.',
          criteria: ['Reads a mark with Scanner', 'Sensible bands, e.g. A 80+, B 70+, C 60+, D 50+, F below'],
          hint: 'Order the if / else if bands from highest to lowest so each mark hits the right one.',
          solution: 'Complete band ladder with no gaps.' },
        { title: 'Liftoff', points: 60, difficulty: 'Boss',
          description: 'Count from ten down to one and print Liftoff at the end.',
          criteria: ['A loop counts downward', 'Liftoff prints once, after the loop'],
          hint: 'A for loop can go down: for (int i = 10; i >= 1; i--).',
          solution: 'Descending loop plus one final println.' },
      ] },
  ],
},

{
  key: 'fc04-linux-cli', course_code: 'FC-04', free: true, submission: 'file',
  title: 'Basics of Linux and the Command Line',
  description: 'Every server, every deployment, and every developer job eventually puts you in a terminal. An hour of real commands turns the most intimidating screen in computing into an ordinary tool. Work in any Linux terminal (or WSL / an online terminal) and submit your commands and output as text or screenshots.',
  outcome: 'Move around the file system, create/copy/delete files, read files, and search - all from the terminal.',
  keywords: ['basics of Linux', 'free Linux course', 'learn command line', 'terminal for beginners', 'Linux commands basics'],
  key_concepts: ['Moving around the file system', 'Creating, copying, and deleting files', 'Reading a file from the terminal', 'Finding things with search', 'Basic permissions and what they mean'],
  pass_mark: 60, titleNames: ['Terminal Tamer', 'Shell Runner'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: the black screen, tamed', topic: 'Stop being scared of the terminal - navigate, create, read, search, and delete with real commands',
      problems: [
        { title: 'Where Am I?', points: 30, difficulty: 'Basic',
          description: 'Find out which folder you are currently in. Submit the command you used and its output.',
          criteria: ['The right command (pwd)', 'Its real output included'],
          hint: 'The command name is short for "print working directory".',
          solution: 'pwd plus a genuine path in the output.' },
        { title: 'Everything, Including Hidden', points: 30, difficulty: 'Basic',
          description: 'List everything in a folder, including hidden files.',
          criteria: ['ls with the flag that reveals dotfiles', 'Output shows at least . and ..'],
          hint: 'Hidden files in Linux start with a dot; one ls flag shows them.',
          solution: 'ls -a (or ls -la) with output.' },
        { title: 'A Projects Folder', points: 40, difficulty: 'Core',
          description: 'Create a new folder called projects and move into it.',
          criteria: ['Folder created with mkdir', 'Moved into it with cd, proven by pwd'],
          hint: 'Three commands tell the whole story: mkdir, cd, pwd.',
          solution: 'The pwd output ends in /projects.' },
        { title: 'One Line in a File', points: 40, difficulty: 'Core',
          description: 'Create a text file and write one line into it.',
          criteria: ['A file created from the terminal', 'One line of content inside it'],
          hint: 'echo "your line" > notes.txt creates and writes in one step.',
          solution: 'Any correct method: echo with >, or an editor.' },
        { title: 'Copy, Then Rename', points: 40, difficulty: 'Core',
          description: 'Copy that file, then rename the copy.',
          criteria: ['cp makes the copy', 'mv renames it', 'ls proves both exist as expected'],
          hint: 'mv is both "move" and "rename" - moving within the same folder renames.',
          solution: 'cp then mv, verified with ls.' },
        { title: 'Read Without an Editor', points: 40, difficulty: 'Core',
          description: 'Read the contents of a file without opening an editor.',
          criteria: ['A terminal command prints the file', 'The content appears in the output'],
          hint: 'cat is the classic; less and head also count.',
          solution: 'cat (or equivalent) with real output.' },
        { title: 'Find the Notes', points: 40, difficulty: 'Core',
          description: 'Search a folder for every file whose name contains the word notes.',
          criteria: ['A search command with a name pattern', 'The matching files listed'],
          hint: 'find . -name "*notes*" searches from the current folder down.',
          solution: 'find (or ls piped to grep) with the pattern.' },
        { title: 'Delete and Prove It', points: 60, difficulty: 'Boss',
          description: 'Delete a file you created, then confirm it is gone.',
          criteria: ['rm removes the file', 'A follow-up command proves it no longer exists'],
          hint: 'ls after rm - or cat it and show the "No such file" error, which is also proof.',
          solution: 'rm plus verification output.' },
      ] },
  ],
},

{
  key: 'fc05-data-structures', course_code: 'FC-05', free: true,
  title: 'Basics of Data Structures',
  description: 'Data structures are the most common technical interview subject in the world, and the reason one program runs instantly while another crawls. This is the plain English version, with no heavy maths - solve the quests in any language you like (Python is perfect).',
  outcome: 'Use arrays, stacks, and queues confidently, and pick the right structure for a task.',
  keywords: ['basics of data structures', 'free data structures course', 'learn stacks and queues', 'data structures for beginners', 'DSA basics'],
  key_concepts: ['Arrays and why position matters', 'Stacks: last in, first out', 'Queues: first in, first out', 'Linked lists in simple terms', 'Choosing the right structure for a task'],
  pass_mark: 60, titleNames: ['Array Apprentice', 'Structure Picker'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: how programs store things', topic: 'Arrays, stacks, and queues in plain English - then choosing between them like an engineer',
      problems: [
        { title: 'The Third Student', points: 30, difficulty: 'Basic',
          description: 'Store five student names in an array and print the third one.',
          criteria: ['Five names in one array/list', 'Exactly the third printed'],
          hint: 'Positions start at zero in most languages - the third item is index 2.',
          solution: 'names[2] - the off-by-one is the whole lesson.' },
        { title: 'The Largest of Eight', points: 40, difficulty: 'Core',
          description: 'Find the largest number in an array of eight numbers.',
          criteria: ['A loop or standard function finds the max', 'Works whatever the eight numbers are'],
          hint: 'Track a "largest so far" while walking the array - or use the built-in max and explain it.',
          solution: 'Correct maximum, not hard-coded.' },
        { title: 'Reverse with a Stack', points: 40, difficulty: 'Core',
          description: 'Use a stack to reverse the word EchoLens.',
          criteria: ['Letters pushed one by one', 'Popped letters produce sneLohcE'],
          hint: 'Last in, first out is exactly what reversing needs - push all, then pop all.',
          solution: 'Push/pop actually used (a list as a stack is fine).' },
        { title: 'The Bank Queue', points: 40, difficulty: 'Core',
          description: 'Model a queue at a bank counter: add three people, then serve one.',
          criteria: ['Three people enqueued in order', 'The FIRST person is the one served'],
          hint: 'First in, first out - if the person served is the last one who joined, it became a stack.',
          solution: 'Dequeue returns person number one.' },
        { title: 'Undo: Stack or Queue?', points: 40, difficulty: 'Core',
          description: 'Explain in one line whether undo in a text editor is a stack or a queue.',
          criteria: ['The right structure named', 'The one-line reason mentions order'],
          hint: 'Which change does Ctrl+Z take back - your first edit or your latest one?',
          solution: 'Stack - undo reverses the most recent action first (LIFO).' },
        { title: 'Into the Middle', points: 40, difficulty: 'Core',
          description: 'Add a new item to the middle of a list and print the result.',
          criteria: ['Item inserted at a middle position, not the end', 'Full list printed after'],
          hint: 'insert(position, item) - notice everything after the position shifts along.',
          solution: 'Correct middle insertion with the shifted list shown.' },
        { title: 'Found or Not', points: 40, difficulty: 'Core',
          description: 'Search an array for a value and print whether it was found.',
          criteria: ['A search over the array', 'Prints found/not found correctly for both cases'],
          hint: 'Walk the array comparing each item - and test once with a value that is not there.',
          solution: 'Linear search handling both outcomes.' },
        { title: 'Pick the Right Structure', points: 60, difficulty: 'Boss',
          description: 'Given a task - browser history "back" button, a printer\'s job list, a class attendance register - pick the right structure from array, stack, or queue for each, and say why.',
          criteria: ['All three matched to a structure', 'Each choice justified in a line'],
          hint: 'Think about the ORDER things come back out: latest first, oldest first, or by position.',
          solution: 'Back button: stack. Printer jobs: queue. Register: array. Reasons over labels.' },
      ] },
  ],
},

{
  key: 'fc06-algorithms-flowcharts', course_code: 'FC-06', free: true, submission: 'file',
  title: 'Basics of Algorithms and Flowcharts',
  description: 'Most beginners fail at programming because they try to write code before they can think in steps. This course teaches the thinking, with no programming language at all, so anyone can do it. Write your answers as text or draw and photograph your flowcharts.',
  outcome: 'Write clear step-by-step algorithms and pseudocode, and draw flowcharts with decisions and loops.',
  keywords: ['basics of algorithms', 'free algorithms course', 'flowchart for beginners', 'pseudocode basics', 'computational thinking'],
  key_concepts: ['What an algorithm really is', 'Writing steps as pseudocode', 'Drawing a flowchart', 'Decisions and loops on paper', 'Spotting a step that is missing or in the wrong order'],
  pass_mark: 60, titleNames: ['Step Thinker', 'Flow Designer'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: think before you code', topic: 'Think like a programmer before you write code - algorithms, pseudocode, and flowcharts on paper',
      problems: [
        { title: 'The Tea Algorithm', points: 30, difficulty: 'Basic',
          description: 'Write the steps to make a cup of tea as a numbered algorithm.',
          criteria: ['Numbered, ordered steps', 'No step assumes something not yet done'],
          hint: 'Could a robot follow it literally? "Add tea" before boiling water fails the test.',
          solution: 'Complete, ordered, unambiguous steps.' },
        { title: 'Add Two Numbers in Pseudocode', points: 30, difficulty: 'Basic',
          description: 'Write pseudocode that adds two numbers and shows the result.',
          criteria: ['INPUT, a sum step, and OUTPUT all present', 'Reads like structured steps, not an essay'],
          hint: 'Three lines are enough: INPUT a, b / total = a + b / OUTPUT total.',
          solution: 'Input -> process -> output shape.' },
        { title: 'Pass or Fail Flowchart', points: 40, difficulty: 'Core',
          description: 'Draw a flowchart for checking whether a student passed or failed.',
          criteria: ['Start/end shapes, a decision diamond', 'Both yes and no paths lead somewhere'],
          hint: 'The diamond asks one question (marks >= 50?) and MUST have two exits.',
          solution: 'Correct shapes with both branches complete.' },
        { title: 'One to Five in Pseudocode', points: 40, difficulty: 'Core',
          description: 'Write pseudocode that prints the numbers one to five.',
          criteria: ['A loop (REPEAT/WHILE/FOR), not five OUTPUT lines', 'Counter starts, changes, and stops correctly'],
          hint: 'Say where the counter starts, when the loop stops, and what changes each round.',
          solution: 'A genuine loop with correct bounds.' },
        { title: 'Fix the Broken Algorithm', points: 40, difficulty: 'Core',
          description: 'Fix an algorithm where two steps are in the wrong order: 1. Open the message 2. Reply to the message 3. Read the message 4. Send the reply.',
          criteria: ['The out-of-order pair identified', 'Corrected sequence written out'],
          hint: 'Walk it literally, step by step - where do you act on something you do not have yet?',
          solution: 'Read must come before reply: 1, 3, 2, 4.' },
        { title: 'The Login Flowchart', points: 40, difficulty: 'Core',
          description: 'Draw a flowchart for logging into an app, including a wrong password path.',
          criteria: ['A password-correct? decision', 'The wrong path loops back or ends sensibly'],
          hint: 'What actually happens on a wrong password - try again, or locked out after three?',
          solution: 'Both outcomes handled; wrong path goes somewhere real.' },
        { title: 'Largest of Three', points: 40, difficulty: 'Core',
          description: 'Write the steps to find the largest of three numbers.',
          criteria: ['Comparisons written as steps or pseudocode', 'Correct for every arrangement, including ties'],
          hint: 'Compare the first two, keep the winner, compare with the third.',
          solution: 'Two comparisons that always find the max.' },
        { title: 'Your Daily Algorithm', points: 60, difficulty: 'Boss',
          description: 'Take a daily task of your own and write it as a clear algorithm.',
          criteria: ['A real task, 6+ ordered steps', 'At least one decision or repeat in it'],
          hint: 'Pick something with a choice in it - making biryani, catching the bus, ironing a uniform.',
          solution: 'Ordered, followable, and contains a genuine decision/loop.' },
      ] },
  ],
},

{
  key: 'fc07-networking', course_code: 'FC-07', free: true, submission: 'file',
  title: 'Basics of Computer Networking',
  description: 'Networking sits underneath every website, app, and cloud service, but almost nobody explains it simply. One hour here makes the internet stop being magic, which helps in every technical role. Run the commands on your own device and submit the outputs as text or screenshots.',
  outcome: 'Understand IP addresses, DNS, and client/server - and inspect your own network with real commands.',
  keywords: ['basics of computer networking', 'free networking course', 'learn IP and DNS', 'networking for beginners', 'how the internet works'],
  key_concepts: ['What an IP address is', 'How DNS turns a name into an address', 'Client and server in plain terms', 'What happens when you press enter on a URL', 'Wifi, routers, and your home network'],
  pass_mark: 60, titleNames: ['Packet Tracer', 'Network Navigator'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: the internet, demystified', topic: 'What actually happens when you open a website - IPs, DNS, ping, and your own home network',
      problems: [
        { title: 'Your Own IP', points: 30, difficulty: 'Basic',
          description: 'Find your own device\'s IP address. Submit the command/screen you used and the address.',
          criteria: ['A real method (ipconfig / ifconfig / phone settings)', 'The address included'],
          hint: 'Windows: ipconfig. Linux/Mac: ifconfig or ip addr. Phones: wifi settings.',
          solution: 'Any local address (often 192.168.x.x) with its source.' },
        { title: 'Ping Something', points: 40, difficulty: 'Core',
          description: 'Ping a website and read what comes back.',
          criteria: ['ping output included', 'One line explaining what the time value means'],
          hint: 'ping google.com - the ms number is the round trip: your machine to theirs and back.',
          solution: 'Real output plus a correct reading of latency.' },
        { title: 'Name to Address', points: 40, difficulty: 'Core',
          description: 'Look up which IP address a website name points to.',
          criteria: ['nslookup / dig (or an online DNS tool) used', 'The returned address shown'],
          hint: 'nslookup echolens.digital - DNS is the phone book doing name -> number.',
          solution: 'A lookup with the resolved IP.' },
        { title: 'Five Steps of a Page Load', points: 40, difficulty: 'Core',
          description: 'Write out, in five steps, what happens when you open a website.',
          criteria: ['DNS lookup and server response both appear', 'Steps in a sensible order'],
          hint: 'Type URL -> name looked up -> request sent -> server responds -> browser renders.',
          solution: 'The five-step chain in order.' },
        { title: 'Who Is Your Provider?', points: 40, difficulty: 'Core',
          description: 'Find out who your internet provider is from a lookup tool.',
          criteria: ['A whois/IP-lookup tool used on your public IP', 'The provider named'],
          hint: 'Search "what is my IP", then put that address into an IP lookup site - the ISP field is your answer.',
          solution: 'Correct ISP from a lookup, e.g. PTCL, Nayatel, StormFiber.' },
        { title: 'Client vs Server', points: 40, difficulty: 'Core',
          description: 'Explain in one line the difference between a client and a server.',
          criteria: ['One clear line', 'Asking vs answering captured'],
          hint: 'Think of a restaurant: who orders, who serves?',
          solution: 'Client requests; server responds with the service/data.' },
        { title: 'Down for Everyone?', points: 40, difficulty: 'Core',
          description: 'Check whether a website is reachable when it seems down.',
          criteria: ['Two different checks (ping + a down-checker site, for example)', 'A conclusion: their side or yours'],
          hint: 'If ping fails but a "down for everyone" checker says up, the problem is on your side.',
          solution: 'Evidence from both checks plus the verdict.' },
        { title: 'Your Home Network Map', points: 60, difficulty: 'Boss',
          description: 'List three devices on your home network and what each one does.',
          criteria: ['Three real devices', 'Each one\'s role in a line (router included if you have one)'],
          hint: 'The router is the postmaster - everything else (phones, TVs, laptops) talks through it.',
          solution: 'Three devices with correct roles.' },
      ] },
  ],
},

{
  key: 'fc08-cybersecurity', course_code: 'FC-08', free: true, submission: 'file',
  title: 'Basics of Cybersecurity and Online Safety',
  description: 'Online fraud and account theft are everyday problems in Pakistan, and most of it succeeds because of simple mistakes. This hour is genuinely useful to every single person, technical or not. Submit your answers and evidence as text or screenshots - never include a real password in a submission.',
  outcome: 'Strong passwords, two-factor authentication, phishing detection, safe wifi habits, and a recovery plan.',
  keywords: ['basics of cybersecurity', 'free cyber security course', 'online safety course', 'phishing awareness', 'password security basics'],
  key_concepts: ['What makes a password strong or weak', 'Two factor authentication and why it matters', 'Spotting a phishing message', 'Safe browsing and public wifi risks', 'What to do if an account is compromised'],
  pass_mark: 60, titleNames: ['Safety Cadet', 'Account Guardian'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: locked down', topic: 'Protect your accounts, your money, and your data - passwords, 2FA, phishing, wifi, and recovery',
      problems: [
        { title: 'Test an Old Password', points: 30, difficulty: 'Basic',
          description: 'Test one of your OLD (no longer used) passwords against a strength checker and note the result.',
          criteria: ['A checker used and the verdict noted', 'The password itself NOT included in the submission'],
          hint: 'Describe the shape (length, words, numbers) and the crack-time estimate - never the password.',
          solution: 'A verdict plus one line on why it was weak/strong.' },
        { title: 'A Passphrase You Can Remember', points: 40, difficulty: 'Core',
          description: 'Create a strong passphrase you can actually remember, and explain the method (do not submit the real one you will use).',
          criteria: ['The method explained (e.g. four random words + numbers)', 'An example of the PATTERN, not your real passphrase'],
          hint: 'Four unrelated words beat P@ss123 - length is what defeats guessing machines.',
          solution: 'A long-passphrase method described correctly.' },
        { title: 'Turn On 2FA', points: 40, difficulty: 'Core',
          description: 'Turn on two factor authentication for one real account.',
          criteria: ['Which account and which method (app/SMS)', 'A screenshot with private details blurred/cropped'],
          hint: 'An authenticator app beats SMS - SIM-swap fraud exists in Pakistan too.',
          solution: 'Evidence 2FA is now on, method named.' },
        { title: 'Spot the Phish', points: 40, difficulty: 'Core',
          description: 'Three messages: (a) "Dear customer, your JazzCash account is block. Click hxxp://jazz-cash-verify.xyz to unblock now" (b) "Your OTP is 447215. Do not share it with anyone." (c) "Electricity bill for July is available in the app." - identify which is phishing, and how you knew.',
          criteria: ['(a) identified as the phish', 'Two clues named'],
          hint: 'Look at the link domain, the spelling, and the pressure to act NOW.',
          solution: '(a): fake domain, urgency, broken English. (b) and (c) are normal.' },
        { title: 'Breach Check', points: 40, difficulty: 'Core',
          description: 'Check whether your email address has appeared in a known data breach.',
          criteria: ['A breach-check service used (e.g. haveibeenpwned.com)', 'The result and your next step noted'],
          hint: 'If it appears in a breach, the move is: change that password everywhere it was reused.',
          solution: 'Check performed, correct follow-up stated.' },
        { title: 'The Padlock', points: 40, difficulty: 'Core',
          description: 'Find the padlock and certificate details on a website and say what they mean.',
          criteria: ['Certificate viewed (click the padlock)', 'One line on what HTTPS does and does NOT promise'],
          hint: 'The padlock means the connection is encrypted - not that the site itself is honest.',
          solution: 'Encryption vs trustworthiness distinguished.' },
        { title: 'Public Wifi Rules', points: 40, difficulty: 'Core',
          description: 'List three things you should never do on public wifi.',
          criteria: ['Three sensible items', 'One line each on why'],
          hint: 'Think about what a stranger on the same network could capture.',
          solution: 'E.g. banking, entering passwords on http sites, sensitive work - with reasons.' },
        { title: 'The Hacked-Account Playbook', points: 60, difficulty: 'Boss',
          description: 'Write the five steps you would take if your account were hacked today.',
          criteria: ['Five ordered steps', 'Password change, 2FA, sessions/devices, and warning contacts all covered'],
          hint: 'Speed matters: regain access, lock it, then contain the damage outward.',
          solution: 'Change password, enable 2FA, sign out all sessions, check recovery info, warn contacts/report.' },
      ] },
  ],
},

{
  key: 'fc09-cloud-computing', course_code: 'FC-09', free: true, submission: 'file',
  title: 'Basics of Cloud Computing',
  description: 'Every company is moving to the cloud, and cloud roles are among the best paid in tech, but the jargon scares people off. This is the plain language introduction with nothing to install and nothing to pay for.',
  outcome: 'Explain what the cloud is, the main service models, free tiers, and why companies migrate.',
  keywords: ['basics of cloud computing', 'free cloud course', 'learn cloud computing', 'cloud for beginners', 'AWS and Azure basics'],
  key_concepts: ['What the cloud actually is', 'Servers, storage, and hosting in simple terms', 'The difference between the main service models', 'Free tiers and how billing works', 'Why companies move to the cloud'],
  pass_mark: 60, titleNames: ['Cloud Curious', 'Cloud Literate'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: where apps actually live', topic: 'Servers, storage, service models, free tiers, and why everyone is migrating',
      problems: [
        { title: 'Where Do Files Go?', points: 30, difficulty: 'Basic',
          description: 'Write in one line where your files go when you save to a cloud drive.',
          criteria: ['Mentions someone else\'s servers/data center', 'One line'],
          hint: '"The cloud" is a building full of computers that are not yours.',
          solution: 'Onto the provider\'s servers in a data center, reached over the internet.' },
        { title: 'Cloud You Already Use', points: 30, difficulty: 'Basic',
          description: 'Name three cloud services you already use without thinking about it.',
          criteria: ['Three real services', 'Each is genuinely cloud-backed'],
          hint: 'Where do your WhatsApp backups, photos, and emails actually live?',
          solution: 'E.g. Google Drive/Photos, WhatsApp backup, Gmail, iCloud.' },
        { title: 'Laptop vs Cloud', points: 40, difficulty: 'Core',
          description: 'Explain the difference between storing a file on your laptop and in the cloud.',
          criteria: ['Access-from-anywhere and device-loss both mentioned', 'A downside of cloud noted too'],
          hint: 'What happens to each copy when the laptop is stolen - and when the internet is down?',
          solution: 'Local: one device, offline. Cloud: any device, survives loss, needs internet/trust.' },
        { title: 'Match the Service Models', points: 40, difficulty: 'Core',
          description: 'Match three real examples to the service model they belong to: renting a virtual server; using Gmail; deploying your app on a managed platform like Render.',
          criteria: ['All three matched (IaaS / SaaS / PaaS)', 'A line on each'],
          hint: 'How much do YOU manage? Everything (IaaS), just your code (PaaS), or nothing (SaaS)?',
          solution: 'Virtual server = IaaS, Gmail = SaaS, Render = PaaS.' },
        { title: 'The Free Tier', points: 40, difficulty: 'Core',
          description: 'Find the free tier page for one major cloud provider and note two things it includes.',
          criteria: ['A real provider\'s free tier (AWS/Azure/GCP/Oracle)', 'Two included items noted'],
          hint: 'Search "<provider> free tier" - note which items are always-free vs 12-months.',
          solution: 'Two genuine free-tier items with the provider named.' },
        { title: 'Upload and Share', points: 40, difficulty: 'Core',
          description: 'Upload a file to a free cloud service and share a link to it.',
          criteria: ['A working share link', 'A line on what permission the link gives'],
          hint: '"Anyone with the link can view" is a permission decision - notice you made it.',
          solution: 'Working link plus the permission understanding.' },
        { title: 'Why Companies Move', points: 40, difficulty: 'Core',
          description: 'List three reasons a business would move off its own servers.',
          criteria: ['Three distinct reasons', 'At least one about cost and one about scaling'],
          hint: 'Think of Eid sale traffic: what would a fixed server room do at 10x load?',
          solution: 'E.g. pay-as-you-go cost, instant scaling, no hardware maintenance, reliability.' },
        { title: 'A Cloud Job', points: 60, difficulty: 'Boss',
          description: 'Write two lines on one cloud job role and what it involves.',
          criteria: ['A real role (cloud engineer, DevOps, architect, SRE)', 'Two accurate lines'],
          hint: 'Search a real job ad for the role and summarise what they actually ask for.',
          solution: 'Correct role summary grounded in real duties.' },
      ] },
  ],
},

{
  key: 'fc10-regex', course_code: 'FC-10', free: true,
  title: 'Basics of Regex and Text Patterns',
  description: 'Regex is a small skill with an outsized payoff. It works in every language, every editor, and every spreadsheet, and it makes you noticeably faster at cleaning and searching data for the rest of your career. Test your patterns in the compiler (Python\'s re module) or any online regex tester.',
  outcome: 'Write patterns for digits, words, emails, phone numbers, dates, and line anchors - and use them to clean text.',
  keywords: ['basics of regex', 'free regex course', 'learn regular expressions', 'regex for beginners', 'text pattern matching'],
  key_concepts: ['What a pattern is and where regex works', 'Matching letters, digits, and spaces', 'Repeating with plus and star', 'Anchors for the start and end of a line', 'Testing patterns safely in a browser tool'],
  pass_mark: 60, titleNames: ['Pattern Spotter', 'Regex Ranger'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'One slot: patterns everywhere', topic: 'Find any pattern in any text, instantly - character classes, repetition, anchors, and real cleanups',
      problems: [
        { title: 'Words Starting with A', points: 30, difficulty: 'Basic',
          description: 'Match every word that starts with the letter a in a paragraph.',
          criteria: ['A working pattern with a word boundary', 'Shown matching sample text'],
          hint: '\\b marks a word edge: \\ba\\w* catches a-words and nothing mid-word.',
          solution: '\\ba\\w* (case-insensitive flag for A too).' },
        { title: 'Three Digits', points: 30, difficulty: 'Basic',
          description: 'Write a pattern that finds any three digit number.',
          criteria: ['Exactly three digits matched', 'Does not match part of a longer number'],
          hint: '\\d{3} counts digits; wrap it in \\b...\\b so 1234 does not sneak in.',
          solution: '\\b\\d{3}\\b' },
        { title: 'Find the Emails', points: 40, difficulty: 'Core',
          description: 'Find every email address inside a block of text.',
          criteria: ['Matches normal emails (name@domain.tld)', 'Tested on text with 2+ emails'],
          hint: 'Something before @, something after, a dot, letters: \\S+@\\S+\\.\\w+ is a fine start.',
          solution: 'A practical email pattern demonstrated on sample text.' },
        { title: 'The Eleven-Digit Mobile', points: 40, difficulty: 'Core',
          description: 'Match a Pakistani mobile number written as eleven digits.',
          criteria: ['Starts 03, eleven digits total', 'Rejects shorter/longer runs'],
          hint: '03 then nine more digits: \\b03\\d{9}\\b.',
          solution: '\\b03\\d{9}\\b' },
        { title: 'Lines Beginning with Error', points: 40, difficulty: 'Core',
          description: 'Find every line that begins with the word Error in a log.',
          criteria: ['The start-of-line anchor used', 'Mid-line "Error" NOT matched'],
          hint: '^ pins the match to the start of a line (multiline mode in code).',
          solution: '^Error with the multiline flag.' },
        { title: 'Match a Date', points: 40, difficulty: 'Core',
          description: 'Write a pattern that matches a date in the format day, month, year (e.g. 19-07-2026 or 19/07/2026).',
          criteria: ['Two digits, separator, two digits, separator, four digits', 'Works with - and /'],
          hint: 'A character class [-/] accepts either separator.',
          solution: '\\b\\d{2}[-/]\\d{2}[-/]\\d{4}\\b' },
        { title: 'Exactly Five Letters', points: 40, difficulty: 'Core',
          description: 'Find all words that are exactly five letters long.',
          criteria: ['Only five-letter words match', 'Boundaries stop 6+ letter words matching inside'],
          hint: '\\b[a-zA-Z]{5}\\b - both boundaries are doing real work here.',
          solution: '\\b[a-zA-Z]{5}\\b' },
        { title: 'Clean the Messy List', points: 60, difficulty: 'Boss',
          description: 'Use a pattern to strip extra spaces out of a messy list.',
          criteria: ['A find/replace with a repetition pattern', 'Before and after shown'],
          hint: 'Find one-or-more spaces ( +, or \\s+) and replace with a single space.',
          solution: 'Replace \\s+ (or " +") with one space; both versions of the text shown.' },
      ] },
  ],
},

];
