'use strict';
/** EchoLens tracks - CS-101/CS-102 (Fundamentals of C / C++ with OOP).
 * free: true -> every quest is open to signed-in learners, and completing
 * all topics above the pass mark issues the verified certificate
 * automatically. The rest of the fundamentals-of-programming curriculum
 * (CS-104..CS-106) lives in tracks/cs-fundamentals.js. Five tracks total:
 * C, C++ (OOP folded into Module 3), Python, JavaScript, HTML & CSS
 * (combined) - most run 4 modules, from zero, per the EchoLens Curriculum
 * Blueprint. FC-01 (Fundamentals of C) is the exception: it follows the
 * official 5-module/16-topic syllabus PDF verbatim (real-life analogy +
 * concept explanation + a real YouTube video + one scenario-based Compiler
 * Quest per topic, each with an exact Sample Input/Expected Output so the
 * grader has a literal target). video_url is populated with real videos
 * for FC-01 only; it is still intentionally left null for the other
 * tracks below until their video links are sourced too.
 */

module.exports = [

{
  key: 'fc01-c-basics', course_code: 'FC-01', free: true, friendly_grading: true, default_language: 'c',
  title: 'CS-101: Fundamentals of C',
  description: 'Absolute beginner to hardware-level understanding - the classic foundation language behind operating systems, databases, and almost every other language you will ever use. Five modules, sixteen topics, one real-life analogy and one scenario-based Compiler Quest each - from how a compiler turns source into machine code, through memory, operators and branching, to loops and modular functions - certificate at the end.',
  outcome: 'Understand the compilation lifecycle, program structure, memory-typed variables and formatted input/output; use relational/logical operators and branching to make decisions; use for/while loops and loop controls to repeat and manage work; write function prototypes, understand pass-by-value, and use return types (including void) to build modular programs.',
  keywords: ['fundamentals of C', 'basics of C programming', 'free C course', 'learn C language online', 'C programming for beginners'],
  key_concepts: ['The compilation lifecycle', 'main() and program entry', 'Standard output & escape sequences', 'Primitive data types & memory', 'Variables, initialization & constants', 'Format specifiers', 'Interactive input with scanf()', 'Arithmetic & modulo operations', 'Relational & logical decisions', 'if / else if / else branching', 'Counter-controlled for loops', 'Condition-driven while loops', 'Loop controls (break & continue)', 'Function declarations & prototypes', 'Pass-by-value & parameter passing', 'Return types & void functions'],
  pass_mark: 60, titleNames: ['C Starter', 'C Solver'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'The C Compilation Lifecycle', video_url: 'https://www.youtube.com/watch?v=KnvbUiSxvbM',
      topic: "Real-life analogy: Think of an architect drawing a blueprint in English. A construction robot that only responds to raw electrical pulses cannot read English words - a precision translator (the Compiler) validates the blueprint syntax and translates every single instruction into binary machine code before construction starts.\n\nComputers execute instructions in machine language (binary 0s and 1s). The C compiler translates human-readable source code (.c) through 4 stages: Preprocessing (expanding headers like #include <stdio.h>), Compilation (translating C to assembly), Assembly (converting assembly to machine object code), and Linking (combining object code with system libraries into a runnable executable).",
      problems: [
        { title: 'Airport Gate Terminal Initialization', points: 30, difficulty: 'Basic',
          description: "Write a minimal C program that compiles cleanly and outputs the gate initialization confirmation message to the standard console, exactly like an airport terminal boots up and confirms it's online before passengers arrive.\n\nInput: None\nExpected Output:\nGate 14B: System Online",
          criteria: ['The program compiles through all 4 stages without error (correct #include, main(), and syntax)', 'The exact line "Gate 14B: System Online" is printed, nothing more, nothing less'],
          hint: 'A single printf("Gate 14B: System Online\\n"); inside main() is all this needs.',
          solution: 'A minimal, cleanly compiling C program whose only output is the exact confirmation line.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Anatomy of main() and Program Entry', video_url: 'https://www.youtube.com/watch?v=h4VBpylsjJc',
      topic: "Real-life analogy: Think of entering an automated factory. No matter how large the facility is, operations always initiate through a single designated master control switch labeled \"Gate 1: Entry Point\" - the main() function is that universal entry point.\n\nEvery C program must have exactly one int main() function. The int keyword indicates that the program reports an exit status integer back to the Operating System. The code block boundaries are defined by curly braces { }, each statement must terminate with a semicolon ;, and return 0; indicates standard error-free termination.",
      problems: [
        { title: 'Server Handshake Status', points: 30, difficulty: 'Basic',
          description: "Create a structured C source file containing the standard main() block and return code that outputs a server handshake status, the way a server confirms a clean connection before any data flows.\n\nInput: None\nExpected Output:\nServer Handshake: 200 OK",
          criteria: ['Exactly one int main() function exists, with curly-brace boundaries and every statement ending in a semicolon', 'The function ends with return 0; after printing the exact handshake line'],
          hint: 'printf("Server Handshake: 200 OK\\n"); then return 0; inside int main() { ... }.',
          solution: 'A correctly structured int main() that prints the handshake line and returns 0 for clean termination.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Standard Output & Escape Sequences', video_url: 'https://www.youtube.com/watch?v=h4VBpylsjJc',
      topic: "Real-life analogy: Think of an office typewriter with carriage-return and tab levers. Typing without the levers puts all text on a single messy line - hitting the return lever moves down to a fresh line, while hitting the tab key aligns items into neat columns.\n\nThe printf() function prints text to standard console output. Escape sequences prefixed by a backslash allow layout formatting: \\n inserts a newline character, \\t creates a tab-stop gap, and \\\" prints a literal double quote.",
      problems: [
        { title: 'Cafe POS Itemized Receipt', points: 40, difficulty: 'Core',
          description: "Use a single printf() statement with escape sequences (\\n and \\t) to print a multi-line, tab-aligned receipt header and line items, the way a cafe's point-of-sale printer lines up an itemized bill.\n\nInput: None\nExpected Output:\nITEM\\tQTY\\tCOST\nEspresso\\t2\\t$6.00\nMuffin\\t1\\t$3.50",
          criteria: ['Every line break comes from \\n and every column gap from \\t inside ONE printf() call, not multiple calls or literal spaces', 'The three output lines and their tab-separated columns match exactly, in order'],
          hint: 'One printf("ITEM\\tQTY\\tCOST\\nEspresso\\t2\\t$6.00\\nMuffin\\t1\\t$3.50\\n"); does the whole receipt.',
          solution: 'A single printf() using \\n and \\t escape sequences to produce the exact tab-aligned 3-line receipt.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'Primitive Data Types & Memory Footprint', video_url: 'https://www.youtube.com/watch?v=sARaqR0hRI4',
      topic: "Real-life analogy: Think of specialized kitchen containers - a small spice jar for salt (1 byte for a char), a mid-sized jug for milk (4 bytes for an integer), and a large tank for water reserves (8 bytes for a high-precision double).\n\nC requires explicit data type declarations to allocate memory in RAM: int allocates 4 bytes for whole numbers (-2 billion to +2 billion), float allocates 4 bytes for 6-decimal-place numbers, double allocates 8 bytes for 15-decimal-place precision, and char allocates 1 byte for an ASCII character.",
      problems: [
        { title: 'Patient Intake Triage Card', points: 30, difficulty: 'Basic',
          description: "Declare an integer for age (28), a double for body temperature (98.6), and a char for blood group ('O'). Print each on a new line, the way a hospital triage card records a patient's vitals in the right-sized container for each value.\n\nInput: None (Hardcoded)\nExpected Output:\nAge: 28\nTemp: 98.600000\nBlood Group: O",
          criteria: ['age is declared int, temperature double, and blood group char - never the wrong container for the value', 'Each is printed with the matching format specifier (%d, %f, %c) producing exactly the 3 lines shown'],
          hint: 'double defaults to 6 decimal places with %f, so 98.6 prints as 98.600000 - that is expected, not a bug.',
          solution: 'Three correctly-typed variables (int, double, char) printed with their matching specifiers, reproducing the triage card exactly.' },
      ] },
    { no: 5, week: 2, session: 2, title: 'Variable Declaration, Initialization & Constants', video_url: 'https://www.youtube.com/watch?v=aIQk1O08zpg',
      topic: "Real-life analogy: Renting a gym locker is declaration - the locker is reserved in your name, but dirty clothes from the last user might be inside (garbage value). Putting your clean gear inside is initialization. Adding a permanent master padlock is declaring it const.\n\nDeclaring a variable allocates RAM but leaves whatever random leftover bits were previously stored at that address. Initializing (int count = 0;) ensures predictable behavior. The const keyword marks a variable as read-only; any subsequent reassignment causes a compiler error.",
      problems: [
        { title: 'Fixed Toll Plaza Billing', points: 30, difficulty: 'Basic',
          description: "Declare a const int toll rate of 50. Declare an integer vehicles initialized to 4. Compute total revenue and print formatted results, the way a toll plaza's rate never changes mid-shift but the vehicle count does.\n\nInput: None\nExpected Output:\nToll Rate: 50\nVehicles: 4\nTotal Revenue: 200",
          criteria: ['tollRate is declared const int and vehicles is a plain, initialized int (never left uninitialized)', 'Total Revenue is computed as tollRate * vehicles and prints as exactly 200'],
          hint: 'const int tollRate = 50; int vehicles = 4; then print tollRate * vehicles for the total.',
          solution: 'A const toll rate multiplied by an initialized vehicle count, printing all three lines exactly as shown.' },
      ] },
    { no: 6, week: 2, session: 3, title: 'Format Specifiers', video_url: 'https://www.youtube.com/watch?v=iLZOL-hmr7M',
      topic: "Real-life analogy: Think of 3D optical filter glasses - the raw screen emits mixed light, but wearing red/cyan lenses lets your eyes decode the exact intended 3D visual. Format specifiers are the decoding lenses that tell printf how to interpret binary data.\n\nBinary data in memory needs interpretation rules: %d formats integers, %f formats floats, %.2f rounds and formats floating-point values to 2 decimal places, and %c displays single character symbols.",
      problems: [
        { title: 'Precision Currency Formatter', points: 40, difficulty: 'Core',
          description: "Take a raw unrounded float value 129.8765 and print it formatted to 2 decimal places preceded by a dollar sign, the way a checkout receipt always shows exactly two decimal places for money, never four.\n\nInput: None\nExpected Output:\nFinal Charge: $129.88",
          criteria: ['The format specifier is %.2f, not the default %f (which would print 6 decimals)', '129.8765 rounds correctly to 129.88 (not truncated to 129.87), with the dollar sign printed literally'],
          hint: 'printf("Final Charge: $%.2f\\n", 129.8765); - %.2f both rounds and limits to 2 decimals.',
          solution: 'A %.2f-formatted printf that correctly rounds 129.8765 to 129.88 with the dollar sign prefix.' },
      ] },
    { no: 7, week: 2, session: 4, title: 'Interactive Input with scanf()', video_url: 'https://www.youtube.com/watch?v=17gp5DJEyiw',
      topic: "Real-life analogy: When a courier delivers a parcel, you don't just describe the package - you must provide your exact physical street address so the parcel is dropped directly at your doorstep. The & symbol gives scanf() your variable's memory address.\n\nThe scanf() function reads characters from the Standard Input (stdin) stream. Because scanf() must write incoming data directly into your variable's memory cell in RAM, it requires the memory address obtained using the address-of operator &.",
      problems: [
        { title: 'ATM Cash Withdrawal Prompt', points: 40, difficulty: 'Core',
          description: "Read an integer withdrawal amount from input using scanf() and print an execution confirmation message, exactly like an ATM confirms the amount before dispensing cash.\n\nSample Input: 500\nExpected Output:\nProcessing withdrawal for $500. Dispensing cash...",
          criteria: ['scanf("%d", &amount); includes the & before the variable name, or it would write to a random memory spot', 'The confirmation line embeds the exact scanned value, matching the sample output for input 500'],
          hint: 'scanf("%d", &amount); then printf("Processing withdrawal for $%d. Dispensing cash...\\n", amount);',
          solution: 'A scanf() read using &, whose value is printed back inside the exact confirmation message format.' },
      ] },
    { no: 8, week: 3, session: 1, title: 'Arithmetic & Modulo Operations', video_url: 'https://www.youtube.com/watch?v=_57FcSBtJNU',
      topic: "Real-life analogy: If you divide 11 apples among 2 people, each person gets 5 whole apples (integer division 11 / 2 = 5), and 1 single apple remains in the basket (modulo remainder 11 % 2 = 1).\n\nArithmetic in C follows standard math rules, but integer division truncates decimal fractions completely without rounding. The modulo operator % yields the integer remainder after division, making it essential for cyclic events, parity tests, and time calculations.",
      problems: [
        { title: 'Warehouse Cargo Box Packer', points: 30, difficulty: 'Basic',
          description: "A shipping crate holds 6 items. Read an integer total of items from input, compute packed crates and leftover loose items - the same way a warehouse worker fills full crates first and sets the remainder aside.\n\nSample Input: 29\nExpected Output:\nFull Crates: 4\nRemaining Items: 5",
          criteria: ['Full crates use integer division (total / 6) and remaining items use modulo (total % 6), not the other way round', 'For input 29, the program prints exactly "Full Crates: 4" and "Remaining Items: 5"'],
          hint: 'crates = total / 6; leftover = total % 6;',
          solution: 'Integer division for crate count and modulo for the leftover, correctly packing 29 items into 4 crates plus 5 loose items.' },
      ] },
    { no: 9, week: 3, session: 2, title: 'Relational & Logical Decisions', video_url: 'https://www.youtube.com/watch?v=xyQrVEFz9kw',
      topic: "Real-life analogy: An airport security check requires: \"Do you have a passport (Condition 1) AND a boarding pass (Condition 2)?\" If both are verified true, you pass through the gate - if either is missing, access is denied.\n\nC treats 0 as False and any non-zero integer as True. Relational operators (<, >, ==, !=) yield 1 or 0. Logical AND (&&) requires all conditions to be true, Logical OR (||) requires at least one to be true, and Logical NOT (!) inverts truth values.",
      problems: [
        { title: 'Theme Park Ride Safety Gate', points: 40, difficulty: 'Core',
          description: "Read height (cm) and age as two space-separated integers. Print Eligibility: 1 if height is at least 120 AND age is at least 10, otherwise print Eligibility: 0 - exactly like a ride's safety gate checks both conditions together before letting anyone through.\n\nSample Input: 135 12\nExpected Output:\nEligibility: 1",
          criteria: ['Both conditions are combined with && (logical AND), not evaluated or printed separately', 'For input "135 12" the program prints exactly "Eligibility: 1"'],
          hint: 'if (height >= 120 && age >= 10) printf("Eligibility: 1\\n"); else printf("Eligibility: 0\\n");',
          solution: 'A single && combined condition correctly gating eligibility to 1 only when both height and age thresholds are met.' },
      ] },
    { no: 10, week: 3, session: 3, title: 'Branching with if, else if, and else', video_url: 'https://www.youtube.com/watch?v=iD05HmGLZXc',
      topic: "Real-life analogy: Think of a train reaching an automated track switch. If the signal is green, the switch steers onto Track 1. If yellow, it steers onto Track 2. In any other condition, it diverts to the safety siding.\n\nThe if statement checks a condition. If true, its block executes and all alternate branches are bypassed. If false, control passes sequentially through each else if block. If all tests fail, the default else fallback block executes.",
      problems: [
        { title: 'Smart Thermostat Temperature Alert', points: 40, difficulty: 'Core',
          description: "Read an integer Celsius temperature. Print ALERT: HIGH if it is above 35, ALERT: LOW if it is below 15, and STATUS: NORMAL otherwise - the same three-way branch a smart thermostat runs on every reading.\n\nSample Input: 38\nExpected Output:\nALERT: HIGH",
          criteria: ['The three outcomes are chained as if / else if / else, not three separate independent if statements', 'For input 38 the program prints exactly "ALERT: HIGH", and only one branch ever runs per input'],
          hint: 'if (temp > 35) ... else if (temp < 15) ... else printf("STATUS: NORMAL\\n");',
          solution: 'A correctly chained if/else-if/else that prints exactly one alert per temperature, HIGH for 38.' },
      ] },
    { no: 11, week: 4, session: 1, title: 'Counter-Controlled for Loops', video_url: 'https://www.youtube.com/watch?v=b4DPj0XAfSg',
      topic: "Real-life analogy: A running coach instructs an athlete: \"Run 5 laps around the track. Start at lap 1, add 1 lap every time you cross the line, and stop after lap 5.\" The start, step, and stop counts are all defined upfront.\n\nWhen the total number of iterations is known before loop entry, a for loop consolidates loop setup: for (initialization; condition; update). The initialization runs once, the condition is evaluated before each iteration, and the update statement executes after each loop body run.",
      problems: [
        { title: 'Rocket Launch Countdown', points: 30, difficulty: 'Basic',
          description: "Read an integer start value from input and count down to 1 using a for loop, followed by LIFTOFF! - the same fixed, known-in-advance countdown every rocket launch runs.\n\nSample Input: 5\nExpected Output:\n5 4 3 2 1 LIFTOFF!",
          criteria: ['A for loop counts down from the input value to 1 (the iteration count is known upfront, matching a for loop, not a while loop)', 'The numbers print space-separated on one line, followed immediately by "LIFTOFF!"'],
          hint: 'for (int i = start; i >= 1; i--) printf("%d ", i); then printf("LIFTOFF!\\n");',
          solution: 'A for loop counting down from the input to 1, space-separated, ending with LIFTOFF! on the same line.' },
      ] },
    { no: 12, week: 4, session: 2, title: 'Condition-Driven while Loops', video_url: 'https://www.youtube.com/watch?v=qUPXsPtWGoY',
      topic: "Real-life analogy: You don't decide in advance to hold an umbrella for exactly 350 steps - you check the sky and keep holding it while rain continues to fall. When the rain stops, you close the umbrella.\n\nA while loop is used when the number of cycles is indeterminate and driven by runtime events or changing data values. It tests the condition before executing the body - if the condition is false initially, the loop never runs.",
      problems: [
        { title: 'EV Fast-Charging Battery Monitor', points: 40, difficulty: 'Core',
          description: "Read an integer starting battery level. Increment it by 10% in a while loop until the level reaches or exceeds 100%, then print the final percentage - the same open-ended charge cycle an EV's battery monitor runs, whose length depends entirely on the starting level.\n\nSample Input: 75\nExpected Output:\nCharging complete: 105%",
          criteria: ['A while loop repeats the +10% step only while level < 100, since the number of cycles is not known in advance', 'For a starting level of 75, the loop runs until it lands on exactly 105% (75 -> 85 -> 95 is still under 100, so a third +10 step is required) and prints "Charging complete: 105%"'],
          hint: 'while (level < 100) { level += level * 0.10; } then print the final level - it will overshoot past 100, which is expected.',
          solution: 'A while loop repeatedly adding 10% until the level is no longer under 100, correctly landing on 105% for a starting level of 75.' },
      ] },
    { no: 13, week: 4, session: 3, title: 'Loop Controls (break & continue)', video_url: 'https://www.youtube.com/watch?v=qUPXsPtWGoY',
      topic: "Real-life analogy: On a bottling line, if an empty bottle passes by, the labeler skips it and moves to the next bottle (continue). But if a glass bottle shatters on the conveyor, the operator hits the emergency stop button immediately (break).\n\nThe break statement causes immediate termination of the innermost loop, transferring control to the next statement outside the loop. The continue statement skips all remaining lines in the current iteration and jumps directly to the next loop evaluation.",
      problems: [
        { title: 'Inventory Defect Scanner', points: 40, difficulty: 'Core',
          description: "Read count N, then N item codes. Print valid positive codes. Skip code 0 using continue. Halt immediately on a negative code with break and print HALTED - exactly like a scanner skips an empty slot but emergency-stops on a damaged item.\n\nSample Input:\n5\n101 0 102 -1 103\nExpected Output:\n101 102 HALTED",
          criteria: ['Code 0 is skipped with continue (never printed), while a negative code triggers break immediately, stopping before any later codes are read', 'For the sample input the program prints exactly "101 102 HALTED", never reaching 103'],
          hint: 'if (code == 0) continue; if (code < 0) { printf("HALTED\\n"); break; } else printf("%d ", code);',
          solution: 'A loop using continue to skip zero codes and break to halt immediately on a negative code, printing 101 102 HALTED and never processing 103.' },
      ] },
    { no: 14, week: 5, session: 1, title: 'Function Declarations & Prototypes', video_url: 'https://www.youtube.com/watch?v=vc9A6HdrTz4',
      topic: "Real-life analogy: Think of a restaurant menu summary. Before the kitchen prepares dishes described further down in the detailed kitchen binder, the customer reads the menu title and ingredients at the front - the prototype announces what exists before use.\n\nC compilers scan files sequentially from top to bottom. If a function is called before its full definition is reached, the compiler raises an undeclared error. A function prototype placed at the top declares the function's name, return type, and parameter list in advance.",
      problems: [
        { title: 'Temperature Unit Converter Module', points: 30, difficulty: 'Basic',
          description: "Declare the prototype float toFahrenheit(float c); at the top of the file. Define the actual function below main(). Read a float Celsius value and print it converted to Fahrenheit, formatted to 1 decimal place - just like the menu announces the dish before the kitchen binder defines how to make it.\n\nSample Input: 25.0\nExpected Output:\n77.0 F",
          criteria: ['A prototype float toFahrenheit(float c); appears above main(), with the full definition placed below main()', 'The formula (c * 9/5) + 32 is used, and the result prints with exactly 1 decimal place followed by " F" (77.0 F for input 25.0)'],
          hint: 'float toFahrenheit(float c) { return (c * 9.0/5.0) + 32; } - print with %.1f.',
          solution: "A prototyped-then-defined-below-main() toFahrenheit function using the correct formula, printed to 1 decimal as '77.0 F'." },
      ] },
    { no: 15, week: 5, session: 2, title: 'Pass-by-Value & Parameter Passing', video_url: 'https://www.youtube.com/watch?v=7VM571tSKC0',
      topic: "Real-life analogy: If you give a classmate a photocopy of your notes and they scribble calculations on it, the original master copy safely in your backpack remains completely clean and unchanged.\n\nC uses Pass-by-Value by default. When passing variables to functions, a separate temporary copy is created in that function's stack frame. Modifying the parameter inside the function alters only the local copy, leaving the original variable in main() intact.",
      problems: [
        { title: 'Coupon Discount Scope Verification', points: 40, difficulty: 'Core',
          description: "Write a function void applyPromo(int val) that subtracts 20 from val. In main(), initialize price = 100, call applyPromo(price), and print price in main() afterward - proving the photocopy (the parameter) was scribbled on, not the original.\n\nInput: None\nExpected Output:\nOriginal Price in main: 100",
          criteria: ['applyPromo(int val) modifies only its local parameter val, never anything declared in main()', "After calling applyPromo(price), main()'s price is printed and is still exactly 100 - proving pass-by-value"],
          hint: 'void applyPromo(int val) { val -= 20; } - calling it can never change price back in main().',
          solution: "An applyPromo function that only edits its own copy, so main()'s price prints unchanged at 100 after the call." },
      ] },
    { no: 16, week: 5, session: 3, title: 'Return Types & Void Functions', video_url: 'https://www.youtube.com/watch?v=7Bq87y7eJEg',
      topic: "Real-life analogy: Asking an accountant to compute net profit yields a specific financial figure back (return value). Asking an office assistant to ring the fire alarm executes an emergency routine without handing you a calculation (void function).\n\nA function's return type dictates the type of data sent back to the caller via the return statement. When a function executes actions (such as logging warnings, playing tones, or formatting screens) without computing a return value, its return type is declared as void.",
      problems: [
        { title: 'Emergency Siren Dispatcher', points: 60, difficulty: 'Boss',
          description: "Write a function void triggerAlert(int code) that prints a formatted emergency dispatch notice. Read an integer code and call the function - the capstone finale, combining everything from functions to formatted output into one dispatch routine, exactly like an office assistant rings the alarm without returning any figure back.\n\nSample Input: 404\nExpected Output:\n*** EMERGENCY ALERT: CODE 404 ACTIVE ***",
          criteria: ['triggerAlert is declared void (it performs an action and returns nothing) and is called with the scanned code', 'For input 404 the exact line "*** EMERGENCY ALERT: CODE 404 ACTIVE ***" is printed, with the code value correctly embedded'],
          hint: 'void triggerAlert(int code) { printf("*** EMERGENCY ALERT: CODE %d ACTIVE ***\\n", code); }',
          solution: 'A void triggerAlert(int code) function that prints the exact dispatch line embedding the scanned code, called from main() with no return value expected.' },
      ] },
  ],
},

{
  key: 'fc02-cpp-objects', course_code: 'FC-02', free: true, friendly_grading: true, default_language: 'cpp',
  title: 'CS-102: Fundamentals of C++ (with Object-Oriented Programming)',
  description: 'Foundation-first, then functions, then full object-oriented programming, then modern C++ and persistence - the standard teaching language for data structures and competitive programming, and OOP done properly in a real language. Four modules, eleven topics, two tasks each, building an expense tracker called LedgerLens with real classes, inheritance and file persistence - certificate at the end.',
  outcome: 'Use modern stream I/O, references and function overloading for clean C++ code; design encapsulated classes with constructors, inheritance and virtual functions for real object-oriented programs; apply STL containers and algorithms (vector, string, sort, accumulate) plus file persistence to build a complete, working application.',
  keywords: ['fundamentals of C++', 'C++ with OOP', 'free C++ course', 'learn C++ online', 'object oriented programming in C++'],
  key_concepts: ['cout/cin & program structure', 'Variables, types & operators', 'Decisions & loops', 'Functions, overloading & defaults', 'References vs pointers', 'std::string & vectors', 'Classes & encapsulation', 'Inheritance & polymorphism', 'Range loops, auto & dynamic memory', 'STL algorithms & file handling'],
  pass_mark: 60, titleNames: ['Object Rookie', 'Class Builder'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'cout / cin & Program Structure', video_url: null,
      topic: "In C++, cout prints to the screen and cin reads input, both using << and >>. Every program runs from main(). This replaces C's printf/scanf with a cleaner style.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"LedgerLens ready\" << endl;\n    return 0;\n}",
      problems: [
        { title: 'Welcome Banner', points: 30, difficulty: 'Basic',
          description: "cout uses << to print and needs #include <iostream> (and using namespace std;, or std::cout) to work. Print a multi-line LedgerLens banner and a text menu using cout.",
          criteria: ['#include <iostream> is present', 'Multiple lines print correctly using << endl or \\n'],
          hint: 'Chain << operators, or use endl / \\n between lines.',
          solution: 'A multi-line banner and menu printed with cout, iostream included.' },
        { title: 'Formatted Receipt', points: 40, difficulty: 'Core',
          description: "setw(n) sets the width of only the very next output, so it must appear before every column, not once at the start. Print an expense receipt with aligned columns (item, category, amount) using iomanip's setw.",
          criteria: ['#include <iomanip> is present', 'setw(n) appears before each column so all rows line up neatly'],
          hint: 'Place setw(n) immediately before each field you print.',
          solution: 'A receipt with setw() applied before every column, producing neatly aligned output.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Variables, Types & Operators', video_url: null,
      topic: "Variables hold typed values: int (whole), double (decimal, best for money math here), bool (true/false), string (text). Operators do arithmetic and comparison.\n\n#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    double amount = 49.99;\n    string category = \"Food\";\n    cout << category << \": \" << amount << endl;\n    return 0;\n}",
      problems: [
        { title: 'One Expense', points: 30, difficulty: 'Basic',
          description: "double stores money correctly (with cents); char only holds a single letter, not a whole word. Store one expense (amount as double, category and note as strings) and print it formatted.",
          criteria: ['amount is a double, category and note are strings (not char)', 'All three print with their real values, not a single truncated letter'],
          hint: 'Use double for amount and string (needs #include <string>) for text.',
          solution: 'An expense with double amount and string fields, printed correctly.' },
        { title: 'Budget Percentage', points: 40, difficulty: 'Core',
          description: "Integer division truncates - 50/200 gives 0 unless at least one operand is a double. Given a monthly budget and total spent, compute and print what percentage of the budget is used, to 1 decimal place.",
          criteria: ['At least one operand in the division is a double so the fraction survives', 'setprecision(1) with fixed shows exactly one decimal place (e.g. 25.0%)'],
          hint: 'percent = (spent / budget) * 100; with at least one double operand.',
          solution: 'A double-safe percentage calculation printed with setprecision(1) and fixed.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Decisions & Loops', video_url: null,
      topic: "if/else-if/switch choose paths; for/while/do-while repeat. Together they drive the interactive menu that keeps running until the user exits.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    bool running = true;\n    while (running) {\n        cout << \"1) Add 2) Exit\" << endl;\n        running = false;\n    }\n    return 0;\n}",
      problems: [
        { title: 'Keep-Alive Menu', points: 30, difficulty: 'Basic',
          description: "A bool flag flipped off on Exit is what actually stops a while(running) loop. Loop the menu (Add / View / Exit) until the user picks Exit.",
          criteria: ['A while(running) or do-while loop wraps the menu', 'The menu returns after every action and stops only when Exit flips the flag'],
          hint: 'Use a bool running flag, set to false only on Exit.',
          solution: 'A while(running) loop that keeps showing the menu until Exit sets running to false.' },
        { title: 'Spending Alert', points: 40, difficulty: 'Core',
          description: "The 100% check must come before (or be an else-if to) the 80% check, or a huge expense only ever triggers the 80% warning. After each expense, if total spending crosses 80% of budget warn the user, and if it crosses 100% block further spending.",
          criteria: ['The 100%-or-over check is evaluated before/exclusive of the 80% check', 'A large expense that blows past 100% shows the block message, not just the 80% warning'],
          hint: 'Check the 100% condition first (or as else-if), then the 80% condition.',
          solution: 'Correctly ordered if/else-if thresholds so a large overage always hits the 100% block, not the 80% warning.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'Functions, Overloading & Default Arguments', video_url: null,
      topic: "Functions group reusable logic. Overloading lets two functions share a name but take different parameters. Default arguments let a parameter fall back to a preset value if the caller omits it.\n\n#include <iostream>\nusing namespace std;\nvoid addExpense(double amount) { cout << amount << endl; }\nint main() { addExpense(50); return 0; }",
      problems: [
        { title: 'Split Into Functions', points: 30, difficulty: 'Basic',
          description: "Functions declared (or prototyped) before main() avoid 'not declared' compile errors. Create addExpense(), showMenu() and showTotal() functions, each doing one job.",
          criteria: ['Each function does exactly one job', 'All three are declared/prototyped before main() (or defined above it)'],
          hint: 'Prototype or define each function above main().',
          solution: 'Three single-purpose functions, main() reduced to a short set of calls to them.' },
        { title: 'Overloaded Add', points: 40, difficulty: 'Core',
          description: "Overloading and defaults can't be combined in a way that makes a call ambiguous, or the compiler will refuse to guess which one you meant. Overload addExpense so one version takes a note and one doesn't, and give category a default value of 'General'.",
          criteria: ['Two addExpense versions exist (overloaded, or one with a default note)', 'Calling with or without a note both work, and omitting category uses "General"'],
          hint: 'Give category a default: string category="General".',
          solution: 'Overloaded/default addExpense that works with or without a note, defaulting category to "General".' },
      ] },
    { no: 5, week: 2, session: 2, title: 'References vs Pointers', video_url: null,
      topic: "Both let you work with the original variable instead of a copy. A pointer stores an address and uses * and &; a reference is a simpler alias to an existing variable using &. References are cleaner for passing big data without copying. This is a Memory Radar lesson.\n\n#include <iostream>\nusing namespace std;\nvoid addExpense(double amount, double &total) { total += amount; }\nint main() {\n    double total = 0;\n    addExpense(50, total);\n    cout << total << endl;\n    return 0;\n}",
      problems: [
        { title: 'Pass By Reference', points: 30, difficulty: 'Basic',
          description: "Without the &, a function edits a COPY of the list and the caller's real list never grows. Refactor addExpense to take the expense list by reference so it isn't copied each call.",
          criteria: ['The parameter is declared with &, e.g. vector<Expense>& list', "The caller's actual list grows after the call, not just a local copy"],
          hint: 'void addExpense(vector<Expense>& list) - the & is required.',
          solution: "addExpense taking the list by reference, confirmed to grow the caller's real list." },
        { title: 'Pointer vs Reference Showdown', points: 40, difficulty: 'Core',
          description: "References need no * to use and can't be null or reseated, which is why they're preferred for simple pass-by-reference; pointers are needed when there might be 'no object'. Write the same 'add 10 to a value' operation twice - once with a pointer, once with a reference - and explain the difference in comments.",
          criteria: ['Both versions actually add 10 correctly (void f(int* x){*x+=10;} vs void f(int& x){x+=10;})', "A comment explains references are safer/cleaner but pointers allow a 'no object' (null) state"],
          hint: 'Pointer: *x += 10; called as f(&n). Reference: x += 10; called as f(n).',
          solution: 'Both a pointer and a reference version producing the same result, with a comment on when each is preferred.' },
      ] },
    { no: 6, week: 2, session: 3, title: 'std::string & Vectors', video_url: null,
      topic: "std::string handles text safely with built-in methods (length, comparison, concatenation). std::vector is a resizable array that grows on demand with push_back - no fixed size limit.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> expenses;\n    expenses.push_back(49.99);\n    cout << expenses.size() << endl;\n    return 0;\n}",
      problems: [
        { title: 'Unlimited Expenses', points: 30, difficulty: 'Basic',
          description: "A fixed array[100] defeats the point - vector grows with push_back so there's no preset limit. Store expenses in a vector and add new ones with push_back, removing any fixed limit.",
          criteria: ['#include <vector> and vector<...> expenses; are used, not a fixed-size array', 'push_back adds new expenses with no upper limit'],
          hint: 'expenses.push_back(amount); - no array size to worry about.',
          solution: 'A vector-based expense list that grows past any preset size using push_back.' },
        { title: 'Validate & Search', points: 40, difficulty: 'Core',
          description: "Exact-match (==) won't find 'food' inside 'fast food' - a substring search needs .find() instead. Reject empty categories and negative amounts, and let the user search expenses by category substring.",
          criteria: ['category.empty() and amount <= 0 are both checked before adding', 'Search uses category.find(query) != string::npos (substring), not =='],
          hint: 'category.find(query) != string::npos matches a substring.',
          solution: 'Validation rejecting empty categories/negative amounts, plus a substring search using .find().' },
      ] },
    { no: 7, week: 3, session: 1, title: 'Structs vs Classes & Encapsulation', video_url: null,
      topic: "A class bundles data AND the functions that act on it. Encapsulation means keeping data private and exposing controlled public methods, so nothing can corrupt an object's state from outside. This is where OOP begins.\n\n#include <iostream>\nusing namespace std;\nclass Expense {\n    double amount;\npublic:\n    double getAmount() { return amount; }\n};",
      problems: [
        { title: 'The Expense Class', points: 30, difficulty: 'Basic',
          description: "If outside code can still write expense.amount directly, the field isn't actually private. Turn Expense into a class with private fields (amount, category, note) and public getters.",
          criteria: ['amount, category and note are declared under private:', 'Public getter methods are the only way to read them from outside'],
          hint: 'Fields under private:, methods under public:.',
          solution: 'A class with private fields and public getters, with no direct outside access to the fields.' },
        { title: 'Constructors & Validation', points: 40, difficulty: 'Core',
          description: "A well-designed class makes it IMPOSSIBLE to create an invalid object - the constructor itself should guard against a negative amount. Add a constructor that sets all fields at creation and rejects invalid values (negative amount) inside the constructor.",
          criteria: ['A constructor Expense(double a, string c, string n) sets all fields at creation', 'A negative amount is clamped or rejected inside the constructor itself, not left to the caller to check'],
          hint: 'Validate a<0 directly inside the constructor body.',
          solution: 'A constructor using an initializer list that also guards against a negative amount, so every Expense is valid the moment it exists.' },
      ] },
    { no: 8, week: 3, session: 2, title: 'Inheritance & Polymorphism', video_url: null,
      topic: "Inheritance lets a class reuse another's members (a RecurringExpense IS-A Expense). Polymorphism lets the same method call behave differently depending on the actual object type, via virtual functions.\n\n#include <iostream>\nusing namespace std;\nclass Expense {\npublic:\n    virtual void describe() { cout << \"Expense\" << endl; }\n};\nclass RecurringExpense : public Expense {\npublic:\n    void describe() override { cout << \"Recurring\" << endl; }\n};",
      problems: [
        { title: 'A Recurring Expense', points: 30, difficulty: 'Basic',
          description: "The derived constructor must explicitly call the base constructor to initialize inherited fields. Create a RecurringExpense class that inherits from Expense and adds a 'frequency' field.",
          criteria: ['class RecurringExpense : public Expense syntax is used', 'The constructor calls the base constructor, e.g. RecurringExpense(...) : Expense(a,c,n)'],
          hint: 'Base fields must be protected (not private) if the derived class needs direct access.',
          solution: 'RecurringExpense inheriting from Expense, calling the base constructor and adding its own frequency field.' },
        { title: 'Polymorphic Reports', points: 40, difficulty: 'Core',
          description: "Storing objects by value 'slices' them and always calls the base version - the list must hold pointers/references for the right describe() to run. Give Expense a virtual describe() method, override it in RecurringExpense, then loop a mixed list calling describe() on each.",
          criteria: ['describe() is declared virtual in the base and overridden in the derived class', 'The list stores pointers (e.g. vector<Expense*>), so each object describes itself correctly, not sliced to the base version'],
          hint: 'Store vector<Expense*>, not a vector of plain Expense objects.',
          solution: 'A virtual describe() overridden in RecurringExpense, called correctly per-object from a pointer-based mixed list.' },
      ] },
    { no: 9, week: 4, session: 1, title: 'Range Loops, auto & Dynamic Memory', video_url: null,
      topic: "Range-based for loops and auto make iteration clean and readable. new/delete are C++'s manual memory tools - useful to understand, though vector usually handles it for you.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> expenses = {10, 20};\n    for (auto &e : expenses) e *= 1.1;\n    return 0;\n}",
      problems: [
        { title: 'Modernize the Loops', points: 30, difficulty: 'Basic',
          description: "for (auto e : ...) without & copies each item - fine for reading, but edits won't stick. Rewrite every display loop as for (auto& e : expenses).",
          criteria: ['Loops use for (auto& e : expenses), with the reference &', 'Editing e inside the loop actually changes the vector, proving no copy was made'],
          hint: 'Add & after auto to avoid copying each element.',
          solution: 'Range-based loops using auto& throughout, confirmed to edit the real elements.' },
        { title: 'Manual Memory, Then Why Not', points: 40, difficulty: 'Core',
          description: "Every new[] needs a matching delete[] (not plain delete), and forgetting it leaks memory - exactly why vector is preferred by default. Allocate an array of expenses with new[], use it, delete[] it - then write a comment on why vector is safer.",
          criteria: ['delete[] (array form) matches the earlier new[] allocation, not plain delete', 'A comment concludes vector is the safer default because it cleans up automatically'],
          hint: 'Use delete[] arr; to match new[], not delete arr;.',
          solution: "A new[]/delete[] pair used correctly, with a comment explaining why vector avoids this risk entirely." },
      ] },
    { no: 10, week: 4, session: 2, title: 'STL Algorithms', video_url: null,
      topic: "The Standard Template Library gives ready-made algorithms - sort, accumulate, max_element, count_if - that work on vectors so you don't hand-write common operations.\n\n#include <numeric>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> v = {10, 20, 30};\n    double total = accumulate(v.begin(), v.end(), 0.0);\n    return 0;\n}",
      problems: [
        { title: 'Instant Total', points: 30, difficulty: 'Basic',
          description: "Starting accumulate's seed at an int 0 forces integer math and drops the cents - it must start at 0.0. Use accumulate to sum all expense amounts in one line.",
          criteria: ['#include <numeric> is present', 'The seed value is 0.0 (a double), not 0, so the decimal total survives'],
          hint: 'accumulate(v.begin(), v.end(), 0.0); - the 0.0 matters.',
          solution: 'A one-line accumulate() call with a double seed producing an exact decimal total.' },
        { title: 'Smart Reports', points: 40, difficulty: 'Core',
          description: "max_element returns an ITERATOR, which must be dereferenced with * to get the actual object, and the sort comparator must use strict < or the sort misbehaves. Sort expenses by amount, find the biggest with max_element, and count how many are in a given category with count_if.",
          criteria: ['The sort comparator uses strict < (not <=)', 'max_element\'s result is dereferenced with * before use, and count_if uses a lambda predicate'],
          hint: '*max_element(v.begin(), v.end(), cmp) - remember to dereference.',
          solution: 'sort() with a strict-< comparator, a correctly dereferenced max_element() result, and count_if() with a matching-category lambda.' },
      ] },
    { no: 11, week: 4, session: 3, title: 'File Handling (fstream)', video_url: null,
      topic: "ofstream writes to a file, ifstream reads from one. This is how LedgerLens saves your expenses on exit and loads them again next time.\n\n#include <fstream>\nusing namespace std;\nint main() {\n    ofstream out(\"expenses.txt\");\n    out << \"50,Food,Lunch\\n\";\n    out.close();\n    return 0;\n}",
      problems: [
        { title: 'Save on Exit', points: 30, difficulty: 'Basic',
          description: "One expense per line with a chosen delimiter keeps the file simple to read back later. Write every expense to a text file when the program closes.",
          criteria: ['ofstream writes one expense per line with a consistent delimiter', 'The file opening is checked and the stream is properly closed'],
          hint: 'ofstream out("expenses.txt"); one line per expense.',
          solution: 'Every expense written to a text file, one per line, on a delimiter, file properly closed.' },
        { title: 'Load & Rebuild', points: 60, difficulty: 'Boss',
          description: "The parse must exactly match the save format, and a note containing the delimiter itself (like a comma) is a real edge case worth testing. On startup, read the file back and rebuild the expense vector so data persists across runs - the capstone finale.",
          criteria: ['The file being absent on first run is handled without crashing', 'The parse format exactly matches the save format, correctly rebuilding every expense (including one edge case like a delimiter inside a note)'],
          hint: 'ifstream in("expenses.txt"); read with getline() and parse each line to match the save format exactly.',
          solution: 'A load routine that handles a missing file gracefully and exactly reverses the save format - close and reopen LedgerLens, and every expense returns.' },
      ] },
  ],
},

];
