'use strict';
/** EchoLens tracks - CS-101/CS-102 (Fundamentals of C / C++ with OOP).
 * free: true -> every quest is open to signed-in learners, and completing
 * all topics above the pass mark issues the verified certificate
 * automatically. The rest of the fundamentals-of-programming curriculum
 * (CS-104..CS-106) lives in tracks/cs-fundamentals.js. Five tracks total:
 * C, C++ (OOP folded into Module 3), Python, JavaScript, HTML & CSS
 * (combined) - each exactly 4 modules, from zero, per the EchoLens
 * Curriculum Blueprint. video_url is intentionally left null across every
 * level here - no video links exist for this curriculum yet.
 */

module.exports = [

{
  key: 'fc01-c-basics', course_code: 'FC-01', free: true, friendly_grading: true, default_language: 'c',
  title: 'CS-101: Fundamentals of C',
  description: 'Absolute beginner to hardware-level understanding - the classic foundation language behind operating systems, databases, and almost every other language you will ever use. Four modules, ten topics, two tasks each, building a menu-driven MiniBank CLI end to end - certificate at the end.',
  outcome: 'Understand program structure, variables and operators, and read/write user input; use decisions and loops to drive an interactive menu; write functions and work with arrays and strings; use pointers, dynamic memory, structs and file handling to build a persistent program.',
  keywords: ['fundamentals of C', 'basics of C programming', 'free C course', 'learn C language online', 'C programming for beginners'],
  key_concepts: ['printf, main & program structure', 'Variables & data types', 'Operators & scanf', 'if / else-if / switch', 'Loops (for, while, do-while)', 'Functions & pass-by-value', 'Arrays & strings', 'Pointers', 'Dynamic memory (malloc/free)', 'Structs & file handling'],
  pass_mark: 60, titleNames: ['C Starter', 'C Solver'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'printf, main & Program Structure', video_url: null,
      topic: "Every C program starts running from main(). printf() prints text to the screen - this is how your program 'talks' to the user.\n\n#include <stdio.h>\nint main() {\n    printf(\"MiniBank ready.\\n\");\n    return 0;\n}",
      problems: [
        { title: 'Welcome Banner', points: 30, difficulty: 'Basic',
          description: "Every C program starts running from main(), and printf() is how it writes text to the screen. Write a program that prints a 3-line welcome banner for MiniBank using printf().",
          criteria: ['#include <stdio.h>, an int main() function, and return 0; are all present', 'printf() calls (single or multiple with \\n) produce exactly 3 lines'],
          hint: 'Use three printf() calls, or one with \\n between lines.',
          solution: 'A compiling main() with #include <stdio.h>, three printed lines, and return 0;.' },
        { title: 'ASCII Art Logo', points: 40, difficulty: 'Core',
          description: "printf() prints exactly what you give it, character for character - including special characters that normally need escaping. Write a program that prints a boxed logo using only printf() and special characters, making sure the box edges line up perfectly.",
          criteria: ['A literal backslash uses \\\\ and a literal quote uses \\" inside the string', 'The box edges align (characters were counted per line)'],
          hint: 'To print a literal backslash you need \\\\, and to print a quote you need \\".',
          solution: 'A printf-only boxed logo with escaped characters and perfectly aligned edges.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Variables & Data Types (int, float, char)', video_url: null,
      topic: "A variable is a labeled box in memory that holds a value. int holds whole numbers, float holds decimals, char holds a single letter. You must declare the type before using it.\n\n#include <stdio.h>\nint main() {\n    int accountNo = 1;\n    float balance = 100.0;\n    char initial = 'A';\n    printf(\"Balance: %f\\n\", balance);\n    return 0;\n}",
      problems: [
        { title: 'Account Snapshot', points: 30, difficulty: 'Basic',
          description: "Check the RIGHT type for each field: float for money, int for whole numbers, char for a single letter. Write a program that declares variables for an account holder's name-initial (char), balance (float) and account number (int), then prints all three.",
          criteria: ['float is used for balance, int for account number, char for the initial', 'Each is printed with its matching specifier (%f, %d, %c)'],
          hint: 'Match specifiers to types: %d for int, %f for float, %c for char.',
          solution: 'Three correctly-typed variables printed with matching format specifiers.' },
        { title: 'Data Type Overflow Test', points: 40, difficulty: 'Core',
          description: "A standard int overflows around 2.1 billion, wrapping to a negative or wrong value once you exceed it. Store a very large number (e.g. 5,000,000,000) in an int, print it, and explain in a comment what happens and why.",
          criteria: ['The program prints the wrong/wrapped value for the oversized number', 'A comment explains that int has a fixed memory size and long long is needed for larger values'],
          hint: 'A standard int cannot hold a number that large - it wraps around.',
          solution: 'The int overflows to an unexpected value, with a comment explaining the fixed-size limit and long long as the fix.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Operators & scanf (Getting Input)', video_url: null,
      topic: "Operators do math (+ - * / %). scanf() reads what the user types and stores it in a variable using its address (&). The % operator gives the remainder of a division.\n\n#include <stdio.h>\nint main() {\n    float balance;\n    scanf(\"%f\", &balance);\n    printf(\"Balance: %.2f\\n\", balance);\n    return 0;\n}",
      problems: [
        { title: 'Deposit Adder', points: 30, difficulty: 'Basic',
          description: "scanf needs the & before the variable name, or it writes to a random memory spot instead of your variable. Write a program that asks the user for a starting balance and a deposit amount, then prints the new balance.",
          criteria: ['Both scanf calls include & before the variable name', 'The printed total is the starting balance plus the deposit'],
          hint: 'scanf("%f", &balance); - never forget the &.',
          solution: 'Two scanf("%f", &var) reads, summed and printed correctly.' },
        { title: 'Change-Making Machine', points: 40, difficulty: 'Core',
          description: "Integer division (/) grabs a count and modulo (%) keeps the leftover, and repeating that pattern breaks an amount into ever-smaller units. Given an amount in cents, use / and % to break it into the fewest dollars, quarters, dimes, nickels and pennies.",
          criteria: ['Each step divides for the count then takes % for the remainder before the next step', 'Multiplying all the coin counts back to cents reproduces the original amount'],
          hint: 'dollars = cents/100; cents = cents%100; quarters = cents/25; and so on.',
          solution: 'A chain of integer-division/modulo pairs that correctly breaks the amount into coins, verified by summing back to the original.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'if / else-if / switch', video_url: null,
      topic: "These let your program choose different paths. if runs code only when a condition is true; else-if adds more choices; switch is a clean way to pick between many fixed options (like menu numbers).\n\n#include <stdio.h>\nint main() {\n    int choice = 1;\n    switch (choice) {\n        case 1: printf(\"Deposit\\n\"); break;\n        default: printf(\"Invalid\\n\");\n    }\n    return 0;\n}",
      problems: [
        { title: 'Overdraft Guard', points: 30, difficulty: 'Basic',
          description: "A single = is assignment, == is comparison - mixing them up is a classic bug. Before a withdrawal, use an if/else to block it if the amount is greater than the balance.",
          criteria: ['The condition uses == or > correctly, not a single =', 'A withdrawal larger than the balance is blocked, not allowed through'],
          hint: 'if (amount > balance) print an error, else subtract.',
          solution: 'if/else blocking any withdrawal greater than the balance.' },
        { title: 'Menu Router with switch', points: 40, difficulty: 'Core',
          description: "Without a break;, execution 'falls through' to the next case and runs multiple options at once. Build the full MiniBank menu (1=Deposit, 2=Withdraw, 3=Balance, 4=Exit) using switch, with a default for invalid input.",
          criteria: ['Every case ends with break;', 'A default: case catches invalid numbers'],
          hint: 'Add break; after every case, and a default: for anything else.',
          solution: 'A switch with a break after each case and a default for invalid choices - choosing one option never triggers another.' },
      ] },
    { no: 5, week: 2, session: 2, title: 'Loops (for, while, do-while)', video_url: null,
      topic: "A loop repeats code. for is best when you know how many times; while repeats as long as a condition holds; do-while always runs at least once (perfect for menus that must show once before checking exit).\n\n#include <stdio.h>\nint main() {\n    int choice;\n    do {\n        printf(\"1) Deposit 2) Exit\\n\");\n        scanf(\"%d\", &choice);\n    } while (choice != 2);\n    return 0;\n}",
      problems: [
        { title: 'Keep-Alive Menu', points: 30, difficulty: 'Basic',
          description: "do-while fits a menu better than while because the menu should show once before the exit condition is even checked. Wrap the menu in a loop so the app keeps returning to it until the user chooses Exit.",
          criteria: ['A do-while loop wraps the menu', 'The menu reappears after every action and stops only on Exit'],
          hint: 'do-while runs the menu body first, then checks whether to loop again.',
          solution: 'A do-while loop showing the menu each pass, ending only when Exit is chosen.' },
        { title: 'Interest Projection Table', points: 40, difficulty: 'Core',
          description: "The balance must carry over between iterations - updated in place, not recalculated from the original each time. Given a balance and yearly interest rate, print a table showing the balance for each of the next 10 years with compound growth.",
          criteria: ['balance is updated in place each iteration (balance += balance*rate), not reset from the original', "Year 2's value compounds on year 1's, not on the starting balance"],
          hint: 'balance = balance + balance*rate; inside a for loop from year 1 to 10.',
          solution: 'A for loop compounding the running balance each year, producing a 10-row growth table.' },
      ] },
    { no: 6, week: 3, session: 1, title: 'Functions, Scope & Pass-By-Value', video_url: null,
      topic: "A function is a named block of code you can reuse. It can take inputs (parameters) and give back a result (return). In C, arguments are passed BY VALUE - the function gets a copy, so changing it inside doesn't affect the original.\n\n#include <stdio.h>\nfloat deposit(float balance, float amount) { return balance + amount; }\nint main() {\n    float bal = 100;\n    bal = deposit(bal, 50);\n    printf(\"%.2f\\n\", bal);\n    return 0;\n}",
      problems: [
        { title: 'Split Into Functions', points: 30, difficulty: 'Basic',
          description: "The caller must capture a function's return value, or the change never sticks since C passes by value. Move deposit and withdraw logic into their own functions that take the balance and amount and return the new balance.",
          criteria: ['Each function returns the new balance rather than modifying it directly', 'The caller reassigns the result, e.g. balance = deposit(balance, amount);'],
          hint: 'float deposit(float balance, float amount) returning balance+amount.',
          solution: "deposit()/withdraw() functions whose return value is reassigned back by the caller." },
        { title: 'The Pass-By-Value Trap', points: 40, difficulty: 'Core',
          description: "Because C passes arguments by value, a function that changes its parameter is only changing a copy - the original is untouched back in main. Write a function that tries to change the balance directly (without returning it), then show the change is lost and explain why in a comment.",
          criteria: ['The function modifies its parameter but does not return anything', "main's before/after values are shown to be identical", 'A comment explains this is because the function worked on a copy (pass-by-value)'],
          hint: 'The parameter changes inside the function, but the original in main never does.',
          solution: "A function proven not to change the caller's variable, with a comment explaining pass-by-value." },
      ] },
    { no: 7, week: 3, session: 2, title: 'Arrays & Strings', video_url: null,
      topic: "An array stores many values of the same type under one name, accessed by index starting at 0. A string in C is just an array of chars ending in a hidden \\0 marker.\n\n#include <stdio.h>\nint main() {\n    float balances[5] = {100, 200, 300, 400, 500};\n    printf(\"%.2f\\n\", balances[0]);\n    return 0;\n}",
      problems: [
        { title: 'Multi-Account Store', points: 30, difficulty: 'Basic',
          description: "Valid indexes for a 5-element array run from 0 to 4 - going to index 5 reads garbage or crashes. Store 5 account balances in an array, then loop through to print them all and the total.",
          criteria: ['The loop only accesses indexes 0 through 4, never 5', 'The printed total correctly sums all 5 balances'],
          hint: 'float balances[5]; access with balances[0] through balances[4].',
          solution: 'A loop from index 0 to 4 that prints each balance and accumulates the correct total.' },
        { title: 'Highest & Lowest Balance', points: 40, difficulty: 'Core',
          description: "Initialize max and min to the FIRST element, not to 0 - a real balance could be negative with overdraft, breaking a max-at-0 start. Without sorting, scan the array once to find both the largest and smallest balance and which account holds each.",
          criteria: ['max and min both start at the first element, not at a hard-coded 0', 'The loop tracks both the value and the index in a single pass'],
          hint: 'Start max/min at the first element, then loop from index 1 updating them.',
          solution: 'A single-pass scan starting max/min at index 0, correctly tracking both value and account index.' },
      ] },
    { no: 8, week: 4, session: 1, title: 'Pointers (& and *)', video_url: null,
      topic: "A pointer is a variable that stores the ADDRESS of another variable, not its value. & gives you an address; * follows an address to reach the value. This is how C lets functions change the original data. This is the Memory Radar hero lesson.\n\n#include <stdio.h>\nvoid deposit(float *balance, float amount) { *balance += amount; }\nint main() {\n    float bal = 100;\n    deposit(&bal, 50);\n    printf(\"%.2f\\n\", bal);\n    return 0;\n}",
      problems: [
        { title: 'Update Through a Pointer', points: 30, difficulty: 'Basic',
          description: "Passing the address with & lets a function reach back and change the REAL variable, fixing last module's pass-by-value trap. Write a function that takes a pointer to the balance and adds a deposit to the original.",
          criteria: ['The function signature takes a float pointer, e.g. void deposit(float *balance, float amount)', 'The caller passes the address (deposit(&balance, 100);) and the change sticks afterward'],
          hint: 'Inside the function use *balance += amount;, and call it as deposit(&balance, 100);.',
          solution: "A pointer-parameter function that permanently updates the caller's original balance." },
        { title: 'Swap Two Accounts', points: 40, difficulty: 'Core',
          description: "A pointer swap needs a temporary variable and every line must dereference with * - swapping the pointers themselves instead of the values they point to is the classic mistake. Write a swap() function that exchanges the balances of two accounts using pointers.",
          criteria: ['A temporary variable holds *a before either assignment happens', 'All three lines dereference with *, and it is called as swap(&acc1, &acc2)'],
          hint: 'temp = *a; *a = *b; *b = temp;',
          solution: 'void swap(float *a, float *b) using a temp variable, called with &acc1, &acc2, correctly exchanging the values.' },
      ] },
    { no: 9, week: 4, session: 2, title: 'Dynamic Memory (malloc / free)', video_url: null,
      topic: "Sometimes you don't know how many items you'll need until the program runs. malloc() asks the operating system for memory at runtime; free() gives it back so it isn't wasted (a leak).\n\n#include <stdlib.h>\nint main() {\n    int n = 3;\n    int *accounts = malloc(n * sizeof(int));\n    free(accounts);\n    return 0;\n}",
      problems: [
        { title: 'Runtime-Sized Account List', points: 30, difficulty: 'Basic',
          description: "Every malloc should have a matching free, and forgetting to multiply by sizeof allocates too little memory. Ask the user how many accounts they have, then malloc exactly that many and fill them.",
          criteria: ['The allocation multiplies by sizeof(int) (or the relevant type), not just n', 'free() is called on the allocated memory before the program ends'],
          hint: 'int *accounts = malloc(n * sizeof(int));',
          solution: 'A runtime-sized malloc allocation, used like a normal array, freed at the end.' },
        { title: 'Grow the List', points: 40, difficulty: 'Core',
          description: "realloc(ptr, newSize) returns a possibly-new address and copies the old data over - you must assign it back, or the old accounts vanish. Start with room for 2 accounts; when the user adds a 3rd, use realloc to double the capacity, keeping the old data.",
          criteria: ["realloc's return value is assigned back to the pointer variable", 'capacity and count are tracked as two separate variables, and old data survives the grow'],
          hint: 'accounts = realloc(accounts, newCap * sizeof(int));',
          solution: 'A realloc-based grow that captures the return value and preserves existing accounts, with capacity and count tracked separately.' },
      ] },
    { no: 10, week: 4, session: 3, title: 'Structures (struct) & File Handling', video_url: null,
      topic: "A struct bundles related data into one type - e.g. an Account with a name, number and balance together. File handling (FILE*, fprintf, fscanf) lets you save that data to disk so it survives after the program closes.\n\n#include <stdio.h>\nstruct Account { char name[30]; int number; float balance; };\nint main() {\n    struct Account acc = {\"Alice\", 1, 100.0};\n    printf(\"%s: %.2f\\n\", acc.name, acc.balance);\n    return 0;\n}",
      problems: [
        { title: 'Model an Account', points: 30, difficulty: 'Basic',
          description: "A struct's fields are accessed with the dot operator directly, or the arrow operator through a pointer to it. Define a struct Account with name, number and balance, create one, and print its fields.",
          criteria: ['The struct has name, number and balance fields', 'Each field prints its own value, not garbage (all were initialized)'],
          hint: 'Access fields with the dot operator: acc.balance.',
          solution: 'A struct Account with three fields, created and printed correctly via the dot operator.' },
        { title: 'Save & Reload Everything', points: 60, difficulty: 'Boss',
          description: "fopen must be checked against NULL for a missing file, and the fprintf/fscanf format strings must match exactly or reloaded data comes out scrambled. Save all accounts to a file on exit, and load them back when the program starts, so data persists - the capstone finale.",
          criteria: ["fopen()'s return value is checked for NULL before use (a missing file on first run must not crash)", 'The fprintf write format and fscanf read format match exactly, and the file is fclose()d'],
          hint: 'fopen("accounts.txt", "w") to save, "r" to load; check for NULL before reading or writing.',
          solution: 'Save/load functions using matching fprintf/fscanf formats, a NULL check for a missing file, and fclose() - accounts survive a restart.' },
      ] },
  ],
},

{
  key: 'fc02-cpp-objects', course_code: 'FC-02', free: true, friendly_grading: true, default_language: 'cpp',
  title: 'CS-102: Fundamentals of C++ (with Object-Oriented Programming)',
  description: 'Foundation-first, then functions, then full object-oriented programming, then modern C++ and persistence - the standard teaching language for data structures and competitive programming, and OOP done properly in a real language. Four modules, eleven topics, two tasks each, building an expense tracker called LedgerLens with real classes, inheritance and file persistence - certificate at the end.',
  outcome: 'Use modern stream I/O, references and function overloading for clean C++ code; design encapsulated classes with constructors, inheritance and virtual functions for real object-oriented programs; apply STL containers and algorithms (vector, string, sort, accumulate) plus file persistence to build a complete, working application.',
  keywords: ['fundamentals of C++', 'C++ with OOP', 'free C++ course', 'learn C++ online', 'object oriented programming in C++'],
  key_concepts: ['cout/cin & program structure', 'Variables, types & operators', 'Decisions & loops', 'Functions, overloading & defaults', 'References vs pointers', 'std::string & vectors', 'Classes & encapsulation', 'Inheritance & polymorphism', 'Range loops, auto & dynamic memory', 'STL algorithms & file handling'],
  pass_mark: 60, titleNames: ['Object Rookie', 'Class Builder'],
  levels: [
    { no: 1, week: 1, session: 1, title: 'cout / cin & Program Structure', video_url: null,
      topic: "In C++, cout prints to the screen and cin reads input, both using << and >>. Every program runs from main(). This replaces C's printf/scanf with a cleaner style.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    cout << \"LedgerLens ready\" << endl;\n    return 0;\n}",
      problems: [
        { title: 'Welcome Banner', points: 30, difficulty: 'Basic',
          description: "cout uses << to print and needs #include <iostream> (and using namespace std;, or std::cout) to work. Print a multi-line LedgerLens banner and a text menu using cout.",
          criteria: ['#include <iostream> is present', 'Multiple lines print correctly using << endl or \\n'],
          hint: 'Chain << operators, or use endl / \\n between lines.',
          solution: 'A multi-line banner and menu printed with cout, iostream included.' },
        { title: 'Formatted Receipt', points: 40, difficulty: 'Core',
          description: "setw(n) sets the width of only the very next output, so it must appear before every column, not once at the start. Print an expense receipt with aligned columns (item, category, amount) using iomanip's setw.",
          criteria: ['#include <iomanip> is present', 'setw(n) appears before each column so all rows line up neatly'],
          hint: 'Place setw(n) immediately before each field you print.',
          solution: 'A receipt with setw() applied before every column, producing neatly aligned output.' },
      ] },
    { no: 2, week: 1, session: 2, title: 'Variables, Types & Operators', video_url: null,
      topic: "Variables hold typed values: int (whole), double (decimal, best for money math here), bool (true/false), string (text). Operators do arithmetic and comparison.\n\n#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n    double amount = 49.99;\n    string category = \"Food\";\n    cout << category << \": \" << amount << endl;\n    return 0;\n}",
      problems: [
        { title: 'One Expense', points: 30, difficulty: 'Basic',
          description: "double stores money correctly (with cents); char only holds a single letter, not a whole word. Store one expense (amount as double, category and note as strings) and print it formatted.",
          criteria: ['amount is a double, category and note are strings (not char)', 'All three print with their real values, not a single truncated letter'],
          hint: 'Use double for amount and string (needs #include <string>) for text.',
          solution: 'An expense with double amount and string fields, printed correctly.' },
        { title: 'Budget Percentage', points: 40, difficulty: 'Core',
          description: "Integer division truncates - 50/200 gives 0 unless at least one operand is a double. Given a monthly budget and total spent, compute and print what percentage of the budget is used, to 1 decimal place.",
          criteria: ['At least one operand in the division is a double so the fraction survives', 'setprecision(1) with fixed shows exactly one decimal place (e.g. 25.0%)'],
          hint: 'percent = (spent / budget) * 100; with at least one double operand.',
          solution: 'A double-safe percentage calculation printed with setprecision(1) and fixed.' },
      ] },
    { no: 3, week: 1, session: 3, title: 'Decisions & Loops', video_url: null,
      topic: "if/else-if/switch choose paths; for/while/do-while repeat. Together they drive the interactive menu that keeps running until the user exits.\n\n#include <iostream>\nusing namespace std;\nint main() {\n    bool running = true;\n    while (running) {\n        cout << \"1) Add 2) Exit\" << endl;\n        running = false;\n    }\n    return 0;\n}",
      problems: [
        { title: 'Keep-Alive Menu', points: 30, difficulty: 'Basic',
          description: "A bool flag flipped off on Exit is what actually stops a while(running) loop. Loop the menu (Add / View / Exit) until the user picks Exit.",
          criteria: ['A while(running) or do-while loop wraps the menu', 'The menu returns after every action and stops only when Exit flips the flag'],
          hint: 'Use a bool running flag, set to false only on Exit.',
          solution: 'A while(running) loop that keeps showing the menu until Exit sets running to false.' },
        { title: 'Spending Alert', points: 40, difficulty: 'Core',
          description: "The 100% check must come before (or be an else-if to) the 80% check, or a huge expense only ever triggers the 80% warning. After each expense, if total spending crosses 80% of budget warn the user, and if it crosses 100% block further spending.",
          criteria: ['The 100%-or-over check is evaluated before/exclusive of the 80% check', 'A large expense that blows past 100% shows the block message, not just the 80% warning'],
          hint: 'Check the 100% condition first (or as else-if), then the 80% condition.',
          solution: 'Correctly ordered if/else-if thresholds so a large overage always hits the 100% block, not the 80% warning.' },
      ] },
    { no: 4, week: 2, session: 1, title: 'Functions, Overloading & Default Arguments', video_url: null,
      topic: "Functions group reusable logic. Overloading lets two functions share a name but take different parameters. Default arguments let a parameter fall back to a preset value if the caller omits it.\n\n#include <iostream>\nusing namespace std;\nvoid addExpense(double amount) { cout << amount << endl; }\nint main() { addExpense(50); return 0; }",
      problems: [
        { title: 'Split Into Functions', points: 30, difficulty: 'Basic',
          description: "Functions declared (or prototyped) before main() avoid 'not declared' compile errors. Create addExpense(), showMenu() and showTotal() functions, each doing one job.",
          criteria: ['Each function does exactly one job', 'All three are declared/prototyped before main() (or defined above it)'],
          hint: 'Prototype or define each function above main().',
          solution: 'Three single-purpose functions, main() reduced to a short set of calls to them.' },
        { title: 'Overloaded Add', points: 40, difficulty: 'Core',
          description: "Overloading and defaults can't be combined in a way that makes a call ambiguous, or the compiler will refuse to guess which one you meant. Overload addExpense so one version takes a note and one doesn't, and give category a default value of 'General'.",
          criteria: ['Two addExpense versions exist (overloaded, or one with a default note)', 'Calling with or without a note both work, and omitting category uses "General"'],
          hint: 'Give category a default: string category="General".',
          solution: 'Overloaded/default addExpense that works with or without a note, defaulting category to "General".' },
      ] },
    { no: 5, week: 2, session: 2, title: 'References vs Pointers', video_url: null,
      topic: "Both let you work with the original variable instead of a copy. A pointer stores an address and uses * and &; a reference is a simpler alias to an existing variable using &. References are cleaner for passing big data without copying. This is a Memory Radar lesson.\n\n#include <iostream>\nusing namespace std;\nvoid addExpense(double amount, double &total) { total += amount; }\nint main() {\n    double total = 0;\n    addExpense(50, total);\n    cout << total << endl;\n    return 0;\n}",
      problems: [
        { title: 'Pass By Reference', points: 30, difficulty: 'Basic',
          description: "Without the &, a function edits a COPY of the list and the caller's real list never grows. Refactor addExpense to take the expense list by reference so it isn't copied each call.",
          criteria: ['The parameter is declared with &, e.g. vector<Expense>& list', "The caller's actual list grows after the call, not just a local copy"],
          hint: 'void addExpense(vector<Expense>& list) - the & is required.',
          solution: "addExpense taking the list by reference, confirmed to grow the caller's real list." },
        { title: 'Pointer vs Reference Showdown', points: 40, difficulty: 'Core',
          description: "References need no * to use and can't be null or reseated, which is why they're preferred for simple pass-by-reference; pointers are needed when there might be 'no object'. Write the same 'add 10 to a value' operation twice - once with a pointer, once with a reference - and explain the difference in comments.",
          criteria: ['Both versions actually add 10 correctly (void f(int* x){*x+=10;} vs void f(int& x){x+=10;})', "A comment explains references are safer/cleaner but pointers allow a 'no object' (null) state"],
          hint: 'Pointer: *x += 10; called as f(&n). Reference: x += 10; called as f(n).',
          solution: 'Both a pointer and a reference version producing the same result, with a comment on when each is preferred.' },
      ] },
    { no: 6, week: 2, session: 3, title: 'std::string & Vectors', video_url: null,
      topic: "std::string handles text safely with built-in methods (length, comparison, concatenation). std::vector is a resizable array that grows on demand with push_back - no fixed size limit.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> expenses;\n    expenses.push_back(49.99);\n    cout << expenses.size() << endl;\n    return 0;\n}",
      problems: [
        { title: 'Unlimited Expenses', points: 30, difficulty: 'Basic',
          description: "A fixed array[100] defeats the point - vector grows with push_back so there's no preset limit. Store expenses in a vector and add new ones with push_back, removing any fixed limit.",
          criteria: ['#include <vector> and vector<...> expenses; are used, not a fixed-size array', 'push_back adds new expenses with no upper limit'],
          hint: 'expenses.push_back(amount); - no array size to worry about.',
          solution: 'A vector-based expense list that grows past any preset size using push_back.' },
        { title: 'Validate & Search', points: 40, difficulty: 'Core',
          description: "Exact-match (==) won't find 'food' inside 'fast food' - a substring search needs .find() instead. Reject empty categories and negative amounts, and let the user search expenses by category substring.",
          criteria: ['category.empty() and amount <= 0 are both checked before adding', 'Search uses category.find(query) != string::npos (substring), not =='],
          hint: 'category.find(query) != string::npos matches a substring.',
          solution: 'Validation rejecting empty categories/negative amounts, plus a substring search using .find().' },
      ] },
    { no: 7, week: 3, session: 1, title: 'Structs vs Classes & Encapsulation', video_url: null,
      topic: "A class bundles data AND the functions that act on it. Encapsulation means keeping data private and exposing controlled public methods, so nothing can corrupt an object's state from outside. This is where OOP begins.\n\n#include <iostream>\nusing namespace std;\nclass Expense {\n    double amount;\npublic:\n    double getAmount() { return amount; }\n};",
      problems: [
        { title: 'The Expense Class', points: 30, difficulty: 'Basic',
          description: "If outside code can still write expense.amount directly, the field isn't actually private. Turn Expense into a class with private fields (amount, category, note) and public getters.",
          criteria: ['amount, category and note are declared under private:', 'Public getter methods are the only way to read them from outside'],
          hint: 'Fields under private:, methods under public:.',
          solution: 'A class with private fields and public getters, with no direct outside access to the fields.' },
        { title: 'Constructors & Validation', points: 40, difficulty: 'Core',
          description: "A well-designed class makes it IMPOSSIBLE to create an invalid object - the constructor itself should guard against a negative amount. Add a constructor that sets all fields at creation and rejects invalid values (negative amount) inside the constructor.",
          criteria: ['A constructor Expense(double a, string c, string n) sets all fields at creation', 'A negative amount is clamped or rejected inside the constructor itself, not left to the caller to check'],
          hint: 'Validate a<0 directly inside the constructor body.',
          solution: 'A constructor using an initializer list that also guards against a negative amount, so every Expense is valid the moment it exists.' },
      ] },
    { no: 8, week: 3, session: 2, title: 'Inheritance & Polymorphism', video_url: null,
      topic: "Inheritance lets a class reuse another's members (a RecurringExpense IS-A Expense). Polymorphism lets the same method call behave differently depending on the actual object type, via virtual functions.\n\n#include <iostream>\nusing namespace std;\nclass Expense {\npublic:\n    virtual void describe() { cout << \"Expense\" << endl; }\n};\nclass RecurringExpense : public Expense {\npublic:\n    void describe() override { cout << \"Recurring\" << endl; }\n};",
      problems: [
        { title: 'A Recurring Expense', points: 30, difficulty: 'Basic',
          description: "The derived constructor must explicitly call the base constructor to initialize inherited fields. Create a RecurringExpense class that inherits from Expense and adds a 'frequency' field.",
          criteria: ['class RecurringExpense : public Expense syntax is used', 'The constructor calls the base constructor, e.g. RecurringExpense(...) : Expense(a,c,n)'],
          hint: 'Base fields must be protected (not private) if the derived class needs direct access.',
          solution: 'RecurringExpense inheriting from Expense, calling the base constructor and adding its own frequency field.' },
        { title: 'Polymorphic Reports', points: 40, difficulty: 'Core',
          description: "Storing objects by value 'slices' them and always calls the base version - the list must hold pointers/references for the right describe() to run. Give Expense a virtual describe() method, override it in RecurringExpense, then loop a mixed list calling describe() on each.",
          criteria: ['describe() is declared virtual in the base and overridden in the derived class', 'The list stores pointers (e.g. vector<Expense*>), so each object describes itself correctly, not sliced to the base version'],
          hint: 'Store vector<Expense*>, not a vector of plain Expense objects.',
          solution: 'A virtual describe() overridden in RecurringExpense, called correctly per-object from a pointer-based mixed list.' },
      ] },
    { no: 9, week: 4, session: 1, title: 'Range Loops, auto & Dynamic Memory', video_url: null,
      topic: "Range-based for loops and auto make iteration clean and readable. new/delete are C++'s manual memory tools - useful to understand, though vector usually handles it for you.\n\n#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> expenses = {10, 20};\n    for (auto &e : expenses) e *= 1.1;\n    return 0;\n}",
      problems: [
        { title: 'Modernize the Loops', points: 30, difficulty: 'Basic',
          description: "for (auto e : ...) without & copies each item - fine for reading, but edits won't stick. Rewrite every display loop as for (auto& e : expenses).",
          criteria: ['Loops use for (auto& e : expenses), with the reference &', 'Editing e inside the loop actually changes the vector, proving no copy was made'],
          hint: 'Add & after auto to avoid copying each element.',
          solution: 'Range-based loops using auto& throughout, confirmed to edit the real elements.' },
        { title: 'Manual Memory, Then Why Not', points: 40, difficulty: 'Core',
          description: "Every new[] needs a matching delete[] (not plain delete), and forgetting it leaks memory - exactly why vector is preferred by default. Allocate an array of expenses with new[], use it, delete[] it - then write a comment on why vector is safer.",
          criteria: ['delete[] (array form) matches the earlier new[] allocation, not plain delete', 'A comment concludes vector is the safer default because it cleans up automatically'],
          hint: 'Use delete[] arr; to match new[], not delete arr;.',
          solution: "A new[]/delete[] pair used correctly, with a comment explaining why vector avoids this risk entirely." },
      ] },
    { no: 10, week: 4, session: 2, title: 'STL Algorithms', video_url: null,
      topic: "The Standard Template Library gives ready-made algorithms - sort, accumulate, max_element, count_if - that work on vectors so you don't hand-write common operations.\n\n#include <numeric>\n#include <vector>\nusing namespace std;\nint main() {\n    vector<double> v = {10, 20, 30};\n    double total = accumulate(v.begin(), v.end(), 0.0);\n    return 0;\n}",
      problems: [
        { title: 'Instant Total', points: 30, difficulty: 'Basic',
          description: "Starting accumulate's seed at an int 0 forces integer math and drops the cents - it must start at 0.0. Use accumulate to sum all expense amounts in one line.",
          criteria: ['#include <numeric> is present', 'The seed value is 0.0 (a double), not 0, so the decimal total survives'],
          hint: 'accumulate(v.begin(), v.end(), 0.0); - the 0.0 matters.',
          solution: 'A one-line accumulate() call with a double seed producing an exact decimal total.' },
        { title: 'Smart Reports', points: 40, difficulty: 'Core',
          description: "max_element returns an ITERATOR, which must be dereferenced with * to get the actual object, and the sort comparator must use strict < or the sort misbehaves. Sort expenses by amount, find the biggest with max_element, and count how many are in a given category with count_if.",
          criteria: ['The sort comparator uses strict < (not <=)', 'max_element\'s result is dereferenced with * before use, and count_if uses a lambda predicate'],
          hint: '*max_element(v.begin(), v.end(), cmp) - remember to dereference.',
          solution: 'sort() with a strict-< comparator, a correctly dereferenced max_element() result, and count_if() with a matching-category lambda.' },
      ] },
    { no: 11, week: 4, session: 3, title: 'File Handling (fstream)', video_url: null,
      topic: "ofstream writes to a file, ifstream reads from one. This is how LedgerLens saves your expenses on exit and loads them again next time.\n\n#include <fstream>\nusing namespace std;\nint main() {\n    ofstream out(\"expenses.txt\");\n    out << \"50,Food,Lunch\\n\";\n    out.close();\n    return 0;\n}",
      problems: [
        { title: 'Save on Exit', points: 30, difficulty: 'Basic',
          description: "One expense per line with a chosen delimiter keeps the file simple to read back later. Write every expense to a text file when the program closes.",
          criteria: ['ofstream writes one expense per line with a consistent delimiter', 'The file opening is checked and the stream is properly closed'],
          hint: 'ofstream out("expenses.txt"); one line per expense.',
          solution: 'Every expense written to a text file, one per line, on a delimiter, file properly closed.' },
        { title: 'Load & Rebuild', points: 60, difficulty: 'Boss',
          description: "The parse must exactly match the save format, and a note containing the delimiter itself (like a comma) is a real edge case worth testing. On startup, read the file back and rebuild the expense vector so data persists across runs - the capstone finale.",
          criteria: ['The file being absent on first run is handled without crashing', 'The parse format exactly matches the save format, correctly rebuilding every expense (including one edge case like a delimiter inside a note)'],
          hint: 'ifstream in("expenses.txt"); read with getline() and parse each line to match the save format exactly.',
          solution: 'A load routine that handles a missing file gracefully and exactly reverses the save format - close and reopen LedgerLens, and every expense returns.' },
      ] },
  ],
},

];
