'use strict';
/** EchoLens prebuilt tracks - Short Courses (6 weeks -> 6 levels).
 * SC-01 Python for Data Science is served by the original 12-level python track. */

module.exports = [
{
  key: 'sc02-genai', course_code: 'SC-02', title: 'Generative AI Essentials',
  description: '6-week quest: engineer real RAG systems in LangChain - from tokens to a hybrid, reranked, agentic pipeline you serve in production.',
  pass_mark: 60, titleNames: ['Token Novice', 'Chunk Engineer', 'Retrieval Tuner', 'RAG Architect', 'GenAI Systems Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Tokens to Chunks', topic: 'Tokenization, context windows, and document chunking',
      problems: [
        { title: 'Token & Context Budget', points: 90, difficulty: 'Core',
          description: "Use a tokenizer to count the tokens in a real document and estimate the API cost of processing it end to end. Then truncate a long input to fit a model's context window and document exactly what information gets lost.\nCourse link: Week 1 - tokenization, context windows, and their cost.",
          refs: [['Tokenizer playground', 'https://platform.openai.com/tokenizer'], ['Context windows explained', 'https://www.ibm.com/think/topics/context-window']],
          criteria: ['Token count and cost estimate stated for the full document', 'Context-window truncation applied and the lost content identified', 'Explanation ties the loss to context-window limits, not vague description'],
          hint: 'Truncate from the middle of the document, not just the end - position within the context often matters as much as total length.',
          solution: 'Both the cost math and the truncation-loss demonstration are required. Vague "some info was lost" answers fail; the lost content must be named.' },
        { title: 'Three Ways to Chunk', points: 110, difficulty: 'Boss',
          description: 'Chunk the same real document three ways: fixed-size, recursive, and semantic. Tune chunk size and overlap for the strategy you prefer, then measure the retrieval hit rate against a handful of known questions to justify your choice.\nCourse link: Week 2 - chunking strategies and overlap tuning.',
          refs: [['Chunking strategies', 'https://www.pinecone.io/learn/chunking-strategies/'], ['LangChain text splitters', 'https://python.langchain.com/docs/concepts/text_splitters/']],
          criteria: ['All three chunking strategies implemented and compared on chunk boundaries', 'Chunk size and overlap tuned with a stated before/after hit rate', 'Final strategy choice justified with the measured numbers, not preference'],
          hint: 'Pick a handful of real questions you already know the answer to before you start tuning - without a fixed question set you cannot honestly measure hit rate.',
          solution: 'The hit-rate table across strategies is the pass gate. A justified choice grounded in numbers passes; a purely aesthetic choice does not.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Embeddings and Your First RAG', topic: 'Vector index engineering and a baseline LCEL RAG pipeline',
      problems: [
        { title: 'Embedding and Index Face-off', points: 100, difficulty: 'Core',
          description: 'Embed a set of texts with two different embedding models and compare the similarity scores they produce. Then index the same corpus in both Chroma and FAISS and compare the query results between the two.\nCourse link: Week 3 - embedding model choice and vector index engineering.',
          refs: [['Chroma docs', 'https://docs.trychroma.com/'], ['FAISS', 'https://github.com/facebookresearch/faiss']],
          criteria: ['Similarity scores compared across two embedding models on the same texts', 'Same corpus indexed and queried in both Chroma and FAISS', 'Differences in results explained, not just listed'],
          hint: 'Query both indexes with the exact same question and top-k so any difference in results comes from the index, not a changed query.',
          solution: 'Side-by-side comparison tables for both parts are required. An explanation of why results differ (index structure vs embedding space) earns the top marks.' },
        { title: 'Grounded, Cited RAG', points: 130, difficulty: 'Boss',
          description: "Build a baseline LCEL RAG chain that returns structured, Pydantic-validated answers with citations to the source chunks. Then feed it a question it cannot answer from the corpus and make it say so instead of hallucinating.\nCourse link: Week 4 - a baseline RAG pipeline and its honest limits.",
          refs: [['LangChain LCEL', 'https://python.langchain.com/docs/concepts/lcel/'], ['Pydantic docs', 'https://docs.pydantic.dev/']],
          criteria: ['RAG chain answers from the corpus with citations that map to real chunks', 'Output validated against a Pydantic schema', 'Unanswerable question correctly triggers a refusal instead of a hallucinated answer'],
          hint: 'The refusal case is the real test - if the model still invents an answer for the unanswerable question, your context-only instruction is not strict enough yet.',
          solution: 'The refusal-on-unanswerable case is the pass gate. Citations must point to verifiable chunks, not invented sources.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'Hybrid Retrieval', topic: 'Query transformation and hybrid BM25 + dense fusion',
      problems: [
        { title: 'Multi-Query and HyDE', points: 110, difficulty: 'Core',
          description: 'Add multi-query retrieval and HyDE (hypothetical document embeddings) to your RAG chain, then measure recall at k and mean reciprocal rank on a fixed question set before and after.\nCourse link: Week 5 - query transformation and measuring retrieval.',
          refs: [['LangChain multi-query retriever', 'https://python.langchain.com/docs/how_to/MultiQueryRetriever/']],
          criteria: ['Both multi-query retrieval and HyDE implemented on top of the baseline', 'Recall@k and MRR measured on the same fixed question set', 'Before/after numbers reported, not just described as "better"'],
          hint: 'Freeze your question set before you start changing the retriever, so the before/after comparison is measuring the same thing both times.',
          solution: 'A before/after recall@k and MRR table is the pass bar. Any genuine, measured delta (even a small one) is acceptable; an undocumented claim is not.' },
        { title: 'Build a Hybrid Retriever', points: 130, difficulty: 'Boss',
          description: 'Build a BM25 retriever, combine it with your dense retriever using reciprocal rank fusion, and find a query with a rare code or ID where dense retrieval fails and BM25 wins - then confirm the hybrid retriever fixes it.\nCourse link: Week 6 - hybrid dense and sparse fusion.',
          refs: [['LangChain ensemble retriever', 'https://python.langchain.com/docs/how_to/ensemble_retriever/']],
          criteria: ['BM25 retriever built and compared against the dense retriever on keyword-heavy queries', 'Reciprocal rank fusion implemented to merge both result lists', 'A specific rare-code query shown failing on dense-only and fixed by hybrid'],
          hint: 'Look for a query containing an exact code, ID, or uncommon proper noun - that is where sparse retrieval reliably beats dense, and the easiest place to prove the hybrid win.',
          solution: 'The fixed rare-code example is mandatory evidence, not a hypothetical. Hybrid must be measured against both dense-only and sparse-only, not just dense.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Reranking and Graphs', topic: 'Two-stage reranking and GraphRAG',
      problems: [
        { title: 'Cross-Encoder Rerank', points: 120, difficulty: 'Core',
          description: 'Retrieve a wide top-k, rerank with a cross-encoder wrapped in a contextual compression retriever, and measure the quality lift against the added latency and cost.\nCourse link: Week 7 - the two-stage retrieve-then-rerank pattern.',
          refs: [['LangChain contextual compression', 'https://python.langchain.com/docs/how_to/contextual_compression/']],
          criteria: ['Reranker wrapped in a contextual compression retriever that plugs into the chain', 'Answer quality compared with and without reranking on hard questions', 'Latency and cost the reranking step adds are measured and reported'],
          hint: 'Time and cost the reranked and non-reranked runs on the same questions back to back so the comparison is fair.',
          solution: 'Both the quality lift and the latency/cost cost must be reported together - a quality win with no cost accounting is an incomplete answer.' },
        { title: 'GraphRAG for Multi-Hop', points: 130, difficulty: 'Boss',
          description: 'Extract entities and relationships from your documents into a small knowledge graph, and answer a multi-hop question that flat vector retrieval fails on. Compare it head to head against vector RAG on the same question.\nCourse link: Week 8 - GraphRAG for relationship questions.',
          refs: [['Knowledge graphs for RAG', 'https://neo4j.com/developer-blog/knowledge-graph-rag-application/']],
          criteria: ['Small knowledge graph built from real extracted entities and relationships', 'Multi-hop question answered correctly using the graph', 'Same question run against plain vector RAG and shown to fail, with the two compared directly'],
          hint: 'Pick a question that genuinely requires connecting two separate facts through a relationship - a question flat retrieval could accidentally answer from one lucky chunk will not prove your point.',
          solution: 'The vector-RAG failure on the same question is the required contrast. Without it, the graph win cannot be verified as a graph win.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Agents and Fine-Tuning', topic: 'Agentic RAG with LangGraph and LoRA/QLoRA fine-tuning',
      problems: [
        { title: 'Agentic RAG Loop', points: 130, difficulty: 'Core',
          description: 'Expose your retriever as a tool an agent can call, build a LangGraph flow with a routing node that decides whether retrieval is needed, and add a corrective-RAG grading node that re-retrieves when the context is weak.\nCourse link: Week 9 - agentic RAG with LangGraph.',
          refs: [['LangGraph', 'https://langchain-ai.github.io/langgraph/']],
          criteria: ['Retriever exposed as a callable tool inside a LangGraph flow', 'Routing node correctly skips retrieval for queries that do not need it', 'Corrective grading node demonstrably re-retrieves on a weak-context case'],
          hint: 'Test the routing node with a query that obviously needs no retrieval at all, like basic arithmetic, to prove it is actually making a decision and not always retrieving.',
          solution: 'The re-retrieval must be shown triggering on a real weak-context example, not just described. Routing must be proven with a genuine no-retrieval case.' },
        { title: 'Fine-Tune vs RAG', points: 140, difficulty: 'Boss',
          description: 'Write a decision note arguing prompt versus RAG versus fine-tune for three given problems, then fine-tune a small open model with LoRA or QLoRA on a narrow task and compare it against your RAG system on the same task.\nCourse link: Week 10 - the retrieve-or-fine-tune decision, and PEFT.',
          refs: [['HuggingFace PEFT', 'https://huggingface.co/docs/peft/index']],
          criteria: ['Decision note argues all three options for each of the three problems with reasons', 'Small open model fine-tuned with LoRA or QLoRA on a narrow task', 'Fine-tuned model and RAG system compared directly on the same task'],
          hint: 'Choose a narrow task for the fine-tune, like a fixed output format or a specific domain style, where a small LoRA adapter can plausibly beat a general RAG answer - that makes the comparison meaningful.',
          solution: 'The decision note must reach a real conclusion per problem, not just list pros and cons. The fine-tune-vs-RAG comparison must run on identical test inputs.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: Ship a Production RAG System', topic: 'RAGAS evaluation, LangSmith tracing, and secure FastAPI serving',
      problems: [
        { title: 'RAGAS Scorecard', points: 130, difficulty: 'Core',
          description: 'Build a fixed evaluation set of question and ground-truth pairs for your corpus, run RAGAS to report faithfulness and answer relevance, and trace a full RAG call in LangSmith to find the slowest and weakest step.\nCourse link: Week 11 - evaluation with RAGAS and LangSmith.',
          refs: [['RAGAS docs', 'https://docs.ragas.io/'], ['LangSmith docs', 'https://docs.smith.langchain.com/']],
          criteria: ['Fixed evaluation set with real question and ground-truth pairs', 'RAGAS faithfulness and answer relevance scores reported', 'LangSmith trace identifies a specific slowest and weakest step'],
          hint: 'Include a few questions in your eval set that you expect to score poorly, not just the easy ones - a scorecard that is all high scores has not been stress-tested.',
          solution: 'Real RAGAS scores with the trace-identified bottleneck are the deliverable. A scorecard with no low scores anywhere is suspicious and should be questioned.' },
        { title: 'Ship a Production RAG System', points: 220, difficulty: 'Boss',
          description: 'Combine everything into a served, secure GenAI product: hybrid retrieval with reranking and routing, served behind a FastAPI endpoint with streaming and caching, a prompt-injection attack you launch yourself plus the guardrail that blocks it, and a README an interviewer could evaluate.\nCourse link: Weeks 1-12 combined - your portfolio project.',
          refs: [['FastAPI', 'https://fastapi.tiangolo.com/'], ['OWASP LLM Top 10', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/']],
          criteria: ['Hybrid retrieval with reranking and routing beats a plain vector-only baseline on the eval set', 'FastAPI endpoint streams responses and caches repeated queries', 'A self-run prompt-injection attack is documented along with the guardrail that blocks it'],
          hint: 'Design your own injection attempt before you build the guardrail, so you can prove the guardrail actually stops a real attack rather than one it was never tested against.',
          solution: 'Rubric: end-to-end system works incl. baseline comparison (35%), eval rigor (25%), security evidence (20%), serving quality incl. streaming/caching (20%).' },
      ] },
  ],
},
{
  key: 'sc03-sql-powerbi', course_code: 'SC-03', title: 'Data Analytics with SQL & Power BI',
  description: '6-week quest: query like an analyst, report like a professional - ending with a business dashboard.',
  pass_mark: 60, titleNames: ['Query Cadet', 'Join Ranger', 'Insight Hunter', 'Dashboard Smith', 'BI Analyst'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'SELECT Your Weapon', topic: 'SELECT, WHERE, ORDER BY, LIMIT',
      problems: [
        { title: 'First Queries', points: 60, difficulty: 'Basic',
          description: 'Load the classic Chinook database (free) into SQLite/DB Browser. Write and screenshot 6 queries: all customers from one country, tracks over 5 minutes, 10 most expensive tracks, invoices in a date range, distinct billing countries, and one query of your own with a business question attached.\nCourse link: Week 1 - core SELECT syntax.',
          refs: [['Chinook database', 'https://github.com/lerocha/chinook-database'], ['SQLite SELECT docs', 'https://www.sqlite.org/lang_select.html']],
          criteria: ['All six required queries run successfully against Chinook', 'Top-10 query uses ORDER BY with LIMIT correctly', 'Self-authored query is paired with a stated business question'],
          hint: 'For the "top 10 most expensive tracks" query, make sure you sort before you limit - limiting first and sorting after gives you the wrong 10 rows.',
          solution: 'All queries must run; check ORDER BY + LIMIT used correctly for "top 10". The self-authored business question shows intent.' },
        { title: 'The Filter Brief', points: 80, difficulty: 'Core',
          description: 'A manager asks: "Which customers from Germany or France spent on invoices above $10 in 2011-2012?" Translate to SQL with combined AND/OR logic (mind the parentheses), then write 2 more manager-style questions and answer them with queries.\nCourse link: Week 1 - boolean logic in WHERE clauses.',
          refs: [['SQL WHERE (W3Schools)', 'https://www.w3schools.com/sql/sql_where.asp']],
          criteria: ['Parentheses correctly group the OR condition inside the overall AND', 'Query correctly restricts to 2011-2012 and amounts above $10', 'Two additional manager-style questions answered with working queries'],
          hint: 'Write the logic out in plain English first, then wrap the OR part in its own parentheses before combining it with the AND conditions.',
          solution: 'The OR-inside-AND parentheses trap is the test. Verify results change when parentheses move - ask students to show both.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Joining Forces', topic: 'JOINs and aggregation',
      problems: [
        { title: 'The Revenue Report', points: 80, difficulty: 'Core',
          description: 'Using JOINs and GROUP BY on Chinook: revenue per country, top 5 artists by revenue, and monthly revenue trend for one year. Each query needs a one-line business takeaway. This is a real weekly analyst deliverable.\nCourse link: Week 2 - INNER JOIN, GROUP BY, aggregate functions.',
          refs: [['SQL JOIN visualizer', 'https://sql-joins.leopard.in.ua/'], ['GROUP BY docs', 'https://www.w3schools.com/sql/sql_groupby.asp']],
          criteria: ['Correct join chain from Invoice through Track and Album to Artist', 'Revenue by country, top-5 artists and monthly trend all produced', 'Each query paired with a one-line takeaway referencing actual numbers'],
          hint: 'For the top-5-artists query, trace the join path carefully: Invoice to InvoiceLine to Track to Album to Artist - skipping a step will silently miscount revenue.',
          solution: 'Check join keys are correct (Invoice->InvoiceLine->Track->Album->Artist chain for artists). Takeaways must reference actual numbers.' },
        { title: 'Find the Missing', points: 100, difficulty: 'Boss',
          description: 'Business question: "Which customers have NEVER purchased jazz?" and "Which genres earn the least?" Solve using LEFT JOIN with NULL checks or subqueries - explain your chosen approach and why the naive INNER JOIN gives the wrong answer.\nCourse link: Week 2 - LEFT JOIN semantics and anti-joins.',
          refs: [['LEFT JOIN explained', 'https://www.w3schools.com/sql/sql_join_left.asp']],
          criteria: ['Never-bought-jazz question solved with a LEFT JOIN/NULL check or anti-join subquery', 'Lowest-earning genres correctly identified', 'Explanation states why a naive INNER JOIN would give the wrong answer'],
          hint: 'Think about what an INNER JOIN between customers and jazz purchases actually returns - it can only ever show customers who did buy jazz, never the ones who did not.',
          solution: 'The anti-join concept is the pass bar. The "why INNER JOIN fails" explanation separates memorizers from understanders.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'Analyst Toolbelt', topic: 'CASE, subqueries, window functions, cleaning',
      problems: [
        { title: 'Customer Tiers', points: 100, difficulty: 'Core',
          description: 'Segment Chinook customers into Gold/Silver/Bronze by lifetime spend using CASE, then use a window function to rank customers within each country. Output one table: name, country, spend, tier, in-country rank.\nCourse link: Week 3 - CASE expressions and window functions.',
          refs: [['Window functions tutorial', 'https://mode.com/sql-tutorial/sql-window-functions/']],
          criteria: ['CASE expression correctly assigns Gold/Silver/Bronze by spend', 'Window function ranks customers within each country partition', 'Tier thresholds are stated and defensible'],
          hint: 'Remember PARTITION BY resets the ranking for each country separately - without it you will rank customers globally instead of within their own country.',
          solution: 'RANK/ROW_NUMBER with PARTITION BY country is the key skill. Tier thresholds must be stated and defensible.' },
        { title: 'Dirty Data Audit', points: 120, difficulty: 'Boss',
          description: 'Download any messy public CSV (Kaggle) and load it into your SQL tool. Write an audit: row count, NULLs per column, duplicates, inconsistent categories - all found via SQL. Then write the cleaning queries. Deliver before/after proof.\nCourse link: Week 3 - data quality checks in SQL.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          criteria: ['Audit reports row count, null counts per column and duplicate rows', 'Inconsistent category values are identified', 'Cleaning queries included with before/after proof'],
          hint: 'To count NULLs per column, compare COUNT(*) against COUNT(column_name) - the gap between them is your NULL count, without needing a separate query per column.',
          solution: 'GROUP BY ... HAVING COUNT(*)>1 for dupes and COUNT vs COUNT(col) for NULLs are expected patterns. Proof queries required.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Enter Power BI', topic: 'Data model, relationships, first visuals',
      problems: [
        { title: 'Model and Visualize', points: 100, difficulty: 'Core',
          description: 'Import 2+ related tables into Power BI Desktop (free), build the relationship correctly, and create 4 visuals: card (total revenue), bar (by category), line (trend), map or table. Screenshot the model view and explain the relationship direction.\nCourse link: Week 4 - star schema thinking and visual basics.',
          refs: [['Power BI Desktop docs', 'https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop'], ['Model relationships', 'https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand']],
          criteria: ['Relationship between tables is correctly key-matched, not auto-guessed', 'All four required visual types are present and working', 'Model view screenshot included with relationship direction explained'],
          hint: 'Check the relationship\'s cardinality and filter direction in the model view - a relationship pointing the wrong way will make some visuals silently show incorrect totals.',
          solution: 'The relationship must be genuine (key-matched), not auto-guessed wrongly. Model view screenshot is mandatory evidence.' },
        { title: 'DAX First Measures', points: 120, difficulty: 'Boss',
          description: 'Write 4 DAX measures: Total Revenue, Revenue LY (or previous period), % Growth, and Average Order Value. Show each formula and the visual using it. Explain the difference between a measure and a calculated column - the classic interview question.\nCourse link: Week 4 - DAX measures fundamentals.',
          refs: [['DAX basics', 'https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-quickstart-learn-dax-basics']],
          criteria: ['All four measures (Total Revenue, Revenue LY, % Growth, AOV) are implemented', 'Each measure is shown working in an actual visual', 'Measure-vs-calculated-column explanation mentions evaluation context'],
          hint: 'For Revenue LY, look into time-intelligence functions rather than manually filtering dates - they handle the context shift correctly across different date ranges.',
          solution: 'CALCULATE + time intelligence (or a clean previous-period filter) shows real skill. The measure-vs-column answer must mention evaluation context.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Dashboard Craft', topic: 'Design, interactivity, storytelling',
      problems: [
        { title: 'Interactive Dashboard', points: 110, difficulty: 'Core',
          description: 'Build a one-page interactive dashboard: KPI cards, slicers (date + category), cross-filtering visuals, consistent color theme, clear titles. Test with a colleague/family member for 5 minutes and report what confused them - real UX testing.\nCourse link: Week 5 - dashboard design and interactivity.',
          refs: [['Dashboard design guide', 'https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips']],
          criteria: ['Slicers for date and category both filter the page correctly', 'Visuals cross-filter each other consistently', 'Genuine five-minute user test conducted with findings reported'],
          hint: 'Pick one restrained color palette before you start adding visuals - it is much harder to fix rainbow-chart syndrome after the dashboard is built than to prevent it.',
          solution: 'Cross-filtering must work and the user-test finding must be genuine. Deduct for rainbow color chaos and unlabeled axes.' },
        { title: 'The Insight Memo', points: 130, difficulty: 'Boss',
          description: 'Analysts write, not just chart. From your dashboard, produce a 1-page memo: 3 findings (each with a number), 1 anomaly you investigated, and 2 recommended actions. Attach the supporting visuals. Findings without numbers are opinions.\nCourse link: Week 5 - from visuals to business decisions.',
          refs: [['Data storytelling', 'https://www.storytellingwithdata.com/blog']],
          criteria: ['All three findings are backed by a specific number from the dashboard', 'One anomaly is investigated, not just noticed', 'Two recommended actions follow logically from the findings'],
          hint: 'For the anomaly, do not just point at the weird spike - dig one level deeper into the data to find a plausible explanation before writing your recommendation.',
          solution: 'Every finding needs a metric. The anomaly investigation (checked, explained or flagged) is what analysts are actually paid for.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: Business Report', topic: 'End-to-end analytics project',
      problems: [
        { title: 'Full-Stack Analytics Project', points: 200, difficulty: 'Boss',
          description: 'Pick a real domain dataset (Pakistan open data, Kaggle retail, etc.): SQL cleaning + 5 analytical queries -> Power BI model -> polished dashboard -> executive memo. Deliver PDF: methodology, queries, dashboard screenshots, memo, and a link to your .pbix file.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [['Pakistan open data', 'https://data.gov.pk/'], ['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          criteria: ['SQL cleaning and five analytical queries are both delivered', 'Power BI model and dashboard are built on top of the cleaned data', 'Executive memo and .pbix link are both included in the final PDF'],
          hint: 'Build the pipeline in order - clean and validate the data in SQL first, since a shaky data model will undermine every visual and finding built on top of it.',
          solution: 'Rubric: SQL correctness (30%), model + DAX (25%), dashboard craft (25%), memo quality (20%). The story must survive without the student explaining it live.' },
      ] },
  ],
},
{
  key: 'sc04-intro-ml', course_code: 'SC-04', title: 'Introduction to Machine Learning',
  description: '6-week quest from ML intuition to trained, honestly-evaluated models.',
  pass_mark: 60, titleNames: ['Data Scout', 'Feature Finder', 'Model Trainer', 'Metric Judge', 'ML Practitioner'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Think in Data', topic: 'ML framing: features, labels, problem types',
      problems: [
        { title: 'Is It Even ML?', points: 60, difficulty: 'Basic',
          description: 'For 6 real scenarios (loan approval, electricity-bill prediction, spam filtering, ranking cricket players, grouping customers, converting currency) state: ML or plain rules? If ML - supervised or unsupervised, regression or classification, and what the features/label would be. Justify each in 2 lines.\nCourse link: Week 1 - problem framing, the most-skipped skill in ML.',
          refs: [['Google ML problem framing', 'https://developers.google.com/machine-learning/problem-framing']],
          criteria: ['Each of the six scenarios correctly classified as ML or plain rules', 'ML scenarios correctly labeled supervised/unsupervised and regression/classification', 'Features and label identified for each ML scenario with a justification'],
          hint: 'Ask yourself whether the task has a fixed, deterministic formula behind it - if a scenario can be solved with a simple formula or lookup table, it is not really ML.',
          solution: 'Currency conversion is rules, not ML - the trap. Grade the feature/label identification hardest.' },
        { title: 'Dataset First Contact', points: 80, difficulty: 'Core',
          description: 'Download the Titanic dataset. In pandas: shape, dtypes, missing values per column, target balance, and 3 charts (survival by sex, by class, age distribution). End with 3 hypotheses about what predicts survival - you will test them in Week 4.\nCourse link: Week 1 - exploratory data analysis before modeling.',
          refs: [['Titanic dataset', 'https://www.kaggle.com/c/titanic/data'], ['pandas EDA guide', 'https://pandas.pydata.org/docs/user_guide/10min.html']],
          criteria: ['Shape, dtypes, missing values and target balance all reported accurately', 'All three required charts are produced (sex, class, age)', 'Three hypotheses are falsifiable and grounded in the charts'],
          hint: 'Write each hypothesis as a specific, testable claim rather than a vague observation - you will need to test these later in Week 4.',
          solution: 'Hypotheses must be falsifiable and chart-grounded (sex and class patterns should surface). Missing-value counts must be exact.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Feature Workshop', topic: 'Cleaning, encoding, scaling',
      problems: [
        { title: 'Make It Model-Ready', points: 80, difficulty: 'Core',
          description: 'Prepare Titanic for ML: impute missing Age (justify your strategy), encode Sex and Embarked, engineer one new feature (FamilySize or Title from name), and scale numeric columns. Show before/after and explain WHY each step exists.\nCourse link: Week 2 - preprocessing pipeline.',
          refs: [['scikit-learn preprocessing', 'https://scikit-learn.org/stable/modules/preprocessing.html']],
          criteria: ['Missing Age imputed with a stated and justified strategy', 'Sex and Embarked encoded and a new feature engineered', 'Numeric columns scaled with before/after shown and each step\'s purpose explained'],
          hint: 'When deciding between mean and median imputation for Age, think about whether the age distribution has outliers that would skew a mean-based fill.',
          solution: 'The "why" per step is the grade: models need numbers, scale sensitivity, information extraction. Median vs mean imputation reasoning earns marks.' },
        { title: 'Leakage Hunt', points: 100, difficulty: 'Boss',
          description: 'The silent ML killer: data leakage. Given 5 described modeling setups (e.g. scaling before splitting, using "total bill paid" to predict default), identify which leak, why, and the fix. Then create one leakage example of your own in code and show the inflated vs honest accuracy.\nCourse link: Week 2 - leakage and why competition winners fail in production.',
          refs: [['Data leakage (Kaggle)', 'https://www.kaggle.com/code/alexisbcook/data-leakage']],
          criteria: ['All five described setups correctly identified as leaking or not, with reasons', 'Scaling-before-split case is correctly caught as leakage', 'Original coded example shows inflated vs honest accuracy side by side'],
          hint: 'For your own leakage example, fit your scaler or encoder on the full dataset before splitting, then compare that accuracy to the same model when the scaler is fit only on the training set.',
          solution: 'The self-made coded example with inflated-vs-honest numbers is the pass gate. Scaling-before-split must be caught.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'First Models', topic: 'Train/test split, regression, classification',
      problems: [
        { title: 'Predict the Price', points: 100, difficulty: 'Core',
          description: 'On the California Housing dataset: 80/20 split (fixed seed), LinearRegression, report MAE and R2 on test, and interpret 2 coefficients in plain Urdu-English a landlord would understand. Real skill: explaining models to non-technical clients.\nCourse link: Week 3 - regression end to end.',
          refs: [['California housing', 'https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset']],
          criteria: ['80/20 split uses a fixed random seed', 'MAE and R2 reported on the test set only', 'Two coefficients interpreted in plain language with correct units and direction'],
          hint: 'When interpreting a coefficient, state clearly what happens to the predicted price when that one feature goes up by one unit, holding everything else constant.',
          solution: 'Metrics must be test-set only. Coefficient interpretation must include units and direction; sign confusion is the common error.' },
        { title: 'Who Survives?', points: 110, difficulty: 'Boss',
          description: 'Train LogisticRegression and DecisionTree on your prepared Titanic data. Compare test accuracy, then answer: which of your Week-1 hypotheses survived? Show the tree\'s top splits as evidence. Close the loop from EDA to model.\nCourse link: Week 3 - classification and hypothesis testing.',
          refs: [['Logistic regression guide', 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression']],
          criteria: ['Both models trained and evaluated on the identical train/test split', 'Test accuracy compared directly between the two models', 'Each Week-1 hypothesis given a verdict backed by coefficients or tree splits'],
          hint: 'Look at which feature the decision tree splits on first, near the root - that is usually the strongest evidence for or against one of your original hypotheses.',
          solution: 'Hypothesis verdicts must cite model evidence (coefficients/splits), not vibes. Both models trained on identical splits.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Honest Evaluation', topic: 'Metrics beyond accuracy, cross-validation',
      problems: [
        { title: 'The Accuracy Trap', points: 110, difficulty: 'Core',
          description: 'Build a fraud-style imbalanced dataset (or use credit-card fraud sample): show a model with 99% accuracy that catches zero fraud. Then report precision, recall, F1 and confusion matrix, and explain which metric the bank should optimize and why.\nCourse link: Week 4 - imbalanced data and metric choice.',
          refs: [['Precision & recall', 'https://developers.google.com/machine-learning/crash-course/classification/precision-and-recall']],
          criteria: ['Demonstration shows a 99%-accurate model that catches zero fraud cases', 'Precision, recall, F1 and confusion matrix all reported', 'Recommended metric for the bank is justified with a cost argument'],
          hint: 'Build the demo by training on a heavily imbalanced dataset where "always predict not-fraud" already gets you 99% accuracy - that is the trap you need to expose.',
          solution: 'The 99%-useless demo is mandatory. Bank answer: recall on fraud class, with the cost argument.' },
        { title: 'Cross-Validation Verdict', points: 120, difficulty: 'Boss',
          description: 'Your single split might be lucky. Run 5-fold cross-validation on two models, report mean and standard deviation, and answer: which model is better AND more stable? When would you prefer stability over average score? Real-world tie: deployment risk.\nCourse link: Week 4 - cross-validation and model selection.',
          refs: [['Cross-validation docs', 'https://scikit-learn.org/stable/modules/cross_validation.html']],
          criteria: ['Five-fold cross-validation run for both models', 'Both mean and standard deviation reported and compared', 'Verdict addresses both which model is better and which is more stable'],
          hint: 'A model with a slightly lower mean score but a much smaller standard deviation might be the safer real-world choice - think about a domain where an unlucky bad run would be costly.',
          solution: 'Both mean AND std must inform the verdict. The stability question tests judgment - medical/finance answers welcome.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Patterns Without Labels', topic: 'Clustering and dimensionality',
      problems: [
        { title: 'Customer Segments', points: 110, difficulty: 'Core',
          description: 'On the Mall Customers dataset: choose k for KMeans with the elbow method (show the plot), cluster, visualize, and write a marketing persona for each segment ("Young high-spenders: target with..."). Turning math into business language is the job.\nCourse link: Week 5 - KMeans and the elbow method.',
          refs: [['Mall customers dataset', 'https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python']],
          criteria: ['Elbow plot shown and used to defend the chosen value of k', 'Clusters visualized clearly on a scatter plot', 'Each segment given a distinct marketing persona grounded in its centroid'],
          hint: 'Look at where the elbow plot\'s improvement rate flattens out - that inflection point, not just the lowest inertia, is what justifies your choice of k.',
          solution: 'Elbow plot with a defended k, plus personas grounded in cluster centroids. Personas must differ meaningfully.' },
        { title: 'Compress and See', points: 120, difficulty: 'Boss',
          description: 'Apply PCA to a multi-feature dataset (wine/iris): reduce to 2 components, plot colored by class, report explained variance, and answer honestly - what did we lose, and when is PCA a bad idea?\nCourse link: Week 5 - PCA intuition and trade-offs.',
          refs: [['PCA explained visually', 'https://setosa.io/ev/principal-component-analysis/']],
          criteria: ['Data reduced to two principal components and plotted by class', 'Explained variance ratio reported for the retained components', 'Answer honestly addresses what information was lost and when PCA is a bad idea'],
          hint: 'Check how much of the total variance your two components actually capture - if it is low, that is exactly the evidence you need for the "what did we lose" discussion.',
          solution: 'Explained-variance ratio must be reported. "When bad" answers: interpretability needs, non-linear structure.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: The ML Report', topic: 'End-to-end supervised project',
      problems: [
        { title: 'Your First Real Model', points: 200, difficulty: 'Boss',
          description: 'Choose a dataset with local relevance if possible (crop yield, air quality, prices): frame the problem -> EDA -> preprocessing -> 2 models compared with cross-validation -> honest metrics -> 1-page non-technical summary for a decision-maker, including where the model should NOT be trusted.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets'], ['Pakistan open data', 'https://data.gov.pk/']],
          criteria: ['Problem framing and EDA both precede any modeling', 'Two models compared using cross-validation with no data leakage', 'Non-technical summary states clearly where the model should not be trusted'],
          hint: 'Write the "where this model should not be trusted" section before you finalize the metrics - it forces you to be honest about the model\'s blind spots rather than just celebrating the best score.',
          solution: 'Rubric: framing + EDA (25%), preprocessing correctness incl. no leakage (25%), evaluation rigor (30%), honest limits section (20%).' },
      ] },
  ],
},
{
  key: 'sc05-ai-tools', course_code: 'SC-05', title: 'AI Automation Tools Track',
  description: '6-week quest through the modern productivity toolkit: automating documents, data, meetings, and whole business workflows.',
  pass_mark: 60, titleNames: ['Tool Scout', 'Stack Builder', 'Process Hacker', 'Ops Automator', 'Toolkit Master'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'The 2026 Toolscape', topic: 'Mapping AI tools to business problems',
      problems: [
        { title: 'Tool-to-Problem Matrix', points: 60, difficulty: 'Basic',
          description: 'Interview one real person about their work (family member, shopkeeper, teacher). List their 8 most repetitive tasks, then map each to a candidate AI tool category (writing, scheduling, data, automation platform) with a specific tool and its free-tier limits. Honest column: "not worth automating because..."\nCourse link: Week 1 - matching problems to tools, not tools to hype.',
          refs: [['There\'s an AI for that (directory)', 'https://theresanaiforthat.com/']],
          criteria: ['Eight real repetitive tasks documented from an actual interview', 'Each task mapped to a specific tool with researched free-tier limits', '"Not worth automating" column completed with honest reasoning'],
          hint: 'Push the interview for specifics - a vague task like "answering messages" cannot be mapped to a tool, but a repeated specific action can.',
          solution: 'The interview must feel real (specific tasks). Free-tier limits researched, not guessed. The "not worth it" column shows maturity.' },
        { title: 'Deep-Dive Review', points: 80, difficulty: 'Core',
          description: 'Pick ONE tool from your matrix and use it for 3 days on real tasks. Write a professional review: setup friction, 3 concrete wins with screenshots, 2 failures, pricing verdict for a Pakistani freelancer, and a 1-5 rating with justification.\nCourse link: Week 1 - evaluating tools like a consultant.',
          refs: [],
          criteria: ['Three concrete wins documented with screenshots from real use', 'Two genuine failures are included, not omitted', 'Pricing verdict and numeric rating both justified for a freelancer context'],
          hint: 'Actively look for the tool\'s rough edges during your three days of use - a review with zero failures reads like marketing copy, not an honest evaluation.',
          solution: 'Screenshots of real use are mandatory. Failures section must exist - all-positive reviews are marketing, not evaluation.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Documents on Autopilot', topic: 'AI docs, templates, contracts, proposals',
      problems: [
        { title: 'The Proposal Factory', points: 80, difficulty: 'Core',
          description: 'Build a reusable client-proposal system: a template with placeholders + an AI prompt that fills it from a 5-line client brief. Generate 2 complete proposals for different fake clients and diff them - what stayed fixed, what adapted?\nCourse link: Week 2 - template + AI hybrid workflows.',
          refs: [['Google Docs templates', 'https://support.google.com/docs/answer/148833']],
          criteria: ['Template with placeholders successfully fills from a short client brief', 'Two complete, client-ready proposals generated for different fake clients', 'Diff analysis clearly separates what stayed fixed from what adapted'],
          hint: 'Design the brief format first - the more structured the five-line brief, the more reliably the AI will fill in the right placeholders instead of improvising.',
          solution: 'The fixed/adaptive analysis proves system thinking. Proposals must be client-ready quality, not raw AI dumps.' },
        { title: 'Meeting-to-Minutes Pipeline', points: 100, difficulty: 'Boss',
          description: 'Record (or simulate with a script) a 10-minute meeting. Build the pipeline: transcription (Whisper or any free tool) -> AI summary with decisions and action items (owner + deadline) -> formatted minutes document. Compare AI minutes against your manual notes: what did it miss?\nCourse link: Week 2 - speech-to-text plus summarization chains.',
          refs: [['Whisper (OpenAI)', 'https://github.com/openai/whisper']],
          criteria: ['Full pipeline runs from transcription through to a formatted minutes document', 'Action items extracted with both an owner and a deadline', 'AI minutes compared against manual notes with misses identified'],
          hint: 'Take your own manual notes during the meeting before you run the AI pipeline, so you have an honest independent baseline to compare against afterward.',
          solution: 'Action items must have owners and deadlines extracted. The miss-analysis is the learning; perfect claims are suspicious.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'Data Without Drudgery', topic: 'AI in spreadsheets and reporting',
      problems: [
        { title: 'Spreadsheet Copilot Trial', points: 100, difficulty: 'Core',
          description: 'Take a 100+ row real dataset. Complete 5 tasks using AI assistance (formula generation, cleaning plan, pivot design, chart choice, anomaly spotting), verifying each output manually. Deliver a trust report: where AI saved time vs where verification cost more than doing it yourself.\nCourse link: Week 3 - AI-assisted data work with verification discipline.',
          refs: [['Gemini in Sheets', 'https://support.google.com/docs/answer/14218565']],
          criteria: ['All five AI-assisted tasks completed and manually verified', 'Formulas and outputs confirmed correct before being trusted', 'Trust report honestly shows at least one task where verification cost more than doing it manually'],
          hint: 'Time yourself doing the verification step, not just the AI step - the real insight in this exercise is in the total time including checking, not the AI\'s speed alone.',
          solution: 'The time-accounting must be honest - some tasks SHOULD show verification overhead. Formulas confirmed working.' },
        { title: 'The Auto-Report', points: 110, difficulty: 'Boss',
          description: 'Automate a weekly report: data source -> automated summary stats -> AI-written narrative paragraph -> emailed/delivered document, using any tool combo (Sheets + Apps Script, n8n, Make). Run it twice on different data and show both outputs adapt correctly.\nCourse link: Week 3 - scheduled reporting automation.',
          refs: [['Apps Script basics', 'https://developers.google.com/apps-script/overview']],
          criteria: ['Pipeline runs automated summary stats into an AI-written narrative', 'Report is delivered or emailed through an automated trigger', 'Two runs on different data produce genuinely different, correct narratives'],
          hint: 'Test with two datasets that would obviously need different narratives, such as one showing growth and one showing decline, so a hardcoded or lazy narrative becomes easy to spot.',
          solution: 'Two runs with genuinely different narratives is the pass bar - hardcoded text fails. Schedule/trigger must be shown.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Connect Everything', topic: 'Automation platforms in business context',
      problems: [
        { title: 'Lead Capture Machine', points: 110, difficulty: 'Core',
          description: 'Build the small-business classic: form/WhatsApp-style intake -> AI qualifies and scores the lead -> CRM row (Sheets/Airtable) -> instant acknowledgment to the lead -> alert to owner for hot leads only. Document each node and the scoring prompt.\nCourse link: Week 4 - multi-app automation with AI decisioning.',
          refs: [['Airtable basics', 'https://support.airtable.com/docs/airtable-getting-started'], ['n8n docs', 'https://docs.n8n.io/']],
          criteria: ['AI scoring step produces a parseable score from the scoring prompt', 'Owner alert is gated on the score, not sent for every lead', 'Every automation node and the scoring prompt are documented'],
          hint: 'Make sure your scoring prompt outputs a value in a consistent, parseable format, like a plain number - that is what lets the next step branch on it reliably.',
          solution: 'The AI scoring step must gate the owner alert (conditional path). Check the prompt outputs a parseable score.' },
        { title: 'Failure-Proofing', points: 120, difficulty: 'Boss',
          description: 'Real automations break at 2am. Take your lead machine and add: error handling with a fallback notification, input validation for malformed data, a retry policy, and a weekly health-check summary. Then break it on purpose (bad input, dead API) and show the safeguards firing.\nCourse link: Week 4 - production-thinking for automations.',
          refs: [['n8n error workflows', 'https://docs.n8n.io/flow-logic/error-handling/']],
          criteria: ['Fallback notification, input validation and a retry policy are all added', 'Weekly health-check summary is implemented', 'Deliberate breakage test shows the safeguards actually firing'],
          hint: 'Test with a genuinely malformed input and a genuinely dead API endpoint, not just a hypothetical description - the evidence needs to show the safeguard actually catching the failure.',
          solution: 'The deliberate-breakage evidence is mandatory. Untested error paths are decoration.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'The Human Question', topic: 'ROI, ethics, and change management',
      problems: [
        { title: 'Automation ROI Case', points: 110, difficulty: 'Core',
          description: 'For one automation you built: measure the manual baseline (time 3 real repetitions), compute monthly hours and rupees saved at a realistic wage, subtract tool costs, and present the ROI with a break-even point. Then the hard question: whose work changed, and how should that be handled?\nCourse link: Week 5 - the business case and the human impact.',
          refs: [['Calculating automation ROI', 'https://www.make.com/en/blog']],
          criteria: ['Manual baseline timed across three real repetitions, not estimated', 'Monthly savings calculated at a realistic wage with tool costs subtracted', 'Break-even point stated and the human-impact question answered seriously'],
          hint: 'Time the manual task three separate times rather than once - a single measurement can be an outlier and will not hold up as a credible baseline.',
          solution: 'Baseline must be measured, not guessed. The human-impact answer graded on seriousness, not a particular position.' },
        { title: 'The Automation Audit', points: 120, difficulty: 'Boss',
          description: 'Act as a consultant: audit a real small operation (family business, a friend\'s shop, your own studies) and deliver a prioritized automation roadmap - 5 opportunities scored by impact vs effort on a 2x2 matrix, with tool recommendations and one thing that should stay human, defended.\nCourse link: Week 5 - consulting deliverables.',
          refs: [['Impact/effort matrix', 'https://www.atlassian.com/team-playbook/plays/impact-effort-matrix']],
          criteria: ['Five automation opportunities identified from a real operation', 'Each opportunity plotted on an impact-vs-effort 2x2 with the priority order following from it', 'One task is defended as something that should stay human'],
          hint: 'Score impact and effort independently for each opportunity before placing them on the matrix - it is tempting to just rank by gut feeling, but the matrix only works if both axes are scored honestly.',
          solution: 'The 2x2 must drive the priority order. "Stay human" defense reveals judgment - grade it generously when sincere.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: The Ops Stack', topic: 'Complete business automation suite',
      problems: [
        { title: 'Ship a Working Stack', points: 200, difficulty: 'Boss',
          description: 'For one real or realistic business: implement 3 connected automations (intake, processing/reporting, communication) with AI in at least 2, error handling throughout, and an owner\'s manual a non-technical person could follow. Deliver: architecture diagram, screenshots, ROI summary, manual, and a 2-minute demo video link.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [],
          criteria: ['Three connected automations cover intake, processing and communication', 'AI adds real decision value in at least two of the automations', 'Owner\'s manual is clear enough for a non-technical person to follow'],
          hint: 'Write the owner\'s manual as if handing the whole system to someone who has never seen an automation platform before - that is the real test of whether your documentation is clear enough.',
          solution: 'Rubric: automations work end-to-end (40%), AI adds decision value (20%), resilience (15%), manual clarity (15%), ROI honesty (10%).' },
      ] },
  ],
},
];
