'use strict';
/** EchoLens prebuilt tracks - Short Courses (6 weeks -> 6 levels).
 * SC-01 Python for Data Science is served by the original 12-level python track. */

module.exports = [
{
  key: 'sc02-genai', course_code: 'SC-02', title: 'Generative AI Essentials',
  description: '6-week quest: understand, use, and build with generative AI - ending with your own working chatbot.',
  pass_mark: 60, titleNames: ['Token Novice', 'Prompt Pilot', 'API Apprentice', 'RAG Runner', 'GenAI Builder'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'How LLMs Think', topic: 'Tokens, context, capabilities and limits',
      problems: [
        { title: 'Stress-Test the Model', points: 60, difficulty: 'Basic',
          description: 'Design 6 test prompts that probe LLM limits: math, recent events, Urdu nuance, logic puzzles, counting letters, long-context recall. Run them, record results, and explain each success/failure using tokens and training-data concepts from class.\nCourse link: Week 1 - how LLMs work: tokens, training data, context windows.',
          refs: [['What is an LLM (Cloudflare)', 'https://www.cloudflare.com/learning/ai/what-is-large-language-model/'], ['Tokenizer playground', 'https://platform.openai.com/tokenizer']],
          solution: 'Explanations must use course vocabulary correctly (tokenization for counting failures, cutoff for recent events). Results without explanations fail.' },
        { title: 'Context Window Experiment', points: 80, difficulty: 'Core',
          description: 'Paste a long document into a chat, ask about a detail from its middle, then keep chatting until the model forgets earlier facts. Document when and how recall degrades, and relate it to context windows. Real-world tie: this is why enterprises use RAG.\nCourse link: Week 1 - context windows and their business consequences.',
          refs: [['Context windows explained', 'https://www.ibm.com/think/topics/context-window']],
          solution: 'Look for a genuine forced-forgetting demonstration and correct causal explanation. Bonus insight: position matters, not just length.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Prompting for Products', topic: 'System prompts, personas, structured output',
      problems: [
        { title: 'The System Prompt', points: 80, difficulty: 'Core',
          description: 'Write a production-style system prompt for a customer-service bot for a Pakistani clothing store: persona, allowed topics, refusal rules, Roman-Urdu handling, and strict JSON output (intent, reply, needs_human). Test with 5 messages including one it must refuse.\nCourse link: Week 2 - system prompts vs user prompts; structured outputs.',
          refs: [['System prompts (Anthropic)', 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/system-prompts'], ['JSON output guide', 'https://platform.openai.com/docs/guides/structured-outputs']],
          solution: 'JSON must parse for all 5 tests and the refusal must trigger. Weak prompts skip refusal rules - that is the differentiator.' },
        { title: 'Eval Like an Engineer', points: 100, difficulty: 'Boss',
          description: 'Real teams measure prompts. Build a mini evaluation: 10 test inputs with expected behaviours for your store bot, run them, score pass/fail in a table, change ONE line of the prompt, re-run, and report the score delta. This is prompt engineering as an engineering discipline.\nCourse link: Week 2 - evaluating and iterating prompts systematically.',
          refs: [['Prompt eval basics', 'https://docs.anthropic.com/en/docs/build-with-claude/develop-tests']],
          solution: 'The controlled single-change comparison is the concept. Any honest delta (even negative) passes; uncontrolled multi-changes do not.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'First API Calls', topic: 'Calling LLM APIs, parameters, cost',
      problems: [
        { title: 'Hello, API', points: 90, difficulty: 'Core',
          description: 'Using Python and a free-tier key (Gemini or Groq), write a script that sends a prompt and prints the reply. Then vary temperature (0 vs 1) on the same creative prompt, 3 runs each, and document the difference. Include code + outputs in your PDF.\nCourse link: Week 3 - LLM APIs: keys, requests, temperature.',
          refs: [['Gemini API quickstart', 'https://ai.google.dev/gemini-api/docs/quickstart'], ['Groq quickstart', 'https://console.groq.com/docs/quickstart']],
          solution: 'Code must show real (redacted-key) calls. Temperature explanation should connect to sampling randomness, not magic.' },
        { title: 'The Cost Auditor', points: 110, difficulty: 'Boss',
          description: 'A startup wants an AI reply-drafter for 500 emails/day. Using public pricing pages, estimate monthly cost for 2 models (one budget, one premium), showing token math per email. Recommend one with reasoning. This is a real pre-sales calculation.\nCourse link: Week 3 - tokens as money: cost estimation.',
          refs: [['OpenAI pricing', 'https://openai.com/api/pricing/'], ['Gemini pricing', 'https://ai.google.dev/pricing']],
          solution: 'Check token estimate per email is stated and multiplied correctly. Any defensible assumption passes; missing assumptions fail.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Grounded AI (RAG)', topic: 'Embeddings and retrieval basics',
      problems: [
        { title: 'Semantic Search by Hand', points: 100, difficulty: 'Core',
          description: 'Take 10 FAQ answers from any real business. Get embeddings for each (any free embedding API), then for 3 user questions compute cosine similarity and show the top match. One table: question, best FAQ, score. Explain why keyword search would fail on one of your examples.\nCourse link: Week 4 - embeddings and semantic similarity.',
          refs: [['Embeddings explained', 'https://ai.google.dev/gemini-api/docs/embeddings'], ['Cosine similarity', 'https://en.wikipedia.org/wiki/Cosine_similarity']],
          solution: 'Correct top-match retrieval on 3 questions passes. The keyword-failure example proves conceptual understanding.' },
        { title: 'Mini-RAG Answerer', points: 120, difficulty: 'Boss',
          description: 'Wire it together: question -> retrieve top-2 FAQ chunks -> stuff into a prompt ("answer ONLY from context") -> answer. Test 3 answerable and 1 unanswerable question (it must say "I don\'t know"). This is the architecture behind almost every enterprise chatbot in 2026.\nCourse link: Week 4 - retrieval-augmented generation end to end.',
          refs: [['RAG overview', 'https://docs.anthropic.com/en/docs/build-with-claude/retrieval-augmented-generation']],
          solution: 'The unanswerable case is the pass gate - hallucinated answers fail. Prompt must explicitly constrain to context.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Beyond Text', topic: 'Vision, image generation, multimodal use',
      problems: [
        { title: 'The Receipt Reader', points: 100, difficulty: 'Core',
          description: 'Photograph 3 real receipts or utility bills. Use a vision-capable model to extract structured data (vendor, date, total, items) as JSON. Report accuracy per field across all 3 and where it failed. Real-world tie: expense automation.\nCourse link: Week 5 - vision models and document extraction.',
          refs: [['Gemini vision docs', 'https://ai.google.dev/gemini-api/docs/vision']],
          solution: 'A per-field accuracy table is required. Failures on handwriting/low-quality images are expected and worth discussing.' },
        { title: 'Brand Image Lab', points: 120, difficulty: 'Boss',
          description: 'Using any free image model, generate a brand visual through 5 documented prompt iterations - show each prompt, image, and what you changed. Then write the ethics paragraph: one real risk of AI imagery (deepfakes, artist displacement) with your stance.\nCourse link: Week 5 - image generation, iteration, and ethics.',
          refs: [['Image prompting guide', 'https://docs.midjourney.com/docs/prompts']],
          solution: 'Grade iteration quality (each change purposeful) over final beauty. Ethics paragraph must take an actual position.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: Ship a Chatbot', topic: 'End-to-end GenAI product',
      problems: [
        { title: 'Your Grounded Chatbot', points: 200, difficulty: 'Boss',
          description: 'Build a complete chatbot for a real use case (academy FAQ, shop assistant, clinic info): system prompt with persona and refusal rules, RAG over 15+ real chunks, structured logging of Q&A, and a 10-question eval with scores. Deliver: code, architecture diagram, eval table, and a 1-page "what I would improve" memo.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [['Building with Claude', 'https://docs.anthropic.com/en/docs/intro-to-claude']],
          solution: 'Rubric: RAG works incl. refusal on unknowns (35%), prompt quality (20%), eval rigor (25%), memo insight (20%).' },
      ] },
  ],
},
{
  key: 'sc03-sql-powerbi', course_code: 'SC-03', title: 'Data Analytics with SQL & Power BI',
  description: '6-week quest: query like an analyst, report like a professional - ending with a business dashboard.',
  pass_mark: 60, titleNames: ['Query Cadet', 'Join Ranger', 'Insight Hunter', 'Dashboard Smith', 'BI Analyst'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'SELECT Your Weapon', topic: 'SELECT, WHERE, ORDER BY, LIMIT',
      problems: [
        { title: 'First Queries', points: 60, difficulty: 'Basic',
          description: 'Load the classic Chinook database (free) into SQLite/DB Browser. Write and screenshot 6 queries: all customers from one country, tracks over 5 minutes, 10 most expensive tracks, invoices in a date range, distinct billing countries, and one query of your own with a business question attached.\nCourse link: Week 1 - core SELECT syntax.',
          refs: [['Chinook database', 'https://github.com/lerocha/chinook-database'], ['SQLite SELECT docs', 'https://www.sqlite.org/lang_select.html']],
          solution: 'All queries must run; check ORDER BY + LIMIT used correctly for "top 10". The self-authored business question shows intent.' },
        { title: 'The Filter Brief', points: 80, difficulty: 'Core',
          description: 'A manager asks: "Which customers from Germany or France spent on invoices above $10 in 2011-2012?" Translate to SQL with combined AND/OR logic (mind the parentheses), then write 2 more manager-style questions and answer them with queries.\nCourse link: Week 1 - boolean logic in WHERE clauses.',
          refs: [['SQL WHERE (W3Schools)', 'https://www.w3schools.com/sql/sql_where.asp']],
          solution: 'The OR-inside-AND parentheses trap is the test. Verify results change when parentheses move - ask students to show both.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Joining Forces', topic: 'JOINs and aggregation',
      problems: [
        { title: 'The Revenue Report', points: 80, difficulty: 'Core',
          description: 'Using JOINs and GROUP BY on Chinook: revenue per country, top 5 artists by revenue, and monthly revenue trend for one year. Each query needs a one-line business takeaway. This is a real weekly analyst deliverable.\nCourse link: Week 2 - INNER JOIN, GROUP BY, aggregate functions.',
          refs: [['SQL JOIN visualizer', 'https://sql-joins.leopard.in.ua/'], ['GROUP BY docs', 'https://www.w3schools.com/sql/sql_groupby.asp']],
          solution: 'Check join keys are correct (Invoice->InvoiceLine->Track->Album->Artist chain for artists). Takeaways must reference actual numbers.' },
        { title: 'Find the Missing', points: 100, difficulty: 'Boss',
          description: 'Business question: "Which customers have NEVER purchased jazz?" and "Which genres earn the least?" Solve using LEFT JOIN with NULL checks or subqueries - explain your chosen approach and why the naive INNER JOIN gives the wrong answer.\nCourse link: Week 2 - LEFT JOIN semantics and anti-joins.',
          refs: [['LEFT JOIN explained', 'https://www.w3schools.com/sql/sql_join_left.asp']],
          solution: 'The anti-join concept is the pass bar. The "why INNER JOIN fails" explanation separates memorizers from understanders.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'Analyst Toolbelt', topic: 'CASE, subqueries, window functions, cleaning',
      problems: [
        { title: 'Customer Tiers', points: 100, difficulty: 'Core',
          description: 'Segment Chinook customers into Gold/Silver/Bronze by lifetime spend using CASE, then use a window function to rank customers within each country. Output one table: name, country, spend, tier, in-country rank.\nCourse link: Week 3 - CASE expressions and window functions.',
          refs: [['Window functions tutorial', 'https://mode.com/sql-tutorial/sql-window-functions/']],
          solution: 'RANK/ROW_NUMBER with PARTITION BY country is the key skill. Tier thresholds must be stated and defensible.' },
        { title: 'Dirty Data Audit', points: 120, difficulty: 'Boss',
          description: 'Download any messy public CSV (Kaggle) and load it into your SQL tool. Write an audit: row count, NULLs per column, duplicates, inconsistent categories - all found via SQL. Then write the cleaning queries. Deliver before/after proof.\nCourse link: Week 3 - data quality checks in SQL.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          solution: 'GROUP BY ... HAVING COUNT(*)>1 for dupes and COUNT vs COUNT(col) for NULLs are expected patterns. Proof queries required.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Enter Power BI', topic: 'Data model, relationships, first visuals',
      problems: [
        { title: 'Model and Visualize', points: 100, difficulty: 'Core',
          description: 'Import 2+ related tables into Power BI Desktop (free), build the relationship correctly, and create 4 visuals: card (total revenue), bar (by category), line (trend), map or table. Screenshot the model view and explain the relationship direction.\nCourse link: Week 4 - star schema thinking and visual basics.',
          refs: [['Power BI Desktop docs', 'https://learn.microsoft.com/en-us/power-bi/fundamentals/desktop-what-is-desktop'], ['Model relationships', 'https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-relationships-understand']],
          solution: 'The relationship must be genuine (key-matched), not auto-guessed wrongly. Model view screenshot is mandatory evidence.' },
        { title: 'DAX First Measures', points: 120, difficulty: 'Boss',
          description: 'Write 4 DAX measures: Total Revenue, Revenue LY (or previous period), % Growth, and Average Order Value. Show each formula and the visual using it. Explain the difference between a measure and a calculated column - the classic interview question.\nCourse link: Week 4 - DAX measures fundamentals.',
          refs: [['DAX basics', 'https://learn.microsoft.com/en-us/power-bi/transform-model/desktop-quickstart-learn-dax-basics']],
          solution: 'CALCULATE + time intelligence (or a clean previous-period filter) shows real skill. The measure-vs-column answer must mention evaluation context.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Dashboard Craft', topic: 'Design, interactivity, storytelling',
      problems: [
        { title: 'Interactive Dashboard', points: 110, difficulty: 'Core',
          description: 'Build a one-page interactive dashboard: KPI cards, slicers (date + category), cross-filtering visuals, consistent color theme, clear titles. Test with a colleague/family member for 5 minutes and report what confused them - real UX testing.\nCourse link: Week 5 - dashboard design and interactivity.',
          refs: [['Dashboard design guide', 'https://learn.microsoft.com/en-us/power-bi/create-reports/service-dashboards-design-tips']],
          solution: 'Cross-filtering must work and the user-test finding must be genuine. Deduct for rainbow color chaos and unlabeled axes.' },
        { title: 'The Insight Memo', points: 130, difficulty: 'Boss',
          description: 'Analysts write, not just chart. From your dashboard, produce a 1-page memo: 3 findings (each with a number), 1 anomaly you investigated, and 2 recommended actions. Attach the supporting visuals. Findings without numbers are opinions.\nCourse link: Week 5 - from visuals to business decisions.',
          refs: [['Data storytelling', 'https://www.storytellingwithdata.com/blog']],
          solution: 'Every finding needs a metric. The anomaly investigation (checked, explained or flagged) is what analysts are actually paid for.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: Business Report', topic: 'End-to-end analytics project',
      problems: [
        { title: 'Full-Stack Analytics Project', points: 200, difficulty: 'Boss',
          description: 'Pick a real domain dataset (Pakistan open data, Kaggle retail, etc.): SQL cleaning + 5 analytical queries -> Power BI model -> polished dashboard -> executive memo. Deliver PDF: methodology, queries, dashboard screenshots, memo, and a link to your .pbix file.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [['Pakistan open data', 'https://data.gov.pk/'], ['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          solution: 'Rubric: SQL correctness (30%), model + DAX (25%), dashboard craft (25%), memo quality (20%). The story must survive without the student explaining it live.' },
      ] },
  ],
},
{
  key: 'sc04-intro-ml', course_code: 'SC-04', title: 'Introduction to Machine Learning',
  description: '6-week quest from ML intuition to trained, honestly-evaluated models.',
  pass_mark: 60, titleNames: ['Data Scout', 'Feature Finder', 'Model Trainer', 'Metric Judge', 'ML Practitioner'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Think in Data', topic: 'ML framing: features, labels, problem types',
      problems: [
        { title: 'Is It Even ML?', points: 60, difficulty: 'Basic',
          description: 'For 6 real scenarios (loan approval, electricity-bill prediction, spam filtering, ranking cricket players, grouping customers, converting currency) state: ML or plain rules? If ML - supervised or unsupervised, regression or classification, and what the features/label would be. Justify each in 2 lines.\nCourse link: Week 1 - problem framing, the most-skipped skill in ML.',
          refs: [['Google ML problem framing', 'https://developers.google.com/machine-learning/problem-framing']],
          solution: 'Currency conversion is rules, not ML - the trap. Grade the feature/label identification hardest.' },
        { title: 'Dataset First Contact', points: 80, difficulty: 'Core',
          description: 'Download the Titanic dataset. In pandas: shape, dtypes, missing values per column, target balance, and 3 charts (survival by sex, by class, age distribution). End with 3 hypotheses about what predicts survival - you will test them in Week 4.\nCourse link: Week 1 - exploratory data analysis before modeling.',
          refs: [['Titanic dataset', 'https://www.kaggle.com/c/titanic/data'], ['pandas EDA guide', 'https://pandas.pydata.org/docs/user_guide/10min.html']],
          solution: 'Hypotheses must be falsifiable and chart-grounded (sex and class patterns should surface). Missing-value counts must be exact.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Feature Workshop', topic: 'Cleaning, encoding, scaling',
      problems: [
        { title: 'Make It Model-Ready', points: 80, difficulty: 'Core',
          description: 'Prepare Titanic for ML: impute missing Age (justify your strategy), encode Sex and Embarked, engineer one new feature (FamilySize or Title from name), and scale numeric columns. Show before/after and explain WHY each step exists.\nCourse link: Week 2 - preprocessing pipeline.',
          refs: [['scikit-learn preprocessing', 'https://scikit-learn.org/stable/modules/preprocessing.html']],
          solution: 'The "why" per step is the grade: models need numbers, scale sensitivity, information extraction. Median vs mean imputation reasoning earns marks.' },
        { title: 'Leakage Hunt', points: 100, difficulty: 'Boss',
          description: 'The silent ML killer: data leakage. Given 5 described modeling setups (e.g. scaling before splitting, using "total bill paid" to predict default), identify which leak, why, and the fix. Then create one leakage example of your own in code and show the inflated vs honest accuracy.\nCourse link: Week 2 - leakage and why competition winners fail in production.',
          refs: [['Data leakage (Kaggle)', 'https://www.kaggle.com/code/alexisbcook/data-leakage']],
          solution: 'The self-made coded example with inflated-vs-honest numbers is the pass gate. Scaling-before-split must be caught.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'First Models', topic: 'Train/test split, regression, classification',
      problems: [
        { title: 'Predict the Price', points: 100, difficulty: 'Core',
          description: 'On the California Housing dataset: 80/20 split (fixed seed), LinearRegression, report MAE and R2 on test, and interpret 2 coefficients in plain Urdu-English a landlord would understand. Real skill: explaining models to non-technical clients.\nCourse link: Week 3 - regression end to end.',
          refs: [['California housing', 'https://scikit-learn.org/stable/datasets/real_world.html#california-housing-dataset']],
          solution: 'Metrics must be test-set only. Coefficient interpretation must include units and direction; sign confusion is the common error.' },
        { title: 'Who Survives?', points: 110, difficulty: 'Boss',
          description: 'Train LogisticRegression and DecisionTree on your prepared Titanic data. Compare test accuracy, then answer: which of your Week-1 hypotheses survived? Show the tree\'s top splits as evidence. Close the loop from EDA to model.\nCourse link: Week 3 - classification and hypothesis testing.',
          refs: [['Logistic regression guide', 'https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression']],
          solution: 'Hypothesis verdicts must cite model evidence (coefficients/splits), not vibes. Both models trained on identical splits.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Honest Evaluation', topic: 'Metrics beyond accuracy, cross-validation',
      problems: [
        { title: 'The Accuracy Trap', points: 110, difficulty: 'Core',
          description: 'Build a fraud-style imbalanced dataset (or use credit-card fraud sample): show a model with 99% accuracy that catches zero fraud. Then report precision, recall, F1 and confusion matrix, and explain which metric the bank should optimize and why.\nCourse link: Week 4 - imbalanced data and metric choice.',
          refs: [['Precision & recall', 'https://developers.google.com/machine-learning/crash-course/classification/precision-and-recall']],
          solution: 'The 99%-useless demo is mandatory. Bank answer: recall on fraud class, with the cost argument.' },
        { title: 'Cross-Validation Verdict', points: 120, difficulty: 'Boss',
          description: 'Your single split might be lucky. Run 5-fold cross-validation on two models, report mean and standard deviation, and answer: which model is better AND more stable? When would you prefer stability over average score? Real-world tie: deployment risk.\nCourse link: Week 4 - cross-validation and model selection.',
          refs: [['Cross-validation docs', 'https://scikit-learn.org/stable/modules/cross_validation.html']],
          solution: 'Both mean AND std must inform the verdict. The stability question tests judgment - medical/finance answers welcome.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'Patterns Without Labels', topic: 'Clustering and dimensionality',
      problems: [
        { title: 'Customer Segments', points: 110, difficulty: 'Core',
          description: 'On the Mall Customers dataset: choose k for KMeans with the elbow method (show the plot), cluster, visualize, and write a marketing persona for each segment ("Young high-spenders: target with..."). Turning math into business language is the job.\nCourse link: Week 5 - KMeans and the elbow method.',
          refs: [['Mall customers dataset', 'https://www.kaggle.com/datasets/vjchoudhary7/customer-segmentation-tutorial-in-python']],
          solution: 'Elbow plot with a defended k, plus personas grounded in cluster centroids. Personas must differ meaningfully.' },
        { title: 'Compress and See', points: 120, difficulty: 'Boss',
          description: 'Apply PCA to a multi-feature dataset (wine/iris): reduce to 2 components, plot colored by class, report explained variance, and answer honestly - what did we lose, and when is PCA a bad idea?\nCourse link: Week 5 - PCA intuition and trade-offs.',
          refs: [['PCA explained visually', 'https://setosa.io/ev/principal-component-analysis/']],
          solution: 'Explained-variance ratio must be reported. "When bad" answers: interpretability needs, non-linear structure.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: The ML Report', topic: 'End-to-end supervised project',
      problems: [
        { title: 'Your First Real Model', points: 200, difficulty: 'Boss',
          description: 'Choose a dataset with local relevance if possible (crop yield, air quality, prices): frame the problem -> EDA -> preprocessing -> 2 models compared with cross-validation -> honest metrics -> 1-page non-technical summary for a decision-maker, including where the model should NOT be trusted.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets'], ['Pakistan open data', 'https://data.gov.pk/']],
          solution: 'Rubric: framing + EDA (25%), preprocessing correctness incl. no leakage (25%), evaluation rigor (30%), honest limits section (20%).' },
      ] },
  ],
},
{
  key: 'sc05-ai-tools', course_code: 'SC-05', title: 'AI Automation Tools Track',
  description: '6-week quest through the modern productivity toolkit: automating documents, data, meetings, and whole business workflows.',
  pass_mark: 60, titleNames: ['Tool Scout', 'Stack Builder', 'Process Hacker', 'Ops Automator', 'Toolkit Master'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'The 2026 Toolscape', topic: 'Mapping AI tools to business problems',
      problems: [
        { title: 'Tool-to-Problem Matrix', points: 60, difficulty: 'Basic',
          description: 'Interview one real person about their work (family member, shopkeeper, teacher). List their 8 most repetitive tasks, then map each to a candidate AI tool category (writing, scheduling, data, automation platform) with a specific tool and its free-tier limits. Honest column: "not worth automating because..."\nCourse link: Week 1 - matching problems to tools, not tools to hype.',
          refs: [['There\'s an AI for that (directory)', 'https://theresanaiforthat.com/']],
          solution: 'The interview must feel real (specific tasks). Free-tier limits researched, not guessed. The "not worth it" column shows maturity.' },
        { title: 'Deep-Dive Review', points: 80, difficulty: 'Core',
          description: 'Pick ONE tool from your matrix and use it for 3 days on real tasks. Write a professional review: setup friction, 3 concrete wins with screenshots, 2 failures, pricing verdict for a Pakistani freelancer, and a 1-5 rating with justification.\nCourse link: Week 1 - evaluating tools like a consultant.',
          refs: [],
          solution: 'Screenshots of real use are mandatory. Failures section must exist - all-positive reviews are marketing, not evaluation.' },
      ] },
    { no: 2, week: 2, session: 4, title: 'Documents on Autopilot', topic: 'AI docs, templates, contracts, proposals',
      problems: [
        { title: 'The Proposal Factory', points: 80, difficulty: 'Core',
          description: 'Build a reusable client-proposal system: a template with placeholders + an AI prompt that fills it from a 5-line client brief. Generate 2 complete proposals for different fake clients and diff them - what stayed fixed, what adapted?\nCourse link: Week 2 - template + AI hybrid workflows.',
          refs: [['Google Docs templates', 'https://support.google.com/docs/answer/148833']],
          solution: 'The fixed/adaptive analysis proves system thinking. Proposals must be client-ready quality, not raw AI dumps.' },
        { title: 'Meeting-to-Minutes Pipeline', points: 100, difficulty: 'Boss',
          description: 'Record (or simulate with a script) a 10-minute meeting. Build the pipeline: transcription (Whisper or any free tool) -> AI summary with decisions and action items (owner + deadline) -> formatted minutes document. Compare AI minutes against your manual notes: what did it miss?\nCourse link: Week 2 - speech-to-text plus summarization chains.',
          refs: [['Whisper (OpenAI)', 'https://github.com/openai/whisper']],
          solution: 'Action items must have owners and deadlines extracted. The miss-analysis is the learning; perfect claims are suspicious.' },
      ] },
    { no: 3, week: 3, session: 6, title: 'Data Without Drudgery', topic: 'AI in spreadsheets and reporting',
      problems: [
        { title: 'Spreadsheet Copilot Trial', points: 100, difficulty: 'Core',
          description: 'Take a 100+ row real dataset. Complete 5 tasks using AI assistance (formula generation, cleaning plan, pivot design, chart choice, anomaly spotting), verifying each output manually. Deliver a trust report: where AI saved time vs where verification cost more than doing it yourself.\nCourse link: Week 3 - AI-assisted data work with verification discipline.',
          refs: [['Gemini in Sheets', 'https://support.google.com/docs/answer/14218565']],
          solution: 'The time-accounting must be honest - some tasks SHOULD show verification overhead. Formulas confirmed working.' },
        { title: 'The Auto-Report', points: 110, difficulty: 'Boss',
          description: 'Automate a weekly report: data source -> automated summary stats -> AI-written narrative paragraph -> emailed/delivered document, using any tool combo (Sheets + Apps Script, n8n, Make). Run it twice on different data and show both outputs adapt correctly.\nCourse link: Week 3 - scheduled reporting automation.',
          refs: [['Apps Script basics', 'https://developers.google.com/apps-script/overview']],
          solution: 'Two runs with genuinely different narratives is the pass bar - hardcoded text fails. Schedule/trigger must be shown.' },
      ] },
    { no: 4, week: 4, session: 8, title: 'Connect Everything', topic: 'Automation platforms in business context',
      problems: [
        { title: 'Lead Capture Machine', points: 110, difficulty: 'Core',
          description: 'Build the small-business classic: form/WhatsApp-style intake -> AI qualifies and scores the lead -> CRM row (Sheets/Airtable) -> instant acknowledgment to the lead -> alert to owner for hot leads only. Document each node and the scoring prompt.\nCourse link: Week 4 - multi-app automation with AI decisioning.',
          refs: [['Airtable basics', 'https://support.airtable.com/docs/airtable-getting-started'], ['n8n docs', 'https://docs.n8n.io/']],
          solution: 'The AI scoring step must gate the owner alert (conditional path). Check the prompt outputs a parseable score.' },
        { title: 'Failure-Proofing', points: 120, difficulty: 'Boss',
          description: 'Real automations break at 2am. Take your lead machine and add: error handling with a fallback notification, input validation for malformed data, a retry policy, and a weekly health-check summary. Then break it on purpose (bad input, dead API) and show the safeguards firing.\nCourse link: Week 4 - production-thinking for automations.',
          refs: [['n8n error workflows', 'https://docs.n8n.io/flow-logic/error-handling/']],
          solution: 'The deliberate-breakage evidence is mandatory. Untested error paths are decoration.' },
      ] },
    { no: 5, week: 5, session: 10, title: 'The Human Question', topic: 'ROI, ethics, and change management',
      problems: [
        { title: 'Automation ROI Case', points: 110, difficulty: 'Core',
          description: 'For one automation you built: measure the manual baseline (time 3 real repetitions), compute monthly hours and rupees saved at a realistic wage, subtract tool costs, and present the ROI with a break-even point. Then the hard question: whose work changed, and how should that be handled?\nCourse link: Week 5 - the business case and the human impact.',
          refs: [['Calculating automation ROI', 'https://www.make.com/en/blog']],
          solution: 'Baseline must be measured, not guessed. The human-impact answer graded on seriousness, not a particular position.' },
        { title: 'The Automation Audit', points: 120, difficulty: 'Boss',
          description: 'Act as a consultant: audit a real small operation (family business, a friend\'s shop, your own studies) and deliver a prioritized automation roadmap - 5 opportunities scored by impact vs effort on a 2x2 matrix, with tool recommendations and one thing that should stay human, defended.\nCourse link: Week 5 - consulting deliverables.',
          refs: [['Impact/effort matrix', 'https://www.atlassian.com/team-playbook/plays/impact-effort-matrix']],
          solution: 'The 2x2 must drive the priority order. "Stay human" defense reveals judgment - grade it generously when sincere.' },
      ] },
    { no: 6, week: 6, session: 12, title: 'Capstone: The Ops Stack', topic: 'Complete business automation suite',
      problems: [
        { title: 'Ship a Working Stack', points: 200, difficulty: 'Boss',
          description: 'For one real or realistic business: implement 3 connected automations (intake, processing/reporting, communication) with AI in at least 2, error handling throughout, and an owner\'s manual a non-technical person could follow. Deliver: architecture diagram, screenshots, ROI summary, manual, and a 2-minute demo video link.\nCourse link: Weeks 1-6 combined - your portfolio project.',
          refs: [],
          solution: 'Rubric: automations work end-to-end (40%), AI adds decision value (20%), resilience (15%), manual clarity (15%), ROI honesty (10%).' },
      ] },
  ],
},
];
