'use strict';
/** EchoLens prebuilt tracks - Specialist & Professional Tracks (2 months).
 * 5 milestone levels per track (levels span ~1.5 weeks each); teachers can
 * edit any problem or add levels via the editor. Solutions = teacher-only. */

module.exports = [
{
  key: 'st01-wordpress', course_code: 'ST-01', title: 'WordPress Development',
  description: '2-month quest: from local install to a client-ready website delivery.',
  clos: [
    'CLO1: Install and configure WordPress locally and build custom themes and page layouts.',
    'CLO2: Extend site functionality with plugins and WooCommerce for a working online store.',
    'CLO3: Deliver a polished, client-ready WordPress site through a real client-delivery workflow.',
  ],
  pass_mark: 60, titleNames: ['Site Starter', 'Theme Tamer', 'Plugin Pro', 'Client Builder', 'WP Developer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Local Foundations', topic: 'Install, dashboard, posts vs pages, media',
      problems: [
        { title: 'Your First Site', points: 60, difficulty: 'Basic',
          description: 'Install WordPress locally (LocalWP/XAMPP). Create 3 pages (Home, About, Contact), 2 blog posts with images, a nav menu, and set a static homepage. Screenshot-report each step and explain posts vs pages.\nCourse link: Week 1 - WordPress anatomy and content types.',
          refs: [['WordPress.org: first steps', 'https://wordpress.org/documentation/article/new-to-wordpress-where-to-start/']],
          solution: 'Static-homepage setting and correct posts-vs-pages explanation (chronological vs structural) are the pass checks.',
          criteria: ['Static homepage correctly configured in Settings', 'All required pages and posts created with media', 'Clear explanation of posts versus pages distinction'],
          hint: 'Remember that pages are for permanent, standalone content while posts are chronological entries - the difference should shape which content type you pick for each piece, and don\'t forget to set the reading settings to a static front page.' },
        { title: 'The Content Model', points: 80, difficulty: 'Core',
          description: 'A restaurant client needs menus, chefs, and testimonials. Plan the content: which become pages, posts, categories, or custom types? Build categories/tags for the blog and justify your model in a diagram.\nCourse link: Week 1-2 - content architecture before building.',
          refs: [['WP taxonomies', 'https://wordpress.org/documentation/article/taxonomies/']],
          solution: 'Any defensible model passes; grade the justification. Testimonials as CPT (or plugin) shows foresight.',
          criteria: ['Sensible content-type mapping for menus, chefs, testimonials', 'Categories and tags actually built and used', 'Diagram clearly justifies each modeling decision'],
          hint: 'Think about which content repeats and needs its own template (like chefs or testimonials) versus content that\'s just a one-off page - that distinction usually points you toward a custom post type.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Themes and Layouts', topic: 'Theme customization, block editor, page builders',
      problems: [
        { title: 'Theme Makeover', points: 90, difficulty: 'Core',
          description: 'Take a free theme (Astra/Kadence) and customize it into a distinct brand: colors, typography, header/footer, and a styled homepage using the block editor - no page builder yet. Before/after screenshots plus what each customizer setting controls.\nCourse link: Week 3 - theme system and the block editor.',
          refs: [['Block editor guide', 'https://wordpress.org/documentation/article/wordpress-block-editor/']],
          solution: 'Distinctiveness matters: default-looking Astra fails. Check header/footer edited, not just colors.',
          criteria: ['Visually distinct from the default theme', 'Header and footer customized, not just colors', 'Before/after screenshots with settings explained'],
          hint: 'Changing the color scheme alone won\'t make it feel like a different brand - dig into the customizer\'s header, footer, and typography options so the site stops looking like stock Astra.' },
        { title: 'Builder Duel', points: 100, difficulty: 'Boss',
          description: 'Rebuild the same landing section twice: once in Gutenberg blocks, once in Elementor (free). Compare honestly: speed to build, page-load weight (check with browser devtools), and lock-in risk. Recommend one for a low-budget client.\nCourse link: Week 4 - page builders: power vs cost.',
          refs: [['Elementor docs', 'https://elementor.com/help/']],
          solution: 'The devtools weight comparison is the differentiator (Elementor loads more). Recommendation must cite the evidence.',
          criteria: ['Same section rebuilt faithfully in both tools', 'Page-weight comparison backed by devtools evidence', 'Recommendation explicitly grounded in the measured data'],
          hint: 'Open the Network tab in devtools for both versions and actually record the transferred size and request count - a gut feeling about which builder is "heavier" isn\'t the same as a measured number.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Plugins and Function', topic: 'Essential plugins, forms, SEO, security',
      problems: [
        { title: 'The Essential Stack', points: 100, difficulty: 'Core',
          description: 'Install and configure a production plugin stack: contact form (with working email test), SEO plugin (meta titles set for all pages), caching, and a security/backup plugin. Document each configuration decision and one setting you deliberately changed from default.\nCourse link: Week 5 - the professional plugin baseline.',
          refs: [['WP plugin directory', 'https://wordpress.org/plugins/']],
          solution: 'Form email must be proven delivered. The changed-default answers reveal whether they read settings or clicked next-next.',
          criteria: ['Contact form proven to deliver a test email', 'Meta titles set for every page via the SEO plugin', 'One deliberately changed default setting explained'],
          hint: 'Don\'t just install and activate each plugin - actually send a test message through the contact form and confirm it lands in an inbox, since an untested form is the most common silent failure.' },
        { title: 'Mini WooCommerce', points: 110, difficulty: 'Boss',
          description: 'Add WooCommerce with 5 real products (images, prices in PKR, categories), configure cash-on-delivery (the Pakistani default), a shipping zone, and complete one full test order. Report the customer journey with screenshots and 2 UX improvements you would make.\nCourse link: Week 6 - e-commerce foundations.',
          refs: [['WooCommerce docs', 'https://woocommerce.com/documentation/woocommerce/']],
          solution: 'COD configured and a completed test order are the pass gates. UX suggestions graded on specificity.',
          criteria: ['Cash-on-delivery configured as a working payment option', 'One full test order completed start to finish', 'Two specific, actionable UX improvements proposed'],
          hint: 'Walk through the checkout exactly as a real Pakistani customer would - stores often ship with card-only payment enabled by default, so make sure COD is actually visible and selectable at checkout, not just configured in the backend.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Client-Grade Polish', topic: 'Performance, responsive QA, launch prep',
      problems: [
        { title: 'Speed Clinic', points: 110, difficulty: 'Core',
          description: 'Audit your site with PageSpeed Insights: record the mobile score, apply 4 improvements (image compression, caching, unused plugins, lazy-loading), and show the score delta with before/after reports. Explain why mobile speed matters for Pakistani users specifically.\nCourse link: Week 7 - performance optimization.',
          refs: [['PageSpeed Insights', 'https://pagespeed.web.dev/']],
          solution: 'Any genuine measured improvement passes; the process matters more than the score. The Pakistan answer: mobile-first, slower networks.',
          criteria: ['Before and after PageSpeed scores both recorded', 'All four listed optimizations actually applied', 'Explanation ties mobile speed to Pakistani network conditions'],
          hint: 'Tackle image compression and unused plugins first - they usually give the biggest score jump for the least risk of breaking something, and re-run the test after each change so you can attribute the improvement correctly.' },
        { title: 'The Launch Checklist', points: 120, difficulty: 'Boss',
          description: 'Produce a professional pre-launch QA: responsive check on 3 viewports (screenshots), all links tested, forms tested, 404 page styled, favicon, and a written handover checklist a client could verify. Run it on your site and mark pass/fail per item honestly.\nCourse link: Week 8 - launch discipline.',
          refs: [['Website launch checklist', 'https://wordpress.org/documentation/article/faq-installation/']],
          solution: 'Honest fails are worth more than fake passes. Responsive screenshots at real breakpoints are mandatory.',
          criteria: ['Responsive screenshots captured at three real breakpoints', 'Every checklist item marked pass or fail honestly', 'Handover checklist is clear enough for a client to verify'],
          hint: 'Resist the urge to make everything look like it passed - a checklist that honestly flags a broken link or missing favicon is worth more than one that pretends everything is perfect.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Client Delivery', topic: 'Complete client website project',
      problems: [
        { title: 'The Client Project', points: 200, difficulty: 'Boss',
          description: 'Deliver a complete website for a real or realistic Pakistani client (academy, clinic, boutique): 5+ pages, brand-consistent design, working contact form, SEO basics, speed-optimized, plus a client manual (how to edit content) and a maintenance proposal with monthly pricing. This is your portfolio and your sales template in one.\nCourse link: Weeks 1-8 combined.',
          refs: [],
          solution: 'Rubric: build quality (35%), performance + QA evidence (25%), client manual clarity (20%), maintenance proposal realism (20%).',
          criteria: ['All core deliverables present: pages, form, SEO, speed work', 'Client manual clearly explains how to edit content', 'Maintenance proposal includes realistic monthly pricing'],
          hint: 'Write the client manual as if the client has never touched a computer\'s admin panel before - if a non-technical reader can follow it step by step, you\'ve hit the bar.' },
      ] },
  ],
},
{
  key: 'st02-graphic-design', course_code: 'ST-02', title: 'Graphic Designing',
  description: '2-month quest: from design fundamentals to a client-ready brand identity system.',
  clos: [
    'CLO1: Apply core design fundamentals - colour, type, composition - to produce professional visual work.',
    'CLO2: Build a complete brand identity system including logo, guidelines and collateral.',
    'CLO3: Deliver a client-ready brand package matching real agency delivery standards.',
  ],
  pass_mark: 60, titleNames: ['Pixel Novice', 'Layout Learner', 'Color Crafter', 'Brand Builder', 'Visual Designer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Eyes Before Hands', topic: 'Design principles: hierarchy, contrast, alignment',
      problems: [
        { title: 'Design Autopsy', points: 60, difficulty: 'Basic',
          description: 'Collect 3 good and 3 bad real designs (local shop banners, posters, social posts). For each, annotate hierarchy, contrast, alignment, proximity, and whitespace - marking exactly where principles are honored or violated. PDF with annotations drawn on the images.\nCourse link: Week 1 - the CRAP principles as a seeing tool.',
          refs: [['Design principles overview', 'https://www.canva.com/learn/design-elements-principles/']],
          solution: 'Annotations must point at specific spots, not general vibes. Local examples encouraged - grade observation sharpness.',
          criteria: ['All five CRAP principles annotated on every example', 'Annotations point at specific spots, not vague comments', 'Mix of genuinely good and bad local examples used'],
          hint: 'Draw an arrow or circle directly on the image for each annotation - if you can\'t point to the exact spot where a principle is honored or broken, the observation is too vague.' },
        { title: 'Redesign the Worst', points: 80, difficulty: 'Core',
          description: 'Take your worst-found design and redesign it in any tool (Canva/Figma/Illustrator) applying the violated principles. Side-by-side with a change log: each edit mapped to the principle it fixes.\nCourse link: Week 1-2 - principles in practice.',
          refs: [['Canva design school', 'https://www.canva.com/learn/']],
          solution: 'The change-log mapping is the assignment. A prettier design without principle mapping earns partial credit only.',
          criteria: ['Redesign directly addresses the previously flagged violations', 'Change log maps every edit to a specific principle', 'Side-by-side comparison clearly shows the improvement'],
          hint: 'Work backwards from your autopsy notes - each violation you flagged earlier should become one line item in your change log, so the two documents connect directly.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Type and Color', topic: 'Typography systems and color theory',
      problems: [
        { title: 'Type Specimen', points: 90, difficulty: 'Core',
          description: 'Build a typography system for a brand: pick a font pairing (justify with contrast/mood), define a scale (h1-h3, body, caption with exact sizes), and demonstrate it in a one-page specimen. Include one pairing that fails and why.\nCourse link: Week 3 - typographic hierarchy and pairing.',
          refs: [['Google Fonts pairing', 'https://fonts.google.com/knowledge']],
          solution: 'A modular scale with stated ratios shows mastery. The failed pairing must fail for an articulable reason (two display fonts, etc.).',
          criteria: ['Type scale specifies exact sizes for every level', 'Font pairing justified with contrast or mood reasoning', 'Failed pairing example with an articulable reason'],
          hint: 'Try building your scale with a consistent ratio (like 1.25 or 1.333) between sizes rather than picking numbers that feel right - it\'s what separates a system from a guess.' },
        { title: 'Palette with Purpose', points: 100, difficulty: 'Boss',
          description: 'Create 2 complete palettes (primary, secondary, neutrals, semantic colors) for two opposite brands: a children\'s academy and a law firm. Test text contrast for accessibility (WCAG AA, show the checker results) and explain each color psychology choice.\nCourse link: Week 4 - color theory + accessibility.',
          refs: [['Contrast checker', 'https://webaim.org/resources/contrastchecker/'], ['Color theory basics', 'https://www.interaction-design.org/literature/topics/color-theory']],
          solution: 'AA-passing text combos are mandatory evidence. Psychology claims must fit the audience, not generic "blue = trust" recitation.',
          criteria: ['Both palettes include primary, secondary, neutral, and semantic colors', 'WCAG AA contrast checker results shown as evidence', 'Color psychology reasoning fits each specific audience'],
          hint: 'Run every text-on-background combination you plan to actually use through the contrast checker, not just the boldest one - a palette can look fine and still fail AA on lighter secondary tones.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'The Working Designer', topic: 'Social media kits, print, mockups',
      problems: [
        { title: 'Social Kit Sprint', points: 100, difficulty: 'Core',
          description: 'For a real local business, design a 6-piece social kit: profile/cover, 3 post templates (announcement, product, testimonial), and a story template - all on one grid system and palette. Present in realistic mockups.\nCourse link: Week 5 - template systems and consistency.',
          refs: [['Free mockups', 'https://www.freepik.com/']],
          solution: 'System consistency across all 6 pieces is the grade - swap the content and it should still look like one brand.',
          criteria: ['All six pieces share one consistent grid and palette', 'Realistic mockups used for presentation', 'Templates would still look on-brand with different content'],
          hint: 'Before presenting, swap the placeholder content in each template with different sample text or images and check it still reads as the same brand - that\'s the real test of a template system.' },
        { title: 'Print Ready', points: 110, difficulty: 'Boss',
          description: 'Design a business card and A5 flyer for the same brand, prepared for real printing: CMYK, 3mm bleed, crop marks, 300 DPI, exported as print PDF. Include a screenshot proving each technical setting and a 5-line note to the print shop.\nCourse link: Week 6 - print production technicals.',
          refs: [['Print bleed explained', 'https://www.printplace.com/blog/full-bleed-printing/']],
          solution: 'Bleed and CMYK evidence are pass gates - RGB/no-bleed files fail regardless of beauty. This is the most common junior mistake.',
          criteria: ['CMYK color mode used throughout, not RGB', '3mm bleed and crop marks present in the export', 'Screenshots prove each technical setting was applied'],
          hint: 'Check your document setup panel before you start designing, not after - bleed and color mode are much easier to set from the start than to retrofit onto a finished RGB file.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Identity Systems', topic: 'Logo design and brand guidelines',
      problems: [
        { title: 'Logo Process', points: 110, difficulty: 'Core',
          description: 'Design a logo the professional way: 10 rough sketches (photograph them), 3 digital directions, 1 refined final with black/white and reversed versions, tested at 16px and billboard scale. Document the full process - clients buy process, not luck.\nCourse link: Week 7 - logo methodology.',
          refs: [['Logo design principles', 'https://99designs.com/blog/tips/logo-design-tips/']],
          solution: 'The sketch photos are mandatory. Scale tests reveal weak marks. Grade process rigor over personal taste.',
          criteria: ['Ten photographed rough sketches included as evidence', 'Final logo tested at both 16px and billboard scale', 'Black/white and reversed versions both provided'],
          hint: 'Test your favorite digital direction at 16 pixels early, not at the end - a mark that only works at large sizes will force you back to the sketch stage anyway.' },
        { title: 'The Mini Brand Book', points: 120, difficulty: 'Boss',
          description: 'Compile a 6-8 page brand guideline: logo usage and misuse (show 4 forbidden treatments), palette with codes, typography system, imagery style, and one applied example. This document is what turns a logo into a paid identity project.\nCourse link: Week 8 - brand guidelines.',
          refs: [['Brand guideline examples', 'https://brandingstyleguides.com/']],
          solution: 'Misuse examples are the professional marker. Codes must be exact (hex/CMYK). Grade completeness and clarity.',
          criteria: ['Four forbidden logo treatments shown explicitly', 'Palette codes given in exact hex or CMYK values', 'Guideline is complete enough to hand to another designer'],
          hint: 'Think about the mistakes you\'d actually want to stop a junior designer or client from making - stretching the logo, wrong colors, low contrast - and use those as your four forbidden examples.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Brand Delivery', topic: 'Complete identity project',
      problems: [
        { title: 'Full Identity Project', points: 200, difficulty: 'Boss',
          description: 'Deliver a complete brand identity for a real or realistic client: logo suite, brand book, social kit, one print item, and a presentation deck pitching the work as you would to the client - including your pricing. Everything consistent, everything justified.\nCourse link: Weeks 1-8 combined - your portfolio centerpiece.',
          refs: [],
          solution: 'Rubric: system consistency (30%), craft quality (30%), brand book completeness (20%), pitch and pricing realism (20%).',
          criteria: ['All five deliverables present and visually consistent', 'Presentation deck pitches the work with realistic pricing', 'Every design decision justified, not just aesthetic'],
          hint: 'Practice presenting the deck out loud as if the client is in the room - a pitch that only works as a silent PDF usually means the reasoning behind each decision isn\'t spelled out clearly enough yet.' },
      ] },
  ],
},
{
  key: 'st03-uiux', course_code: 'ST-03', title: 'UI/UX Designing',
  description: '2-month quest: from user research to a tested, developer-ready Figma prototype.',
  clos: [
    'CLO1: Conduct user research and translate findings into information architecture and user flows.',
    'CLO2: Design high-fidelity interfaces in Figma with a consistent, reusable design system.',
    'CLO3: Build and usability-test a developer-ready prototype, documented as a product case study.',
  ],
  pass_mark: 60, titleNames: ['UX Explorer', 'Wireframe Weaver', 'Flow Designer', 'Prototype Pro', 'Product Designer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Users First', topic: 'UX research: interviews, personas, journeys',
      problems: [
        { title: 'Real User Interviews', points: 60, difficulty: 'Basic',
          description: 'Pick an everyday app problem (ordering food, paying bills, bus booking). Interview 3 real people using open questions (script included), then synthesize: top 5 pain points with supporting quotes. No solutions yet - discipline is the lesson.\nCourse link: Week 1 - research before pixels.',
          refs: [['User interview guide (NN/g)', 'https://www.nngroup.com/articles/user-interviews/']],
          solution: 'Verbatim quotes prove real interviews. Reject leading questions in the script. Solutions appearing = principle missed.',
          criteria: ['Three real interviews with verbatim supporting quotes', 'Top five pain points clearly synthesized', 'No solutions proposed, only observed problems'],
          hint: 'Watch your own interview script for buried assumptions - a question like "wouldn\'t a faster checkout help?" leads the witness, while "walk me through the last time you paid a bill" just opens the door.' },
        { title: 'Persona and Journey', points: 80, difficulty: 'Core',
          description: 'From your interviews, build 1 evidence-based persona (goals, frustrations, context - every claim traceable to an interview) and map their current journey with emotion curve, marking the 2 worst moments as design opportunities.\nCourse link: Week 2 - personas and journey mapping.',
          refs: [['Journey mapping 101', 'https://www.nngroup.com/articles/journey-mapping-101/']],
          solution: 'Traceability is the grade: invented persona details fail. The two opportunity moments should be genuinely painful ones.',
          criteria: ['Every persona detail traceable to an actual interview', 'Journey map includes an emotion curve across steps', 'Two worst moments flagged as concrete design opportunities'],
          hint: 'Before writing any trait into the persona, ask yourself which interview quote supports it - if you can\'t point to one, leave it out rather than filling gaps with assumptions.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Structure and Flow', topic: 'Information architecture, user flows, wireframes',
      problems: [
        { title: 'Flows Before Screens', points: 90, difficulty: 'Core',
          description: 'For your chosen problem: define the core task, map the user flow (every screen, decision, and error state as a flowchart), then wireframe the 5 key screens low-fidelity in Figma. Grey boxes only - color is banned this week.\nCourse link: Week 3 - flows and low-fi wireframing.',
          refs: [['Figma basics', 'https://help.figma.com/hc/en-us/categories/360002042553'], ['User flows guide', 'https://www.nngroup.com/articles/user-flows/']],
          solution: 'Error states in the flow separate professionals from beginners. Ban enforcement: any styling = redo.',
          criteria: ['User flow includes decision points and error states', 'Five key screens wireframed at low fidelity', 'No color or styling used, greyscale only'],
          hint: 'Don\'t stop your flowchart at the happy path - trace through what happens when the user enters something wrong or the network fails, since that\'s exactly what separates a professional flow from a beginner one.' },
        { title: 'The IA Card Sort', points: 100, difficulty: 'Boss',
          description: 'Take a cluttered real app or site menu (a bank, a government portal). List its 20+ items, run a card sort with 3 people (physical or online), and propose a reorganized IA with rationale. Show the before/after site map.\nCourse link: Week 4 - information architecture.',
          refs: [['Card sorting (NN/g)', 'https://www.nngroup.com/articles/card-sorting-definition/']],
          solution: 'Participant groupings must visibly drive the new IA. Look for sensible label renaming, not just reshuffling.',
          criteria: ['Card sort actually run with three participants', 'New IA structure clearly derived from sort groupings', 'Before and after site maps both shown'],
          hint: 'When you propose the new structure, point back to specific groupings your participants made rather than just applying your own mental model - the sort data should visibly drive the reorganization.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Interface Craft', topic: 'Visual design, components, design systems in Figma',
      problems: [
        { title: 'High-Fidelity Screens', points: 100, difficulty: 'Core',
          description: 'Take your 5 wireframes to high fidelity: type scale, 8pt spacing grid, color styles, and Figma components with variants (buttons: default/hover/disabled). Screens must use ONLY defined styles - no detached one-offs.\nCourse link: Week 5 - visual systems in Figma.',
          refs: [['Figma components', 'https://help.figma.com/hc/en-us/articles/360038662654'], ['8pt grid', 'https://spec.fm/specifics/8-pt-grid']],
          solution: 'Open the Figma file: styles panel and component variants are the evidence. Detached instances = deductions.',
          criteria: ['Consistent type scale and 8pt spacing grid applied', 'Component variants used for interactive states', 'No detached, one-off styled elements in the file'],
          hint: 'Before calling it done, click through your Figma layers panel checking for any element not linked to a style or component - a single detached instance usually means the system has a gap somewhere.' },
        { title: 'Accessibility Pass', points: 110, difficulty: 'Boss',
          description: 'Audit your screens: contrast (AA), touch targets (44px+), focus states, and text scaling at 200%. Fix failures and document each with before/after. Then the empathy test: navigate a competitor app with eyes closed using a screen reader for 5 minutes and write what you felt.\nCourse link: Week 6 - accessible design.',
          refs: [['WCAG quick ref', 'https://www.w3.org/WAI/WCAG22/quickref/'], ['Contrast checker', 'https://webaim.org/resources/contrastchecker/']],
          solution: 'Measured evidence per check. The screen-reader reflection is graded on sincerity - it changes designers permanently.',
          criteria: ['Each accessibility check has measured before/after evidence', 'Touch targets meet the 44px minimum', 'Screen-reader reflection is genuine and specific'],
          hint: 'Actually turn on a screen reader and close your eyes for the full five minutes rather than skimming with your eyes open - the disorientation is the point, and it\'s hard to fake in the write-up.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Prototype and Test', topic: 'Interactive prototypes and usability testing',
      problems: [
        { title: 'Click-Through Prototype', points: 110, difficulty: 'Core',
          description: 'Wire your screens into an interactive Figma prototype covering the full core task including one error path, with sensible transitions. Share the prototype link and a 60-second screen recording of the happy path.\nCourse link: Week 7 - prototyping.',
          refs: [['Figma prototyping', 'https://help.figma.com/hc/en-us/articles/360040314193']],
          solution: 'The error path interaction is the differentiator. Check overlays/back behavior work, not just forward taps.',
          criteria: ['Full core task wired with working interactions', 'At least one error path included in the prototype', '60-second recording clearly demonstrates the happy path'],
          hint: 'Don\'t just wire the forward taps - build an overlay or alternate frame for what happens when something goes wrong, since that\'s the interaction most prototypes skip.' },
        { title: 'Watch Them Struggle', points: 120, difficulty: 'Boss',
          description: 'Run moderated usability tests with 3 people: task script, think-aloud, no helping. Record findings: completion, time, confusions with severity ratings. Fix the top 2 issues and show the redesigned screens. This loop IS the job.\nCourse link: Week 8 - usability testing and iteration.',
          refs: [['Usability testing 101', 'https://www.nngroup.com/articles/usability-testing-101/']],
          solution: 'Severity-rated findings and the two evidenced fixes are the pass bar. "Everyone loved it" = tests were led.',
          criteria: ['Three moderated sessions run without helping participants', 'Findings include severity ratings, not just a list', 'Top two issues fixed with redesigned screens shown'],
          hint: 'The hardest part is staying silent when someone gets stuck - resist jumping in to help, because their unscripted confusion is exactly the data you need.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Product Case Study', topic: 'End-to-end portfolio case study',
      problems: [
        { title: 'The Case Study', points: 200, difficulty: 'Boss',
          description: 'Package your entire project as a hiring-grade case study: problem, research evidence, IA/flows, design system, final UI, testing results, iterations, and outcomes - as a PDF plus the live Figma link. Write for a hiring manager with 3 minutes.\nCourse link: Weeks 1-8 combined - this document gets you interviews.',
          refs: [['UX case study guide', 'https://www.casestudy.club/journal']],
          solution: 'Rubric: evidence-driven narrative (35%), craft (30%), testing honesty (20%), presentation economy (15%).',
          criteria: ['All project phases represented with supporting evidence', 'Testing results and iterations reported honestly', 'Written for a hiring manager in a concise, scannable format'],
          hint: 'Write the case study as if your reader has three minutes and a short attention span - lead each section with the outcome, then back it up with the evidence, rather than narrating chronologically.' },
      ] },
  ],
},
{
  key: 'st04-data-analytics', course_code: 'ST-04', title: 'Data Analytics Specialist Track',
  description: '2-month quest: the full analyst workflow - Python, SQL, statistics, and executive storytelling.',
  clos: [
    'CLO1: Use Python and SQL together to extract, clean and analyse real-world datasets.',
    'CLO2: Apply statistical methods correctly to draw honest, defensible conclusions from data.',
    'CLO3: Communicate analysis results to a non-technical, executive audience in a portfolio project.',
  ],
  pass_mark: 60, titleNames: ['Data Rookie', 'Query Analyst', 'Stat Sleuth', 'Insight Lead', 'Analytics Specialist'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Analyst Python', topic: 'pandas mastery for analysis',
      problems: [
        { title: 'The Sales Deep-Dive', points: 70, difficulty: 'Basic',
          description: 'Using a Kaggle retail dataset: load, clean (nulls, dtypes, duplicates - documented), and answer 5 business questions with pandas (top products, monthly trend, weekday patterns, basket size, city comparison). Code + outputs + one-line answers.\nCourse link: Week 1 - pandas as the analyst\'s primary tool.',
          refs: [['Superstore dataset', 'https://www.kaggle.com/datasets/vivek468/superstore-dataset-final'], ['pandas docs', 'https://pandas.pydata.org/docs/']],
          solution: 'Cleaning must be documented with counts. Answers must be exact numbers from code, not chart eyeballing.',
          criteria: ['Cleaning steps documented with before/after counts', 'All five business questions answered with exact code output', 'Correct handling of nulls, dtypes, and duplicates'],
          hint: 'Print the row count and null count before and after each cleaning step so the documentation isn\'t just a description - it\'s proof.' },
        { title: 'GroupBy Gymnastics', points: 90, difficulty: 'Core',
          description: 'Produce a pivot analysis: revenue by region x category with subtotals, month-over-month growth per region, and top-3 products within each category (groupby + head trick). Explain when pivot_table beats groupby.\nCourse link: Week 2 - advanced aggregation patterns.',
          refs: [['pandas groupby guide', 'https://pandas.pydata.org/docs/user_guide/groupby.html']],
          solution: 'The within-group top-N pattern (groupby-apply or sort+groupby+head) is the skill test. MoM growth needs pct_change or shift.',
          criteria: ['Top-3-within-category correctly implemented with groupby', 'Month-over-month growth computed with pct_change or shift', 'Clear explanation of when pivot_table beats groupby'],
          hint: 'For the top-3-per-category problem, sort within each group before you group, then take head(3) on the grouped result - grouping first and sorting after won\'t give you what you want.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'SQL for Analysts', topic: 'Analytical SQL: windows, CTEs, cohorts',
      problems: [
        { title: 'CTE Storylines', points: 100, difficulty: 'Core',
          description: 'Rewrite 3 nested-subquery monsters as readable CTE chains on any SQL dataset, then build one multi-step analysis (filter -> aggregate -> rank) as a single CTE pipeline with comments narrating each step.\nCourse link: Week 3 - readable analytical SQL.',
          refs: [['CTEs explained', 'https://learnsql.com/blog/what-is-cte/']],
          solution: 'Readability is the grade: each CTE named for what it holds. The narrated pipeline should read like a paragraph.',
          criteria: ['Three nested subqueries rewritten as clean CTE chains', 'Each CTE named for the data it represents', 'Comments narrate the pipeline step by step'],
          hint: 'Name each CTE like a variable that describes its contents, such as filtered_orders or ranked_customers - a CTE named step1 defeats the whole point of readability.' },
        { title: 'Cohort Retention', points: 120, difficulty: 'Boss',
          description: 'The interview classic: build a monthly cohort retention table in SQL (first-purchase cohort x months-since, with retention %). Visualize as a heatmap (any tool) and write 3 sentences on what the retention pattern means for the business.\nCourse link: Week 4 - cohort analysis.',
          refs: [['Cohort analysis guide', 'https://mode.com/blog/cohort-analysis-helps-look-ahead/']],
          solution: 'Correct cohorting (MIN purchase month per customer) is the crux. Diagonal reading of the heatmap in their interpretation earns full marks.',
          criteria: ['Cohort correctly defined by each customer\'s first purchase month', 'Retention percentages computed per cohort and month offset', 'Heatmap visualization with a clear business interpretation'],
          hint: 'Get the cohort assignment right first - each customer should be tagged with the calendar month of their very first purchase, computed once, before you calculate anything about months-since.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Statistics That Matter', topic: 'Distributions, hypothesis tests, correlation traps',
      problems: [
        { title: 'The A/B Verdict', points: 110, difficulty: 'Core',
          description: 'Simulate or take an A/B dataset (two landing pages, conversion rates). Run the appropriate significance test in Python, report p-value and confidence interval, and write the verdict a marketing manager would understand - including what p-value does NOT mean.\nCourse link: Week 5 - hypothesis testing for business.',
          refs: [['A/B testing statistics', 'https://www.evanmiller.org/ab-testing/']],
          solution: 'Correct test choice (proportions z-test/chi-square) and the p-value misconception paragraph are the pass gates.',
          criteria: ['Correct statistical test chosen for proportions data', 'P-value and confidence interval both reported', 'Explanation correctly addresses what a p-value does not mean'],
          hint: 'Since you\'re comparing two conversion rates, reach for a proportions z-test or chi-square test rather than a t-test - and when writing the verdict, explicitly avoid saying the p-value is "the probability the result is due to chance".' },
        { title: 'Correlation Crime Scene', points: 120, difficulty: 'Boss',
          description: 'Find or construct 3 correlation traps: a spurious correlation, a confounder case, and Simpson\'s paradox (aggregated vs grouped trend reversal - show both charts). Explain each and state the business decision each trap would have ruined.\nCourse link: Week 6 - causal thinking.',
          refs: [['Spurious correlations', 'https://www.tylervigen.com/spurious-correlations'], ['Simpson\'s paradox', 'https://en.wikipedia.org/wiki/Simpson%27s_paradox']],
          solution: 'A working Simpson\'s demonstration (real or constructed data, both charts) is the boss criterion.',
          criteria: ['Simpson\'s paradox shown with both aggregated and grouped charts', 'Confounder example clearly identifies the hidden variable', 'Each trap tied to a concrete business decision it would ruin'],
          hint: 'For Simpson\'s paradox, the trend needs to genuinely flip direction between the combined chart and the per-group charts - if it doesn\'t reverse, you haven\'t constructed the paradox yet.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Executive Communication', topic: 'Dashboards and data storytelling',
      problems: [
        { title: 'The One-Screen KPI Story', points: 120, difficulty: 'Core',
          description: 'Design a single-screen executive dashboard (Power BI/Tableau Public/Looker Studio) for your dataset: 4 KPIs with period comparison, one trend, one breakdown, one alert-worthy highlight - every element answering "so what?". Include the 5-second test result: what does a viewer grasp in 5 seconds?\nCourse link: Week 7 - executive dashboard design.',
          refs: [['Looker Studio (free)', 'https://lookerstudio.google.com/'], ['Dashboard design', 'https://www.storytellingwithdata.com/blog']],
          solution: 'The 5-second test with a real person is required evidence. Chart-junk and unlabeled deltas are the common deductions.',
          criteria: ['Four KPIs shown with period-over-period comparison', '5-second test actually run with a real viewer', 'Every element answers a clear so-what question'],
          hint: 'Actually show the dashboard to someone for five seconds, cover it, and ask what they remember - don\'t estimate what they\'d notice, since that\'s the whole point of the test.' },
        { title: 'The Recommendation Deck', points: 130, difficulty: 'Boss',
          description: 'Turn your full analysis into a 6-slide decision deck: situation, 3 evidence slides (one chart each, assertion-style titles), recommendation with quantified impact, and risks/assumptions. Assertion titles are sentences ("Karachi drives 60% of growth"), not labels ("Sales by City").\nCourse link: Week 8 - analytics storytelling.',
          refs: [['Assertion-evidence slides', 'https://www.assertion-evidence.com/']],
          solution: 'Every title must be a claim; every claim must match its chart. Quantified recommendation is the pass gate.',
          criteria: ['Every slide title is a claim, not a label', 'Each evidence slide\'s chart matches its assertion', 'Recommendation includes a quantified impact estimate'],
          hint: 'Turn each slide title into a full sentence that states the finding, like "Karachi drives 60% of growth" instead of "Sales by City" - if the title could apply to any chart, it isn\'t an assertion yet.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Analyst Portfolio Project', topic: 'End-to-end business analysis',
      problems: [
        { title: 'The Full Analysis', points: 200, difficulty: 'Boss',
          description: 'Complete analyst engagement on a fresh dataset: business questions -> SQL + Python analysis -> statistical validation of one key claim -> dashboard -> recommendation deck -> appendix with reproducible code. One PDF + links. This is the portfolio piece that gets analyst interviews in 2026.\nCourse link: Weeks 1-8 combined.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          solution: 'Rubric: technical correctness (35%), statistical rigor on the key claim (20%), dashboard craft (20%), deck persuasiveness (25%).',
          criteria: ['End-to-end pipeline from raw data to recommendation deck', 'One key claim backed by a statistical validation test', 'Code is reproducible from the appendix alone'],
          hint: 'Pick the single claim your recommendation most depends on and make sure that\'s the one you rigorously test statistically - not every finding needs a hypothesis test, but your headline one does.' },
      ] },
  ],
},
{
  key: 'st05-genai-eng', course_code: 'ST-05', title: 'Generative AI Engineering',
  description: '2-month quest: engineering real LLM applications - RAG, evaluation, and production thinking.',
  clos: [
    'CLO1: Engineer LLM API calls with structured prompts and output for production use.',
    'CLO2: Build a retrieval-augmented generation (RAG) system grounded on real data.',
    'CLO3: Evaluate and productionise an LLM application with proper testing and deployment thinking.',
  ],
  pass_mark: 60, titleNames: ['API Cadet', 'Prompt Engineer', 'RAG Builder', 'Eval Master', 'GenAI Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'LLM API Engineering', topic: 'APIs, streaming, error handling, cost control',
      problems: [
        { title: 'The Robust Client', points: 70, difficulty: 'Basic',
          description: 'Write a Python LLM client (Gemini/Groq free tier) with: retries with exponential backoff, timeout handling, token counting, and per-call cost logging to a file. Prove each safeguard by forcing a failure.\nCourse link: Week 1 - production API hygiene.',
          refs: [['Gemini API docs', 'https://ai.google.dev/gemini-api/docs'], ['Backoff pattern', 'https://en.wikipedia.org/wiki/Exponential_backoff']],
          solution: 'Forced-failure evidence for each safeguard is the pass bar. Cost log must accumulate across calls.',
          criteria: ['Retry with exponential backoff demonstrated under forced failure', 'Timeout handling proven with an actual timeout scenario', 'Cost log accumulates correctly across multiple calls'],
          hint: 'Simulate each failure deliberately - point the client at a bad URL or set an impossibly short timeout - rather than just writing the retry logic and hoping it works when something actually breaks.' },
        { title: 'Structured Output Contract', points: 90, difficulty: 'Core',
          description: 'Build an extraction endpoint: messy job-ad text in -> validated JSON out (title, skills[], salary_range, city) using schema-constrained prompting + a Pydantic validation layer + one retry-on-invalid. Test on 5 real job ads including one that should partially fail.\nCourse link: Week 2 - reliable structured outputs.',
          refs: [['Pydantic docs', 'https://docs.pydantic.dev/'], ['Structured outputs', 'https://ai.google.dev/gemini-api/docs/structured-output']],
          solution: 'The validation-retry loop is the engineering skill. Partial-failure handling (nulls vs crash) shows maturity.',
          criteria: ['Pydantic schema validates all required output fields', 'Retry-on-invalid loop actually triggers and recovers', 'Partial-failure case handled gracefully, not with a crash'],
          hint: 'Design the job ad that should partially fail on purpose - missing a salary range, for instance - so you can show the system fills that field with null rather than crashing or hallucinating a number.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'RAG Engineering', topic: 'Chunking, embeddings, vector search, grounding',
      problems: [
        { title: 'Chunking Lab', points: 110, difficulty: 'Core',
          description: 'Take a 20+ page real document (prospectus, policy, manual). Implement 2 chunking strategies (fixed-size with overlap vs structure-aware) and compare retrieval quality on 5 questions: which strategy surfaces the right chunk more often, and why?\nCourse link: Week 3 - chunking, the most underrated RAG decision.',
          refs: [['Chunking strategies', 'https://www.pinecone.io/learn/chunking-strategies/']],
          solution: 'A per-question hit table per strategy is required. Structure-aware should usually win on headed documents - discussion matters.',
          criteria: ['Both chunking strategies implemented and tested', 'Per-question hit/miss table comparing the two strategies', 'Discussion explains why one strategy wins on this document'],
          hint: 'Build a simple table with one row per question and one column per strategy marking hit or miss - eyeballing which felt better isn\'t the same as a structured comparison.' },
        { title: 'Full RAG Service', points: 130, difficulty: 'Boss',
          description: 'Build a complete RAG pipeline: embed chunks (free embedding API + chromadb/FAISS), retrieve top-k, answer with citations to chunk IDs, refuse when retrieval confidence is low. Test: 6 answerable, 2 unanswerable, 1 adversarial ("ignore your instructions..."). Report all outputs.\nCourse link: Week 4 - grounded generation with refusal.',
          refs: [['ChromaDB docs', 'https://docs.trychroma.com/'], ['RAG best practices', 'https://docs.anthropic.com/en/docs/build-with-claude/retrieval-augmented-generation']],
          solution: 'Refusal on unanswerables and surviving the injection attempt are pass gates. Citations must map to real chunks.',
          criteria: ['Refuses correctly on the unanswerable test questions', 'Citations map to real, verifiable chunk IDs', 'Survives the adversarial prompt-injection test case'],
          hint: 'Set an explicit confidence or similarity-score threshold below which the system refuses to answer, rather than always attempting a response - that threshold is what makes the unanswerable cases behave correctly.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Evaluation Engineering', topic: 'Golden sets, LLM-as-judge, regression testing',
      problems: [
        { title: 'The Golden Set', points: 120, difficulty: 'Core',
          description: 'Create a 20-case golden test set for your RAG service (question, expected answer/behaviour, category). Build a runner that scores each run (exact/contains/judge) and outputs a scorecard. Run twice with different top-k and report the delta.\nCourse link: Week 5 - systematic evaluation.',
          refs: [['LLM evaluation guide', 'https://docs.anthropic.com/en/docs/build-with-claude/develop-tests']],
          solution: 'The scored A/B (top-k change) proves the harness works. Categories should include refusal cases.',
          criteria: ['Golden set includes refusal cases, not just answerable ones', 'Runner produces a scorecard across exact/contains/judge methods', 'Two runs with different top-k show a measurable delta'],
          hint: 'Make sure a few of your 20 cases are questions the system should refuse to answer - a golden set that only tests correct answers can\'t catch a system that answers everything confidently.' },
        { title: 'LLM-as-Judge, Audited', points: 130, difficulty: 'Boss',
          description: 'Implement an LLM judge scoring answer quality 1-5 with a rubric prompt. Then audit the judge: score 10 answers yourself blind, compute agreement with the judge, and report where and why they disagree. Trusting an unaudited judge is the field\'s current sin.\nCourse link: Week 6 - meta-evaluation.',
          refs: [['LLM-as-judge paper', 'https://arxiv.org/abs/2306.05685']],
          solution: 'The human-vs-judge agreement number is the deliverable. Disagreement analysis (verbosity bias, position bias) earns top marks.',
          criteria: ['Judge scores computed with a clear rubric prompt', 'Human-vs-judge agreement rate calculated and reported', 'Disagreement cases analyzed for patterns like verbosity bias'],
          hint: 'Score your 10 answers blind before looking at what the judge said, not after - seeing the judge\'s score first will unconsciously anchor your own rating and defeat the whole audit.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Production Thinking', topic: 'Safety, caching, monitoring, cost at scale',
      problems: [
        { title: 'The Safety Layer', points: 130, difficulty: 'Core',
          description: 'Add to your service: input guardrails (injection patterns, PII detection with regex+LLM hybrid), output checks (no system-prompt leakage), and a red-team report - 8 attack attempts of your own design with results. Attack your own system before users do.\nCourse link: Week 7 - AI application security.',
          refs: [['Prompt injection primer', 'https://www.lakera.ai/blog/guide-to-prompt-injection'], ['OWASP LLM Top 10', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/']],
          solution: 'The 8-attack red-team with honest pass/fail is the core. At least one attack should succeed and get patched.',
          criteria: ['Eight distinct attack attempts documented with results', 'At least one attack succeeds and is subsequently patched', 'Output checks verify no system-prompt leakage occurs'],
          hint: 'Don\'t design all eight attacks to fail - if none of your own attacks get through, you likely aren\'t trying hard enough, and the exercise is as much about finding a real hole as defending against it.' },
        { title: 'Scale Economics', points: 140, difficulty: 'Boss',
          description: 'Your RAG bot goes to 10,000 queries/day. Engineer the plan: semantic caching design (with hit-rate estimate from your golden set), model tiering (cheap model for easy queries, escalation rules), and a monthly cost model comparing naive vs engineered - with the monitoring metrics you would track.\nCourse link: Week 8 - GenAI systems at scale.',
          refs: [['Semantic caching', 'https://www.pinecone.io/learn/semantic-caching/']],
          solution: 'Escalation rules must be concrete (confidence/length/category based). Cost model with stated assumptions passes; magic numbers fail.',
          criteria: ['Cache hit-rate estimate grounded in the golden-set data', 'Escalation rules are concrete, not vague heuristics', 'Cost model states its assumptions explicitly'],
          hint: 'Base your hit-rate estimate on how many of your golden-set questions are actually near-duplicates of each other, rather than guessing a round number like 30% out of thin air.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Production RAG Product', topic: 'Complete GenAI application',
      problems: [
        { title: 'Ship It', points: 220, difficulty: 'Boss',
          description: 'Deliver a deployable GenAI application for a real domain (academy assistant, legal-doc helper, medical-info bot with disclaimers): full RAG, safety layer, golden-set eval with scores, cost model, README with architecture diagram, and a 3-minute demo video. Code in a GitHub repo.\nCourse link: Weeks 1-8 combined - a genuinely hireable portfolio project.',
          refs: [],
          solution: 'Rubric: works end-to-end (30%), eval rigor (25%), safety evidence (20%), engineering quality (15%), demo clarity (10%).',
          criteria: ['Application works end-to-end on a real domain', 'Golden-set evaluation scores included as evidence', 'README documents architecture with a diagram'],
          hint: 'Record the demo video walking through a real query end-to-end, including a case where the system correctly refuses - a demo that only shows the happy path undersells the safety work you did.' },
      ] },
  ],
},
{
  key: 'st06-ai-agents', course_code: 'ST-06', title: 'AI Agents & Automation Engineering',
  description: '2-month quest: from tool-calling basics to multi-step autonomous agents with guardrails.',
  clos: [
    'CLO1: Implement tool-calling so an AI agent can take real actions, not just respond with text.',
    'CLO2: Build a multi-step agent loop that plans, acts and adapts across steps.',
    'CLO3: Orchestrate multiple agents with guardrails into a working autonomous assistant.',
  ],
  pass_mark: 60, titleNames: ['Tool Caller', 'Loop Runner', 'Agent Smith', 'Orchestrator', 'Agent Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Tools in Hand', topic: 'Function calling fundamentals',
      problems: [
        { title: 'First Function Call', points: 70, difficulty: 'Basic',
          description: 'Implement function calling with a free-tier LLM: define 2 tools (get_weather stub, calculate) with JSON schemas, let the model choose, execute, and return the result to the model for a final answer. Trace the full message loop in your report.\nCourse link: Week 1 - the tool-calling loop.',
          refs: [['Gemini function calling', 'https://ai.google.dev/gemini-api/docs/function-calling'], ['Groq tool use', 'https://console.groq.com/docs/tool-use']],
          solution: 'The traced loop (model->tool_call->execution->model->answer) is the deliverable. Check schemas are honest JSON Schema.',
          criteria: ['Both tools defined with valid JSON Schema', 'Full message loop traced from call to final answer', 'Model correctly selects and executes the right tool'],
          hint: 'Print or log every message in the loop - the tool call request, your execution result, and the model\'s follow-up - so the trace actually shows the round trip rather than just the final answer.' },
        { title: 'The Tool Router', points: 90, difficulty: 'Core',
          description: 'Give the model 5 tools (search stub, calculator, date, unit converter, none-needed). Test 10 varied queries and build a confusion table: which tool was chosen vs which was right. Improve the worst tool description and show the fix.\nCourse link: Week 2 - tool selection quality.',
          refs: [['Tool use best practices', 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use']],
          solution: 'The description-improvement experiment is the point: tool docs ARE the interface. Before/after selection accuracy required.',
          criteria: ['Confusion table covers all 10 test queries', 'Worst-performing tool description identified and rewritten', 'Before/after accuracy comparison shows the improvement'],
          hint: 'When a tool gets picked incorrectly, look at its description rather than its logic first - vague or overlapping descriptions are usually what confuse the model\'s tool choice, not bad implementation.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'The Agent Loop', topic: 'ReAct pattern, memory, termination',
      problems: [
        { title: 'ReAct From Scratch', points: 110, difficulty: 'Core',
          description: 'Implement a ReAct agent loop without frameworks: thought -> action -> observation cycles with a max-step limit and explicit final-answer detection. Run it on a 3-step task (e.g. "find X, compute Y from it, format Z") and include the full trace.\nCourse link: Week 3 - the agent loop, demystified.',
          refs: [['ReAct paper', 'https://arxiv.org/abs/2210.03629']],
          solution: 'No LangChain - the raw loop is the lesson. Max-step guard and stop condition must be visible in code and trace.',
          criteria: ['Loop implemented without any agent framework', 'Max-step limit and stop condition both visible in code', 'Full trace shows all thought/action/observation cycles'],
          hint: 'Write the stop condition as an explicit check the loop makes every iteration, like looking for a special final-answer marker in the model\'s output, rather than just hoping the model stops calling tools on its own.' },
        { title: 'Agent That Remembers', points: 130, difficulty: 'Boss',
          description: 'Add memory: short-term (conversation window with summarization when long) and a simple long-term store (facts file the agent reads/writes via tools). Demonstrate: teach it a fact in session 1, restart, and have it recall in session 2. Discuss what should NOT be memorized.\nCourse link: Week 4 - agent memory architectures.',
          refs: [['Memory in agents (LangChain concepts)', 'https://python.langchain.com/docs/concepts/memory/']],
          solution: 'The restart-recall demo is the pass gate. The should-not-memorize discussion (PII, stale facts) shows judgment.',
          criteria: ['Fact taught in session 1 correctly recalled after a restart', 'Long-term store persists to a file the agent reads and writes', 'Discussion identifies specific things that should not be memorized'],
          hint: 'Actually kill and restart the process between sessions rather than just calling a new function - the memory has to survive a genuine process restart, reading only from the persisted file.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Agents That Act', topic: 'Real-world integration: files, web, APIs',
      problems: [
        { title: 'The File Clerk Agent', points: 120, difficulty: 'Core',
          description: 'Build an agent with file tools (list, read, write - sandboxed to one folder) that can: organize 15 messy files into folders by type/topic and produce an index document. Log every action for audit. Safety: it must refuse operations outside its sandbox - prove it.\nCourse link: Week 5 - agents with real side effects.',
          refs: [['Python pathlib', 'https://docs.python.org/3/library/pathlib.html']],
          solution: 'The sandbox-escape refusal test is mandatory. Audit log completeness is the engineering grade.',
          criteria: ['All 15 files correctly organized by type or topic', 'Sandbox-escape attempt explicitly tested and refused', 'Every file action recorded in an audit log'],
          hint: 'Actually try to get the agent to read or write a path outside its assigned folder, like using a relative ../ path, and confirm it refuses - don\'t just assume the sandbox boundary works because you wrote a check for it.' },
        { title: 'Research Agent', points: 140, difficulty: 'Boss',
          description: 'An agent that answers "compare X and Y" questions by: searching (any free search API/wrapper), reading 3+ sources, extracting claims with citations, and producing a comparison table with a confidence note per claim. Test on a question whose answer you can verify. Report hallucination incidents honestly.\nCourse link: Week 6 - research agent patterns.',
          refs: [['Tavily search API (free tier)', 'https://tavily.com/']],
          solution: 'Per-claim citations checkable against sources are the bar. Honest hallucination reporting earns marks, hiding it loses them.',
          criteria: ['Comparison table includes a citation for every claim', 'At least three sources actually read and used', 'Hallucination incidents reported honestly if they occurred'],
          hint: 'Pick a comparison question where you already know the correct answer before running the agent - that\'s the only way you\'ll reliably catch and honestly report a hallucinated claim.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Orchestration and Guardrails', topic: 'Multi-agent patterns, approvals, evaluation',
      problems: [
        { title: 'The Two-Agent Newsroom', points: 130, difficulty: 'Core',
          description: 'Build a writer-agent + critic-agent pipeline: writer drafts a piece from a brief, critic reviews against a rubric and returns structured feedback, writer revises - max 2 rounds. Show all intermediate artifacts and compare draft 1 vs final quality.\nCourse link: Week 7 - multi-agent collaboration.',
          refs: [['Multi-agent patterns (Anthropic)', 'https://www.anthropic.com/research/building-effective-agents']],
          solution: 'Structured critic feedback (not vibes) and measurable improvement between rounds are the criteria.',
          criteria: ['Critic feedback follows a structured rubric, not vague comments', 'Revision loop capped at two rounds as specified', 'Draft 1 and final version compared to show measurable improvement'],
          hint: 'Have the critic return feedback in a fixed structured format, like a list of specific issues with severity, rather than free-text prose - that structure is what the writer agent can actually act on.' },
        { title: 'Human-in-the-Loop Gate', points: 140, difficulty: 'Boss',
          description: 'Take any agent you built and add approval gates for consequential actions (file writes, sends): the agent proposes, a human approves/rejects/edits via console, and rejections feed back as observations. Demonstrate all 3 paths, then write your agent-autonomy policy: what may this agent do unsupervised, and why?\nCourse link: Week 8 - deploying agents responsibly.',
          refs: [['Building effective agents', 'https://www.anthropic.com/research/building-effective-agents']],
          solution: 'All three demonstrated paths (approve/reject/edit) are the pass gate. The autonomy policy is graded on reasoned boundaries.',
          criteria: ['All three approval paths demonstrated: approve, reject, edit', 'Rejected actions correctly feed back as new observations', 'Autonomy policy gives reasoned, specific boundaries'],
          hint: 'Make sure a rejection doesn\'t just stop the agent - route the rejection reason back into the loop as an observation so the agent can try a different approach, which is the harder half of this exercise.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Autonomous Assistant', topic: 'Complete agent product',
      problems: [
        { title: 'Your Agent, Shipped', points: 220, difficulty: 'Boss',
          description: 'Deliver a working agent for a real workflow (study assistant that builds revision packs, business assistant that drafts and files documents, data agent that produces weekly reports): 3+ tools, memory, guardrails with approval gates, an evaluation of 10 tasks with success rate, and a post-mortem of its worst failure. Repo + demo video.\nCourse link: Weeks 1-8 combined.',
          refs: [],
          solution: 'Rubric: reliable task completion (35%), guardrail evidence (25%), evaluation honesty incl. failure post-mortem (25%), code quality (15%).',
          criteria: ['Success rate reported across all 10 evaluated tasks', 'Guardrails and approval gates demonstrably working', 'Post-mortem honestly analyzes the worst failure case'],
          hint: 'Choose your worst failure for the post-mortem rather than a minor one - a thorough analysis of a real breakdown teaches more, and is graded more favorably, than glossing over it.' },
      ] },
  ],
},
{
  key: 'st07-ml-fundamentals', course_code: 'ST-07', title: 'Machine Learning Fundamentals',
  description: '2-month quest: the complete classical ML toolkit with mathematical intuition and rigorous practice.',
  clos: [
    'CLO1: Apply classical ML algorithms - regression, trees, ensembles - with correct mathematical intuition.',
    'CLO2: Engineer features and tune hyperparameters using rigorous cross-validation.',
    'CLO3: Build and honestly evaluate a complete ML system end to end.',
  ],
  pass_mark: 60, titleNames: ['Gradient Novice', 'Model Mechanic', 'Ensemble Rider', 'Tuning Expert', 'ML Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Under the Hood', topic: 'Gradient descent and linear models from scratch',
      problems: [
        { title: 'Gradient Descent by Hand', points: 80, difficulty: 'Basic',
          description: 'Implement linear regression with gradient descent in pure NumPy: loss curve plotted, learning-rate experiment (too small/right/too large - show all three curves), and final weights compared against sklearn\'s. Understanding this loop is understanding half of ML.\nCourse link: Week 1 - optimization intuition.',
          refs: [['Gradient descent visual', 'https://developers.google.com/machine-learning/crash-course/linear-regression/gradient-descent']],
          solution: 'The three learning-rate curves (crawl/converge/diverge) are the pass evidence. Weights should match sklearn to ~2 decimals.',
          criteria: ['All three learning-rate curves shown: crawl, converge, diverge', 'Final weights closely match sklearn\'s fitted coefficients', 'Loss curve plotted showing convergence behavior'],
          hint: 'Pick your three learning rates far enough apart that the behaviors are unmistakable - something clearly too small, a well-tuned value, and something clearly too large so the diverging curve visibly explodes rather than just looking noisy.' },
        { title: 'Regularization Reality', points: 100, difficulty: 'Core',
          description: 'On a small noisy dataset, fit polynomial regression degrees 1-15: plot train vs validation error to expose overfitting, then apply Ridge and Lasso and show how they tame degree-15. Explain L1 vs L2 including why Lasso zeros features.\nCourse link: Week 2 - bias-variance and regularization.',
          refs: [['Bias-variance (scikit-learn)', 'https://scikit-learn.org/stable/auto_examples/model_selection/plot_underfitting_overfitting.html']],
          solution: 'The U-shaped validation curve and Lasso coefficient zeros are the evidence. The geometric L1 corner explanation earns bonus.',
          criteria: ['Train-vs-validation curve shows the expected U-shape', 'Lasso demonstrably zeros out some coefficients', 'Explanation correctly distinguishes L1 from L2 geometrically'],
          hint: 'When explaining why Lasso zeros coefficients, think about the shape of the L1 penalty\'s constraint region - its corners are what let the optimal solution land exactly on an axis, unlike the smooth L2 circle.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'The Classics', topic: 'Trees, KNN, SVM, Naive Bayes',
      problems: [
        { title: 'Four-Model Tournament', points: 110, difficulty: 'Core',
          description: 'On one classification dataset (bank marketing / heart disease): train DecisionTree, KNN, SVM, NaiveBayes with identical CV protocol. Report F1 per model, decision-boundary plots on 2 features, and a paragraph on WHY the winner suits this data\'s shape.\nCourse link: Week 3 - algorithm intuitions.',
          refs: [['Heart disease dataset', 'https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction'], ['Classifier comparison', 'https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html']],
          solution: 'Identical CV protocol is the rigor test. The "why" paragraph must reference data properties (scale, boundaries, feature independence).',
          criteria: ['All four models evaluated under an identical CV protocol', 'Decision-boundary plots shown for two features', 'Explanation of the winner ties to concrete data properties'],
          hint: 'When justifying the winning model, reference something concrete about the data - like whether classes are linearly separable, on similar scales, or have correlated features - rather than just restating that it scored highest.' },
        { title: 'Explain the Tree', points: 120, difficulty: 'Boss',
          description: 'Train a depth-limited decision tree on loan/heart data, export the tree diagram, and translate its top 3 paths into plain-language rules a bank officer could apply. Then break it: find one person the rules judge unfairly and discuss.\nCourse link: Week 4 - interpretability and its limits.',
          refs: [['Tree visualization', 'https://scikit-learn.org/stable/modules/tree.html']],
          solution: 'Accurate path-to-rule translation is the skill. The fairness case must be a concrete instance from the data.',
          criteria: ['Top three decision paths translated into clear plain-language rules', 'Tree diagram exported and matches the stated rules', 'One concrete unfairly-judged instance identified from the data'],
          hint: 'Look through the actual rows for someone whose real outcome contradicts what the tree\'s top rule would predict for them - the unfair case needs to be a real record, not a hypothetical.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Ensemble Power', topic: 'Random forests, gradient boosting',
      problems: [
        { title: 'Forest vs Boosting', points: 120, difficulty: 'Core',
          description: 'Same dataset: RandomForest vs XGBoost/LightGBM. Compare CV scores, training time, and feature importances (do they agree?). Explain bagging vs boosting with a cricket-team analogy of your own making.\nCourse link: Week 5 - ensemble methods.',
          refs: [['XGBoost docs', 'https://xgboost.readthedocs.io/'], ['Ensembles (sklearn)', 'https://scikit-learn.org/stable/modules/ensemble.html']],
          solution: 'Importance-agreement analysis shows depth. The analogy must correctly capture parallel-independent vs sequential-corrective.',
          criteria: ['Feature importance agreement between the two models analyzed', 'Training time and CV scores both compared', 'Cricket analogy accurately captures parallel versus sequential learning'],
          hint: 'For the analogy to actually land, make sure it captures that bagging trains independent members in parallel while boosting trains each new member to correct the previous ones\' mistakes - not just that both involve a team.' },
        { title: 'The Kaggle Gauntlet', points: 140, difficulty: 'Boss',
          description: 'Enter a live or playground Kaggle competition: baseline -> feature engineering (3+ engineered features, justified) -> tuned ensemble -> submission. Deliver your leaderboard screenshot, ablation table (score with/without each feature), and biggest lesson.\nCourse link: Week 6 - competitive practice.',
          refs: [['Kaggle competitions', 'https://www.kaggle.com/competitions']],
          solution: 'The ablation table is the grade - it proves which engineering actually helped. Leaderboard position is NOT the grade.',
          criteria: ['Ablation table shows score with and without each engineered feature', 'At least three engineered features included and justified', 'Leaderboard screenshot submitted as supporting evidence, not the grade itself'],
          hint: 'Build the ablation table as you go rather than at the end - add one feature at a time and record the score change immediately, since reconstructing it afterward from memory is unreliable.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Rigor and Reality', topic: 'Tuning, pipelines, fairness, drift',
      problems: [
        { title: 'The Honest Pipeline', points: 130, difficulty: 'Core',
          description: 'Build a leak-proof sklearn Pipeline (imputation, encoding, scaling, model) tuned with GridSearchCV/RandomizedSearchCV inside cross-validation. Then demonstrate the crime: the same tuning done wrong (fit preprocessing on full data) and quantify the optimism gap.\nCourse link: Week 7 - pipelines and nested validation.',
          refs: [['sklearn Pipeline', 'https://scikit-learn.org/stable/modules/compose.html']],
          solution: 'The measured optimism gap between wrong and right protocols is the deliverable. Pipeline must contain ALL preprocessing.',
          criteria: ['Pipeline includes all preprocessing steps, not just the model', 'Leaky version deliberately implemented for comparison', 'Optimism gap between correct and leaky protocols quantified'],
          hint: 'To construct the leaky version, fit your scaler or encoder on the entire dataset before splitting into folds - that\'s the exact mistake that inflates the score, and reproducing it deliberately is the point.' },
        { title: 'Model on Trial', points: 140, difficulty: 'Boss',
          description: 'Audit your best model like a regulator: performance across subgroups (gender/age bands - find a gap and discuss), calibration curve, and a drift plan (which input stats to monitor, what triggers retraining). Real ML work is 20% fitting, 80% this.\nCourse link: Week 8 - responsible ML practice.',
          refs: [['Fairness in ML (Google)', 'https://developers.google.com/machine-learning/crash-course/fairness'], ['Calibration', 'https://scikit-learn.org/stable/modules/calibration.html']],
          solution: 'Subgroup table + calibration plot + concrete drift triggers. The discussion of an actual found gap is the boss criterion.',
          criteria: ['Subgroup performance table reveals a concrete found gap', 'Calibration curve plotted and interpreted', 'Drift plan specifies concrete monitored stats and retrain triggers'],
          hint: 'Don\'t stop if the first subgroup split looks fine - try a couple of different groupings, since a real performance gap across gender or age bands is often hiding in a specific slice rather than the overall average.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: The ML System', topic: 'Complete rigorous ML project',
      problems: [
        { title: 'End-to-End ML Project', points: 220, difficulty: 'Boss',
          description: 'A locally-relevant prediction problem (crop yield, AQI, prices, dropout risk): framing -> EDA -> leak-proof pipeline -> 3 models with nested CV -> ensemble -> fairness and calibration audit -> technical report + 1-page non-technical brief. Repo with reproducible code.\nCourse link: Weeks 1-8 combined.',
          refs: [['Pakistan open data', 'https://data.gov.pk/']],
          solution: 'Rubric: protocol rigor (30%), modeling quality (25%), audit depth (25%), communication (20%). Reproducibility spot-check: run their notebook.',
          criteria: ['Pipeline is leak-proof with nested cross-validation throughout', 'Fairness and calibration audit included with real findings', 'Notebook runs end-to-end reproducibly from raw data'],
          hint: 'Before submitting, clear all outputs and re-run the notebook top to bottom in a fresh environment - a project that only works because of leftover variables in your kernel will fail the reproducibility check.' },
      ] },
  ],
},
{
  key: 'st08-pytorch-dl', course_code: 'ST-08', title: 'Deep Learning with PyTorch',
  description: '2-month quest: tensors to trained networks - vision, transfer learning, and a deployed model.',
  clos: [
    'CLO1: Build neural networks in PyTorch using tensors and autograd from first principles.',
    'CLO2: Train convolutional networks and apply transfer learning for computer vision tasks.',
    'CLO3: Deploy a trained deep learning model as a working applied product.',
  ],
  pass_mark: 60, titleNames: ['Tensor Trainee', 'Backprop Believer', 'Network Builder', 'Vision Voyager', 'DL Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Tensors and Autograd', topic: 'PyTorch fundamentals',
      problems: [
        { title: 'Tensor Bootcamp', points: 80, difficulty: 'Basic',
          description: 'In a notebook: tensor creation/reshaping/broadcasting exercises (8 given operations), then use autograd to compute and verify the gradient of a small function by hand-check. Finish with requires_grad, .backward(), and .grad explained in your own words.\nCourse link: Week 1 - tensors and automatic differentiation.',
          refs: [['PyTorch tensors tutorial', 'https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html'], ['Autograd tutorial', 'https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html']],
          solution: 'The hand-verified gradient (simple polynomial) is the pass check. Own-words explanations catch copy-pasters.',
          criteria: ['All eight tensor operations completed correctly', 'Autograd gradient verified against a manual hand calculation', 'requires_grad, backward, and grad explained in own words'],
          hint: 'Pick a simple polynomial function you can differentiate by hand, like x squared plus 3x, so you have an exact number to check autograd\'s output against rather than just trusting it ran without error.' },
        { title: 'Linear Regression, Torch Style', points: 100, difficulty: 'Core',
          description: 'Implement linear regression in raw PyTorch (manual training loop: forward, loss, backward, step, zero_grad) on synthetic data. Plot the loss curve and the fitted line. Then rewrite using nn.Linear + optim and confirm identical behavior. The training loop you write here is every training loop.\nCourse link: Week 2 - the canonical training loop.',
          refs: [['PyTorch optimization tutorial', 'https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html']],
          solution: 'zero_grad placement and loss-curve convergence are the checks. The raw-vs-nn equivalence proves understanding.',
          criteria: ['Manual loop correctly calls zero_grad before each backward pass', 'Loss curve shows clear convergence over training', 'nn.Linear rewrite produces equivalent results to the manual version'],
          hint: 'If your loss explodes or plateaus strangely, check exactly where zero_grad is called relative to backward - forgetting it, or calling it in the wrong order, silently accumulates gradients across steps.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'First Neural Networks', topic: 'MLPs, activation, loss functions, training craft',
      problems: [
        { title: 'MNIST From Scratch', points: 110, difficulty: 'Core',
          description: 'Build an MLP for MNIST: DataLoaders, 2 hidden layers, ReLU, CrossEntropyLoss, accuracy on a proper validation split, and a plot of train vs val loss per epoch. Show 5 misclassified digits and hypothesize why each fooled the network.\nCourse link: Week 3 - full training pipeline.',
          refs: [['MNIST with PyTorch', 'https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html']],
          solution: '95%+ val accuracy is normal; grade the pipeline hygiene and the misclassification analysis quality.',
          criteria: ['Train and validation loss plotted per epoch', 'Five actual misclassified digits shown with hypotheses', 'Proper validation split kept separate from training data'],
          hint: 'Look closely at the five misclassified digits themselves before writing your hypothesis - often it\'s genuinely ambiguous handwriting, like a 4 that looks like a 9, rather than a flaw in the network.' },
        { title: 'Overfit It, Then Fix It', points: 130, difficulty: 'Boss',
          description: 'Deliberately overfit: train your MLP on only 500 examples until train accuracy is ~100% while validation collapses (show curves). Then rescue it three ways - dropout, weight decay, data augmentation - reporting each fix\'s effect separately. Diagnose-and-treat is the daily DL skill.\nCourse link: Week 4 - regularization in deep learning.',
          refs: [['Dropout paper (summary)', 'https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html']],
          solution: 'The engineered overfit curves plus three separate ablations are the deliverable. Combined-fix-only reports fail the "separately" requirement.',
          criteria: ['Overfitting curves clearly show train and validation diverging', 'Each of the three fixes applied and reported separately', 'Effect of each individual fix is measurable and distinct'],
          hint: 'Run three completely separate training sessions, one per fix, rather than stacking dropout, weight decay, and augmentation together in a single run - the assignment specifically wants each one\'s isolated effect.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Convolutional Vision', topic: 'CNNs and image pipelines',
      problems: [
        { title: 'CNN on CIFAR-10', points: 120, difficulty: 'Core',
          description: 'Build a CNN (3+ conv blocks with pooling and batchnorm) for CIFAR-10 with augmentation (flips, crops). Compare against your MLP on the same data - accuracy and parameter count - and explain WHY convolutions win on images (locality, weight sharing).\nCourse link: Week 5 - convolutional architectures.',
          refs: [['CIFAR-10 tutorial', 'https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html']],
          solution: 'The MLP-vs-CNN comparison with parameter counts is the concept test. Expect ~70%+ with augmentation on modest training.',
          criteria: ['CNN compared against the MLP on both accuracy and parameter count', 'Data augmentation with flips and crops actually applied', 'Explanation correctly cites locality and weight sharing'],
          hint: 'When comparing parameter counts, remember a fully-connected layer over a flattened image scales with the number of pixels while a conv filter is shared across the whole image - that\'s the number that should surprise you.' },
        { title: 'See What It Sees', points: 130, difficulty: 'Boss',
          description: 'Open the black box: visualize first-layer filters, feature maps for one image through the network, and a Grad-CAM (or simple occlusion map) showing where the model looks for 3 predictions - including one wrong prediction. What was it looking at when it failed?\nCourse link: Week 6 - CNN interpretability.',
          refs: [['Grad-CAM explained', 'https://arxiv.org/abs/1610.02391']],
          solution: 'The wrong-prediction attention map with interpretation is the boss criterion. Any reasonable CAM/occlusion implementation accepted.',
          criteria: ['First-layer filters and feature maps both visualized', 'Grad-CAM or occlusion map shown for a wrong prediction', 'Interpretation explains what the model was focusing on when it failed'],
          hint: 'Specifically hunt for a wrong prediction to run your Grad-CAM on rather than just picking three easy correct ones - the failure case is where the visualization actually teaches you something.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Transfer Learning', topic: 'Pretrained models and fine-tuning',
      problems: [
        { title: 'Stand on Giants', points: 130, difficulty: 'Core',
          description: 'Fine-tune a pretrained ResNet18 on a custom small dataset you collect (200+ images, 3+ classes - local fruits, vehicles, dishes). Compare: frozen-backbone vs full fine-tune vs training from scratch, on the same split. The result will teach you why nobody trains from scratch anymore.\nCourse link: Week 7 - transfer learning economics.',
          refs: [['Transfer learning tutorial', 'https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html']],
          solution: 'Three-way comparison table is the deliverable; scratch should lose badly on small data. Dataset collection effort counts.',
          criteria: ['Custom dataset has at least 200 images across 3+ classes', 'All three training strategies compared on the same split', 'From-scratch result clearly underperforms the transfer-learned ones'],
          hint: 'Make sure all three variants train on exactly the same train/val split and for a comparable number of epochs - otherwise the comparison isn\'t fair and the from-scratch model might just need more time, not more data.' },
        { title: 'The Deployment Gap', points: 140, difficulty: 'Boss',
          description: 'Take your fine-tuned model to the real world: export (TorchScript/ONNX), wrap in a minimal API or Gradio app, measure inference latency on CPU, then test with 10 fresh photos in bad conditions (lighting, angle) and report the accuracy drop from your test set. The gap IS the lesson.\nCourse link: Week 8 - from notebook to product.',
          refs: [['Gradio quickstart', 'https://www.gradio.app/guides/quickstart'], ['TorchScript intro', 'https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html']],
          solution: 'The measured lab-vs-wild accuracy gap with example failures is the boss criterion. Latency numbers must be real measurements.',
          criteria: ['Model successfully exported and served through a working app', 'Inference latency measured with real CPU timing, not estimated', 'Accuracy drop between test set and 10 wild photos reported honestly'],
          hint: 'Take the 10 fresh photos in genuinely bad conditions - bad lighting, odd angles, cluttered backgrounds - rather than clean photos similar to your training data, or the gap you\'re supposed to measure won\'t show up.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Applied DL Product', topic: 'Complete deep learning project',
      problems: [
        { title: 'Deep Learning, Deployed', points: 220, difficulty: 'Boss',
          description: 'A locally-relevant vision project (crop disease from leaf photos, traffic counting, waste classification): dataset collection/curation with documentation -> transfer-learned model with proper splits and augmentation -> interpretability evidence -> deployed demo (Gradio/HF Spaces) -> report with limitations and ethics section. Repo + live demo link.\nCourse link: Weeks 1-8 combined - a genuinely impressive 2026 portfolio project.',
          refs: [['Hugging Face Spaces', 'https://huggingface.co/spaces'], ['PlantVillage dataset', 'https://www.kaggle.com/datasets/emmarex/plantdisease']],
          solution: 'Rubric: dataset rigor (25%), training correctness (25%), deployed demo works (25%), report honesty incl. ethics (25%).',
          criteria: ['Dataset collection and curation process clearly documented', 'Deployed demo actually works end-to-end, not just locally', 'Report includes an honest limitations and ethics discussion'],
          hint: 'Test the live deployed demo yourself with fresh inputs right before submitting, not just the local notebook version - a demo link that errors out on the grader\'s first try undoes a lot of otherwise good work.' },
      ] },
  ],
},
];
