'use strict';
/** EchoLens prebuilt tracks - Specialist & Professional Tracks (2 months).
 * 5 milestone levels per track (levels span ~1.5 weeks each); teachers can
 * edit any problem or add levels via the editor. Solutions = teacher-only. */

module.exports = [
{
  key: 'st01-wordpress', course_code: 'ST-01', title: 'WordPress Development',
  description: '2-month quest: from local install to a client-ready website delivery.',
  pass_mark: 60, titleNames: ['Site Starter', 'Theme Tamer', 'Plugin Pro', 'Client Builder', 'WP Developer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Local Foundations', topic: 'Install, dashboard, posts vs pages, media',
      problems: [
        { title: 'Your First Site', points: 60, difficulty: 'Basic',
          description: 'Install WordPress locally (LocalWP/XAMPP). Create 3 pages (Home, About, Contact), 2 blog posts with images, a nav menu, and set a static homepage. Screenshot-report each step and explain posts vs pages.\nCourse link: Week 1 - WordPress anatomy and content types.',
          refs: [['WordPress.org: first steps', 'https://wordpress.org/documentation/article/new-to-wordpress-where-to-start/']],
          solution: 'Static-homepage setting and correct posts-vs-pages explanation (chronological vs structural) are the pass checks.' },
        { title: 'The Content Model', points: 80, difficulty: 'Core',
          description: 'A restaurant client needs menus, chefs, and testimonials. Plan the content: which become pages, posts, categories, or custom types? Build categories/tags for the blog and justify your model in a diagram.\nCourse link: Week 1-2 - content architecture before building.',
          refs: [['WP taxonomies', 'https://wordpress.org/documentation/article/taxonomies/']],
          solution: 'Any defensible model passes; grade the justification. Testimonials as CPT (or plugin) shows foresight.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Themes and Layouts', topic: 'Theme customization, block editor, page builders',
      problems: [
        { title: 'Theme Makeover', points: 90, difficulty: 'Core',
          description: 'Take a free theme (Astra/Kadence) and customize it into a distinct brand: colors, typography, header/footer, and a styled homepage using the block editor - no page builder yet. Before/after screenshots plus what each customizer setting controls.\nCourse link: Week 3 - theme system and the block editor.',
          refs: [['Block editor guide', 'https://wordpress.org/documentation/article/wordpress-block-editor/']],
          solution: 'Distinctiveness matters: default-looking Astra fails. Check header/footer edited, not just colors.' },
        { title: 'Builder Duel', points: 100, difficulty: 'Boss',
          description: 'Rebuild the same landing section twice: once in Gutenberg blocks, once in Elementor (free). Compare honestly: speed to build, page-load weight (check with browser devtools), and lock-in risk. Recommend one for a low-budget client.\nCourse link: Week 4 - page builders: power vs cost.',
          refs: [['Elementor docs', 'https://elementor.com/help/']],
          solution: 'The devtools weight comparison is the differentiator (Elementor loads more). Recommendation must cite the evidence.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Plugins and Function', topic: 'Essential plugins, forms, SEO, security',
      problems: [
        { title: 'The Essential Stack', points: 100, difficulty: 'Core',
          description: 'Install and configure a production plugin stack: contact form (with working email test), SEO plugin (meta titles set for all pages), caching, and a security/backup plugin. Document each configuration decision and one setting you deliberately changed from default.\nCourse link: Week 5 - the professional plugin baseline.',
          refs: [['WP plugin directory', 'https://wordpress.org/plugins/']],
          solution: 'Form email must be proven delivered. The changed-default answers reveal whether they read settings or clicked next-next.' },
        { title: 'Mini WooCommerce', points: 110, difficulty: 'Boss',
          description: 'Add WooCommerce with 5 real products (images, prices in PKR, categories), configure cash-on-delivery (the Pakistani default), a shipping zone, and complete one full test order. Report the customer journey with screenshots and 2 UX improvements you would make.\nCourse link: Week 6 - e-commerce foundations.',
          refs: [['WooCommerce docs', 'https://woocommerce.com/documentation/woocommerce/']],
          solution: 'COD configured and a completed test order are the pass gates. UX suggestions graded on specificity.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Client-Grade Polish', topic: 'Performance, responsive QA, launch prep',
      problems: [
        { title: 'Speed Clinic', points: 110, difficulty: 'Core',
          description: 'Audit your site with PageSpeed Insights: record the mobile score, apply 4 improvements (image compression, caching, unused plugins, lazy-loading), and show the score delta with before/after reports. Explain why mobile speed matters for Pakistani users specifically.\nCourse link: Week 7 - performance optimization.',
          refs: [['PageSpeed Insights', 'https://pagespeed.web.dev/']],
          solution: 'Any genuine measured improvement passes; the process matters more than the score. The Pakistan answer: mobile-first, slower networks.' },
        { title: 'The Launch Checklist', points: 120, difficulty: 'Boss',
          description: 'Produce a professional pre-launch QA: responsive check on 3 viewports (screenshots), all links tested, forms tested, 404 page styled, favicon, and a written handover checklist a client could verify. Run it on your site and mark pass/fail per item honestly.\nCourse link: Week 8 - launch discipline.',
          refs: [['Website launch checklist', 'https://wordpress.org/documentation/article/faq-installation/']],
          solution: 'Honest fails are worth more than fake passes. Responsive screenshots at real breakpoints are mandatory.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Client Delivery', topic: 'Complete client website project',
      problems: [
        { title: 'The Client Project', points: 200, difficulty: 'Boss',
          description: 'Deliver a complete website for a real or realistic Pakistani client (academy, clinic, boutique): 5+ pages, brand-consistent design, working contact form, SEO basics, speed-optimized, plus a client manual (how to edit content) and a maintenance proposal with monthly pricing. This is your portfolio and your sales template in one.\nCourse link: Weeks 1-8 combined.',
          refs: [],
          solution: 'Rubric: build quality (35%), performance + QA evidence (25%), client manual clarity (20%), maintenance proposal realism (20%).' },
      ] },
  ],
},
{
  key: 'st02-graphic-design', course_code: 'ST-02', title: 'Graphic Designing',
  description: '2-month quest: from design fundamentals to a client-ready brand identity system.',
  pass_mark: 60, titleNames: ['Pixel Novice', 'Layout Learner', 'Color Crafter', 'Brand Builder', 'Visual Designer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Eyes Before Hands', topic: 'Design principles: hierarchy, contrast, alignment',
      problems: [
        { title: 'Design Autopsy', points: 60, difficulty: 'Basic',
          description: 'Collect 3 good and 3 bad real designs (local shop banners, posters, social posts). For each, annotate hierarchy, contrast, alignment, proximity, and whitespace - marking exactly where principles are honored or violated. PDF with annotations drawn on the images.\nCourse link: Week 1 - the CRAP principles as a seeing tool.',
          refs: [['Design principles overview', 'https://www.canva.com/learn/design-elements-principles/']],
          solution: 'Annotations must point at specific spots, not general vibes. Local examples encouraged - grade observation sharpness.' },
        { title: 'Redesign the Worst', points: 80, difficulty: 'Core',
          description: 'Take your worst-found design and redesign it in any tool (Canva/Figma/Illustrator) applying the violated principles. Side-by-side with a change log: each edit mapped to the principle it fixes.\nCourse link: Week 1-2 - principles in practice.',
          refs: [['Canva design school', 'https://www.canva.com/learn/']],
          solution: 'The change-log mapping is the assignment. A prettier design without principle mapping earns partial credit only.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Type and Color', topic: 'Typography systems and color theory',
      problems: [
        { title: 'Type Specimen', points: 90, difficulty: 'Core',
          description: 'Build a typography system for a brand: pick a font pairing (justify with contrast/mood), define a scale (h1-h3, body, caption with exact sizes), and demonstrate it in a one-page specimen. Include one pairing that fails and why.\nCourse link: Week 3 - typographic hierarchy and pairing.',
          refs: [['Google Fonts pairing', 'https://fonts.google.com/knowledge']],
          solution: 'A modular scale with stated ratios shows mastery. The failed pairing must fail for an articulable reason (two display fonts, etc.).' },
        { title: 'Palette with Purpose', points: 100, difficulty: 'Boss',
          description: 'Create 2 complete palettes (primary, secondary, neutrals, semantic colors) for two opposite brands: a children\'s academy and a law firm. Test text contrast for accessibility (WCAG AA, show the checker results) and explain each color psychology choice.\nCourse link: Week 4 - color theory + accessibility.',
          refs: [['Contrast checker', 'https://webaim.org/resources/contrastchecker/'], ['Color theory basics', 'https://www.interaction-design.org/literature/topics/color-theory']],
          solution: 'AA-passing text combos are mandatory evidence. Psychology claims must fit the audience, not generic "blue = trust" recitation.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'The Working Designer', topic: 'Social media kits, print, mockups',
      problems: [
        { title: 'Social Kit Sprint', points: 100, difficulty: 'Core',
          description: 'For a real local business, design a 6-piece social kit: profile/cover, 3 post templates (announcement, product, testimonial), and a story template - all on one grid system and palette. Present in realistic mockups.\nCourse link: Week 5 - template systems and consistency.',
          refs: [['Free mockups', 'https://www.freepik.com/']],
          solution: 'System consistency across all 6 pieces is the grade - swap the content and it should still look like one brand.' },
        { title: 'Print Ready', points: 110, difficulty: 'Boss',
          description: 'Design a business card and A5 flyer for the same brand, prepared for real printing: CMYK, 3mm bleed, crop marks, 300 DPI, exported as print PDF. Include a screenshot proving each technical setting and a 5-line note to the print shop.\nCourse link: Week 6 - print production technicals.',
          refs: [['Print bleed explained', 'https://www.printplace.com/blog/full-bleed-printing/']],
          solution: 'Bleed and CMYK evidence are pass gates - RGB/no-bleed files fail regardless of beauty. This is the most common junior mistake.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Identity Systems', topic: 'Logo design and brand guidelines',
      problems: [
        { title: 'Logo Process', points: 110, difficulty: 'Core',
          description: 'Design a logo the professional way: 10 rough sketches (photograph them), 3 digital directions, 1 refined final with black/white and reversed versions, tested at 16px and billboard scale. Document the full process - clients buy process, not luck.\nCourse link: Week 7 - logo methodology.',
          refs: [['Logo design principles', 'https://99designs.com/blog/tips/logo-design-tips/']],
          solution: 'The sketch photos are mandatory. Scale tests reveal weak marks. Grade process rigor over personal taste.' },
        { title: 'The Mini Brand Book', points: 120, difficulty: 'Boss',
          description: 'Compile a 6-8 page brand guideline: logo usage and misuse (show 4 forbidden treatments), palette with codes, typography system, imagery style, and one applied example. This document is what turns a logo into a paid identity project.\nCourse link: Week 8 - brand guidelines.',
          refs: [['Brand guideline examples', 'https://brandingstyleguides.com/']],
          solution: 'Misuse examples are the professional marker. Codes must be exact (hex/CMYK). Grade completeness and clarity.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Brand Delivery', topic: 'Complete identity project',
      problems: [
        { title: 'Full Identity Project', points: 200, difficulty: 'Boss',
          description: 'Deliver a complete brand identity for a real or realistic client: logo suite, brand book, social kit, one print item, and a presentation deck pitching the work as you would to the client - including your pricing. Everything consistent, everything justified.\nCourse link: Weeks 1-8 combined - your portfolio centerpiece.',
          refs: [],
          solution: 'Rubric: system consistency (30%), craft quality (30%), brand book completeness (20%), pitch and pricing realism (20%).' },
      ] },
  ],
},
{
  key: 'st03-uiux', course_code: 'ST-03', title: 'UI/UX Designing',
  description: '2-month quest: from user research to a tested, developer-ready Figma prototype.',
  pass_mark: 60, titleNames: ['UX Explorer', 'Wireframe Weaver', 'Flow Designer', 'Prototype Pro', 'Product Designer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Users First', topic: 'UX research: interviews, personas, journeys',
      problems: [
        { title: 'Real User Interviews', points: 60, difficulty: 'Basic',
          description: 'Pick an everyday app problem (ordering food, paying bills, bus booking). Interview 3 real people using open questions (script included), then synthesize: top 5 pain points with supporting quotes. No solutions yet - discipline is the lesson.\nCourse link: Week 1 - research before pixels.',
          refs: [['User interview guide (NN/g)', 'https://www.nngroup.com/articles/user-interviews/']],
          solution: 'Verbatim quotes prove real interviews. Reject leading questions in the script. Solutions appearing = principle missed.' },
        { title: 'Persona and Journey', points: 80, difficulty: 'Core',
          description: 'From your interviews, build 1 evidence-based persona (goals, frustrations, context - every claim traceable to an interview) and map their current journey with emotion curve, marking the 2 worst moments as design opportunities.\nCourse link: Week 2 - personas and journey mapping.',
          refs: [['Journey mapping 101', 'https://www.nngroup.com/articles/journey-mapping-101/']],
          solution: 'Traceability is the grade: invented persona details fail. The two opportunity moments should be genuinely painful ones.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'Structure and Flow', topic: 'Information architecture, user flows, wireframes',
      problems: [
        { title: 'Flows Before Screens', points: 90, difficulty: 'Core',
          description: 'For your chosen problem: define the core task, map the user flow (every screen, decision, and error state as a flowchart), then wireframe the 5 key screens low-fidelity in Figma. Grey boxes only - color is banned this week.\nCourse link: Week 3 - flows and low-fi wireframing.',
          refs: [['Figma basics', 'https://help.figma.com/hc/en-us/categories/360002042553'], ['User flows guide', 'https://www.nngroup.com/articles/user-flows/']],
          solution: 'Error states in the flow separate professionals from beginners. Ban enforcement: any styling = redo.' },
        { title: 'The IA Card Sort', points: 100, difficulty: 'Boss',
          description: 'Take a cluttered real app or site menu (a bank, a government portal). List its 20+ items, run a card sort with 3 people (physical or online), and propose a reorganized IA with rationale. Show the before/after site map.\nCourse link: Week 4 - information architecture.',
          refs: [['Card sorting (NN/g)', 'https://www.nngroup.com/articles/card-sorting-definition/']],
          solution: 'Participant groupings must visibly drive the new IA. Look for sensible label renaming, not just reshuffling.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Interface Craft', topic: 'Visual design, components, design systems in Figma',
      problems: [
        { title: 'High-Fidelity Screens', points: 100, difficulty: 'Core',
          description: 'Take your 5 wireframes to high fidelity: type scale, 8pt spacing grid, color styles, and Figma components with variants (buttons: default/hover/disabled). Screens must use ONLY defined styles - no detached one-offs.\nCourse link: Week 5 - visual systems in Figma.',
          refs: [['Figma components', 'https://help.figma.com/hc/en-us/articles/360038662654'], ['8pt grid', 'https://spec.fm/specifics/8-pt-grid']],
          solution: 'Open the Figma file: styles panel and component variants are the evidence. Detached instances = deductions.' },
        { title: 'Accessibility Pass', points: 110, difficulty: 'Boss',
          description: 'Audit your screens: contrast (AA), touch targets (44px+), focus states, and text scaling at 200%. Fix failures and document each with before/after. Then the empathy test: navigate a competitor app with eyes closed using a screen reader for 5 minutes and write what you felt.\nCourse link: Week 6 - accessible design.',
          refs: [['WCAG quick ref', 'https://www.w3.org/WAI/WCAG22/quickref/'], ['Contrast checker', 'https://webaim.org/resources/contrastchecker/']],
          solution: 'Measured evidence per check. The screen-reader reflection is graded on sincerity - it changes designers permanently.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Prototype and Test', topic: 'Interactive prototypes and usability testing',
      problems: [
        { title: 'Click-Through Prototype', points: 110, difficulty: 'Core',
          description: 'Wire your screens into an interactive Figma prototype covering the full core task including one error path, with sensible transitions. Share the prototype link and a 60-second screen recording of the happy path.\nCourse link: Week 7 - prototyping.',
          refs: [['Figma prototyping', 'https://help.figma.com/hc/en-us/articles/360040314193']],
          solution: 'The error path interaction is the differentiator. Check overlays/back behavior work, not just forward taps.' },
        { title: 'Watch Them Struggle', points: 120, difficulty: 'Boss',
          description: 'Run moderated usability tests with 3 people: task script, think-aloud, no helping. Record findings: completion, time, confusions with severity ratings. Fix the top 2 issues and show the redesigned screens. This loop IS the job.\nCourse link: Week 8 - usability testing and iteration.',
          refs: [['Usability testing 101', 'https://www.nngroup.com/articles/usability-testing-101/']],
          solution: 'Severity-rated findings and the two evidenced fixes are the pass bar. "Everyone loved it" = tests were led.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Product Case Study', topic: 'End-to-end portfolio case study',
      problems: [
        { title: 'The Case Study', points: 200, difficulty: 'Boss',
          description: 'Package your entire project as a hiring-grade case study: problem, research evidence, IA/flows, design system, final UI, testing results, iterations, and outcomes - as a PDF plus the live Figma link. Write for a hiring manager with 3 minutes.\nCourse link: Weeks 1-8 combined - this document gets you interviews.',
          refs: [['UX case study guide', 'https://www.casestudy.club/journal']],
          solution: 'Rubric: evidence-driven narrative (35%), craft (30%), testing honesty (20%), presentation economy (15%).' },
      ] },
  ],
},
{
  key: 'st04-data-analytics', course_code: 'ST-04', title: 'Data Analytics Specialist Track',
  description: '2-month quest: the full analyst workflow - Python, SQL, statistics, and executive storytelling.',
  pass_mark: 60, titleNames: ['Data Rookie', 'Query Analyst', 'Stat Sleuth', 'Insight Lead', 'Analytics Specialist'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Analyst Python', topic: 'pandas mastery for analysis',
      problems: [
        { title: 'The Sales Deep-Dive', points: 70, difficulty: 'Basic',
          description: 'Using a Kaggle retail dataset: load, clean (nulls, dtypes, duplicates - documented), and answer 5 business questions with pandas (top products, monthly trend, weekday patterns, basket size, city comparison). Code + outputs + one-line answers.\nCourse link: Week 1 - pandas as the analyst\'s primary tool.',
          refs: [['Superstore dataset', 'https://www.kaggle.com/datasets/vivek468/superstore-dataset-final'], ['pandas docs', 'https://pandas.pydata.org/docs/']],
          solution: 'Cleaning must be documented with counts. Answers must be exact numbers from code, not chart eyeballing.' },
        { title: 'GroupBy Gymnastics', points: 90, difficulty: 'Core',
          description: 'Produce a pivot analysis: revenue by region x category with subtotals, month-over-month growth per region, and top-3 products within each category (groupby + head trick). Explain when pivot_table beats groupby.\nCourse link: Week 2 - advanced aggregation patterns.',
          refs: [['pandas groupby guide', 'https://pandas.pydata.org/docs/user_guide/groupby.html']],
          solution: 'The within-group top-N pattern (groupby-apply or sort+groupby+head) is the skill test. MoM growth needs pct_change or shift.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'SQL for Analysts', topic: 'Analytical SQL: windows, CTEs, cohorts',
      problems: [
        { title: 'CTE Storylines', points: 100, difficulty: 'Core',
          description: 'Rewrite 3 nested-subquery monsters as readable CTE chains on any SQL dataset, then build one multi-step analysis (filter -> aggregate -> rank) as a single CTE pipeline with comments narrating each step.\nCourse link: Week 3 - readable analytical SQL.',
          refs: [['CTEs explained', 'https://learnsql.com/blog/what-is-cte/']],
          solution: 'Readability is the grade: each CTE named for what it holds. The narrated pipeline should read like a paragraph.' },
        { title: 'Cohort Retention', points: 120, difficulty: 'Boss',
          description: 'The interview classic: build a monthly cohort retention table in SQL (first-purchase cohort x months-since, with retention %). Visualize as a heatmap (any tool) and write 3 sentences on what the retention pattern means for the business.\nCourse link: Week 4 - cohort analysis.',
          refs: [['Cohort analysis guide', 'https://mode.com/blog/cohort-analysis-helps-look-ahead/']],
          solution: 'Correct cohorting (MIN purchase month per customer) is the crux. Diagonal reading of the heatmap in their interpretation earns full marks.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Statistics That Matter', topic: 'Distributions, hypothesis tests, correlation traps',
      problems: [
        { title: 'The A/B Verdict', points: 110, difficulty: 'Core',
          description: 'Simulate or take an A/B dataset (two landing pages, conversion rates). Run the appropriate significance test in Python, report p-value and confidence interval, and write the verdict a marketing manager would understand - including what p-value does NOT mean.\nCourse link: Week 5 - hypothesis testing for business.',
          refs: [['A/B testing statistics', 'https://www.evanmiller.org/ab-testing/']],
          solution: 'Correct test choice (proportions z-test/chi-square) and the p-value misconception paragraph are the pass gates.' },
        { title: 'Correlation Crime Scene', points: 120, difficulty: 'Boss',
          description: 'Find or construct 3 correlation traps: a spurious correlation, a confounder case, and Simpson\'s paradox (aggregated vs grouped trend reversal - show both charts). Explain each and state the business decision each trap would have ruined.\nCourse link: Week 6 - causal thinking.',
          refs: [['Spurious correlations', 'https://www.tylervigen.com/spurious-correlations'], ['Simpson\'s paradox', 'https://en.wikipedia.org/wiki/Simpson%27s_paradox']],
          solution: 'A working Simpson\'s demonstration (real or constructed data, both charts) is the boss criterion.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Executive Communication', topic: 'Dashboards and data storytelling',
      problems: [
        { title: 'The One-Screen KPI Story', points: 120, difficulty: 'Core',
          description: 'Design a single-screen executive dashboard (Power BI/Tableau Public/Looker Studio) for your dataset: 4 KPIs with period comparison, one trend, one breakdown, one alert-worthy highlight - every element answering "so what?". Include the 5-second test result: what does a viewer grasp in 5 seconds?\nCourse link: Week 7 - executive dashboard design.',
          refs: [['Looker Studio (free)', 'https://lookerstudio.google.com/'], ['Dashboard design', 'https://www.storytellingwithdata.com/blog']],
          solution: 'The 5-second test with a real person is required evidence. Chart-junk and unlabeled deltas are the common deductions.' },
        { title: 'The Recommendation Deck', points: 130, difficulty: 'Boss',
          description: 'Turn your full analysis into a 6-slide decision deck: situation, 3 evidence slides (one chart each, assertion-style titles), recommendation with quantified impact, and risks/assumptions. Assertion titles are sentences ("Karachi drives 60% of growth"), not labels ("Sales by City").\nCourse link: Week 8 - analytics storytelling.',
          refs: [['Assertion-evidence slides', 'https://www.assertion-evidence.com/']],
          solution: 'Every title must be a claim; every claim must match its chart. Quantified recommendation is the pass gate.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Analyst Portfolio Project', topic: 'End-to-end business analysis',
      problems: [
        { title: 'The Full Analysis', points: 200, difficulty: 'Boss',
          description: 'Complete analyst engagement on a fresh dataset: business questions -> SQL + Python analysis -> statistical validation of one key claim -> dashboard -> recommendation deck -> appendix with reproducible code. One PDF + links. This is the portfolio piece that gets analyst interviews in 2026.\nCourse link: Weeks 1-8 combined.',
          refs: [['Kaggle datasets', 'https://www.kaggle.com/datasets']],
          solution: 'Rubric: technical correctness (35%), statistical rigor on the key claim (20%), dashboard craft (20%), deck persuasiveness (25%).' },
      ] },
  ],
},
{
  key: 'st05-genai-eng', course_code: 'ST-05', title: 'Generative AI Engineering',
  description: '2-month quest: engineering real LLM applications - RAG, evaluation, and production thinking.',
  pass_mark: 60, titleNames: ['API Cadet', 'Prompt Engineer', 'RAG Builder', 'Eval Master', 'GenAI Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'LLM API Engineering', topic: 'APIs, streaming, error handling, cost control',
      problems: [
        { title: 'The Robust Client', points: 70, difficulty: 'Basic',
          description: 'Write a Python LLM client (Gemini/Groq free tier) with: retries with exponential backoff, timeout handling, token counting, and per-call cost logging to a file. Prove each safeguard by forcing a failure.\nCourse link: Week 1 - production API hygiene.',
          refs: [['Gemini API docs', 'https://ai.google.dev/gemini-api/docs'], ['Backoff pattern', 'https://en.wikipedia.org/wiki/Exponential_backoff']],
          solution: 'Forced-failure evidence for each safeguard is the pass bar. Cost log must accumulate across calls.' },
        { title: 'Structured Output Contract', points: 90, difficulty: 'Core',
          description: 'Build an extraction endpoint: messy job-ad text in -> validated JSON out (title, skills[], salary_range, city) using schema-constrained prompting + a Pydantic validation layer + one retry-on-invalid. Test on 5 real job ads including one that should partially fail.\nCourse link: Week 2 - reliable structured outputs.',
          refs: [['Pydantic docs', 'https://docs.pydantic.dev/'], ['Structured outputs', 'https://ai.google.dev/gemini-api/docs/structured-output']],
          solution: 'The validation-retry loop is the engineering skill. Partial-failure handling (nulls vs crash) shows maturity.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'RAG Engineering', topic: 'Chunking, embeddings, vector search, grounding',
      problems: [
        { title: 'Chunking Lab', points: 110, difficulty: 'Core',
          description: 'Take a 20+ page real document (prospectus, policy, manual). Implement 2 chunking strategies (fixed-size with overlap vs structure-aware) and compare retrieval quality on 5 questions: which strategy surfaces the right chunk more often, and why?\nCourse link: Week 3 - chunking, the most underrated RAG decision.',
          refs: [['Chunking strategies', 'https://www.pinecone.io/learn/chunking-strategies/']],
          solution: 'A per-question hit table per strategy is required. Structure-aware should usually win on headed documents - discussion matters.' },
        { title: 'Full RAG Service', points: 130, difficulty: 'Boss',
          description: 'Build a complete RAG pipeline: embed chunks (free embedding API + chromadb/FAISS), retrieve top-k, answer with citations to chunk IDs, refuse when retrieval confidence is low. Test: 6 answerable, 2 unanswerable, 1 adversarial ("ignore your instructions..."). Report all outputs.\nCourse link: Week 4 - grounded generation with refusal.',
          refs: [['ChromaDB docs', 'https://docs.trychroma.com/'], ['RAG best practices', 'https://docs.anthropic.com/en/docs/build-with-claude/retrieval-augmented-generation']],
          solution: 'Refusal on unanswerables and surviving the injection attempt are pass gates. Citations must map to real chunks.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Evaluation Engineering', topic: 'Golden sets, LLM-as-judge, regression testing',
      problems: [
        { title: 'The Golden Set', points: 120, difficulty: 'Core',
          description: 'Create a 20-case golden test set for your RAG service (question, expected answer/behaviour, category). Build a runner that scores each run (exact/contains/judge) and outputs a scorecard. Run twice with different top-k and report the delta.\nCourse link: Week 5 - systematic evaluation.',
          refs: [['LLM evaluation guide', 'https://docs.anthropic.com/en/docs/build-with-claude/develop-tests']],
          solution: 'The scored A/B (top-k change) proves the harness works. Categories should include refusal cases.' },
        { title: 'LLM-as-Judge, Audited', points: 130, difficulty: 'Boss',
          description: 'Implement an LLM judge scoring answer quality 1-5 with a rubric prompt. Then audit the judge: score 10 answers yourself blind, compute agreement with the judge, and report where and why they disagree. Trusting an unaudited judge is the field\'s current sin.\nCourse link: Week 6 - meta-evaluation.',
          refs: [['LLM-as-judge paper', 'https://arxiv.org/abs/2306.05685']],
          solution: 'The human-vs-judge agreement number is the deliverable. Disagreement analysis (verbosity bias, position bias) earns top marks.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Production Thinking', topic: 'Safety, caching, monitoring, cost at scale',
      problems: [
        { title: 'The Safety Layer', points: 130, difficulty: 'Core',
          description: 'Add to your service: input guardrails (injection patterns, PII detection with regex+LLM hybrid), output checks (no system-prompt leakage), and a red-team report - 8 attack attempts of your own design with results. Attack your own system before users do.\nCourse link: Week 7 - AI application security.',
          refs: [['Prompt injection primer', 'https://www.lakera.ai/blog/guide-to-prompt-injection'], ['OWASP LLM Top 10', 'https://owasp.org/www-project-top-10-for-large-language-model-applications/']],
          solution: 'The 8-attack red-team with honest pass/fail is the core. At least one attack should succeed and get patched.' },
        { title: 'Scale Economics', points: 140, difficulty: 'Boss',
          description: 'Your RAG bot goes to 10,000 queries/day. Engineer the plan: semantic caching design (with hit-rate estimate from your golden set), model tiering (cheap model for easy queries, escalation rules), and a monthly cost model comparing naive vs engineered - with the monitoring metrics you would track.\nCourse link: Week 8 - GenAI systems at scale.',
          refs: [['Semantic caching', 'https://www.pinecone.io/learn/semantic-caching/']],
          solution: 'Escalation rules must be concrete (confidence/length/category based). Cost model with stated assumptions passes; magic numbers fail.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Production RAG Product', topic: 'Complete GenAI application',
      problems: [
        { title: 'Ship It', points: 220, difficulty: 'Boss',
          description: 'Deliver a deployable GenAI application for a real domain (academy assistant, legal-doc helper, medical-info bot with disclaimers): full RAG, safety layer, golden-set eval with scores, cost model, README with architecture diagram, and a 3-minute demo video. Code in a GitHub repo.\nCourse link: Weeks 1-8 combined - a genuinely hireable portfolio project.',
          refs: [],
          solution: 'Rubric: works end-to-end (30%), eval rigor (25%), safety evidence (20%), engineering quality (15%), demo clarity (10%).' },
      ] },
  ],
},
{
  key: 'st06-ai-agents', course_code: 'ST-06', title: 'AI Agents & Automation Engineering',
  description: '2-month quest: from tool-calling basics to multi-step autonomous agents with guardrails.',
  pass_mark: 60, titleNames: ['Tool Caller', 'Loop Runner', 'Agent Smith', 'Orchestrator', 'Agent Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Tools in Hand', topic: 'Function calling fundamentals',
      problems: [
        { title: 'First Function Call', points: 70, difficulty: 'Basic',
          description: 'Implement function calling with a free-tier LLM: define 2 tools (get_weather stub, calculate) with JSON schemas, let the model choose, execute, and return the result to the model for a final answer. Trace the full message loop in your report.\nCourse link: Week 1 - the tool-calling loop.',
          refs: [['Gemini function calling', 'https://ai.google.dev/gemini-api/docs/function-calling'], ['Groq tool use', 'https://console.groq.com/docs/tool-use']],
          solution: 'The traced loop (model->tool_call->execution->model->answer) is the deliverable. Check schemas are honest JSON Schema.' },
        { title: 'The Tool Router', points: 90, difficulty: 'Core',
          description: 'Give the model 5 tools (search stub, calculator, date, unit converter, none-needed). Test 10 varied queries and build a confusion table: which tool was chosen vs which was right. Improve the worst tool description and show the fix.\nCourse link: Week 2 - tool selection quality.',
          refs: [['Tool use best practices', 'https://docs.anthropic.com/en/docs/build-with-claude/tool-use']],
          solution: 'The description-improvement experiment is the point: tool docs ARE the interface. Before/after selection accuracy required.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'The Agent Loop', topic: 'ReAct pattern, memory, termination',
      problems: [
        { title: 'ReAct From Scratch', points: 110, difficulty: 'Core',
          description: 'Implement a ReAct agent loop without frameworks: thought -> action -> observation cycles with a max-step limit and explicit final-answer detection. Run it on a 3-step task (e.g. "find X, compute Y from it, format Z") and include the full trace.\nCourse link: Week 3 - the agent loop, demystified.',
          refs: [['ReAct paper', 'https://arxiv.org/abs/2210.03629']],
          solution: 'No LangChain - the raw loop is the lesson. Max-step guard and stop condition must be visible in code and trace.' },
        { title: 'Agent That Remembers', points: 130, difficulty: 'Boss',
          description: 'Add memory: short-term (conversation window with summarization when long) and a simple long-term store (facts file the agent reads/writes via tools). Demonstrate: teach it a fact in session 1, restart, and have it recall in session 2. Discuss what should NOT be memorized.\nCourse link: Week 4 - agent memory architectures.',
          refs: [['Memory in agents (LangChain concepts)', 'https://python.langchain.com/docs/concepts/memory/']],
          solution: 'The restart-recall demo is the pass gate. The should-not-memorize discussion (PII, stale facts) shows judgment.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Agents That Act', topic: 'Real-world integration: files, web, APIs',
      problems: [
        { title: 'The File Clerk Agent', points: 120, difficulty: 'Core',
          description: 'Build an agent with file tools (list, read, write - sandboxed to one folder) that can: organize 15 messy files into folders by type/topic and produce an index document. Log every action for audit. Safety: it must refuse operations outside its sandbox - prove it.\nCourse link: Week 5 - agents with real side effects.',
          refs: [['Python pathlib', 'https://docs.python.org/3/library/pathlib.html']],
          solution: 'The sandbox-escape refusal test is mandatory. Audit log completeness is the engineering grade.' },
        { title: 'Research Agent', points: 140, difficulty: 'Boss',
          description: 'An agent that answers "compare X and Y" questions by: searching (any free search API/wrapper), reading 3+ sources, extracting claims with citations, and producing a comparison table with a confidence note per claim. Test on a question whose answer you can verify. Report hallucination incidents honestly.\nCourse link: Week 6 - research agent patterns.',
          refs: [['Tavily search API (free tier)', 'https://tavily.com/']],
          solution: 'Per-claim citations checkable against sources are the bar. Honest hallucination reporting earns marks, hiding it loses them.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Orchestration and Guardrails', topic: 'Multi-agent patterns, approvals, evaluation',
      problems: [
        { title: 'The Two-Agent Newsroom', points: 130, difficulty: 'Core',
          description: 'Build a writer-agent + critic-agent pipeline: writer drafts a piece from a brief, critic reviews against a rubric and returns structured feedback, writer revises - max 2 rounds. Show all intermediate artifacts and compare draft 1 vs final quality.\nCourse link: Week 7 - multi-agent collaboration.',
          refs: [['Multi-agent patterns (Anthropic)', 'https://www.anthropic.com/research/building-effective-agents']],
          solution: 'Structured critic feedback (not vibes) and measurable improvement between rounds are the criteria.' },
        { title: 'Human-in-the-Loop Gate', points: 140, difficulty: 'Boss',
          description: 'Take any agent you built and add approval gates for consequential actions (file writes, sends): the agent proposes, a human approves/rejects/edits via console, and rejections feed back as observations. Demonstrate all 3 paths, then write your agent-autonomy policy: what may this agent do unsupervised, and why?\nCourse link: Week 8 - deploying agents responsibly.',
          refs: [['Building effective agents', 'https://www.anthropic.com/research/building-effective-agents']],
          solution: 'All three demonstrated paths (approve/reject/edit) are the pass gate. The autonomy policy is graded on reasoned boundaries.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Autonomous Assistant', topic: 'Complete agent product',
      problems: [
        { title: 'Your Agent, Shipped', points: 220, difficulty: 'Boss',
          description: 'Deliver a working agent for a real workflow (study assistant that builds revision packs, business assistant that drafts and files documents, data agent that produces weekly reports): 3+ tools, memory, guardrails with approval gates, an evaluation of 10 tasks with success rate, and a post-mortem of its worst failure. Repo + demo video.\nCourse link: Weeks 1-8 combined.',
          refs: [],
          solution: 'Rubric: reliable task completion (35%), guardrail evidence (25%), evaluation honesty incl. failure post-mortem (25%), code quality (15%).' },
      ] },
  ],
},
{
  key: 'st07-ml-fundamentals', course_code: 'ST-07', title: 'Machine Learning Fundamentals',
  description: '2-month quest: the complete classical ML toolkit with mathematical intuition and rigorous practice.',
  pass_mark: 60, titleNames: ['Gradient Novice', 'Model Mechanic', 'Ensemble Rider', 'Tuning Expert', 'ML Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Under the Hood', topic: 'Gradient descent and linear models from scratch',
      problems: [
        { title: 'Gradient Descent by Hand', points: 80, difficulty: 'Basic',
          description: 'Implement linear regression with gradient descent in pure NumPy: loss curve plotted, learning-rate experiment (too small/right/too large - show all three curves), and final weights compared against sklearn\'s. Understanding this loop is understanding half of ML.\nCourse link: Week 1 - optimization intuition.',
          refs: [['Gradient descent visual', 'https://developers.google.com/machine-learning/crash-course/linear-regression/gradient-descent']],
          solution: 'The three learning-rate curves (crawl/converge/diverge) are the pass evidence. Weights should match sklearn to ~2 decimals.' },
        { title: 'Regularization Reality', points: 100, difficulty: 'Core',
          description: 'On a small noisy dataset, fit polynomial regression degrees 1-15: plot train vs validation error to expose overfitting, then apply Ridge and Lasso and show how they tame degree-15. Explain L1 vs L2 including why Lasso zeros features.\nCourse link: Week 2 - bias-variance and regularization.',
          refs: [['Bias-variance (scikit-learn)', 'https://scikit-learn.org/stable/auto_examples/model_selection/plot_underfitting_overfitting.html']],
          solution: 'The U-shaped validation curve and Lasso coefficient zeros are the evidence. The geometric L1 corner explanation earns bonus.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'The Classics', topic: 'Trees, KNN, SVM, Naive Bayes',
      problems: [
        { title: 'Four-Model Tournament', points: 110, difficulty: 'Core',
          description: 'On one classification dataset (bank marketing / heart disease): train DecisionTree, KNN, SVM, NaiveBayes with identical CV protocol. Report F1 per model, decision-boundary plots on 2 features, and a paragraph on WHY the winner suits this data\'s shape.\nCourse link: Week 3 - algorithm intuitions.',
          refs: [['Heart disease dataset', 'https://www.kaggle.com/datasets/fedesoriano/heart-failure-prediction'], ['Classifier comparison', 'https://scikit-learn.org/stable/auto_examples/classification/plot_classifier_comparison.html']],
          solution: 'Identical CV protocol is the rigor test. The "why" paragraph must reference data properties (scale, boundaries, feature independence).' },
        { title: 'Explain the Tree', points: 120, difficulty: 'Boss',
          description: 'Train a depth-limited decision tree on loan/heart data, export the tree diagram, and translate its top 3 paths into plain-language rules a bank officer could apply. Then break it: find one person the rules judge unfairly and discuss.\nCourse link: Week 4 - interpretability and its limits.',
          refs: [['Tree visualization', 'https://scikit-learn.org/stable/modules/tree.html']],
          solution: 'Accurate path-to-rule translation is the skill. The fairness case must be a concrete instance from the data.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Ensemble Power', topic: 'Random forests, gradient boosting',
      problems: [
        { title: 'Forest vs Boosting', points: 120, difficulty: 'Core',
          description: 'Same dataset: RandomForest vs XGBoost/LightGBM. Compare CV scores, training time, and feature importances (do they agree?). Explain bagging vs boosting with a cricket-team analogy of your own making.\nCourse link: Week 5 - ensemble methods.',
          refs: [['XGBoost docs', 'https://xgboost.readthedocs.io/'], ['Ensembles (sklearn)', 'https://scikit-learn.org/stable/modules/ensemble.html']],
          solution: 'Importance-agreement analysis shows depth. The analogy must correctly capture parallel-independent vs sequential-corrective.' },
        { title: 'The Kaggle Gauntlet', points: 140, difficulty: 'Boss',
          description: 'Enter a live or playground Kaggle competition: baseline -> feature engineering (3+ engineered features, justified) -> tuned ensemble -> submission. Deliver your leaderboard screenshot, ablation table (score with/without each feature), and biggest lesson.\nCourse link: Week 6 - competitive practice.',
          refs: [['Kaggle competitions', 'https://www.kaggle.com/competitions']],
          solution: 'The ablation table is the grade - it proves which engineering actually helped. Leaderboard position is NOT the grade.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Rigor and Reality', topic: 'Tuning, pipelines, fairness, drift',
      problems: [
        { title: 'The Honest Pipeline', points: 130, difficulty: 'Core',
          description: 'Build a leak-proof sklearn Pipeline (imputation, encoding, scaling, model) tuned with GridSearchCV/RandomizedSearchCV inside cross-validation. Then demonstrate the crime: the same tuning done wrong (fit preprocessing on full data) and quantify the optimism gap.\nCourse link: Week 7 - pipelines and nested validation.',
          refs: [['sklearn Pipeline', 'https://scikit-learn.org/stable/modules/compose.html']],
          solution: 'The measured optimism gap between wrong and right protocols is the deliverable. Pipeline must contain ALL preprocessing.' },
        { title: 'Model on Trial', points: 140, difficulty: 'Boss',
          description: 'Audit your best model like a regulator: performance across subgroups (gender/age bands - find a gap and discuss), calibration curve, and a drift plan (which input stats to monitor, what triggers retraining). Real ML work is 20% fitting, 80% this.\nCourse link: Week 8 - responsible ML practice.',
          refs: [['Fairness in ML (Google)', 'https://developers.google.com/machine-learning/crash-course/fairness'], ['Calibration', 'https://scikit-learn.org/stable/modules/calibration.html']],
          solution: 'Subgroup table + calibration plot + concrete drift triggers. The discussion of an actual found gap is the boss criterion.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: The ML System', topic: 'Complete rigorous ML project',
      problems: [
        { title: 'End-to-End ML Project', points: 220, difficulty: 'Boss',
          description: 'A locally-relevant prediction problem (crop yield, AQI, prices, dropout risk): framing -> EDA -> leak-proof pipeline -> 3 models with nested CV -> ensemble -> fairness and calibration audit -> technical report + 1-page non-technical brief. Repo with reproducible code.\nCourse link: Weeks 1-8 combined.',
          refs: [['Pakistan open data', 'https://data.gov.pk/']],
          solution: 'Rubric: protocol rigor (30%), modeling quality (25%), audit depth (25%), communication (20%). Reproducibility spot-check: run their notebook.' },
      ] },
  ],
},
{
  key: 'st08-pytorch-dl', course_code: 'ST-08', title: 'Deep Learning with PyTorch',
  description: '2-month quest: tensors to trained networks - vision, transfer learning, and a deployed model.',
  pass_mark: 60, titleNames: ['Tensor Trainee', 'Backprop Believer', 'Network Builder', 'Vision Voyager', 'DL Engineer'],
  levels: [
    { no: 1, week: 1, session: 2, title: 'Tensors and Autograd', topic: 'PyTorch fundamentals',
      problems: [
        { title: 'Tensor Bootcamp', points: 80, difficulty: 'Basic',
          description: 'In a notebook: tensor creation/reshaping/broadcasting exercises (8 given operations), then use autograd to compute and verify the gradient of a small function by hand-check. Finish with requires_grad, .backward(), and .grad explained in your own words.\nCourse link: Week 1 - tensors and automatic differentiation.',
          refs: [['PyTorch tensors tutorial', 'https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html'], ['Autograd tutorial', 'https://pytorch.org/tutorials/beginner/basics/autogradqs_tutorial.html']],
          solution: 'The hand-verified gradient (simple polynomial) is the pass check. Own-words explanations catch copy-pasters.' },
        { title: 'Linear Regression, Torch Style', points: 100, difficulty: 'Core',
          description: 'Implement linear regression in raw PyTorch (manual training loop: forward, loss, backward, step, zero_grad) on synthetic data. Plot the loss curve and the fitted line. Then rewrite using nn.Linear + optim and confirm identical behavior. The training loop you write here is every training loop.\nCourse link: Week 2 - the canonical training loop.',
          refs: [['PyTorch optimization tutorial', 'https://pytorch.org/tutorials/beginner/basics/optimization_tutorial.html']],
          solution: 'zero_grad placement and loss-curve convergence are the checks. The raw-vs-nn equivalence proves understanding.' },
      ] },
    { no: 2, week: 3, session: 6, title: 'First Neural Networks', topic: 'MLPs, activation, loss functions, training craft',
      problems: [
        { title: 'MNIST From Scratch', points: 110, difficulty: 'Core',
          description: 'Build an MLP for MNIST: DataLoaders, 2 hidden layers, ReLU, CrossEntropyLoss, accuracy on a proper validation split, and a plot of train vs val loss per epoch. Show 5 misclassified digits and hypothesize why each fooled the network.\nCourse link: Week 3 - full training pipeline.',
          refs: [['MNIST with PyTorch', 'https://pytorch.org/tutorials/beginner/basics/quickstart_tutorial.html']],
          solution: '95%+ val accuracy is normal; grade the pipeline hygiene and the misclassification analysis quality.' },
        { title: 'Overfit It, Then Fix It', points: 130, difficulty: 'Boss',
          description: 'Deliberately overfit: train your MLP on only 500 examples until train accuracy is ~100% while validation collapses (show curves). Then rescue it three ways - dropout, weight decay, data augmentation - reporting each fix\'s effect separately. Diagnose-and-treat is the daily DL skill.\nCourse link: Week 4 - regularization in deep learning.',
          refs: [['Dropout paper (summary)', 'https://pytorch.org/docs/stable/generated/torch.nn.Dropout.html']],
          solution: 'The engineered overfit curves plus three separate ablations are the deliverable. Combined-fix-only reports fail the "separately" requirement.' },
      ] },
    { no: 3, week: 5, session: 10, title: 'Convolutional Vision', topic: 'CNNs and image pipelines',
      problems: [
        { title: 'CNN on CIFAR-10', points: 120, difficulty: 'Core',
          description: 'Build a CNN (3+ conv blocks with pooling and batchnorm) for CIFAR-10 with augmentation (flips, crops). Compare against your MLP on the same data - accuracy and parameter count - and explain WHY convolutions win on images (locality, weight sharing).\nCourse link: Week 5 - convolutional architectures.',
          refs: [['CIFAR-10 tutorial', 'https://pytorch.org/tutorials/beginner/blitz/cifar10_tutorial.html']],
          solution: 'The MLP-vs-CNN comparison with parameter counts is the concept test. Expect ~70%+ with augmentation on modest training.' },
        { title: 'See What It Sees', points: 130, difficulty: 'Boss',
          description: 'Open the black box: visualize first-layer filters, feature maps for one image through the network, and a Grad-CAM (or simple occlusion map) showing where the model looks for 3 predictions - including one wrong prediction. What was it looking at when it failed?\nCourse link: Week 6 - CNN interpretability.',
          refs: [['Grad-CAM explained', 'https://arxiv.org/abs/1610.02391']],
          solution: 'The wrong-prediction attention map with interpretation is the boss criterion. Any reasonable CAM/occlusion implementation accepted.' },
      ] },
    { no: 4, week: 7, session: 14, title: 'Transfer Learning', topic: 'Pretrained models and fine-tuning',
      problems: [
        { title: 'Stand on Giants', points: 130, difficulty: 'Core',
          description: 'Fine-tune a pretrained ResNet18 on a custom small dataset you collect (200+ images, 3+ classes - local fruits, vehicles, dishes). Compare: frozen-backbone vs full fine-tune vs training from scratch, on the same split. The result will teach you why nobody trains from scratch anymore.\nCourse link: Week 7 - transfer learning economics.',
          refs: [['Transfer learning tutorial', 'https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html']],
          solution: 'Three-way comparison table is the deliverable; scratch should lose badly on small data. Dataset collection effort counts.' },
        { title: 'The Deployment Gap', points: 140, difficulty: 'Boss',
          description: 'Take your fine-tuned model to the real world: export (TorchScript/ONNX), wrap in a minimal API or Gradio app, measure inference latency on CPU, then test with 10 fresh photos in bad conditions (lighting, angle) and report the accuracy drop from your test set. The gap IS the lesson.\nCourse link: Week 8 - from notebook to product.',
          refs: [['Gradio quickstart', 'https://www.gradio.app/guides/quickstart'], ['TorchScript intro', 'https://pytorch.org/tutorials/beginner/Intro_to_TorchScript_tutorial.html']],
          solution: 'The measured lab-vs-wild accuracy gap with example failures is the boss criterion. Latency numbers must be real measurements.' },
      ] },
    { no: 5, week: 8, session: 16, title: 'Capstone: Applied DL Product', topic: 'Complete deep learning project',
      problems: [
        { title: 'Deep Learning, Deployed', points: 220, difficulty: 'Boss',
          description: 'A locally-relevant vision project (crop disease from leaf photos, traffic counting, waste classification): dataset collection/curation with documentation -> transfer-learned model with proper splits and augmentation -> interpretability evidence -> deployed demo (Gradio/HF Spaces) -> report with limitations and ethics section. Repo + live demo link.\nCourse link: Weeks 1-8 combined - a genuinely impressive 2026 portfolio project.',
          refs: [['Hugging Face Spaces', 'https://huggingface.co/spaces'], ['PlantVillage dataset', 'https://www.kaggle.com/datasets/emmarex/plantdisease']],
          solution: 'Rubric: dataset rigor (25%), training correctness (25%), deployed demo works (25%), report honesty incl. ethics (25%).' },
      ] },
  ],
},
];
