'use strict';
const {test}=require('node:test');const assert=require('node:assert/strict');
const {resolveOffering}=require('../offering-policy');const {deliverRegistrationMail}=require('../registration-delivery');
const catalogue=[{code:'A',title:'Official title',price_pkr:12500},{code:'FREE',price_pkr:0}];
test('only a published paid offering has an authoritative fee',()=>{assert.equal(resolveOffering('a',catalogue).offer.price_pkr,12500);for(const code of ['','UNKNOWN','PATH','FREE'])assert.ok(resolveOffering(code,catalogue).error);assert.ok(resolveOffering('A',catalogue,[{code:'A',active:false}]).error);});
function fixture(){const r={id:1,status:{}};const writes=[];const store={Registrations:{delivery(id,state,details,kind){const value={state,...details};r.status[kind==='challan'?'delivery':'confirmation_delivery']=value;writes.push(state);return value;}},pendingPersist:async()=>{}};return{r,store,writes};}
test('skipped/rejected mail remains failed and retry is recoverable',async()=>{const f=fixture();const fail=await deliverRegistrationMail(f.store,{send:async()=>({sent:false,skipped:true})},f.r,{},{reference:'C1'});assert.equal(fail.state,'failed');const retry=await deliverRegistrationMail(f.store,{send:async()=>({sent:true,id:'test-provider-id'})},f.r,{},{reference:'C1'});assert.equal(retry.state,'provider_accepted');assert.deepEqual(f.writes,['queued','failed','queued','provider_accepted']);});
test('concurrent requests and a retry after provider acceptance send once',async()=>{const f=fixture();let count=0;const provider={send:async()=>{count++;await new Promise(r=>setTimeout(r,10));return{sent:true,id:'local-ack'};}};await Promise.all([1,2].map(()=>deliverRegistrationMail(f.store,provider,f.r,{},{reference:'C2'})));await deliverRegistrationMail(f.store,provider,f.r,{},{reference:'C2'});assert.equal(count,1);assert.equal(f.r.status.delivery.state,'provider_accepted');});
test('a durable queue write must succeed before contacting the provider',async()=>{const f=fixture();let called=false;f.store.pendingPersist=async()=>{throw Error('synthetic storage failure');};const outcome=await deliverRegistrationMail(f.store,{send:async()=>{called=true;}},f.r,{},{reference:'C3'});assert.equal(called,false);assert.equal(outcome.state,'failed');});
