'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict');
const {BASE,launch,context}=require('./browser-lib.cjs');
const rows=[];
async function check(id,fn){try{const actual=await fn();rows.push({id,status:'PASS',actual});}catch(e){rows.push({id,status:'FAIL',error:e.message});}console.log(JSON.stringify(rows.at(-1)));}
(async()=>{
 await check('RECOVERY-RETURN',async()=>{const destination='/open#course/cs105-javascript/lesson/1/practice/1';const r=await fetch(BASE+'/api/auth/forgot-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email:'observer@qa.invalid',returnTo:destination})});const d=await r.json();assert.ok(d.dev_link,'Synthetic development reset link is required');const token=new URL(d.dev_link).searchParams.get('token');const reset=await fetch(BASE+'/api/auth/reset-password',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,password:'LocalQa!2026'})});const result=await reset.json();assert.equal(result.return_to,destination);return {status:reset.status,destination:result.return_to};});
 const b=await launch();try{
 await check('FILTER-REFRESH-BACK-FORWARD',async()=>{const c=await context(b),p=await c.newPage();try{await p.goto(BASE+'/open#courses');await p.waitForFunction(()=>CATALOGUE.length);await p.locator('#cSearch').fill('Python');await p.waitForTimeout(200);await p.reload();await p.waitForFunction(()=>CATALOGUE.length&&document.querySelector('#cSearch').value==='python');await p.evaluate(()=>openCourse('cs104-python'));await p.waitForFunction(()=>location.hash==='#course/cs104-python');await p.goBack();await p.waitForFunction(()=>document.querySelector('#cSearch').value==='python'&&location.hash==='#courses');await p.goForward();await p.waitForFunction(()=>location.hash==='#course/cs104-python'&&CUR?.track.key==='cs104-python');return {search:'python',returnedCourse:'cs104-python'};}finally{await c.close();}});
 await check('VIDEO-TIMESTAMP-AND-GUIDE',async()=>{const c=await context(b,{width:390,height:844}),p=await c.newPage();try{await p.goto(BASE+'/open#course/cs104-python/lesson/3');await p.waitForFunction(()=>CUR?.track.key==='cs104-python');const src=await p.locator('#svVideoWrap iframe').getAttribute('src').catch(async()=>p.locator('iframe[src*="embed"]').first().getAttribute('src'));assert.equal(new URL(src).searchParams.get('start'),'548');const box=await p.locator('iframe[src*="embed"]').first().boundingBox();assert.ok(Math.abs(box.width/box.height-16/9)<.05);const track=await(await fetch(BASE+'/api/public/tracks/js-advanced')).json();const lesson=track.levels.find(l=>l.no===12);assert.equal(lesson.video_url,null);assert.match(lesson.resource_url,/developer.mozilla.org/);return {start:548,ratio:box.width/box.height,asyncGeneratorGuide:lesson.resource_url};}finally{await c.close();}});
 }finally{await b.close();}
 fs.writeFileSync('qa-implementation/evidence/final-checks.json',JSON.stringify(rows,null,2));if(rows.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
