'use strict';
const fs=require('node:fs'),path=require('node:path');
const root=__dirname,BASE='http://127.0.0.1:4318';const f=require('./runtime/fixtures.json');const cookies={},rows=[];
async function api(url,role,method='GET',body){const multipart=body instanceof FormData;const r=await fetch(BASE+url,{method,headers:{...(cookies[role]?{Cookie:cookies[role]}:{}),...(body!==undefined&&!multipart?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:multipart?body:JSON.stringify(body)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw}return{status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
function record(id,actual,pass){rows.push({id,actual,status:pass?'PASS':'FAIL'});console.log(JSON.stringify(rows.at(-1)));}
(async()=>{
for(const role of ['admin','free','student','empty','instructor','observer']){const r=await api('/api/auth/login',null,'POST',{login:role+'@qa.invalid',password:'LocalQa!2026'});cookies[role]=r.cookie;}
const form=new FormData();form.set('title','QA private course resource');form.set('type','file');form.set('file',new Blob(['%PDF-1.4\nQA PRIVATE COURSE MATERIAL\n%%EOF'],{type:'application/pdf'}),'QA-private.pdf');const uploaded=await api(`/api/batches/${f.batchId}/lessons`,'instructor','POST',form);
const url=uploaded.data.lesson?.url;const free=await api(url,'observer'),student=await api(url,'student'),teacher=await api(url,'instructor'),anon=await api(url,null);record('D-01',{free:free.status,member:student.status,assigned:teacher.status,anonymous:anon.status},free.status===403&&student.status===200&&teacher.status===200&&anon.status===401);
const award=await api(`/api/batches/${f.batchId}/award`,'instructor','POST',{user_id:f.users.empty.id,amount:25,reason:'QA nonmember'});record('D-11',{status:award.status},award.status===400||award.status===403);
const cert=await api('/api/certificates/issue','instructor','POST',{user_id:f.users.empty.id,batch_id:f.batchId,kind:'course',title:'QA ineligible certificate'});record('D-06',{status:cert.status},cert.status===400||cert.status===403);
const beforeCerts=JSON.parse(fs.readFileSync(path.join(root,'runtime/data.json'),'utf8')).certificates.length;const incomplete=await api('/api/certificates/issue','instructor','POST',{user_id:f.users.student.id,batch_id:f.batchId,kind:'course',title:'QA incomplete member certificate'});const afterCerts=JSON.parse(fs.readFileSync(path.join(root,'runtime/data.json'),'utf8')).certificates.length;record('D-06-incomplete-member',{status:incomplete.status,beforeCerts,afterCerts},(incomplete.status===400||incomplete.status===403)&&beforeCerts===afterCerts);
await api('/api/admin/batches','admin','POST',{course_id:f.courseId,name:'QA unrelated batch',start_date:'2026-09-01'});
const other=JSON.parse(fs.readFileSync(path.join(root,'runtime/data.json'),'utf8')).batches.find(b=>b.id!==f.batchId);
if(other){const quiz=await api(`/api/batches/${f.batchId}/quizzes`,'instructor','POST',{batch_id:other.id,title:'QA authorized batch binding',questions:[{q:'2+2?',options:['3','4'],answer:1}]});record('D-12',{status:quiz.status,batch:quiz.data.quiz?.batch_id},quiz.status===400||quiz.status===403||quiz.data.quiz?.batch_id===f.batchId);}
const reset=await api('/api/auth/forgot-password',null,'POST',{email:'observer@qa.invalid'});const token=reset.data.dev_link&&new URL(reset.data.dev_link).searchParams.get('token');if(token){await api('/api/auth/reset-password',null,'POST',{token,password:'LocalQa!2026'});const old=await api('/api/auth/me','observer');record('D-02',{oldSession:old.status},old.status===401);}
const adminReset=await api('/api/admin/users/'+f.users.student.id+'/password','admin','POST',{password:'LocalQa!2026'});const oldStudent=await api('/api/auth/me','student');record('D-02-admin-reset',{reset:adminReset.status,oldSession:oldStudent.status},adminReset.status===200&&oldStudent.status===401);
fs.writeFileSync(path.join(root,'evidence',process.argv[2]==='before'?'security-before.json':'security-after.json'),JSON.stringify(rows,null,2));if(process.argv[2]!=='before'&&rows.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
