'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict');
const {BASE,launch,context,login,inspect}=require('./browser-lib.cjs');
const rows=[];function save(r){rows.push(r);fs.writeFileSync('qa-implementation/evidence/ui-survey-after.json',JSON.stringify(rows,null,2));console.log(JSON.stringify({id:r.id,status:r.status,error:r.error}));}
(async()=>{const b=await launch();try{
for(const role of ['student','admin','instructor','coordinator','hr','finance','student_coordinator','staff','ambassador','recruiter','observer']){
 const c=await context(b);await login(c,role);const p=await c.newPage();const errors=[];p.on('pageerror',e=>errors.push(e.message));await p.goto(BASE+'/dashboard',{waitUntil:'domcontentloaded'});await p.locator('#app').waitFor({state:'visible'});await p.waitForTimeout(500);
 if(await p.locator('#modal.open').count())await p.evaluate(()=>{window.MODAL_LOCK=false;closeModal()});
 const views=await p.locator('.nav-item[data-view]').evaluateAll(ns=>ns.filter(n=>getComputedStyle(n).display!=='none'&&n.getClientRects().length).map(n=>n.dataset.view));
 for(const view of [...new Set(views)]){try{await p.evaluate(async v=>{await show(v)},view);await p.waitForTimeout(180);const text=await p.locator('.view.active').innerText();save({id:role+'/'+view,status:/Loading[….]*\s*$/.test(text.trim())?'FAIL':/temporarily unavailable|could not finish/i.test(text)?'UNAVAILABLE':'PASS',text:text.slice(0,300),pageErrors:[...errors]});}catch(e){save({id:role+'/'+view,status:'FAIL',error:e.message});}}
 if(['admin','student','coordinator'].includes(role)){await p.evaluate(()=>show('overview'));await p.waitForTimeout(300);await p.screenshot({path:'qa-implementation/evidence/'+role+'-overview-after-1440.png',fullPage:true});await p.setViewportSize({width:390,height:844});await p.screenshot({path:'qa-implementation/evidence/'+role+'-overview-after-390.png',fullPage:true});const x=await inspect(p);save({id:role+'/mobile',status:x.documentWidth<=392?'PASS':'FAIL',documentWidth:x.documentWidth,overflow:x.overflow});}
 await c.close();
}
for(const width of [1440,390]){const c=await context(b,{width,height:844}),p=await c.newPage();await p.goto(BASE+'/open#free');await p.locator('.oc-lang-btn').first().waitFor();await p.evaluate(()=>navCourses('live'));assert.equal(await p.locator('#cFree').inputValue(),'');assert.ok(await p.locator('.oc-card').count()<=12);await p.locator('#cSearch').fill('Python');await p.waitForTimeout(200);assert.ok((await p.locator('#courseTable').innerText()).includes('Python'));save({id:'D-13/search/'+width,status:'PASS'});await p.screenshot({path:'qa-implementation/evidence/catalogue-after-'+width+'.png',fullPage:true});await c.close();}
const c=await context(b,{width:390,height:844});await login(c,'observer');const p=await c.newPage();await p.goto(BASE+'/dashboard#view=settings');await p.waitForTimeout(500);await p.evaluate(()=>{ME.profile.phone='';requireWhatsapp()});await p.locator('input[name=whatsapp]').fill('03008887777');await p.getByRole('button',{name:'Finish later',exact:true}).click();assert.equal(await p.locator('#modal.open').count(),0);await p.evaluate(()=>requireWhatsapp());assert.equal(await p.locator('input[name=whatsapp]').inputValue(),'03008887777');await p.screenshot({path:'qa-implementation/evidence/onboarding-after-390.png',fullPage:true});save({id:'U-07/onboarding-resume',status:'PASS'});await c.close();
}finally{await b.close();}if(rows.some(r=>r.status==='FAIL'))process.exitCode=1;})().catch(e=>{console.error(e);process.exitCode=1});
