'use strict';
const fs=require('node:fs'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const BASE='http://127.0.0.1:4318',fixtures=require('./runtime/fixtures.json'),cookies={},rows=[];
async function api(url,role,method='GET',body){const form=body instanceof FormData;const r=await fetch(BASE+url,{method,headers:{...(cookies[role]?{Cookie:cookies[role]}:{}),...(body!==undefined&&!form?{'Content-Type':'application/json'}:{})},body:body===undefined?undefined:form?body:JSON.stringify(body)});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data=raw}return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0]};}
async function check(id,fn){try{const detail=await fn();rows.push({id,status:'PASS',detail});}catch(e){rows.push({id,status:'FAIL',error:e.stack});}console.log(JSON.stringify(rows.at(-1)));fs.writeFileSync('qa-implementation/evidence/workflow-after.json',JSON.stringify(rows,null,2));}
const runtime=()=>JSON.parse(fs.readFileSync('qa-implementation/runtime/data.json','utf8'));
(async()=>{
for(const role of ['admin','free','student','empty','instructor','coordinator','student_coordinator','finance']){const r=await api('/api/auth/login',null,'POST',{login:role+'@qa.invalid',password:'LocalQa!2026'});assert.equal(r.status,200);cookies[role]=r.cookie;}
await check('D-03 profile clearing',async()=>{await api('/api/me/profile','student','POST',{city:'QA city',goal:'QA goal'});const r=await api('/api/me/profile','student','POST',{city:'',goal:null,role:'admin'});assert.equal(r.status,200);assert.equal(r.data.profile.city,undefined);assert.equal(r.data.profile.goal,undefined);const me=await api('/api/auth/me','student');assert.equal(me.data.role,'student');return {city:me.data.profile.city??null,goal:me.data.profile.goal??null,role:me.data.role};});
await check('D-08/09/10/17 enrollment lifecycle',async()=>{
 const data={name:'QA free',email:'free@qa.invalid',whatsapp:'03001234567',course_code:'SC-01',course_title:'tampered',request_key:crypto.randomUUID()};
 for(const course_code of ['PATH','INVALID','CS-104'])assert.equal((await api('/api/public/register-interest',null,'POST',{...data,course_code})).status,400);
 const created=await Promise.all([api('/api/public/register-interest',null,'POST',data),api('/api/public/register-interest',null,'POST',data)]);assert.equal(created[0].status,200,JSON.stringify(created[0].data));assert.equal(created[1].data.reference,created[0].data.reference);
 const reg=runtime().registrations.find(r=>r.email===data.email&&r.course_code===data.course_code);assert.equal(runtime().registrations.filter(r=>r.email===data.email&&r.course_code===data.course_code).length,1);assert.notEqual(reg.course_title,'tampered');
 const receipt=created.map(r=>r.data.receipt_url).find(Boolean)||'/registration-status#'+reg.status.receipt_token;const token=receipt.split('#')[1];assert.equal((await api('/api/public/registration-status',null,'POST',{token:'invalid'})).status,404);const status=await api('/api/public/registration-status',null,'POST',{token});assert.equal(status.status,200,JSON.stringify(status.data));
 const challans=await Promise.all([api('/api/admissions/registrations/'+reg.id+'/challan','student_coordinator','POST',{deadline:'2026-10-01'}),api('/api/admissions/registrations/'+reg.id+'/challan','student_coordinator','POST',{deadline:'2026-10-01'})]);assert.equal(challans[0].status,200);assert.equal(challans[0].data.challan.serial,challans[1].data.challan.serial);const c=challans[0].data.challan;assert.ok(c.net_fee>0);
 const email=await api('/api/admissions/challans/'+c.serial+'/send','student_coordinator','POST',{});assert.equal(email.status,503);assert.notEqual(runtime().registrations.find(r=>r.id===reg.id).payment_stage,'challan_sent');
 assert.equal((await api('/api/finance/registrations/'+reg.id+'/clear','free','POST',{})).status,403);assert.equal((await api('/api/finance/registrations/'+reg.id+'/clear','finance','POST',{})).status,200);
 const enroll=await api('/api/admissions/registrations/'+reg.id+'/enroll','student_coordinator','POST',{batch_id:fixtures.batchId});assert.equal(enroll.status,200,JSON.stringify(enroll.data));assert.equal(enroll.data.registration.payment_stage,'enrolled');await api('/api/finance/registrations/'+reg.id+'/clear','finance','POST',{});assert.equal(runtime().registrations.find(r=>r.id===reg.id).payment_stage,'enrolled');assert.equal(runtime().enrollments.filter(e=>e.user_id===fixtures.users.free.id&&e.batch_id===fixtures.batchId).length,1);
 return {registration:reg.id,reference:created[0].data.reference,fee:c.net_fee,email:email.status,stage:'enrolled',duplicateRequests:2,receiptStatus:status.status};
});
await check('D-16/18 attempts, feedback, mastery and certificate',async()=>{
 const track='cs105-javascript',def=(await api('/api/public/tracks/'+track)).data;let last,serial;
 for(const l of def.levels){for(const p of l.problems){const payload={track_key:track,level:l.no,pid:p.pid,code:'<script>console.log("QA attempt");</script>',language:'web',request_key:crypto.randomUUID()};const r=await api('/api/open/submit','empty','POST',payload);assert.equal(r.status,202,JSON.stringify(r.data));assert.equal(r.data.attempt.status,'failed');const again=await api('/api/open/submit','empty','POST',payload);assert.equal(again.data.attempt.id,r.data.attempt.id);assert.equal((await api('/api/open/attempts/'+r.data.attempt.id+'/retry','empty','POST')).status,503);assert.equal((await api('/api/admin/open-attempts/'+r.data.attempt.id+'/grade','empty','POST',{score:100,feedback:'forged'})).status,403);
 const grade=await api('/api/admin/open-attempts/'+r.data.attempt.id+'/grade','admin','POST',{score:100,feedback:'QA manual review: requirements satisfied.'});assert.equal(grade.status,200,JSON.stringify(grade.data));last={l,p,payload,attempt:r.data.attempt.id};if(grade.data.certificate)serial=grade.data.certificate.serial;
 }}
 const before=(await api('/api/open/progress?track='+track,'empty')).data.progress;assert.equal(before.passed,true);assert.equal(before.required_total,def.levels.reduce((n,l)=>n+l.problems.filter(p=>p.required!==false).length,0));assert.ok(serial);
 const failed=await api('/api/open/submit','empty','POST',{...last.payload,code:'lower score attempt',request_key:crypto.randomUUID()});assert.equal(failed.data.attempt.status,'failed');const pending=(await api('/api/open/progress?track='+track,'empty')).data.progress;assert.equal(pending.gems,before.gems);await api('/api/admin/open-attempts/'+failed.data.attempt.id+'/grade','admin','POST',{score:10,feedback:'QA: lower score retained separately.'});const after=(await api('/api/open/progress?track='+track,'empty')).data.progress;assert.equal(after.gems,before.gems);assert.equal(after.passed,true);assert.ok(after.submissions[last.l.no+':'+last.p.pid].history.length>=2);assert.equal((await api('/api/open/attempts?track='+track,'student')).data.attempts.length,0);
 const verify=await api('/api/verify/'+serial);assert.equal(verify.status,200);assert.equal(verify.data.valid,true);return {required:after.required_total,passed:after.required_passed,gems:after.gems,certificate:serial,publicVerification:verify.status};
});
await check('Teacher grading and learner feedback',async()=>{const q=runtime().quests.find(q=>q.batch_id===fixtures.batchId);const r=await api('/api/quests/'+q.id+'/problems/'+q.problems[0].pid+'/submit','student','POST',{code:'print("QA lesson")',language:'python'});assert.equal(r.status,200,JSON.stringify(r.data));const sub=r.data.submission||runtime().quest_submissions.find(s=>s.quest_id===q.id&&s.user_id===fixtures.users.student.id);assert.equal((await api('/api/quest-submissions/'+sub.id+'/grade','empty','POST',{grade:100})).status,403);const g=await api('/api/quest-submissions/'+sub.id+'/grade','instructor','POST',{grade:85,remarks:'QA teacher feedback'});assert.equal(g.status,200);assert.equal(g.data.submission.remarks,'QA teacher feedback');return {submission:sub.id,grade:g.data.submission.grade};});
await check('D-19 challenge corrections',async()=>{const c=await api('/api/admin/challenges','admin','POST',{title:'QA ledger '+Date.now(),gems:50});const r=await api('/api/challenges/'+c.data.challenge.id+'/submit','empty','POST',{link:'https://example.invalid/qa',note:'Synthetic'});assert.equal(r.status,200);const sid=r.data.submission.id;for(const approve of [true,false,true,true])assert.equal((await api('/api/challenge-submissions/'+sid+'/review','admin','POST',{approve,gems:50,remarks:'QA correction'})).status,200);const ledger=runtime().gem_events.filter(e=>e.reference_type==='challenge_review'&&e.reference_id.startsWith(sid+':'));assert.deepEqual(ledger.map(e=>e.amount),[50,-50,50]);return {ledger:ledger.map(e=>e.amount),net:50};});
await check('D-20 team identity and prizes',async()=>{const h=await api('/api/admin/hackathons','admin','POST',{title:'QA team '+Date.now(),mode:'team',team_max:4,starts_at:'2026-09-01T00:00',ends_at:'2026-10-01T00:00',prize1:300});const id=h.data.hackathon.id;const bad=await api('/api/hackathons/'+id+'/register','empty','POST',{member_regs:['qa.student','student@qa.invalid']});assert.equal(bad.status,400,JSON.stringify(bad.data));const reg=await api('/api/hackathons/'+id+'/register','empty','POST',{member_regs:['qa.student']});assert.equal(reg.status,200);const sub=await api('/api/hackathons/'+id+'/submit','empty','POST',{link:'https://example.invalid/qa'});assert.equal(sub.status,200);assert.equal((await api('/api/admin/hackathon-submissions/'+sub.data.submission.id+'/score','admin','POST',{score:90})).status,200);assert.equal((await api('/api/admin/hackathons/'+id+'/finalize','admin','POST',{})).status,200);await api('/api/admin/hackathons/'+id+'/finalize','admin','POST',{});const awards=runtime().gem_events.filter(e=>e.reference_type==='hackathon_prize'&&e.reference_id===String(id));assert.equal(awards.length,2);assert.equal(new Set(awards.map(a=>a.user_id)).size,2);return {members:2,awards:awards.length};});
await check('D-14 coordinator permissions',async()=>{assert.equal((await api('/api/instructors-lite','coordinator')).status,403);assert.equal((await api('/api/batches/'+fixtures.batchId+'/chat','coordinator','POST',{body:'QA denied'})).status,403);const r=await api('/api/batches/'+fixtures.batchId+'/chat','coordinator');assert.equal(r.status,200);assert.equal(r.data.can_post,false);return {read:200,write:403};});
if(rows.some(r=>r.status==='FAIL'))process.exitCode=1;
})().catch(e=>{console.error(e);process.exitCode=1});
