'use strict';
// TT-03 Data Structures and Algorithmic Problem Solving.
// Quiz rows: [question, options, index of the correct option, explanation].
module.exports = {
  quizzes: {
    'A3.1': [
      ['What is the time complexity of two pointers converging on a sorted array?', ['O(log n)', 'O(n)', 'O(n log n)', 'O(n²)'], 1, 'Each step moves one pointer, so at most n steps.'],
      ['3Sum with sorting plus two pointers runs in...', ['O(n)', 'O(n log n)', 'O(n²)', 'O(n³)'], 2, 'Sorting is O(n log n); the outer loop × two-pointer scan is O(n²).'],
      ['In Container With Most Water, which pointer should move?', ['The taller one', 'The shorter one', 'Both always', 'Neither - restart'], 1, 'Moving the taller side can never increase the area bounded by the shorter.'],
      ['How does 3Sum avoid repeated triplets?', ['Uses a random seed', 'Skips equal adjacent values after sorting', 'Sorts in descending order', 'Limits input size'], 1, 'Skipping duplicates at each pointer prevents repeats.'],
      ['Big-O describes...', ['exact running time in seconds', 'how cost grows with input size, ignoring constants', 'memory in bytes', 'the best case only'], 1, 'It is an asymptotic upper bound on growth.'],
    ],
    'A3.2': [
      ['A sliding window is best suited to problems about...', ['contiguous subarrays or substrings', 'trees', 'sorting', 'random access only'], 0, 'Windows expand and shrink over contiguous ranges.'],
      ['For Longest Substring Without Repeating Characters, when a repeat enters the window you...', ['restart from the next index always', 'move the left edge past the previous occurrence', 'sort the window', 'stop'], 1, 'The left pointer jumps so the window becomes valid again.'],
      ['Minimum Window Substring("ADOBECODEBANC", "ABC") returns...', ['"ADOBEC"', '"BANC"', '"CODEBA"', '"ABC"'], 1, '"BANC" is the shortest window containing A, B and C.'],
      ['A loop invariant is...', ['a variable that never changes', 'a condition that holds before and after every iteration', 'the loop counter', 'a compiler optimisation'], 1, 'Invariants are how you argue the loop is correct.'],
      ['A dynamic sliding window over a string of length n runs in...', ['O(n²) always', 'O(n), because each index enters and leaves the window at most once', 'O(log n)', 'O(n³)'], 1, 'Both pointers only move forward.'],
    ],
    'A3.3': [
      ['Binary search requires the search space to be...', ['unsorted', 'monotonic (sorted, or a predicate that flips once)', 'small', 'stored in a linked list'], 1, 'Monotonicity lets you discard half each step.'],
      ['"Binary search on the answer" (e.g. Koko\'s eating speed) searches over...', ['array indices only', 'the range of possible answers, testing feasibility', 'random values', 'string characters'], 1, 'A feasibility predicate tells you which half to keep.'],
      ['A feasibility predicate for Capacity To Ship returns true when...', ['the capacity is a prime number', 'all packages can be shipped within D days at that capacity', 'the capacity equals the total weight', 'D is even'], 1, 'Then search for the smallest capacity that is feasible.'],
      ['Binary search over a range of size R takes...', ['O(R)', 'O(log R) iterations', 'O(1)', 'O(R log R)'], 1, 'The range halves every iteration.'],
      ['A common bug in binary search is...', ['using recursion', 'an off-by-one in the bounds causing an infinite loop or a missed answer', 'using integers', 'sorting first'], 1, 'Be precise about lo/hi and whether mid is kept.'],
    ],
    'A3.4': [
      ['Floyd\'s fast and slow pointers detect...', ['a sorted list', 'a cycle in a linked list', 'the list length only', 'duplicate values'], 1, 'If there is a cycle, the fast pointer eventually meets the slow one.'],
      ['After the pointers meet, how do you find the cycle\'s entry?', ['Reverse the list', 'Reset one pointer to the head and move both one step at a time until they meet', 'Use a hash set', 'Count nodes'], 1, 'They meet exactly at the cycle start.'],
      ['Reversing a singly linked list in place uses how much extra space?', ['O(n)', 'O(1)', 'O(log n)', 'O(n²)'], 1, 'Only a few pointers (prev, curr, next) are needed.'],
      ['Reversing an empty list should return...', ['an error', 'None / null', 'a new node', 'the tail'], 1, 'With prev starting at None, an empty input naturally returns None.'],
      ['Why does a hash set cycle detector not meet the brief?', ['It is wrong', 'It uses O(n) extra space instead of O(1)', 'It is slower than O(n²)', 'Python has no sets'], 1, 'The brief asks for constant extra space.'],
    ],
    'A3.5': [
      ['A monotonic stack keeps its elements...', ['in random order', 'in increasing or decreasing order', 'sorted by insertion time only', 'unique'], 1, 'Elements that break the order are popped.'],
      ['Daily Temperatures for [73,74,75,71,69,72,76,73] returns...', ['[1,1,4,2,1,1,0,0]', '[1,1,1,1,1,1,0,0]', '[0,0,0,0,0,0,0,0]', '[2,1,4,2,1,1,0,1]'], 0, 'Each answer is the days until a warmer temperature.'],
      ['Why is a monotonic stack solution O(n)?', ['It sorts first', 'Each element is pushed once and popped at most once', 'It uses recursion', 'It is O(n²)'], 1, 'Total pushes + pops ≤ 2n.'],
      ['In Largest Rectangle in Histogram, popping a bar means...', ['the bar is deleted', 'the next smaller bar on the right has been found, so its maximal width is known', 'the answer is final', 'the input is invalid'], 1, 'The stack top\'s left bound is the new top, right bound is the current index.'],
      ['Which stack order finds the next greater element?', ['A decreasing stack (pop while the current value is greater)', 'An increasing stack', 'A queue', 'A heap'], 0, 'Smaller waiting elements are resolved by the next greater one.'],
    ],
    'A3.6': [
      ['A binary heap gives which costs?', ['O(1) insert and O(1) pop', 'O(log n) insert and pop, O(1) peek', 'O(n) insert', 'O(log n) peek'], 1, 'Sift-up/down is logarithmic; the root is the min/max.'],
      ['Top K Frequent Elements with a size-k min-heap runs in...', ['O(n log k)', 'O(k)', 'O(n²)', 'O(log n)'], 0, 'Each of n items costs O(log k).'],
      ['Find Median from Data Stream uses two heaps:', ['two min-heaps', 'a max-heap for the lower half and a min-heap for the upper half', 'one sorted list', 'a stack and a queue'], 1, 'The median sits at the tops of the two halves.'],
      ['Python\'s heapq module implements a...', ['max-heap', 'min-heap', 'balanced tree', 'hash table'], 1, 'Negate values to simulate a max-heap.'],
      ['How do you keep the two median heaps balanced?', ['Never - sizes do not matter', 'Move the top element across so their sizes differ by at most one', 'Sort both after each insert', 'Clear them periodically'], 1, 'Rebalancing keeps the median at the tops.'],
    ],
    'A3.7': [
      ['Level order traversal uses which data structure?', ['A stack', 'A queue', 'A heap', 'A hash map'], 1, 'BFS processes nodes in FIFO order level by level.'],
      ['How do you group BFS output by level?', ['Sort the output', 'Process exactly the current queue length per loop iteration', 'Use recursion depth only', 'It is impossible'], 1, 'The queue size at the start of a level is the level\'s width.'],
      ['In a BST, the lowest common ancestor of p and q is the first node where...', ['the value is the maximum', 'p and q fall on different sides (or one equals the node)', 'the node is a leaf', 'the depth is 1'], 1, 'Walk down while both are on the same side.'],
      ['The BST LCA walk runs in...', ['O(n)', 'O(h), where h is the tree height', 'O(1)', 'O(n log n)'], 1, 'It follows a single root-to-node path.'],
      ['An in-order traversal of a BST visits values in...', ['random order', 'sorted ascending order', 'level order', 'reverse insertion order'], 1, 'Left, node, right yields sorted output.'],
    ],
    'A3.8': [
      ['Number of Islands counts...', ['water cells', 'connected components of land', 'the largest island', 'grid rows'], 1, 'Each DFS from an unvisited land cell marks one island.'],
      ['Course Schedule is impossible exactly when the prerequisite graph...', ['is disconnected', 'contains a cycle', 'has more than 10 nodes', 'is a tree'], 1, 'A cycle means no valid ordering exists.'],
      ['DFS detects a cycle in a directed graph by finding an edge to a node that is...', ['unvisited', 'currently on the recursion stack (visiting)', 'already fully finished', 'a leaf'], 1, 'Three colours: unvisited, visiting, done.'],
      ['DFS over a graph with V vertices and E edges runs in...', ['O(V)', 'O(V + E)', 'O(V²) always', 'O(E log V)'], 1, 'Each vertex and edge is processed once.'],
      ['Why mark grid cells as visited during an island DFS?', ['To print them', 'To avoid infinite loops and recounting the same land', 'To sort them', 'It is optional'], 1, 'Unmarked cells would be revisited endlessly.'],
    ],
    'A3.9': [
      ['Plain BFS finds shortest paths when...', ['all edges have equal weight', 'edges have negative weights', 'the graph is weighted arbitrarily', 'never'], 0, 'BFS counts edges, which equals cost only with uniform weights.'],
      ['Dijkstra\'s algorithm requires edge weights to be...', ['negative', 'non-negative', 'integers only', 'all equal'], 1, 'A negative edge could improve an already-finalised node.'],
      ['Dijkstra with a binary heap runs in about...', ['O(V²E)', 'O((V + E) log V)', 'O(1)', 'O(V)'], 1, 'Each edge relaxation may push to the heap.'],
      ['How do you return the path, not just the cost?', ['Store a parent pointer for each node and walk back from the target', 'Sort the nodes', 'Run BFS again', 'It is impossible'], 0, 'Parents record how each node was best reached.'],
      ['Why compare against brute force on a small graph?', ['To make it faster', 'An exhaustive search gives a trusted answer to verify correctness', 'Brute force is required by Dijkstra', 'To use more memory'], 1, 'Small brute-force oracles catch subtle bugs.'],
    ],
    'A3.10': [
      ['Backtracking explores...', ['only one path', 'choices recursively, undoing each choice before trying the next', 'random solutions', 'sorted outputs only'], 1, 'Choose, explore, un-choose.'],
      ['How many solutions does 8-Queens have?', ['8', '12', '92', '4,426'], 2, 'There are 92 distinct solutions (12 up to symmetry).'],
      ['How many solutions does 4-Queens have?', ['0', '1', '2', '4'], 2, 'Two boards solve 4-Queens.'],
      ['For Subsets II with input [1,2,2], how do you avoid duplicate subsets?', ['Use a random order', 'Sort, then skip an element equal to its predecessor at the same recursion depth', 'Remove duplicates from the input', 'Use a set of tuples only'], 1, 'Skipping same-level duplicates prunes repeats directly.'],
      ['Pruning means...', ['deleting the input', 'abandoning a branch as soon as it cannot lead to a valid solution', 'sorting results', 'caching results'], 1, 'Early cut-offs shrink the search tree.'],
    ],
    'A3.11': [
      ['Dynamic programming applies when a problem has...', ['no repeated work', 'overlapping subproblems and optimal substructure', 'random inputs', 'only one answer'], 1, 'DP reuses solved subproblems.'],
      ['Coin Change with coins [1,2,5] and amount 11 returns...', ['2', '3', '4', '11'], 1, '5 + 5 + 1 = 11 uses three coins.'],
      ['Coin Change should return what for an impossible amount?', ['0', '-1', 'infinity', 'the amount'], 1, 'The conventional sentinel is -1.'],
      ['House Robber can run in O(1) space because each state depends only on...', ['all previous houses', 'the previous two states', 'the next house', 'nothing'], 1, 'Keep two rolling variables.'],
      ['Longest Increasing Subsequence with patience sorting and binary search runs in...', ['O(n²)', 'O(n log n)', 'O(n)', 'O(2ⁿ)'], 1, 'Each element does one binary search over the tails array.'],
    ],
    'A3.12': [
      ['In the 0/1 knapsack, each item can be taken...', ['any number of times', 'at most once', 'exactly twice', 'only if it is the lightest'], 1, '0/1 means take it or leave it.'],
      ['The LCS of "abcde" and "ace" is...', ['"ae"', '"ace"', '"abc"', '"bcd"'], 1, 'Length 3: a, c, e in order.'],
      ['How do you reconstruct the chosen knapsack items?', ['Re-run with random weights', 'Walk the DP table backwards, noting where the value changed from the row above', 'Sort the items', 'It cannot be done'], 1, 'A change means the item was taken.'],
      ['A 2D DP table for LCS of lengths m and n has size...', ['m + n', '(m + 1) × (n + 1)', 'm × m', 'n²'], 1, 'An extra row and column hold the empty-prefix base cases.'],
      ['Knapsack DP runs in...', ['O(n)', 'O(n × W), where W is the capacity', 'O(2ⁿ) always', 'O(log W)'], 1, 'Pseudo-polynomial: it depends on the numeric capacity.'],
    ],
  },
  tasks: {
    'A3.1': { language: 'python', title: 'Two pointers: Two Sum (sorted), Container With Most Water, 3Sum', description: 'Implement Two Sum on a sorted array, Container With Most Water and 3Sum using converging pointers. Put a complexity comment (time and extra space) at the top of each function. Test 3Sum on a generated array of 3,000 integers with duplicates (use random with a fixed seed) and confirm no triplet repeats.', criteria: ['All three functions use converging pointers.', 'Each function states its time and space complexity.', '3Sum returns correct triplets with no duplicates on 3,000 elements.', 'Small hand-checked examples are printed for each function.'], hint: 'For 3Sum: sort, fix i, then move lo/hi inward; skip equal neighbours at i, lo and hi.' },
    'A3.2': { language: 'python', title: 'Sliding window: Longest Substring and Minimum Window', description: 'Solve Longest Substring Without Repeating Characters and Minimum Window Substring. Print results for several inputs, including "ADOBECODEBANC" with target "ABC". Add a comment naming the invariant each loop maintains.', criteria: ['minWindow("ADOBECODEBANC", "ABC") returns "BANC".', 'Longest substring returns 3 for "abcabcbb" and 1 for "bbbbb".', 'Both run in O(n).', 'The loop invariant is stated in a comment.'], hint: 'Track character counts and how many required characters are currently satisfied.' },
    'A3.3': { language: 'python', title: 'Binary search on the answer: Koko and ship capacity', description: 'Solve Koko Eating Bananas and Capacity To Ship Packages Within D Days with binary search over the answer range. Write each feasibility predicate as its own function. Include edge-case tests for a single item and for all items identical.', criteria: ['Each solution uses a standalone feasibility predicate.', 'Binary search is over the answer range, not the array.', 'Edge cases (single item, all identical) pass.', 'Known examples: Koko([3,6,7,11], h=8) = 4; ship([1..10], days=5) = 15.'], hint: 'Search for the smallest value where the predicate becomes true.' },
    'A3.4': { language: 'python', title: 'Linked lists: reversal and cycle entry', description: 'Implement a ListNode class, in-place reversal, cycle detection and cycle-entry finding, all in O(1) extra space. Test reversal on empty, single-node and five-node lists, and cycle entry on a list whose tail links back to the third node.', criteria: ['Reversal is in place and handles empty and single-node lists without a special-case branch.', 'Cycle detection uses fast and slow pointers.', 'The correct entry node is returned.', 'No extra data structures (sets, lists of nodes) are used.'], hint: 'After the pointers meet, move one from the head; both stepping by one meet at the entry.' },
    'A3.5': { language: 'python', title: 'Monotonic stacks: Daily Temperatures and Largest Rectangle', description: 'Solve Daily Temperatures and Largest Rectangle in Histogram with monotonic stacks. In a comment, justify the linear bound by counting pushes and pops.', criteria: ['dailyTemperatures([73,74,75,71,69,72,76,73]) returns [1,1,4,2,1,1,0,0].', 'largestRectangle([2,1,5,6,2,3]) returns 10.', 'Both use a monotonic stack and run in O(n).', 'The push/pop counting argument is written as a comment.'], hint: 'Append a 0-height sentinel bar so every bar gets popped.' },
    'A3.6': { language: 'python', title: 'Heaps: Top K Frequent and streaming median', description: 'Solve Top K Frequent Elements and Find Median from Data Stream using two heaps (heapq). Stream 1,000 random values (fixed seed) through the median structure and compare every median against a sorted reference.', criteria: ['Top K uses a heap, not a full sort.', 'The median structure uses a max-heap and a min-heap.', 'All 1,000 streamed medians match the sorted reference.', 'Insert is O(log n) and median is O(1).'], hint: 'Python heapq is a min-heap; push negatives for the lower half.' },
    'A3.7': { language: 'python', title: 'Trees: level order and BST lowest common ancestor', description: 'Build a 15-node binary search tree, implement level-order traversal returning nested lists per level, and implement the lowest common ancestor for a BST in O(h). Print the level order output and three LCA queries.', criteria: ['Level order output matches the expected nested lists exactly.', 'LCA walks down from the root without visiting the whole tree.', 'LCA handles the case where one node is the ancestor of the other.', 'Output is printed for the 15-node tree.'], hint: 'Use collections.deque and process len(queue) nodes per level.' },
    'A3.8': { language: 'python', title: 'DFS: Number of Islands and Course Schedule', description: 'Solve Number of Islands with DFS on a grid and Course Schedule with DFS cycle detection on a prerequisite graph. Include a grid with exactly three islands and a prerequisite cycle of length four.', criteria: ['The three-island grid returns 3.', 'Course Schedule returns False for a cycle of length four.', 'Course Schedule returns True for an acyclic graph.', 'Cycle detection uses visiting/visited states.'], hint: 'Use an iterative stack if you are worried about recursion depth.' },
    'A3.9': { language: 'python', title: 'Dijkstra with path reconstruction', description: 'Implement Dijkstra with heapq on a weighted 10-node graph, returning both the cost and the path from node 0 to node 5. Verify against a brute-force search over all simple paths.', criteria: ['Dijkstra returns the minimal cost and a valid path.', 'Parent pointers reconstruct the path.', 'Brute force over simple paths agrees on the minimal cost.', 'The comparison output is printed.'], hint: 'Skip heap entries whose distance is larger than the best known one.' },
    'A3.10': { language: 'python', title: 'Backtracking: Subsets II, Combination Sum, N-Queens', description: 'Implement Subsets with duplicates, Combination Sum and an N-Queens solver with pruning. Print the counts for n = 4 and n = 8 and the subsets of [1, 2, 2].', criteria: ['N-Queens returns 2 for n = 4 and 92 for n = 8.', 'Subsets of [1,2,2] contain no repeated set.', 'Combination Sum([2,3,6,7], 7) returns [[2,2,3],[7]].', 'Pruning uses column and diagonal sets.'], hint: 'Diagonals: row - col and row + col are constant.' },
    'A3.11': { language: 'python', title: '1D DP: House Robber, Coin Change, LIS', description: 'Solve House Robber (in O(1) extra space), Coin Change and Longest Increasing Subsequence. Include the impossible-amount case for Coin Change.', criteria: ['coinChange([1,2,5], 11) returns 3.', 'An impossible amount (e.g. coins [2], amount 3) returns -1.', 'House Robber uses O(1) extra space.', 'lengthOfLIS([10,9,2,5,3,7,101,18]) returns 4.'], hint: 'House Robber: keep two variables, prev and curr.' },
    'A3.12': { language: 'python', title: '2D DP: knapsack and LCS with reconstruction', description: 'Implement the 0/1 knapsack and longest common subsequence, then reconstruct the chosen items and the subsequence itself by walking the tables backwards.', criteria: ['LCS("abcde", "ace") returns length 3 and prints "ace".', 'The knapsack returns both the optimal value and the selected item list.', 'Reconstruction walks the DP table backwards.', 'A second test case is shown for each.'], hint: 'For knapsack, item i was taken if dp[i][w] != dp[i-1][w].' },
  },
};
