'use strict';
const accounts = require('./accounts');
module.exports = function landing() {
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Explore EchoLens — Client Demo</title>
  <style>*{box-sizing:border-box}body{margin:0;background:#f5f7ff;color:#14203b;font:16px/1.6 system-ui}main{max-width:1150px;margin:auto;padding:55px 24px 100px}.brand{font-weight:800;color:#4f46e5;letter-spacing:.08em}h1{font-size:clamp(32px,5vw,52px);line-height:1.15;margin:16px 0}header p{max-width:760px;color:#536079}.info{margin:25px 0;padding:16px 20px;border:1px solid #c7d2fe;background:#eef2ff;border-radius:14px}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(245px,1fr));gap:18px}.card{background:white;border:1px solid #e2e8f0;border-radius:18px;padding:24px;display:flex;flex-direction:column;box-shadow:0 4px 18px #17255405}h2{font-size:19px;margin:0 0 8px}.card p{color:#536079;font-size:14px;min-height:44px;margin:0 0 14px}.credentials{font-size:14px;margin-bottom:18px}code{background:#eef2ff;padding:3px 8px;border-radius:6px;color:#312e81}button{font:inherit;background:#4f46e5;color:#fff;border:0;border-radius:10px;padding:11px 16px;cursor:pointer;margin-top:auto}button:disabled{opacity:.65}a{color:#4338ca}#error{color:#b91c1c;min-height:26px}footer{margin-top:25px;color:#536079;font-size:14px}</style></head><body><main>
  <header><div class="brand">ECHOLENS DIGITAL LMS</div><h1>Take a look inside.</h1><p>Explore the learning platform from every role. These are the actual portal screens with fictional learners, courses, payments and staff records.</p></header>
  <div class="info"><strong>Every demo password is <code>admin</code>.</strong> Browse pages, open forms and view sample records. Saving, submitting, uploading, sending mail, payments and external service actions are disabled. These accounts work only in this demo.</div>
  <p id="error" role="alert"></p><div class="grid">${accounts.map(a => `<article class="card"><h2>${a.label}</h2><p>${a.description}</p><div class="credentials">Username <code>${a.username}</code> · Password <code>admin</code></div><button data-account="${a.username}">Explore ${a.label.toLowerCase()}</button></article>`).join('')}</div>
  <footer>AI, email, live meetings and external integrations are not invoked in the demo. Sample certificates are marked as demonstration records. <a href="/" data-demo-exit>Return to the main website</a>.</footer></main>
  <script>document.querySelectorAll('[data-account]').forEach(button=>button.addEventListener('click',async()=>{button.disabled=true;document.getElementById('error').textContent='';try{const response=await fetch('/api/auth/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({login:button.dataset.account,password:'admin'})});const data=await response.json();if(!response.ok)throw Error(data.error||'Sign-in could not finish.');location.href=data.role==='free'?'/open#free':button.dataset.account==='head'?'/dashboard#view=my-department':'/dashboard';}catch(error){document.getElementById('error').textContent=error.message;button.disabled=false;}}));</script></body></html>`;
};
