import { chromium } from 'playwright';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
const errors = [];
page.on('pageerror', (e) => errors.push(String(e)));
await page.goto('http://localhost:3200/login', { waitUntil: 'networkidle' });
await page.fill('input[name="login"], #login', 'student@echolens.digital');
await page.fill('input[name="password"], #password', 'ChangeMe!2026');
await page.click('button[type="submit"]');
await page.waitForURL(/\/(dashboard|open)/, { timeout: 15000 });
await page.goto('http://localhost:3200/open', { waitUntil: 'networkidle' });
await page.waitForTimeout(1500);
const profVisible = await page.evaluate(() => document.getElementById('profileNavLink').style.display !== 'none');
console.log('My Profile link visible for portal student:', profVisible);
await page.click('#profileNavLink');
await page.waitForTimeout(1500);
const profText = await page.evaluate(() => (document.getElementById('tab-profile')?.textContent || '').replace(/\s+/g, ' ').slice(0, 120));
console.log('profile tab renders:', JSON.stringify(profText));
await page.screenshot({ path: 'screenshots/unified-profile.png' });
await browser.close();
console.log(errors.length ? 'PAGE ERRORS:\n' + errors.join('\n') : 'no page errors');
